//
// Generated file, do not edit! Created by opp_msgc 4.3 from common/GlobalTraceManager.msg.
//

#ifndef _GLOBALTRACEMANAGER_M_H_
#define _GLOBALTRACEMANAGER_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>common/GlobalTraceManager.msg</tt> by opp_msgc.
 * <pre>
 * packet GlobalTraceManagerMessage
 * {
 *         int internalNodeId;
 *         int lineNumber;
 * }
 * </pre>
 */
class GlobalTraceManagerMessage : public ::cPacket
{
  protected:
    int internalNodeId_var;
    int lineNumber_var;

  private:
    void copy(const GlobalTraceManagerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GlobalTraceManagerMessage&);

  public:
    GlobalTraceManagerMessage(const char *name=NULL, int kind=0);
    GlobalTraceManagerMessage(const GlobalTraceManagerMessage& other);
    virtual ~GlobalTraceManagerMessage();
    GlobalTraceManagerMessage& operator=(const GlobalTraceManagerMessage& other);
    virtual GlobalTraceManagerMessage *dup() const {return new GlobalTraceManagerMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getInternalNodeId() const;
    virtual void setInternalNodeId(int internalNodeId);
    virtual int getLineNumber() const;
    virtual void setLineNumber(int lineNumber);
};

inline void doPacking(cCommBuffer *b, GlobalTraceManagerMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GlobalTraceManagerMessage& obj) {obj.parsimUnpack(b);}


#endif // _GLOBALTRACEMANAGER_M_H_
