//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/realworldtestapp/RealWorldTestMessage.msg.
//

#ifndef _REALWORLDTESTMESSAGE_M_H_
#define _REALWORLDTESTMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>applications/realworldtestapp/RealWorldTestMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet RealWorldTestMessage
 * {
 * 	string msg;     
 * }
 * </pre>
 */
class RealWorldTestMessage : public ::cPacket
{
  protected:
    opp_string msg_var;

  private:
    void copy(const RealWorldTestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RealWorldTestMessage&);

  public:
    RealWorldTestMessage(const char *name=NULL, int kind=0);
    RealWorldTestMessage(const RealWorldTestMessage& other);
    virtual ~RealWorldTestMessage();
    RealWorldTestMessage& operator=(const RealWorldTestMessage& other);
    virtual RealWorldTestMessage *dup() const {return new RealWorldTestMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getMsg() const;
    virtual void setMsg(const char * msg);
};

inline void doPacking(cCommBuffer *b, RealWorldTestMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RealWorldTestMessage& obj) {obj.parsimUnpack(b);}


#endif // _REALWORLDTESTMESSAGE_M_H_
