OverSim: ALMTestTracedMessage_m.h File Reference
ALMTestTracedMessage_m.h File Reference
#include <omnetpp.h>
#include <OverlayKey.h>
Classes
class ALMTestTracedMessage
Class generated from applications/almtest/ALMTestTracedMessage.msg by opp_msgc.
Defines
#define MSGC_VERSION 0x0403
Functions
void doPacking (cCommBuffer *b, ALMTestTracedMessage &obj)
void doUnpacking (cCommBuffer *b, ALMTestTracedMessage &obj)
Define Documentation
#define MSGC_VERSION 0x0403
Definition at line 11 of file ALMTestTracedMessage_m.h.
Function Documentation
void doPacking (cCommBuffer * b, ALMTestTracedMessage & obj) [inline]
Definition at line 79 of file ALMTestTracedMessage_m.h.
Referenced by doPacking(), BinaryValue::netPack(), Vector2D::netPack(), HNode::netPack(), NodeHandle::netPack(), and OverlayKey::netPack().
{obj.parsimPack(b);}
void doUnpacking (cCommBuffer * b, ALMTestTracedMessage & obj) [inline]
Definition at line 80 of file ALMTestTracedMessage_m.h.
Referenced by doUnpacking(), BinaryValue::netUnpack(), Vector2D::netUnpack(), HNode::netUnpack(), NodeHandle::netUnpack(), and OverlayKey::netUnpack().
{obj.parsimUnpack(b);}