OverSim: RttToNodeResponse Class Reference
RttToNodeResponse Class Reference
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
#include <CoordMessages_m.h>
Public Member Functions
RttToNodeResponse (const char *name=NULL, int kind=0)
RttToNodeResponse (const RttToNodeResponse &other)
virtual ~RttToNodeResponse ()
RttToNodeResponse & operator= (const RttToNodeResponse &other)
virtual RttToNodeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getPingedNode ()
virtual const TransportAddress & getPingedNode () const
virtual void setPingedNode (const TransportAddress &pingedNode)
virtual void setOwnCoordinatesArraySize (unsigned int size)
virtual unsigned int getOwnCoordinatesArraySize () const
virtual double getOwnCoordinates (unsigned int k) const
virtual void setOwnCoordinates (unsigned int k, double ownCoordinates)
virtual simtime_t getRttToNode () const
virtual void setRttToNode (simtime_t rttToNode)
Protected Member Functions
bool operator== (const RttToNodeResponse &)
Protected Attributes
TransportAddress pingedNode_var
double * ownCoordinates_var
unsigned int ownCoordinates_arraysize
simtime_t rttToNode_var
Private Member Functions
void copy (const RttToNodeResponse &other)
Detailed Description
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
 packet RttToNodeResponse extends BaseResponseMessage
 {
     TransportAddress pingedNode;
     double ownCoordinates[];
     simtime_t rttToNode;
 }
Definition at line 151 of file CoordMessages_m.h.
Constructor & Destructor Documentation
RttToNodeResponse::RttToNodeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
RttToNodeResponse::RttToNodeResponse (const RttToNodeResponse & other)
virtual RttToNodeResponse::~RttToNodeResponse () [virtual]
Member Function Documentation
void RttToNodeResponse::copy (const RttToNodeResponse & other) [private]
virtual RttToNodeResponse* RttToNodeResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 171 of file CoordMessages_m.h.
{return new RttToNodeResponse(*this);}
virtual double RttToNodeResponse::getOwnCoordinates (unsigned int k) const [virtual]
virtual unsigned int RttToNodeResponse::getOwnCoordinatesArraySize () const [virtual]
virtual TransportAddress& RttToNodeResponse::getPingedNode () [virtual]
virtual const TransportAddress& RttToNodeResponse::getPingedNode () const [inline, virtual]
Definition at line 177 of file CoordMessages_m.h.
Referenced by getPingedNode().
{return const_cast<RttToNodeResponse*>(this)->getPingedNode();}
virtual simtime_t RttToNodeResponse::getRttToNode () const [virtual]
RttToNodeResponse& RttToNodeResponse::operator= (const RttToNodeResponse & other)
bool RttToNodeResponse::operator== (const RttToNodeResponse &) [protected]
virtual void RttToNodeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void RttToNodeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void RttToNodeResponse::setOwnCoordinates (unsigned int k, double ownCoordinates) [virtual]
Referenced by Nps::coordsReqRpcResponse(), and Nps::handleRpcTimeout().
virtual void RttToNodeResponse::setOwnCoordinatesArraySize (unsigned int size) [virtual]
Referenced by Nps::coordsReqRpcResponse(), and Nps::handleRpcTimeout().
virtual void RttToNodeResponse::setPingedNode (const TransportAddress & pingedNode) [virtual]
Referenced by Nps::coordsReqRpcResponse(), and Nps::handleRpcTimeout().
virtual void RttToNodeResponse::setRttToNode (simtime_t rttToNode) [virtual]
Referenced by Nps::coordsReqRpcResponse(), and Nps::handleRpcTimeout().
Member Data Documentation
unsigned int RttToNodeResponse::ownCoordinates_arraysize [protected]
Definition at line 156 of file CoordMessages_m.h.
double* RttToNodeResponse::ownCoordinates_var [protected]
Definition at line 155 of file CoordMessages_m.h.
TransportAddress RttToNodeResponse::pingedNode_var [protected]
Definition at line 154 of file CoordMessages_m.h.
simtime_t RttToNodeResponse::rttToNode_var [protected]
Definition at line 157 of file CoordMessages_m.h.
The documentation for this class was generated from the following file:
CoordMessages_m.h