OverSim: GIAput Class Reference
GIAput Class Reference
Class generated from common/ExtAPIMessages.msg by opp_msgc.
#include <ExtAPIMessages_m.h>
Public Member Functions
GIAput (const char *name=NULL, int kind=0)
GIAput (const GIAput &other)
virtual ~GIAput ()
GIAput & operator= (const GIAput &other)
virtual GIAput * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setKeysArraySize (unsigned int size)
virtual unsigned int getKeysArraySize () const
virtual OverlayKey & getKeys (unsigned int k)
virtual const OverlayKey & getKeys (unsigned int k) const
virtual void setKeys (unsigned int k, const OverlayKey &keys)
Protected Member Functions
bool operator== (const GIAput &)
Protected Attributes
OverlayKey * keys_var
unsigned int keys_arraysize
Private Member Functions
void copy (const GIAput &other)
Detailed Description
Class generated from common/ExtAPIMessages.msg by opp_msgc.
 packet GIAput extends GIASearchAppMessage
 {
         OverlayKey keys[];
 }
Definition at line 93 of file ExtAPIMessages_m.h.
Constructor & Destructor Documentation
GIAput::GIAput (const char * name = NULL, int kind = 0)
Referenced by dup().
GIAput::GIAput (const GIAput & other)
virtual GIAput::~GIAput () [virtual]
Member Function Documentation
void GIAput::copy (const GIAput & other) [private]
virtual GIAput* GIAput::dup () const [inline, virtual]
Reimplemented from GIASearchAppMessage.
Definition at line 111 of file ExtAPIMessages_m.h.
{return new GIAput(*this);}
virtual OverlayKey& GIAput::getKeys (unsigned int k) [virtual]
Referenced by Gia::handleAppMessage().
virtual const OverlayKey& GIAput::getKeys (unsigned int k) const [inline, virtual]
Definition at line 119 of file ExtAPIMessages_m.h.
Referenced by getKeys().
{return const_cast<GIAput*>(this)->getKeys(k);}
virtual unsigned int GIAput::getKeysArraySize () const [virtual]
Referenced by Gia::handleAppMessage().
GIAput& GIAput::operator= (const GIAput & other)
bool GIAput::operator== (const GIAput &) [protected]
virtual void GIAput::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GIASearchAppMessage.
Referenced by doPacking().
virtual void GIAput::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GIASearchAppMessage.
Referenced by doUnpacking().
virtual void GIAput::setKeys (unsigned int k, const OverlayKey & keys) [virtual]
Referenced by GIASearchApp::handleTimerEvent().
virtual void GIAput::setKeysArraySize (unsigned int size) [virtual]
Referenced by GIASearchApp::handleTimerEvent().
Member Data Documentation
unsigned int GIAput::keys_arraysize [protected]
Definition at line 97 of file ExtAPIMessages_m.h.
OverlayKey* GIAput::keys_var [protected]
Definition at line 96 of file ExtAPIMessages_m.h.
The documentation for this class was generated from the following file:
ExtAPIMessages_m.h