OverSim: GIAanswer Class Reference
GIAanswer Class Reference
Class generated from common/ExtAPIMessages.msg by opp_msgc.
#include <ExtAPIMessages_m.h>
Public Member Functions
GIAanswer (const char *name=NULL, int kind=0)
GIAanswer (const GIAanswer &other)
virtual ~GIAanswer ()
GIAanswer & operator= (const GIAanswer &other)
virtual GIAanswer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getSearchKey ()
virtual const OverlayKey & getSearchKey () const
virtual void setSearchKey (const OverlayKey &searchKey)
virtual NodeHandle & getNode ()
virtual const NodeHandle & getNode () const
virtual void setNode (const NodeHandle &node)
Protected Member Functions
bool operator== (const GIAanswer &)
Protected Attributes
OverlayKey searchKey_var
NodeHandle node_var
Private Member Functions
void copy (const GIAanswer &other)
Detailed Description
Class generated from common/ExtAPIMessages.msg by opp_msgc.
 packet GIAanswer extends GIASearchAppMessage
 {
        OverlayKey searchKey;
     NodeHandle node;
 }
Definition at line 213 of file ExtAPIMessages_m.h.
Constructor & Destructor Documentation
GIAanswer::GIAanswer (const char * name = NULL, int kind = 0)
Referenced by dup().
GIAanswer::GIAanswer (const GIAanswer & other)
virtual GIAanswer::~GIAanswer () [virtual]
Member Function Documentation
void GIAanswer::copy (const GIAanswer & other) [private]
virtual GIAanswer* GIAanswer::dup () const [inline, virtual]
Reimplemented from GIASearchAppMessage.
Definition at line 231 of file ExtAPIMessages_m.h.
{return new GIAanswer(*this);}
virtual NodeHandle& GIAanswer::getNode () [virtual]
Referenced by GIASearchApp::handleLowerMessage().
virtual const NodeHandle& GIAanswer::getNode () const [inline, virtual]
Definition at line 240 of file ExtAPIMessages_m.h.
Referenced by getNode().
{return const_cast<GIAanswer*>(this)->getNode();}
virtual OverlayKey& GIAanswer::getSearchKey () [virtual]
Referenced by GIASearchApp::handleLowerMessage().
virtual const OverlayKey& GIAanswer::getSearchKey () const [inline, virtual]
Definition at line 237 of file ExtAPIMessages_m.h.
Referenced by getSearchKey().
{return const_cast<GIAanswer*>(this)->getSearchKey();}
GIAanswer& GIAanswer::operator= (const GIAanswer & other)
bool GIAanswer::operator== (const GIAanswer &) [protected]
virtual void GIAanswer::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GIASearchAppMessage.
Referenced by doPacking().
virtual void GIAanswer::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GIASearchAppMessage.
Referenced by doUnpacking().
virtual void GIAanswer::setNode (const NodeHandle & node) [virtual]
Referenced by Gia::deliverSearchResult().
virtual void GIAanswer::setSearchKey (const OverlayKey & searchKey) [virtual]
Referenced by Gia::deliverSearchResult().
Member Data Documentation
NodeHandle GIAanswer::node_var [protected]
Definition at line 217 of file ExtAPIMessages_m.h.
OverlayKey GIAanswer::searchKey_var [protected]
Definition at line 216 of file ExtAPIMessages_m.h.
The documentation for this class was generated from the following file:
ExtAPIMessages_m.h