OverSim: KeyListMessage Class Reference
KeyListMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
KeyListMessage (const char *name=NULL, int kind=0)
KeyListMessage (const KeyListMessage &other)
virtual ~KeyListMessage ()
KeyListMessage & operator= (const KeyListMessage &other)
virtual KeyListMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setKeysArraySize (unsigned int size)
virtual unsigned int getKeysArraySize () const
virtual OverlayKey & getKeys (unsigned int k)
virtual const OverlayKey & getKeys (unsigned int k) const
virtual void setKeys (unsigned int k, const OverlayKey &keys)
Protected Member Functions
bool operator== (const KeyListMessage &)
Protected Attributes
OverlayKey * keys_var
unsigned int keys_arraysize
Private Member Functions
void copy (const KeyListMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message KeyListMessage extends GiaMessage
 {
        OverlayKey keys[];
 };
Definition at line 320 of file GiaMessage_m.h.
Constructor & Destructor Documentation
KeyListMessage::KeyListMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
KeyListMessage::KeyListMessage (const KeyListMessage & other)
virtual KeyListMessage::~KeyListMessage () [virtual]
Member Function Documentation
void KeyListMessage::copy (const KeyListMessage & other) [private]
virtual KeyListMessage* KeyListMessage::dup () const [inline, virtual]
Reimplemented from GiaMessage.
Definition at line 338 of file GiaMessage_m.h.
{return new KeyListMessage(*this);}
virtual OverlayKey& KeyListMessage::getKeys (unsigned int k) [virtual]
Referenced by Gia::handleUDPMessage().
virtual const OverlayKey& KeyListMessage::getKeys (unsigned int k) const [inline, virtual]
Definition at line 346 of file GiaMessage_m.h.
Referenced by getKeys().
{return const_cast<KeyListMessage*>(this)->getKeys(k);}
virtual unsigned int KeyListMessage::getKeysArraySize () const [virtual]
Referenced by Gia::handleUDPMessage().
KeyListMessage& KeyListMessage::operator= (const KeyListMessage & other)
bool KeyListMessage::operator== (const KeyListMessage &) [protected]
virtual void KeyListMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Referenced by doPacking().
virtual void KeyListMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Referenced by doUnpacking().
virtual void KeyListMessage::setKeys (unsigned int k, const OverlayKey & keys) [virtual]
Referenced by Gia::sendKeyListToNeighbor().
virtual void KeyListMessage::setKeysArraySize (unsigned int size) [virtual]
Referenced by Gia::sendKeyListToNeighbor().
Member Data Documentation
unsigned int KeyListMessage::keys_arraysize [protected]
Definition at line 324 of file GiaMessage_m.h.
OverlayKey* KeyListMessage::keys_var [protected]
Definition at line 323 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h