OverSim: DeBruijnCall Class Reference
DeBruijnCall Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
DeBruijnCall (const char *name=NULL, int kind=0)
DeBruijnCall (const DeBruijnCall &other)
virtual ~DeBruijnCall ()
DeBruijnCall & operator= (const DeBruijnCall &other)
virtual DeBruijnCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
Protected Member Functions
bool operator== (const DeBruijnCall &)
Protected Attributes
OverlayKey destKey_var
Private Member Functions
void copy (const DeBruijnCall &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet DeBruijnCall extends BaseCallMessage
 {
     OverlayKey destKey;
 }
Definition at line 537 of file ChordMessage_m.h.
Constructor & Destructor Documentation
DeBruijnCall::DeBruijnCall (const char * name = NULL, int kind = 0)
Referenced by dup().
DeBruijnCall::DeBruijnCall (const DeBruijnCall & other)
virtual DeBruijnCall::~DeBruijnCall () [virtual]
Member Function Documentation
void DeBruijnCall::copy (const DeBruijnCall & other) [private]
virtual DeBruijnCall* DeBruijnCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 554 of file ChordMessage_m.h.
{return new DeBruijnCall(*this);}
virtual OverlayKey& DeBruijnCall::getDestKey () [virtual]
Referenced by oversim::Koorde::handleDeBruijnTimerExpired(), and oversim::Koorde::handleRpcDeBruijnRequest().
virtual const OverlayKey& DeBruijnCall::getDestKey () const [inline, virtual]
Definition at line 560 of file ChordMessage_m.h.
Referenced by getDestKey().
{return const_cast<DeBruijnCall*>(this)->getDestKey();}
DeBruijnCall& DeBruijnCall::operator= (const DeBruijnCall & other)
bool DeBruijnCall::operator== (const DeBruijnCall &) [protected]
virtual void DeBruijnCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void DeBruijnCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void DeBruijnCall::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by oversim::Koorde::handleDeBruijnTimerExpired().
Member Data Documentation
OverlayKey DeBruijnCall::destKey_var [protected]
Definition at line 540 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h