OverSim: DhtDumpEntry Class Reference
DhtDumpEntry Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
DhtDumpEntry ()
DhtDumpEntry (const DhtDumpEntry &other)
virtual ~DhtDumpEntry ()
DhtDumpEntry & operator= (const DhtDumpEntry &other)
virtual DhtDumpEntry * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
virtual BinaryValue & getValue ()
virtual const BinaryValue & getValue () const
virtual void setValue (const BinaryValue &value)
virtual int getTtl () const
virtual void setTtl (int ttl)
virtual NodeHandle & getOwnerNode ()
virtual const NodeHandle & getOwnerNode () const
virtual void setOwnerNode (const NodeHandle &ownerNode)
virtual bool getIs_modifiable () const
virtual void setIs_modifiable (bool is_modifiable)
virtual bool getResponsible () const
virtual void setResponsible (bool responsible)
Protected Member Functions
bool operator== (const DhtDumpEntry &)
Protected Attributes
OverlayKey key_var
uint32_t kind_var
uint32_t id_var
BinaryValue value_var
int ttl_var
NodeHandle ownerNode_var
bool is_modifiable_var
bool responsible_var
Private Member Functions
void copy (const DhtDumpEntry &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 class DhtDumpEntry
 {
     OverlayKey key;
     uint32_t kind;
     uint32_t id;
     BinaryValue value;
     int ttl;
     NodeHandle ownerNode;
     bool is_modifiable;
     bool responsible;
 }
Definition at line 1331 of file CommonMessages_m.h.
Constructor & Destructor Documentation
DhtDumpEntry::DhtDumpEntry ()
Referenced by dup().
DhtDumpEntry::DhtDumpEntry (const DhtDumpEntry & other)
virtual DhtDumpEntry::~DhtDumpEntry () [virtual]
Member Function Documentation
void DhtDumpEntry::copy (const DhtDumpEntry & other) [private]
virtual DhtDumpEntry* DhtDumpEntry::dup () const [inline, virtual]
Definition at line 1355 of file CommonMessages_m.h.
{return new DhtDumpEntry(*this);}
virtual uint32_t DhtDumpEntry::getId () const [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse().
virtual bool DhtDumpEntry::getIs_modifiable () const [virtual]
virtual OverlayKey& DhtDumpEntry::getKey () [virtual]
virtual const OverlayKey& DhtDumpEntry::getKey () const [inline, virtual]
Definition at line 1361 of file CommonMessages_m.h.
Referenced by getKey().
{return const_cast<DhtDumpEntry*>(this)->getKey();}
virtual uint32_t DhtDumpEntry::getKind () const [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse().
virtual NodeHandle& DhtDumpEntry::getOwnerNode () [virtual]
virtual const NodeHandle& DhtDumpEntry::getOwnerNode () const [inline, virtual]
Definition at line 1373 of file CommonMessages_m.h.
Referenced by getOwnerNode().
{return const_cast<DhtDumpEntry*>(this)->getOwnerNode();}
virtual bool DhtDumpEntry::getResponsible () const [virtual]
virtual int DhtDumpEntry::getTtl () const [virtual]
virtual BinaryValue& DhtDumpEntry::getValue () [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), CBRDHT::handleGetResponse(), DHTTestApp::handleGetResponse(), XmlRpcInterface::handleRpcResponse(), CBRDHT::resultValuesBitLength(), and DHT::resultValuesBitLength().
virtual const BinaryValue& DhtDumpEntry::getValue () const [inline, virtual]
Definition at line 1368 of file CommonMessages_m.h.
Referenced by getValue().
{return const_cast<DhtDumpEntry*>(this)->getValue();}
DhtDumpEntry& DhtDumpEntry::operator= (const DhtDumpEntry & other)
bool DhtDumpEntry::operator== (const DhtDumpEntry &) [protected]
virtual void DhtDumpEntry::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void DhtDumpEntry::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void DhtDumpEntry::setId (uint32_t id) [virtual]
Referenced by DHTDataStorage::dumpDht().
virtual void DhtDumpEntry::setIs_modifiable (bool is_modifiable) [virtual]
Referenced by DHTDataStorage::dumpDht().
virtual void DhtDumpEntry::setKey (const OverlayKey & key) [virtual]
Referenced by DHTDataStorage::dumpDht(), CBRDHT::handleGetRequest(), CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), and CBRDHT::handleRpcTimeout().
virtual void DhtDumpEntry::setKind (uint32_t kind) [virtual]
Referenced by DHTDataStorage::dumpDht().
virtual void DhtDumpEntry::setOwnerNode (const NodeHandle & ownerNode) [virtual]
Referenced by DHTDataStorage::dumpDht().
virtual void DhtDumpEntry::setResponsible (bool responsible) [virtual]
Referenced by DHTDataStorage::dumpDht().
virtual void DhtDumpEntry::setTtl (int ttl) [virtual]
Referenced by DHTDataStorage::dumpDht().
virtual void DhtDumpEntry::setValue (const BinaryValue & value) [virtual]
Referenced by DHTDataStorage::dumpDht(), CBRDHT::handleGetRequest(), CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), and CBRDHT::handleRpcTimeout().
Member Data Documentation
uint32_t DhtDumpEntry::id_var [protected]
Definition at line 1336 of file CommonMessages_m.h.
bool DhtDumpEntry::is_modifiable_var [protected]
Definition at line 1340 of file CommonMessages_m.h.
OverlayKey DhtDumpEntry::key_var [protected]
Definition at line 1334 of file CommonMessages_m.h.
uint32_t DhtDumpEntry::kind_var [protected]
Definition at line 1335 of file CommonMessages_m.h.
NodeHandle DhtDumpEntry::ownerNode_var [protected]
Definition at line 1339 of file CommonMessages_m.h.
bool DhtDumpEntry::responsible_var [protected]
Definition at line 1341 of file CommonMessages_m.h.
int DhtDumpEntry::ttl_var [protected]
Definition at line 1338 of file CommonMessages_m.h.
BinaryValue DhtDumpEntry::value_var [protected]
Definition at line 1337 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h