OverSim: SearchResponseMessage Class Reference
SearchResponseMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
SearchResponseMessage (const char *name=NULL, int kind=0)
SearchResponseMessage (const SearchResponseMessage &other)
virtual ~SearchResponseMessage ()
SearchResponseMessage & operator= (const SearchResponseMessage &other)
virtual SearchResponseMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getSearchKey ()
virtual const OverlayKey & getSearchKey () const
virtual void setSearchKey (const OverlayKey &searchKey)
virtual void setReversePathArraySize (unsigned int size)
virtual unsigned int getReversePathArraySize () const
virtual OverlayKey & getReversePath (unsigned int k)
virtual const OverlayKey & getReversePath (unsigned int k) const
virtual void setReversePath (unsigned int k, const OverlayKey &reversePath)
virtual GiaNode & getFoundNode ()
virtual const GiaNode & getFoundNode () const
virtual void setFoundNode (const GiaNode &foundNode)
virtual int getSearchHopCount () const
virtual void setSearchHopCount (int searchHopCount)
Protected Member Functions
bool operator== (const SearchResponseMessage &)
Protected Attributes
OverlayKey searchKey_var
OverlayKey * reversePath_var
unsigned int reversePath_arraysize
GiaNode foundNode_var
int searchHopCount_var
Private Member Functions
void copy (const SearchResponseMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message SearchResponseMessage extends GiaIDMessage
 {
        OverlayKey searchKey;
        OverlayKey reversePath[];
        GiaNode foundNode;
        int searchHopCount;
 };
Definition at line 424 of file GiaMessage_m.h.
Constructor & Destructor Documentation
SearchResponseMessage::SearchResponseMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
SearchResponseMessage::SearchResponseMessage (const SearchResponseMessage & other)
virtual SearchResponseMessage::~SearchResponseMessage () [virtual]
Member Function Documentation
void SearchResponseMessage::copy (const SearchResponseMessage & other) [private]
virtual SearchResponseMessage* SearchResponseMessage::dup () const [inline, virtual]
Reimplemented from GiaIDMessage.
Definition at line 445 of file GiaMessage_m.h.
{return new SearchResponseMessage(*this);}
virtual GiaNode& SearchResponseMessage::getFoundNode () [virtual]
Referenced by Gia::deliverSearchResult().
virtual const GiaNode& SearchResponseMessage::getFoundNode () const [inline, virtual]
Definition at line 459 of file GiaMessage_m.h.
Referenced by getFoundNode().
{return const_cast<SearchResponseMessage*>(this)->getFoundNode();}
virtual OverlayKey& SearchResponseMessage::getReversePath (unsigned int k) [virtual]
Referenced by Gia::forwardSearchResponseMessage().
virtual const OverlayKey& SearchResponseMessage::getReversePath (unsigned int k) const [inline, virtual]
Definition at line 456 of file GiaMessage_m.h.
Referenced by getReversePath().
{return const_cast<SearchResponseMessage*>(this)->getReversePath(k);}
virtual unsigned int SearchResponseMessage::getReversePathArraySize () const [virtual]
Referenced by Gia::forwardSearchResponseMessage().
virtual int SearchResponseMessage::getSearchHopCount () const [virtual]
Referenced by Gia::deliverSearchResult().
virtual OverlayKey& SearchResponseMessage::getSearchKey () [virtual]
Referenced by Gia::deliverSearchResult().
virtual const OverlayKey& SearchResponseMessage::getSearchKey () const [inline, virtual]
Definition at line 451 of file GiaMessage_m.h.
Referenced by getSearchKey().
{return const_cast<SearchResponseMessage*>(this)->getSearchKey();}
SearchResponseMessage& SearchResponseMessage::operator= (const SearchResponseMessage & other)
bool SearchResponseMessage::operator== (const SearchResponseMessage &) [protected]
virtual void SearchResponseMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaIDMessage.
Referenced by doPacking().
virtual void SearchResponseMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaIDMessage.
Referenced by doUnpacking().
virtual void SearchResponseMessage::setFoundNode (const GiaNode & foundNode) [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual void SearchResponseMessage::setReversePath (unsigned int k, const OverlayKey & reversePath) [virtual]
Referenced by Gia::forwardSearchResponseMessage().
virtual void SearchResponseMessage::setReversePathArraySize (unsigned int size) [virtual]
Referenced by Gia::forwardSearchResponseMessage().
virtual void SearchResponseMessage::setSearchHopCount (int searchHopCount) [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual void SearchResponseMessage::setSearchKey (const OverlayKey & searchKey) [virtual]
Referenced by Gia::sendSearchResponseMessage().
Member Data Documentation
GiaNode SearchResponseMessage::foundNode_var [protected]
Definition at line 430 of file GiaMessage_m.h.
unsigned int SearchResponseMessage::reversePath_arraysize [protected]
Definition at line 429 of file GiaMessage_m.h.
OverlayKey* SearchResponseMessage::reversePath_var [protected]
Definition at line 428 of file GiaMessage_m.h.
int SearchResponseMessage::searchHopCount_var [protected]
Definition at line 431 of file GiaMessage_m.h.
OverlayKey SearchResponseMessage::searchKey_var [protected]
Definition at line 427 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h