OverSim: NTreePingCall Class Reference
NTreePingCall Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreePingCall (const char *name=NULL, int kind=0)
NTreePingCall (const NTreePingCall &other)
virtual ~NTreePingCall ()
NTreePingCall & operator= (const NTreePingCall &other)
virtual NTreePingCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual NodeHandle & getParent ()
virtual const NodeHandle & getParent () const
virtual void setParent (const NodeHandle &parent)
Protected Member Functions
bool operator== (const NTreePingCall &)
Protected Attributes
Vector2D origin_var
double size_var
NodeHandle parent_var
Private Member Functions
void copy (const NTreePingCall &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreePingCall extends BaseCallMessage
 {
         Vector2D origin;
         double size;
         NodeHandle parent;
 }
Definition at line 230 of file NTree_m.h.
Constructor & Destructor Documentation
NTreePingCall::NTreePingCall (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreePingCall::NTreePingCall (const NTreePingCall & other)
virtual NTreePingCall::~NTreePingCall () [virtual]
Member Function Documentation
void NTreePingCall::copy (const NTreePingCall & other) [private]
virtual NTreePingCall* NTreePingCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Reimplemented in NTreeNodePingCall.
Definition at line 249 of file NTree_m.h.
{return new NTreePingCall(*this);}
virtual Vector2D& NTreePingCall::getOrigin () [virtual]
Referenced by NTree::handlePingCall().
virtual const Vector2D& NTreePingCall::getOrigin () const [inline, virtual]
Definition at line 255 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreePingCall*>(this)->getOrigin();}
virtual NodeHandle& NTreePingCall::getParent () [virtual]
virtual const NodeHandle& NTreePingCall::getParent () const [inline, virtual]
Definition at line 260 of file NTree_m.h.
Referenced by getParent().
{return const_cast<NTreePingCall*>(this)->getParent();}
virtual double NTreePingCall::getSize () const [virtual]
Referenced by NTree::handlePingCall().
NTreePingCall& NTreePingCall::operator= (const NTreePingCall & other)
bool NTreePingCall::operator== (const NTreePingCall &) [protected]
virtual void NTreePingCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in NTreeNodePingCall.
Referenced by doPacking().
virtual void NTreePingCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in NTreeNodePingCall.
Referenced by doUnpacking().
virtual void NTreePingCall::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::pingNodes().
virtual void NTreePingCall::setParent (const NodeHandle & parent) [virtual]
Referenced by NTree::pingNodes().
virtual void NTreePingCall::setSize (double size) [virtual]
Referenced by NTree::pingNodes().
Member Data Documentation
Vector2D NTreePingCall::origin_var [protected]
Definition at line 233 of file NTree_m.h.
NodeHandle NTreePingCall::parent_var [protected]
Definition at line 235 of file NTree_m.h.
double NTreePingCall::size_var [protected]
Definition at line 234 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h