OverSim: PubSubHelpCall Class Reference
PubSubHelpCall Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubHelpCall (const char *name=NULL, int kind=0)
PubSubHelpCall (const PubSubHelpCall &other)
virtual ~PubSubHelpCall ()
PubSubHelpCall & operator= (const PubSubHelpCall &other)
virtual PubSubHelpCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual int getHelpType () const
virtual void setHelpType (int helpType)
Protected Member Functions
bool operator== (const PubSubHelpCall &)
Protected Attributes
int subspaceId_var
int helpType_var
Private Member Functions
void copy (const PubSubHelpCall &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubHelpCall extends BaseCallMessage
 {
         int subspaceId;
         int helpType enum(PubSubHelpType);
 }
Definition at line 530 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubHelpCall::PubSubHelpCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubHelpCall::PubSubHelpCall (const PubSubHelpCall & other)
virtual PubSubHelpCall::~PubSubHelpCall () [virtual]
Member Function Documentation
void PubSubHelpCall::copy (const PubSubHelpCall & other) [private]
virtual PubSubHelpCall* PubSubHelpCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 548 of file PubSubMessage_m.h.
{return new PubSubHelpCall(*this);}
virtual int PubSubHelpCall::getHelpType () const [virtual]
Referenced by PubSubLobby::handleHelpCall().
virtual int PubSubHelpCall::getSubspaceId () const [virtual]
Referenced by PubSubLobby::handleHelpCall().
PubSubHelpCall& PubSubHelpCall::operator= (const PubSubHelpCall & other)
bool PubSubHelpCall::operator== (const PubSubHelpCall &) [protected]
virtual void PubSubHelpCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PubSubHelpCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void PubSubHelpCall::setHelpType (int helpType) [virtual]
Referenced by PubSubMMOG::handleBackupCallTimeout(), PubSubMMOG::handlePingCallTimeout(), PubSubMMOG::handleSubscriptionCall(), and PubSubMMOG::takeOverSubspace().
virtual void PubSubHelpCall::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleBackupCallTimeout(), PubSubMMOG::handlePingCallTimeout(), PubSubMMOG::handleSubscriptionCall(), and PubSubMMOG::takeOverSubspace().
Member Data Documentation
int PubSubHelpCall::helpType_var [protected]
Definition at line 534 of file PubSubMessage_m.h.
int PubSubHelpCall::subspaceId_var [protected]
Definition at line 533 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h