OverSim: NTreeReplaceNodeMessage Class Reference
NTreeReplaceNodeMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeReplaceNodeMessage (const char *name=NULL, int kind=0)
NTreeReplaceNodeMessage (const NTreeReplaceNodeMessage &other)
virtual ~NTreeReplaceNodeMessage ()
NTreeReplaceNodeMessage & operator= (const NTreeReplaceNodeMessage &other)
virtual NTreeReplaceNodeMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual NodeHandle & getParent ()
virtual const NodeHandle & getParent () const
virtual void setParent (const NodeHandle &parent)
virtual void setChildrenArraySize (unsigned int size)
virtual unsigned int getChildrenArraySize () const
virtual NodeHandle & getChildren (unsigned int k)
virtual const NodeHandle & getChildren (unsigned int k) const
virtual void setChildren (unsigned int k, const NodeHandle &children)
virtual TransportAddress & getOldNode ()
virtual const TransportAddress & getOldNode () const
virtual void setOldNode (const TransportAddress &oldNode)
virtual bool getIsLeaf () const
virtual void setIsLeaf (bool isLeaf)
Protected Member Functions
bool operator== (const NTreeReplaceNodeMessage &)
Protected Attributes
Vector2D origin_var
double size_var
NodeHandle parent_var
NodeHandle * children_var
unsigned int children_arraysize
TransportAddress oldNode_var
bool isLeaf_var
Private Member Functions
void copy (const NTreeReplaceNodeMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeReplaceNodeMessage extends BaseOverlayMessage
 {
         Vector2D origin;
         double size;
         NodeHandle parent;
         NodeHandle children[];
         TransportAddress oldNode;
         bool isLeaf;
 }
Definition at line 634 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeReplaceNodeMessage::NTreeReplaceNodeMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeReplaceNodeMessage::NTreeReplaceNodeMessage (const NTreeReplaceNodeMessage & other)
virtual NTreeReplaceNodeMessage::~NTreeReplaceNodeMessage () [virtual]
Member Function Documentation
void NTreeReplaceNodeMessage::copy (const NTreeReplaceNodeMessage & other) [private]
virtual NTreeReplaceNodeMessage* NTreeReplaceNodeMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 657 of file NTree_m.h.
{return new NTreeReplaceNodeMessage(*this);}
virtual NodeHandle& NTreeReplaceNodeMessage::getChildren (unsigned int k) [virtual]
Referenced by NTree::checkParentTimeout(), NTree::handlePingCallTimeout(), and NTree::handleReplaceMessage().
virtual const NodeHandle& NTreeReplaceNodeMessage::getChildren (unsigned int k) const [inline, virtual]
Definition at line 673 of file NTree_m.h.
Referenced by getChildren().
{return const_cast<NTreeReplaceNodeMessage*>(this)->getChildren(k);}
virtual unsigned int NTreeReplaceNodeMessage::getChildrenArraySize () const [virtual]
Referenced by NTree::handleReplaceMessage().
virtual bool NTreeReplaceNodeMessage::getIsLeaf () const [virtual]
Referenced by NTree::handlePingCallTimeout(), and NTree::handleReplaceMessage().
virtual TransportAddress& NTreeReplaceNodeMessage::getOldNode () [virtual]
Referenced by NTree::handleReplaceMessage().
virtual const TransportAddress& NTreeReplaceNodeMessage::getOldNode () const [inline, virtual]
Definition at line 676 of file NTree_m.h.
Referenced by getOldNode().
{return const_cast<NTreeReplaceNodeMessage*>(this)->getOldNode();}
virtual Vector2D& NTreeReplaceNodeMessage::getOrigin () [virtual]
Referenced by NTree::handleReplaceMessage().
virtual const Vector2D& NTreeReplaceNodeMessage::getOrigin () const [inline, virtual]
Definition at line 663 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeReplaceNodeMessage*>(this)->getOrigin();}
virtual NodeHandle& NTreeReplaceNodeMessage::getParent () [virtual]
Referenced by NTree::handleReplaceMessage().
virtual const NodeHandle& NTreeReplaceNodeMessage::getParent () const [inline, virtual]
Definition at line 668 of file NTree_m.h.
Referenced by getParent().
{return const_cast<NTreeReplaceNodeMessage*>(this)->getParent();}
virtual double NTreeReplaceNodeMessage::getSize () const [virtual]
Referenced by NTree::handleReplaceMessage().
NTreeReplaceNodeMessage& NTreeReplaceNodeMessage::operator= (const NTreeReplaceNodeMessage & other)
bool NTreeReplaceNodeMessage::operator== (const NTreeReplaceNodeMessage &) [protected]
virtual void NTreeReplaceNodeMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeReplaceNodeMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeReplaceNodeMessage::setChildren (unsigned int k, const NodeHandle & children) [virtual]
Referenced by NTree::checkParentTimeout(), NTree::handleNodeGracefulLeaveNotification(), and NTree::handlePingCallTimeout().
virtual void NTreeReplaceNodeMessage::setChildrenArraySize (unsigned int size) [virtual]
Referenced by NTree::checkParentTimeout(), NTree::handleNodeGracefulLeaveNotification(), and NTree::handlePingCallTimeout().
virtual void NTreeReplaceNodeMessage::setIsLeaf (bool isLeaf) [virtual]
Referenced by NTree::checkParentTimeout(), NTree::handleNodeGracefulLeaveNotification(), and NTree::handlePingCallTimeout().
virtual void NTreeReplaceNodeMessage::setOldNode (const TransportAddress & oldNode) [virtual]
Referenced by NTree::checkParentTimeout(), and NTree::handlePingCallTimeout().
virtual void NTreeReplaceNodeMessage::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::checkParentTimeout(), NTree::handleNodeGracefulLeaveNotification(), and NTree::handlePingCallTimeout().
virtual void NTreeReplaceNodeMessage::setParent (const NodeHandle & parent) [virtual]
Referenced by NTree::handleNodeGracefulLeaveNotification(), and NTree::handlePingCallTimeout().
virtual void NTreeReplaceNodeMessage::setSize (double size) [virtual]
Referenced by NTree::checkParentTimeout(), NTree::handleNodeGracefulLeaveNotification(), and NTree::handlePingCallTimeout().
Member Data Documentation
unsigned int NTreeReplaceNodeMessage::children_arraysize [protected]
Definition at line 641 of file NTree_m.h.
NodeHandle* NTreeReplaceNodeMessage::children_var [protected]
Definition at line 640 of file NTree_m.h.
bool NTreeReplaceNodeMessage::isLeaf_var [protected]
Definition at line 643 of file NTree_m.h.
TransportAddress NTreeReplaceNodeMessage::oldNode_var [protected]
Definition at line 642 of file NTree_m.h.
Vector2D NTreeReplaceNodeMessage::origin_var [protected]
Definition at line 637 of file NTree_m.h.
NodeHandle NTreeReplaceNodeMessage::parent_var [protected]
Definition at line 639 of file NTree_m.h.
double NTreeReplaceNodeMessage::size_var [protected]
Definition at line 638 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h