OverSim: HGetParametersCall Class Reference
HGetParametersCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HGetParametersCall (const char *name=NULL, int kind=0)
HGetParametersCall (const HGetParametersCall &other)
virtual ~HGetParametersCall ()
HGetParametersCall & operator= (const HGetParametersCall &other)
virtual HGetParametersCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const HGetParametersCall &)
Private Member Functions
void copy (const HGetParametersCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HGetParametersCall extends BaseCallMessage {
 };
Definition at line 171 of file HMessage_m.h.
Constructor & Destructor Documentation
HGetParametersCall::HGetParametersCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HGetParametersCall::HGetParametersCall (const HGetParametersCall & other)
virtual HGetParametersCall::~HGetParametersCall () [virtual]
Member Function Documentation
void HGetParametersCall::copy (const HGetParametersCall & other) [private]
virtual HGetParametersCall* HGetParametersCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 187 of file HMessage_m.h.
{return new HGetParametersCall(*this);}
HGetParametersCall& HGetParametersCall::operator= (const HGetParametersCall & other)
bool HGetParametersCall::operator== (const HGetParametersCall &) [protected]
virtual void HGetParametersCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HGetParametersCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
HMessage_m.h