OverSim: HNode Class Reference
HNode Class Reference
#include <HNode.h>
Public Member Functions
HNode ()
Constructs an unspecified NodeHandle.
virtual ~HNode ()
Standard destructor.
HNode (const HNode &node)
Copy constructor.
HNode (const OverlayKey &key, const IPvXAddress &ip, int port)
Complete constructor.
HNode (const TransportAddress &ta)
Constructor to generate a NodeHandle from a TransportAddress.
HNode (const OverlayKey &key, const TransportAddress &ta)
Constructor to generate a NodeHandle from an existing OverlayKey and TransportAddress.
bool operator== (const HNode &rhs) const
compares this NodeHandle to another given NodeHandle
bool operator!= (const HNode &rhs) const
compares this NodeHandle to another given NodeHandle
bool operator< (const HNode &rhs) const
compares this to a given NodeHandle
bool operator> (const HNode &rhs) const
compares this to a given NodeHandle
bool operator<= (const HNode &rhs) const
compares this to a given NodeHandle
bool operator>= (const HNode &rhs) const
compares this to a given NodeHandle
HNode & operator= (const HNode &rhs)
assigns key, ip and port of rhs to this->key, this->ip and this->port
const OverlayKey getKey () const
returns key of this NodeHandle
const NodeHandle getHandle () const
const NodeVector getNodeVector () const
void setHandle (NodeHandle handle)
void setNodeVector (NodeVector nvector)
bool isUnspecified () const
indicates if this NodeHandle is specified
virtual void netPack (cCommBuffer *b)
serializes the object into a buffer
virtual void netUnpack (cCommBuffer *b)
deserializes the object from a buffer
virtual TransportAddress * dup () const
returns a copy of the NodeHandle
Static Public Attributes
static const HNode unspecifiedNode
the unspecified NodeHandle
Protected Attributes
NodeHandle handle
NodeVector children
Private Member Functions
void assertUnspecified (const HNode &node) const
throws an opp_error if this or handle is unspecified
Friends
std::ostream & operator<< (std::ostream &os, const HNode &n)
standard output stream for NodeHandle, gives out ip, port and key
Detailed Description
Definition at line 15 of file HNode.h.
Constructor & Destructor Documentation
HNode::HNode ()
Constructs an unspecified NodeHandle.
Definition at line 25 of file HNode.cc.
             {
    handle = NodeHandle();
    children = NodeVector();
}
virtual HNode::~HNode () [inline, virtual]
Standard destructor.
Definition at line 34 of file HNode.h.
{};
HNode::HNode (const HNode & node)
Copy constructor.
Parameters:
handle The NodeHandle to copy
Definition at line 31 of file HNode.cc.
{
    handle = node.handle;
    children = node.children;
}
HNode::HNode (const OverlayKey & key, const IPvXAddress & ip, int port)
Complete constructor.
Parameters:
key The OverlayKey
ip The IPvXAddress
port The UDP-Port
Definition at line 42 of file HNode.cc.
{
    children = NodeVector();
    handle = NodeHandle (key, ip, port);
}
HNode::HNode (const TransportAddress & ta)
Constructor to generate a NodeHandle from a TransportAddress.
The key will be unspecified.
Parameters:
ta transport address
Definition at line 36 of file HNode.cc.
{
    handle = NodeHandle (ta);
    children = NodeVector();
}
HNode::HNode (const OverlayKey & key, const TransportAddress & ta)
Constructor to generate a NodeHandle from an existing OverlayKey and TransportAddress.
Parameters:
key the overlay key
ta transport address
Definition at line 48 of file HNode.cc.
{
    children = NodeVector();
    handle = NodeHandle (key, ta);
}
Member Function Documentation
void HNode::assertUnspecified (const HNode & node) const [inline, private]
throws an opp_error if this or handle is unspecified
Parameters:
handle the NodeHandle to check
Definition at line 124 of file HNode.cc.
Referenced by operator!=(), operator<(), operator==(), and operator>().
{
    if ( this->isUnspecified() || node.isUnspecified() )
        opp_error("NodeHandle: Trying to compare unspecified NodeHandle!");
}
TransportAddress * HNode::dup () const [virtual]
returns a copy of the NodeHandle
Returns:
a copy of the NodeHandle
Definition at line 142 of file HNode.cc.
{
    return new NodeHandle(handle);
}
const NodeHandle HNode::getHandle () const
Definition at line 107 of file HNode.cc.
Referenced by HTopology::finishOverlay(), HTopology::getNodeHandle(), HTopology::goAheadWithRestSelectionProcess(), HTopology::handleJoinCall(), HTopology::handleLeaveCall(), HTopology::handleResponsibilityAsParentCall(), HTopology::handleSwitchToRescueModeCall(), HTopology::initializeNodesOneUp(), HTopology::setNodesOneUp(), and HTopology::updateTooltip().
{
    return handle;
}
const OverlayKey HNode::getKey () const
returns key of this NodeHandle
Returns:
the key of this NodeHandle
Definition at line 103 of file HNode.cc.
{
    return handle.getKey();
}
const NodeVector HNode::getNodeVector () const
Definition at line 111 of file HNode.cc.
{
    return children;
}
bool HNode::isUnspecified () const
indicates if this NodeHandle is specified
Returns:
true, if NodeHandle has no ip or key specified, false otherwise
Definition at line 54 of file HNode.cc.
Referenced by assertUnspecified(), HTopology::finishOverlay(), HTopology::handleJoinCall(), and HTopology::initializeNodesOneUp().
{
    return handle.isUnspecified();
}
void HNode::netPack (cCommBuffer * b) [virtual]
serializes the object into a buffer
Parameters:
b the buffer
Definition at line 130 of file HNode.cc.
{
    //cMessage::netPack(b);
    doPacking(b,this->handle);
    doPacking(b,this->children);
}
void HNode::netUnpack (cCommBuffer * b) [virtual]
deserializes the object from a buffer
Parameters:
b the buffer
Definition at line 136 of file HNode.cc.
{
    //cMessage::netUnpack(b);
    doUnpacking(b,this->handle);
    doUnpacking(b,this->children);
}
bool HNode::operator!= (const HNode & rhs) const
compares this NodeHandle to another given NodeHandle
Parameters:
rhs the NodeHandle this is compared to
Returns:
true if OverlayKey, IPvXAddress and port is not equal, false otherwise
Definition at line 73 of file HNode.cc.
{
    assertUnspecified( rhs );
    return !operator==(rhs);
}
bool HNode::operator< (const HNode & rhs) const
compares this to a given NodeHandle
Parameters:
rhs the NodeHandle this is compared to
Returns:
true if this->key is smaller than rhs->key, false otherwise
Definition at line 79 of file HNode.cc.
Referenced by operator>=().
{
    assertUnspecified(rhs);
    return handle < rhs.handle;
    // TODO do we need to take into account children?
}
bool HNode::operator<= (const HNode & rhs) const
compares this to a given NodeHandle
Parameters:
rhs the NodeHandle this is compared to
Returns:
true if this->key is smaller than or equal to rhs->key, false otherwise
Definition at line 93 of file HNode.cc.
{
    return !operator>(rhs);
}
HNode & HNode::operator= (const HNode & rhs)
assigns key, ip and port of rhs to this->key, this->ip and this->port
Parameters:
rhs the NodeHandle with the defined key, ip and port
Returns:
this NodeHandle object
Definition at line 59 of file HNode.cc.
{
    this->handle = rhs.handle;
    this->children = rhs.children;
    return *this;
}
bool HNode::operator== (const HNode & rhs) const
compares this NodeHandle to another given NodeHandle
Parameters:
rhs the NodeHandle this is compared to
Returns:
true if OverlayKey, IPvXAddress and port is equal, false otherwise
Definition at line 67 of file HNode.cc.
Referenced by operator!=().
{
    assertUnspecified(rhs);
    return (this->handle==rhs.handle && this->children==rhs.children);
}
bool HNode::operator> (const HNode & rhs) const
compares this to a given NodeHandle
Parameters:
rhs the NodeHandle this is compared to
Returns:
true if this->key is greater than rhs->key, false otherwise
Definition at line 86 of file HNode.cc.
Referenced by operator<=().
{
    assertUnspecified(rhs);
    return handle > rhs.handle;
    // TODO do we need to take into account children?
}
bool HNode::operator>= (const HNode & rhs) const
compares this to a given NodeHandle
Parameters:
rhs the NodeHandle this is compared to
Returns:
true if this->key is greater than or equal to rhs->key, false otherwise
Definition at line 98 of file HNode.cc.
{
    return !operator<(rhs);
}
void HNode::setHandle (NodeHandle handle)
Definition at line 115 of file HNode.cc.
Referenced by HTopology::goAheadWithRestSelectionProcess(), HTopology::handleJoinCall(), HTopology::handleNewParentSelectedCall(), HTopology::handleResponsibilityAsParentCall(), and HTopology::handleRpcResponse().
{
    this->handle = handle;
}
void HNode::setNodeVector (NodeVector nvector)
Definition at line 119 of file HNode.cc.
Referenced by HTopology::goAheadWithRestSelectionProcess().
{
    this->children = nvector;
}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const HNode & n) [friend]
standard output stream for NodeHandle, gives out ip, port and key
Parameters:
os the ostream
n the NodeHandle
Returns:
the output stream
Definition at line 14 of file HNode.cc.
{
    os << "thisNode:" << node.handle;
    for (int i=0; i<node.children.size(); ++i) {
        os << "child-" << i << ":" << node.children[i];
    }
    return os;
};
Member Data Documentation
NodeVector HNode::children [protected]
Definition at line 21 of file HNode.h.
Referenced by getNodeVector(), HNode(), netPack(), netUnpack(), operator<<(), operator=(), operator==(), and setNodeVector().
NodeHandle HNode::handle [protected]
Definition at line 17 of file HNode.h.
Referenced by dup(), getHandle(), getKey(), HNode(), isUnspecified(), netPack(), netUnpack(), operator<(), operator<<(), operator=(), operator==(), operator>(), and setHandle().
const HNode HNode::unspecifiedNode [static]
the unspecified NodeHandle
Definition at line 72 of file HNode.h.
Referenced by HTopology::changeState().
The documentation for this class was generated from the following files:
HNode.h
HNode.cc