OverSim: LookupListener Class Reference
LookupListener Class Reference
This class declares an abstract lookup listener.
#include <LookupListener.h>
Public Member Functions
virtual ~LookupListener ()
virtual destructor
virtual void lookupFinished (AbstractLookup *lookup)=0
Detailed Description
This class declares an abstract lookup listener.
Author:
Sebastian Mies
Definition at line 34 of file LookupListener.h.
Constructor & Destructor Documentation
LookupListener::~LookupListener () [virtual]
virtual destructor
Definition at line 38 of file IterativeLookup.cc.
{}
Member Function Documentation
virtual void LookupListener::lookupFinished (AbstractLookup * lookup) [pure virtual]
Implemented in SendToKeyListener, BambooLookupListener, KademliaLookupListener, Bamboo, and BrooseLookupListener.
Referenced by RecursiveLookup::handleRpcResponse(), RecursiveLookup::handleRpcTimeout(), and IterativeLookup::stop().
The documentation for this class was generated from the following files:
LookupListener.h
IterativeLookup.cc