OverSim: PubSubBackupCall Class Reference
PubSubBackupCall Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubBackupCall (const char *name=NULL, int kind=0)
PubSubBackupCall (const PubSubBackupCall &other)
virtual ~PubSubBackupCall ()
PubSubBackupCall & operator= (const PubSubBackupCall &other)
virtual PubSubBackupCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual void setIntermediatesArraySize (unsigned int size)
virtual unsigned int getIntermediatesArraySize () const
virtual NodeHandle & getIntermediates (unsigned int k)
virtual const NodeHandle & getIntermediates (unsigned int k) const
virtual void setIntermediates (unsigned int k, const NodeHandle &intermediates)
virtual void setChildrenArraySize (unsigned int size)
virtual unsigned int getChildrenArraySize () const
virtual NodeHandle & getChildren (unsigned int k)
virtual const NodeHandle & getChildren (unsigned int k) const
virtual void setChildren (unsigned int k, const NodeHandle &children)
virtual void setChildrenPosArraySize (unsigned int size)
virtual unsigned int getChildrenPosArraySize () const
virtual int getChildrenPos (unsigned int k) const
virtual void setChildrenPos (unsigned int k, int childrenPos)
Protected Member Functions
bool operator== (const PubSubBackupCall &)
Protected Attributes
int subspaceId_var
NodeHandle * intermediates_var
unsigned int intermediates_arraysize
NodeHandle * children_var
unsigned int children_arraysize
int * childrenPos_var
unsigned int childrenPos_arraysize
Private Member Functions
void copy (const PubSubBackupCall &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubBackupCall extends BaseCallMessage
 {
         int subspaceId;
         NodeHandle intermediates[];
         NodeHandle children[];
         int childrenPos[];
 }
Definition at line 697 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubBackupCall::PubSubBackupCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubBackupCall::PubSubBackupCall (const PubSubBackupCall & other)
virtual PubSubBackupCall::~PubSubBackupCall () [virtual]
Member Function Documentation
void PubSubBackupCall::copy (const PubSubBackupCall & other) [private]
virtual PubSubBackupCall* PubSubBackupCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 720 of file PubSubMessage_m.h.
{return new PubSubBackupCall(*this);}
virtual NodeHandle& PubSubBackupCall::getChildren (unsigned int k) [virtual]
Referenced by PubSubMMOG::handleBackupCall().
virtual const NodeHandle& PubSubBackupCall::getChildren (unsigned int k) const [inline, virtual]
Definition at line 735 of file PubSubMessage_m.h.
Referenced by getChildren().
{return const_cast<PubSubBackupCall*>(this)->getChildren(k);}
virtual unsigned int PubSubBackupCall::getChildrenArraySize () const [virtual]
Referenced by PubSubMMOG::handleBackupCall().
virtual int PubSubBackupCall::getChildrenPos (unsigned int k) const [virtual]
Referenced by PubSubMMOG::handleBackupCall().
virtual unsigned int PubSubBackupCall::getChildrenPosArraySize () const [virtual]
virtual NodeHandle& PubSubBackupCall::getIntermediates (unsigned int k) [virtual]
Referenced by PubSubMMOG::handleBackupCall().
virtual const NodeHandle& PubSubBackupCall::getIntermediates (unsigned int k) const [inline, virtual]
Definition at line 730 of file PubSubMessage_m.h.
Referenced by getIntermediates().
{return const_cast<PubSubBackupCall*>(this)->getIntermediates(k);}
virtual unsigned int PubSubBackupCall::getIntermediatesArraySize () const [virtual]
Referenced by PubSubMMOG::handleBackupCall().
virtual int PubSubBackupCall::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleBackupCall(), and PubSubMMOG::handleBackupCallTimeout().
PubSubBackupCall& PubSubBackupCall::operator= (const PubSubBackupCall & other)
bool PubSubBackupCall::operator== (const PubSubBackupCall &) [protected]
virtual void PubSubBackupCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PubSubBackupCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void PubSubBackupCall::setChildren (unsigned int k, const NodeHandle & children) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual void PubSubBackupCall::setChildrenArraySize (unsigned int size) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual void PubSubBackupCall::setChildrenPos (unsigned int k, int childrenPos) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual void PubSubBackupCall::setChildrenPosArraySize (unsigned int size) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual void PubSubBackupCall::setIntermediates (unsigned int k, const NodeHandle & intermediates) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual void PubSubBackupCall::setIntermediatesArraySize (unsigned int size) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual void PubSubBackupCall::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
Member Data Documentation
unsigned int PubSubBackupCall::children_arraysize [protected]
Definition at line 704 of file PubSubMessage_m.h.
NodeHandle* PubSubBackupCall::children_var [protected]
Definition at line 703 of file PubSubMessage_m.h.
unsigned int PubSubBackupCall::childrenPos_arraysize [protected]
Definition at line 706 of file PubSubMessage_m.h.
int* PubSubBackupCall::childrenPos_var [protected]
Definition at line 705 of file PubSubMessage_m.h.
unsigned int PubSubBackupCall::intermediates_arraysize [protected]
Definition at line 702 of file PubSubMessage_m.h.
NodeHandle* PubSubBackupCall::intermediates_var [protected]
Definition at line 701 of file PubSubMessage_m.h.
int PubSubBackupCall::subspaceId_var [protected]
Definition at line 700 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h