OverSim: PubSubResponsibleNodeCall Class Reference
PubSubResponsibleNodeCall Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubResponsibleNodeCall (const char *name=NULL, int kind=0)
PubSubResponsibleNodeCall (const PubSubResponsibleNodeCall &other)
virtual ~PubSubResponsibleNodeCall ()
PubSubResponsibleNodeCall & operator= (const PubSubResponsibleNodeCall &other)
virtual PubSubResponsibleNodeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getSubspacePos ()
virtual const Vector2D & getSubspacePos () const
virtual void setSubspacePos (const Vector2D &subspacePos)
Protected Member Functions
bool operator== (const PubSubResponsibleNodeCall &)
Protected Attributes
Vector2D subspacePos_var
Private Member Functions
void copy (const PubSubResponsibleNodeCall &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubResponsibleNodeCall extends BaseCallMessage
 {
         Vector2D subspacePos;
 }
Definition at line 250 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubResponsibleNodeCall::PubSubResponsibleNodeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubResponsibleNodeCall::PubSubResponsibleNodeCall (const PubSubResponsibleNodeCall & other)
virtual PubSubResponsibleNodeCall::~PubSubResponsibleNodeCall () [virtual]
Member Function Documentation
void PubSubResponsibleNodeCall::copy (const PubSubResponsibleNodeCall & other) [private]
virtual PubSubResponsibleNodeCall* PubSubResponsibleNodeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 267 of file PubSubMessage_m.h.
{return new PubSubResponsibleNodeCall(*this);}
virtual Vector2D& PubSubResponsibleNodeCall::getSubspacePos () [virtual]
Referenced by PubSubLobby::handleRespCall().
virtual const Vector2D& PubSubResponsibleNodeCall::getSubspacePos () const [inline, virtual]
Definition at line 273 of file PubSubMessage_m.h.
Referenced by getSubspacePos().
{return const_cast<PubSubResponsibleNodeCall*>(this)->getSubspacePos();}
PubSubResponsibleNodeCall& PubSubResponsibleNodeCall::operator= (const PubSubResponsibleNodeCall & other)
bool PubSubResponsibleNodeCall::operator== (const PubSubResponsibleNodeCall &) [protected]
virtual void PubSubResponsibleNodeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PubSubResponsibleNodeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void PubSubResponsibleNodeCall::setSubspacePos (const Vector2D & subspacePos) [virtual]
Referenced by PubSubMMOG::handleJoinResponse(), PubSubMMOG::handleMove(), and PubSubMMOG::handleSubscriptionCallTimeout().
Member Data Documentation
Vector2D PubSubResponsibleNodeCall::subspacePos_var [protected]
Definition at line 253 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h