OverSim: HLeaveOverlayCall Class Reference
HLeaveOverlayCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HLeaveOverlayCall (const char *name=NULL, int kind=0)
HLeaveOverlayCall (const HLeaveOverlayCall &other)
virtual ~HLeaveOverlayCall ()
HLeaveOverlayCall & operator= (const HLeaveOverlayCall &other)
virtual HLeaveOverlayCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const HLeaveOverlayCall &)
Private Member Functions
void copy (const HLeaveOverlayCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HLeaveOverlayCall extends BaseCallMessage {
 }
Definition at line 457 of file HMessage_m.h.
Constructor & Destructor Documentation
HLeaveOverlayCall::HLeaveOverlayCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HLeaveOverlayCall::HLeaveOverlayCall (const HLeaveOverlayCall & other)
virtual HLeaveOverlayCall::~HLeaveOverlayCall () [virtual]
Member Function Documentation
void HLeaveOverlayCall::copy (const HLeaveOverlayCall & other) [private]
virtual HLeaveOverlayCall* HLeaveOverlayCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 473 of file HMessage_m.h.
{return new HLeaveOverlayCall(*this);}
HLeaveOverlayCall& HLeaveOverlayCall::operator= (const HLeaveOverlayCall & other)
bool HLeaveOverlayCall::operator== (const HLeaveOverlayCall &) [protected]
virtual void HLeaveOverlayCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HLeaveOverlayCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
HMessage_m.h