OverSim: PastryFindNodeExtData Class Reference
PastryFindNodeExtData Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
PastryFindNodeExtData (const char *name=NULL, int kind=0)
PastryFindNodeExtData (const PastryFindNodeExtData &other)
virtual ~PastryFindNodeExtData ()
PastryFindNodeExtData & operator= (const PastryFindNodeExtData &other)
virtual PastryFindNodeExtData * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getSendStateTo ()
virtual const TransportAddress & getSendStateTo () const
virtual void setSendStateTo (const TransportAddress &sendStateTo)
virtual int getJoinHopCount () const
virtual void setJoinHopCount (int joinHopCount)
Protected Member Functions
bool operator== (const PastryFindNodeExtData &)
Protected Attributes
TransportAddress sendStateTo_var
int joinHopCount_var
Private Member Functions
void copy (const PastryFindNodeExtData &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet PastryFindNodeExtData
 {
     TransportAddress sendStateTo = TransportAddress::UNSPECIFIED_NODE;
     int joinHopCount = 0;
 }
Definition at line 174 of file PastryMessage_m.h.
Constructor & Destructor Documentation
PastryFindNodeExtData::PastryFindNodeExtData (const char * name = NULL, int kind = 0)
Referenced by dup().
PastryFindNodeExtData::PastryFindNodeExtData (const PastryFindNodeExtData & other)
virtual PastryFindNodeExtData::~PastryFindNodeExtData () [virtual]
Member Function Documentation
void PastryFindNodeExtData::copy (const PastryFindNodeExtData & other) [private]
virtual PastryFindNodeExtData* PastryFindNodeExtData::dup () const [inline, virtual]
Definition at line 192 of file PastryMessage_m.h.
{return new PastryFindNodeExtData(*this);}
virtual int PastryFindNodeExtData::getJoinHopCount () const [virtual]
Referenced by Pastry::iterativeJoinHook().
virtual TransportAddress& PastryFindNodeExtData::getSendStateTo () [virtual]
Referenced by Pastry::iterativeJoinHook().
virtual const TransportAddress& PastryFindNodeExtData::getSendStateTo () const [inline, virtual]
Definition at line 198 of file PastryMessage_m.h.
Referenced by getSendStateTo().
{return const_cast<PastryFindNodeExtData*>(this)->getSendStateTo();}
PastryFindNodeExtData& PastryFindNodeExtData::operator= (const PastryFindNodeExtData & other)
bool PastryFindNodeExtData::operator== (const PastryFindNodeExtData &) [protected]
virtual void PastryFindNodeExtData::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PastryFindNodeExtData::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void PastryFindNodeExtData::setJoinHopCount (int joinHopCount) [virtual]
Referenced by BasePastry::createLookup(), and Pastry::iterativeJoinHook().
virtual void PastryFindNodeExtData::setSendStateTo (const TransportAddress & sendStateTo) [virtual]
Referenced by BasePastry::createLookup().
Member Data Documentation
int PastryFindNodeExtData::joinHopCount_var [protected]
Definition at line 178 of file PastryMessage_m.h.
TransportAddress PastryFindNodeExtData::sendStateTo_var [protected]
Definition at line 177 of file PastryMessage_m.h.
The documentation for this class was generated from the following file:
PastryMessage_m.h