OverSim: FixfingersResponse Class Reference
FixfingersResponse Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
FixfingersResponse (const char *name=NULL, int kind=0)
FixfingersResponse (const FixfingersResponse &other)
virtual ~FixfingersResponse ()
FixfingersResponse & operator= (const FixfingersResponse &other)
virtual FixfingersResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getFinger () const
virtual void setFinger (int finger)
virtual void setSucNodeArraySize (unsigned int size)
virtual unsigned int getSucNodeArraySize () const
virtual NodeHandle & getSucNode (unsigned int k)
virtual const NodeHandle & getSucNode (unsigned int k) const
virtual void setSucNode (unsigned int k, const NodeHandle &sucNode)
Protected Member Functions
bool operator== (const FixfingersResponse &)
Protected Attributes
int finger_var
NodeHandle * sucNode_var
unsigned int sucNode_arraysize
Private Member Functions
void copy (const FixfingersResponse &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet FixfingersResponse extends BaseResponseMessage
 {
     int finger;
     NodeHandle sucNode[];
 }
Definition at line 449 of file ChordMessage_m.h.
Constructor & Destructor Documentation
FixfingersResponse::FixfingersResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
FixfingersResponse::FixfingersResponse (const FixfingersResponse & other)
virtual FixfingersResponse::~FixfingersResponse () [virtual]
Member Function Documentation
void FixfingersResponse::copy (const FixfingersResponse & other) [private]
virtual FixfingersResponse* FixfingersResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 468 of file ChordMessage_m.h.
{return new FixfingersResponse(*this);}
virtual int FixfingersResponse::getFinger () const [virtual]
Referenced by oversim::Chord::handleRpcFixfingersResponse().
virtual NodeHandle& FixfingersResponse::getSucNode (unsigned int k) [virtual]
Referenced by oversim::Chord::handleRpcFixfingersResponse().
virtual const NodeHandle& FixfingersResponse::getSucNode (unsigned int k) const [inline, virtual]
Definition at line 478 of file ChordMessage_m.h.
Referenced by getSucNode().
{return const_cast<FixfingersResponse*>(this)->getSucNode(k);}
virtual unsigned int FixfingersResponse::getSucNodeArraySize () const [virtual]
Referenced by oversim::Chord::handleRpcFixfingersResponse().
FixfingersResponse& FixfingersResponse::operator= (const FixfingersResponse & other)
bool FixfingersResponse::operator== (const FixfingersResponse &) [protected]
virtual void FixfingersResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void FixfingersResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void FixfingersResponse::setFinger (int finger) [virtual]
Referenced by oversim::Chord::rpcFixfingers().
virtual void FixfingersResponse::setSucNode (unsigned int k, const NodeHandle & sucNode) [virtual]
Referenced by oversim::Chord::rpcFixfingers().
virtual void FixfingersResponse::setSucNodeArraySize (unsigned int size) [virtual]
Referenced by oversim::Chord::rpcFixfingers().
Member Data Documentation
int FixfingersResponse::finger_var [protected]
Definition at line 452 of file ChordMessage_m.h.
unsigned int FixfingersResponse::sucNode_arraysize [protected]
Definition at line 454 of file ChordMessage_m.h.
NodeHandle* FixfingersResponse::sucNode_var [protected]
Definition at line 453 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h