OverSim: RequestRepairResponse Class Reference
RequestRepairResponse Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestRepairResponse (const char *name=NULL, int kind=0)
RequestRepairResponse (const RequestRepairResponse &other)
virtual ~RequestRepairResponse ()
RequestRepairResponse & operator= (const RequestRepairResponse &other)
virtual RequestRepairResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RequestRepairResponse &)
Private Member Functions
void copy (const RequestRepairResponse &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestRepairResponse extends BaseResponseMessage
 {
 }
Definition at line 466 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestRepairResponse::RequestRepairResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestRepairResponse::RequestRepairResponse (const RequestRepairResponse & other)
virtual RequestRepairResponse::~RequestRepairResponse () [virtual]
Member Function Documentation
void RequestRepairResponse::copy (const RequestRepairResponse & other) [private]
virtual RequestRepairResponse* RequestRepairResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 482 of file PastryMessage_m.h.
{return new RequestRepairResponse(*this);}
RequestRepairResponse& RequestRepairResponse::operator= (const RequestRepairResponse & other)
bool RequestRepairResponse::operator== (const RequestRepairResponse &) [protected]
virtual void RequestRepairResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void RequestRepairResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h