OverSim: FindNodeResponse Class Reference
FindNodeResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
FindNodeResponse (const char *name=NULL, int kind=0)
FindNodeResponse (const FindNodeResponse &other)
virtual ~FindNodeResponse ()
FindNodeResponse & operator= (const FindNodeResponse &other)
virtual FindNodeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getSiblings () const
virtual void setSiblings (bool siblings)
virtual void setClosestNodesArraySize (unsigned int size)
virtual unsigned int getClosestNodesArraySize () const
virtual NodeHandle & getClosestNodes (unsigned int k)
virtual const NodeHandle & getClosestNodes (unsigned int k) const
virtual void setClosestNodes (unsigned int k, const NodeHandle &closestNodes)
Protected Member Functions
bool operator== (const FindNodeResponse &)
Protected Attributes
bool siblings_var
NodeHandle * closestNodes_var
unsigned int closestNodes_arraysize
Private Member Functions
void copy (const FindNodeResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet FindNodeResponse extends BaseResponseMessage
 {
     bool siblings;
     NodeHandle closestNodes[];
 }
Definition at line 689 of file CommonMessages_m.h.
Constructor & Destructor Documentation
FindNodeResponse::FindNodeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
FindNodeResponse::FindNodeResponse (const FindNodeResponse & other)
virtual FindNodeResponse::~FindNodeResponse () [virtual]
Member Function Documentation
void FindNodeResponse::copy (const FindNodeResponse & other) [private]
virtual FindNodeResponse* FindNodeResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in ProxFindNodeResponse.
Definition at line 708 of file CommonMessages_m.h.
{return new FindNodeResponse(*this);}
virtual NodeHandle& FindNodeResponse::getClosestNodes (unsigned int k) [virtual]
Referenced by IterativePathLookup::handleResponse(), and RecursiveLookup::handleRpcResponse().
virtual const NodeHandle& FindNodeResponse::getClosestNodes (unsigned int k) const [inline, virtual]
Definition at line 718 of file CommonMessages_m.h.
Referenced by getClosestNodes().
{return const_cast<FindNodeResponse*>(this)->getClosestNodes(k);}
virtual unsigned int FindNodeResponse::getClosestNodesArraySize () const [virtual]
Referenced by IterativePathLookup::handleResponse(), and RecursiveLookup::handleRpcResponse().
virtual bool FindNodeResponse::getSiblings () const [virtual]
Referenced by IterativePathLookup::handleResponse(), RecursiveLookup::handleRpcResponse(), and IterativeLookup::handleRpcResponse().
FindNodeResponse& FindNodeResponse::operator= (const FindNodeResponse & other)
bool FindNodeResponse::operator== (const FindNodeResponse &) [protected]
virtual void FindNodeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in ProxFindNodeResponse.
Referenced by doPacking().
virtual void FindNodeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in ProxFindNodeResponse.
Referenced by doUnpacking().
virtual void FindNodeResponse::setClosestNodes (unsigned int k, const NodeHandle & closestNodes) [virtual]
Referenced by BaseOverlay::findNodeRpc().
virtual void FindNodeResponse::setClosestNodesArraySize (unsigned int size) [virtual]
Referenced by BaseOverlay::findNodeRpc().
virtual void FindNodeResponse::setSiblings (bool siblings) [virtual]
Referenced by BaseOverlay::findNodeRpc().
Member Data Documentation
unsigned int FindNodeResponse::closestNodes_arraysize [protected]
Definition at line 694 of file CommonMessages_m.h.
NodeHandle* FindNodeResponse::closestNodes_var [protected]
Definition at line 693 of file CommonMessages_m.h.
bool FindNodeResponse::siblings_var [protected]
Definition at line 692 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h