OverSim: PubSubBackupSubscriptionMessage Class Reference
PubSubBackupSubscriptionMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubBackupSubscriptionMessage (const char *name=NULL, int kind=0)
PubSubBackupSubscriptionMessage (const PubSubBackupSubscriptionMessage &other)
virtual ~PubSubBackupSubscriptionMessage ()
PubSubBackupSubscriptionMessage & operator= (const PubSubBackupSubscriptionMessage &other)
virtual
PubSubBackupSubscriptionMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getChild ()
virtual const NodeHandle & getChild () const
virtual void setChild (const NodeHandle &child)
virtual NodeHandle & getParent ()
virtual const NodeHandle & getParent () const
virtual void setParent (const NodeHandle &parent)
virtual NodeHandle & getOldParent ()
virtual const NodeHandle & getOldParent () const
virtual void setOldParent (const NodeHandle &oldParent)
Protected Member Functions
bool operator== (const PubSubBackupSubscriptionMessage &)
Protected Attributes
int subspaceId_var
NodeHandle child_var
NodeHandle parent_var
NodeHandle oldParent_var
Private Member Functions
void copy (const PubSubBackupSubscriptionMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubBackupSubscriptionMessage extends BaseOverlayMessage
 {
         int subspaceId;
         NodeHandle child;
         NodeHandle parent;
         NodeHandle oldParent;
 }
Definition at line 1168 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubBackupSubscriptionMessage::PubSubBackupSubscriptionMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubBackupSubscriptionMessage::PubSubBackupSubscriptionMessage (const PubSubBackupSubscriptionMessage & other)
virtual PubSubBackupSubscriptionMessage::~PubSubBackupSubscriptionMessage () [virtual]
Member Function Documentation
void PubSubBackupSubscriptionMessage::copy (const PubSubBackupSubscriptionMessage & other) [private]
virtual PubSubBackupSubscriptionMessage* PubSubBackupSubscriptionMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 1188 of file PubSubMessage_m.h.
{return new PubSubBackupSubscriptionMessage(*this);}
virtual NodeHandle& PubSubBackupSubscriptionMessage::getChild () [virtual]
Referenced by PubSubMMOG::handleSubscriptionBackup().
virtual const NodeHandle& PubSubBackupSubscriptionMessage::getChild () const [inline, virtual]
Definition at line 1196 of file PubSubMessage_m.h.
Referenced by getChild().
{return const_cast<PubSubBackupSubscriptionMessage*>(this)->getChild();}
virtual NodeHandle& PubSubBackupSubscriptionMessage::getOldParent () [virtual]
Referenced by PubSubMMOG::handleSubscriptionBackup().
virtual const NodeHandle& PubSubBackupSubscriptionMessage::getOldParent () const [inline, virtual]
Definition at line 1202 of file PubSubMessage_m.h.
Referenced by getOldParent().
{return const_cast<PubSubBackupSubscriptionMessage*>(this)->getOldParent();}
virtual NodeHandle& PubSubBackupSubscriptionMessage::getParent () [virtual]
Referenced by PubSubMMOG::handleSubscriptionBackup().
virtual const NodeHandle& PubSubBackupSubscriptionMessage::getParent () const [inline, virtual]
Definition at line 1199 of file PubSubMessage_m.h.
Referenced by getParent().
{return const_cast<PubSubBackupSubscriptionMessage*>(this)->getParent();}
virtual int PubSubBackupSubscriptionMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleSubscriptionBackup().
PubSubBackupSubscriptionMessage& PubSubBackupSubscriptionMessage::operator= (const PubSubBackupSubscriptionMessage & other)
bool PubSubBackupSubscriptionMessage::operator== (const PubSubBackupSubscriptionMessage &) [protected]
virtual void PubSubBackupSubscriptionMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubBackupSubscriptionMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubBackupSubscriptionMessage::setChild (const NodeHandle & child) [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse(), PubSubMMOG::handleIntermediateResponse(), PubSubMMOG::handlePingCallTimeout(), and PubSubMMOG::handleSubscriptionCall().
virtual void PubSubBackupSubscriptionMessage::setOldParent (const NodeHandle & oldParent) [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse(), and PubSubMMOG::handlePingCallTimeout().
virtual void PubSubBackupSubscriptionMessage::setParent (const NodeHandle & parent) [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse(), and PubSubMMOG::handleSubscriptionCall().
virtual void PubSubBackupSubscriptionMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse(), PubSubMMOG::handleIntermediateResponse(), PubSubMMOG::handlePingCallTimeout(), and PubSubMMOG::handleSubscriptionCall().
Member Data Documentation
NodeHandle PubSubBackupSubscriptionMessage::child_var [protected]
Definition at line 1172 of file PubSubMessage_m.h.
NodeHandle PubSubBackupSubscriptionMessage::oldParent_var [protected]
Definition at line 1174 of file PubSubMessage_m.h.
NodeHandle PubSubBackupSubscriptionMessage::parent_var [protected]
Definition at line 1173 of file PubSubMessage_m.h.
int PubSubBackupSubscriptionMessage::subspaceId_var [protected]
Definition at line 1171 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h