OverSim: TCPExampleMessage Class Reference
TCPExampleMessage Class Reference
Class generated from applications/tcpexampleapp/TCPExampleMessage.msg by opp_msgc.
#include <TCPExampleMessage_m.h>
Public Member Functions
TCPExampleMessage (const char *name=NULL, int kind=0)
TCPExampleMessage (const TCPExampleMessage &other)
virtual ~TCPExampleMessage ()
TCPExampleMessage & operator= (const TCPExampleMessage &other)
virtual TCPExampleMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type)
virtual TransportAddress & getSenderAddress ()
virtual const TransportAddress & getSenderAddress () const
virtual void setSenderAddress (const TransportAddress &senderAddress)
Protected Member Functions
bool operator== (const TCPExampleMessage &)
Protected Attributes
int type_var
TransportAddress senderAddress_var
Private Member Functions
void copy (const TCPExampleMessage &other)
Detailed Description
Class generated from applications/tcpexampleapp/TCPExampleMessage.msg by opp_msgc.
 packet TCPExampleMessage
 {
     int type enum(MessageType);
     TransportAddress senderAddress;
 }
Definition at line 47 of file TCPExampleMessage_m.h.
Constructor & Destructor Documentation
TCPExampleMessage::TCPExampleMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
TCPExampleMessage::TCPExampleMessage (const TCPExampleMessage & other)
virtual TCPExampleMessage::~TCPExampleMessage () [virtual]
Member Function Documentation
void TCPExampleMessage::copy (const TCPExampleMessage & other) [private]
virtual TCPExampleMessage* TCPExampleMessage::dup () const [inline, virtual]
Definition at line 65 of file TCPExampleMessage_m.h.
{return new TCPExampleMessage(*this);}
virtual TransportAddress& TCPExampleMessage::getSenderAddress () [virtual]
Referenced by TCPExampleApp::handleDataReceived().
virtual const TransportAddress& TCPExampleMessage::getSenderAddress () const [inline, virtual]
Definition at line 73 of file TCPExampleMessage_m.h.
Referenced by getSenderAddress().
{return const_cast<TCPExampleMessage*>(this)->getSenderAddress();}
virtual int TCPExampleMessage::getType () const [virtual]
Referenced by TCPExampleApp::handleDataReceived().
TCPExampleMessage& TCPExampleMessage::operator= (const TCPExampleMessage & other)
bool TCPExampleMessage::operator== (const TCPExampleMessage &) [protected]
virtual void TCPExampleMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TCPExampleMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void TCPExampleMessage::setSenderAddress (const TransportAddress & senderAddress) [virtual]
Referenced by TCPExampleApp::handleDataReceived(), and TCPExampleApp::handleTimerEvent().
virtual void TCPExampleMessage::setType (int type) [virtual]
Referenced by TCPExampleApp::handleDataReceived(), and TCPExampleApp::handleTimerEvent().
Member Data Documentation
TransportAddress TCPExampleMessage::senderAddress_var [protected]
Definition at line 51 of file TCPExampleMessage_m.h.
int TCPExampleMessage::type_var [protected]
Definition at line 50 of file TCPExampleMessage_m.h.
The documentation for this class was generated from the following file:
TCPExampleMessage_m.h