OverSim: NiceHeartbeat Class Reference
NiceHeartbeat Class Reference
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
#include <NiceMessage_m.h>
Public Member Functions
NiceHeartbeat (const char *name=NULL, int kind=0)
NiceHeartbeat (const NiceHeartbeat &other)
virtual ~NiceHeartbeat ()
NiceHeartbeat & operator= (const NiceHeartbeat &other)
virtual NiceHeartbeat * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getSeqNo () const
virtual void setSeqNo (unsigned int seqNo)
virtual unsigned int getSeqRspNo () const
virtual void setSeqRspNo (unsigned int seqRspNo)
virtual double getHb_delay () const
virtual void setHb_delay (double hb_delay)
virtual void setDistancesArraySize (unsigned int size)
virtual unsigned int getDistancesArraySize () const
virtual double getDistances (unsigned int k) const
virtual void setDistances (unsigned int k, double distances)
virtual double getOne_hop_distance () const
virtual void setOne_hop_distance (double one_hop_distance)
virtual unsigned int getSublayermembers () const
virtual void setSublayermembers (unsigned int sublayermembers)
Protected Member Functions
bool operator== (const NiceHeartbeat &)
Protected Attributes
unsigned int seqNo_var
unsigned int seqRspNo_var
double hb_delay_var
double * distances_var
unsigned int distances_arraysize
double one_hop_distance_var
unsigned int sublayermembers_var
Private Member Functions
void copy (const NiceHeartbeat &other)
Detailed Description
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
 message NiceHeartbeat extends NiceMemberMessage
 {
     unsigned int seqNo;
     unsigned int seqRspNo;
     double hb_delay;
     double distances[];
     double one_hop_distance;
     unsigned int sublayermembers;
 }
Definition at line 229 of file NiceMessage_m.h.
Constructor & Destructor Documentation
NiceHeartbeat::NiceHeartbeat (const char * name = NULL, int kind = 0)
Referenced by dup().
NiceHeartbeat::NiceHeartbeat (const NiceHeartbeat & other)
virtual NiceHeartbeat::~NiceHeartbeat () [virtual]
Member Function Documentation
void NiceHeartbeat::copy (const NiceHeartbeat & other) [private]
virtual NiceHeartbeat* NiceHeartbeat::dup () const [inline, virtual]
Reimplemented from NiceMemberMessage.
Reimplemented in NiceLeaderHeartbeat.
Definition at line 252 of file NiceMessage_m.h.
Referenced by oversim::Nice::sendHeartbeats().
{return new NiceHeartbeat(*this);}
virtual double NiceHeartbeat::getDistances (unsigned int k) const [virtual]
Referenced by oversim::Nice::handleNiceHeartbeat(), and oversim::Nice::handleNiceLeaderHeartbeat().
virtual unsigned int NiceHeartbeat::getDistancesArraySize () const [virtual]
virtual double NiceHeartbeat::getHb_delay () const [virtual]
Referenced by oversim::Nice::handleNiceHeartbeat(), and oversim::Nice::handleNiceLeaderHeartbeat().
virtual double NiceHeartbeat::getOne_hop_distance () const [virtual]
virtual unsigned int NiceHeartbeat::getSeqNo () const [virtual]
Referenced by oversim::Nice::handleNiceHeartbeat(), and oversim::Nice::handleNiceLeaderHeartbeat().
virtual unsigned int NiceHeartbeat::getSeqRspNo () const [virtual]
Referenced by oversim::Nice::handleNiceHeartbeat(), and oversim::Nice::handleNiceLeaderHeartbeat().
virtual unsigned int NiceHeartbeat::getSublayermembers () const [virtual]
Referenced by oversim::Nice::handleNiceHeartbeat().
NiceHeartbeat& NiceHeartbeat::operator= (const NiceHeartbeat & other)
bool NiceHeartbeat::operator== (const NiceHeartbeat &) [protected]
virtual void NiceHeartbeat::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from NiceMemberMessage.
Reimplemented in NiceLeaderHeartbeat.
Referenced by doPacking().
virtual void NiceHeartbeat::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from NiceMemberMessage.
Reimplemented in NiceLeaderHeartbeat.
Referenced by doUnpacking().
virtual void NiceHeartbeat::setDistances (unsigned int k, double distances) [virtual]
Referenced by oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceHeartbeat::setDistancesArraySize (unsigned int size) [virtual]
Referenced by oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceHeartbeat::setHb_delay (double hb_delay) [virtual]
Referenced by oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceHeartbeat::setOne_hop_distance (double one_hop_distance) [virtual]
Referenced by oversim::Nice::sendHeartbeats().
virtual void NiceHeartbeat::setSeqNo (unsigned int seqNo) [virtual]
Referenced by oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceHeartbeat::setSeqRspNo (unsigned int seqRspNo) [virtual]
Referenced by oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceHeartbeat::setSublayermembers (unsigned int sublayermembers) [virtual]
Referenced by oversim::Nice::sendHeartbeats().
Member Data Documentation
unsigned int NiceHeartbeat::distances_arraysize [protected]
Definition at line 236 of file NiceMessage_m.h.
double* NiceHeartbeat::distances_var [protected]
Definition at line 235 of file NiceMessage_m.h.
double NiceHeartbeat::hb_delay_var [protected]
Definition at line 234 of file NiceMessage_m.h.
double NiceHeartbeat::one_hop_distance_var [protected]
Definition at line 237 of file NiceMessage_m.h.
unsigned int NiceHeartbeat::seqNo_var [protected]
Definition at line 232 of file NiceMessage_m.h.
unsigned int NiceHeartbeat::seqRspNo_var [protected]
Definition at line 233 of file NiceMessage_m.h.
unsigned int NiceHeartbeat::sublayermembers_var [protected]
Definition at line 238 of file NiceMessage_m.h.
The documentation for this class was generated from the following file:
NiceMessage_m.h