OverSim: SendCoordinatesCall Class Reference
SendCoordinatesCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
SendCoordinatesCall (const char *name=NULL, int kind=0)
SendCoordinatesCall (const SendCoordinatesCall &other)
virtual ~SendCoordinatesCall ()
SendCoordinatesCall & operator= (const SendCoordinatesCall &other)
virtual SendCoordinatesCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual CoordDataContainer & getCoordData ()
virtual const CoordDataContainer & getCoordData () const
virtual void setCoordData (const CoordDataContainer &coordData)
Protected Member Functions
bool operator== (const SendCoordinatesCall &)
Protected Attributes
CoordDataContainer coordData_var
Private Member Functions
void copy (const SendCoordinatesCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet SendCoordinatesCall extends GlobalViewBuilderCall
 {
     CoordDataContainer coordData;
 }
Definition at line 415 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
SendCoordinatesCall::SendCoordinatesCall (const char * name = NULL, int kind = 0)
Referenced by dup().
SendCoordinatesCall::SendCoordinatesCall (const SendCoordinatesCall & other)
virtual SendCoordinatesCall::~SendCoordinatesCall () [virtual]
Member Function Documentation
void SendCoordinatesCall::copy (const SendCoordinatesCall & other) [private]
virtual SendCoordinatesCall* SendCoordinatesCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 432 of file TreeManagementMessage_m.h.
{return new SendCoordinatesCall(*this);}
virtual CoordDataContainer& SendCoordinatesCall::getCoordData () [virtual]
virtual const CoordDataContainer& SendCoordinatesCall::getCoordData () const [inline, virtual]
Definition at line 438 of file TreeManagementMessage_m.h.
Referenced by getCoordData().
{return const_cast<SendCoordinatesCall*>(this)->getCoordData();}
SendCoordinatesCall& SendCoordinatesCall::operator= (const SendCoordinatesCall & other)
bool SendCoordinatesCall::operator== (const SendCoordinatesCall &) [protected]
virtual void SendCoordinatesCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void SendCoordinatesCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void SendCoordinatesCall::setCoordData (const CoordDataContainer & coordData) [virtual]
Member Data Documentation
CoordDataContainer SendCoordinatesCall::coordData_var [protected]
Definition at line 418 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h