OverSim: HResponsibilityAsParentCall Class Reference
HResponsibilityAsParentCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HResponsibilityAsParentCall (const char *name=NULL, int kind=0)
HResponsibilityAsParentCall (const HResponsibilityAsParentCall &other)
virtual ~HResponsibilityAsParentCall ()
HResponsibilityAsParentCall & operator= (const HResponsibilityAsParentCall &other)
virtual
HResponsibilityAsParentCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getParent ()
virtual const NodeHandle & getParent () const
virtual void setParent (const NodeHandle &parent)
virtual void setChildrenArraySize (unsigned int size)
virtual unsigned int getChildrenArraySize () const
virtual NodeHandle & getChildren (unsigned int k)
virtual const NodeHandle & getChildren (unsigned int k) const
virtual void setChildren (unsigned int k, const NodeHandle &children)
Protected Member Functions
bool operator== (const HResponsibilityAsParentCall &)
Protected Attributes
NodeHandle parent_var
NodeHandle * children_var
unsigned int children_arraysize
Private Member Functions
void copy (const HResponsibilityAsParentCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HResponsibilityAsParentCall extends BaseCallMessage {
     NodeHandle parent;
     NodeHandle children[];
 }
Definition at line 567 of file HMessage_m.h.
Constructor & Destructor Documentation
HResponsibilityAsParentCall::HResponsibilityAsParentCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HResponsibilityAsParentCall::HResponsibilityAsParentCall (const HResponsibilityAsParentCall & other)
virtual HResponsibilityAsParentCall::~HResponsibilityAsParentCall () [virtual]
Member Function Documentation
void HResponsibilityAsParentCall::copy (const HResponsibilityAsParentCall & other) [private]
virtual HResponsibilityAsParentCall* HResponsibilityAsParentCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 586 of file HMessage_m.h.
{return new HResponsibilityAsParentCall(*this);}
virtual NodeHandle& HResponsibilityAsParentCall::getChildren (unsigned int k) [virtual]
Referenced by HTopology::handleResponsibilityAsParentCall().
virtual const NodeHandle& HResponsibilityAsParentCall::getChildren (unsigned int k) const [inline, virtual]
Definition at line 597 of file HMessage_m.h.
Referenced by getChildren().
{return const_cast<HResponsibilityAsParentCall*>(this)->getChildren(k);}
virtual unsigned int HResponsibilityAsParentCall::getChildrenArraySize () const [virtual]
Referenced by HTopology::handleResponsibilityAsParentCall().
virtual NodeHandle& HResponsibilityAsParentCall::getParent () [virtual]
Referenced by HTopology::handleResponsibilityAsParentCall().
virtual const NodeHandle& HResponsibilityAsParentCall::getParent () const [inline, virtual]
Definition at line 592 of file HMessage_m.h.
Referenced by getParent().
{return const_cast<HResponsibilityAsParentCall*>(this)->getParent();}
HResponsibilityAsParentCall& HResponsibilityAsParentCall::operator= (const HResponsibilityAsParentCall & other)
bool HResponsibilityAsParentCall::operator== (const HResponsibilityAsParentCall &) [protected]
virtual void HResponsibilityAsParentCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HResponsibilityAsParentCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void HResponsibilityAsParentCall::setChildren (unsigned int k, const NodeHandle & children) [virtual]
Referenced by HTopology::goAheadWithRestSelectionProcess().
virtual void HResponsibilityAsParentCall::setChildrenArraySize (unsigned int size) [virtual]
Referenced by HTopology::goAheadWithRestSelectionProcess().
virtual void HResponsibilityAsParentCall::setParent (const NodeHandle & parent) [virtual]
Referenced by HTopology::goAheadWithRestSelectionProcess().
Member Data Documentation
unsigned int HResponsibilityAsParentCall::children_arraysize [protected]
Definition at line 572 of file HMessage_m.h.
NodeHandle* HResponsibilityAsParentCall::children_var [protected]
Definition at line 571 of file HMessage_m.h.
NodeHandle HResponsibilityAsParentCall::parent_var [protected]
Definition at line 570 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h