OverSim: ScribeDataMessage Class Reference
ScribeDataMessage Class Reference
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
#include <ScribeMessage_m.h>
Public Member Functions
ScribeDataMessage (const char *name=NULL, int kind=0)
ScribeDataMessage (const ScribeDataMessage &other)
virtual ~ScribeDataMessage ()
ScribeDataMessage & operator= (const ScribeDataMessage &other)
virtual ScribeDataMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getGroupId ()
virtual const OverlayKey & getGroupId () const
virtual void setGroupId (const OverlayKey &groupId)
virtual bool getEmpty () const
virtual void setEmpty (bool empty)
Protected Member Functions
bool operator== (const ScribeDataMessage &)
Protected Attributes
OverlayKey groupId_var
bool empty_var
Private Member Functions
void copy (const ScribeDataMessage &other)
Detailed Description
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
 packet ScribeDataMessage
 {
         OverlayKey groupId;
         bool empty = false;
 }
Definition at line 370 of file ScribeMessage_m.h.
Constructor & Destructor Documentation
ScribeDataMessage::ScribeDataMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ScribeDataMessage::ScribeDataMessage (const ScribeDataMessage & other)
virtual ScribeDataMessage::~ScribeDataMessage () [virtual]
Member Function Documentation
void ScribeDataMessage::copy (const ScribeDataMessage & other) [private]
virtual ScribeDataMessage* ScribeDataMessage::dup () const [inline, virtual]
Definition at line 388 of file ScribeMessage_m.h.
{return new ScribeDataMessage(*this);}
virtual bool ScribeDataMessage::getEmpty () const [virtual]
Referenced by Scribe::deliverALMDataToGroup().
virtual OverlayKey& ScribeDataMessage::getGroupId () [virtual]
Referenced by Scribe::deliverALMDataToGroup(), and Scribe::deliverALMDataToRoot().
virtual const OverlayKey& ScribeDataMessage::getGroupId () const [inline, virtual]
Definition at line 394 of file ScribeMessage_m.h.
Referenced by getGroupId().
{return const_cast<ScribeDataMessage*>(this)->getGroupId();}
ScribeDataMessage& ScribeDataMessage::operator= (const ScribeDataMessage & other)
bool ScribeDataMessage::operator== (const ScribeDataMessage &) [protected]
virtual void ScribeDataMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ScribeDataMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ScribeDataMessage::setEmpty (bool empty) [virtual]
Referenced by Scribe::handleTimerEvent().
virtual void ScribeDataMessage::setGroupId (const OverlayKey & groupId) [virtual]
Referenced by Scribe::deliverALMDataToRoot(), and Scribe::handleTimerEvent().
Member Data Documentation
bool ScribeDataMessage::empty_var [protected]
Definition at line 374 of file ScribeMessage_m.h.
OverlayKey ScribeDataMessage::groupId_var [protected]
Definition at line 373 of file ScribeMessage_m.h.
The documentation for this class was generated from the following file:
ScribeMessage_m.h