OverSim: PubSubUnsubscriptionMessage Class Reference
PubSubUnsubscriptionMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubUnsubscriptionMessage (const char *name=NULL, int kind=0)
PubSubUnsubscriptionMessage (const PubSubUnsubscriptionMessage &other)
virtual ~PubSubUnsubscriptionMessage ()
PubSubUnsubscriptionMessage & operator= (const PubSubUnsubscriptionMessage &other)
virtual
PubSubUnsubscriptionMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getSrc ()
virtual const NodeHandle & getSrc () const
virtual void setSrc (const NodeHandle &src)
Protected Member Functions
bool operator== (const PubSubUnsubscriptionMessage &)
Protected Attributes
int subspaceId_var
NodeHandle src_var
Private Member Functions
void copy (const PubSubUnsubscriptionMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubUnsubscriptionMessage extends BaseOverlayMessage
 {
         int subspaceId;
         NodeHandle src;
 }
Definition at line 487 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubUnsubscriptionMessage::PubSubUnsubscriptionMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubUnsubscriptionMessage::PubSubUnsubscriptionMessage (const PubSubUnsubscriptionMessage & other)
virtual PubSubUnsubscriptionMessage::~PubSubUnsubscriptionMessage () [virtual]
Member Function Documentation
void PubSubUnsubscriptionMessage::copy (const PubSubUnsubscriptionMessage & other) [private]
virtual PubSubUnsubscriptionMessage* PubSubUnsubscriptionMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 505 of file PubSubMessage_m.h.
{return new PubSubUnsubscriptionMessage(*this);}
virtual NodeHandle& PubSubUnsubscriptionMessage::getSrc () [virtual]
Referenced by PubSubMMOG::handleUnsubscriptionMessage().
virtual const NodeHandle& PubSubUnsubscriptionMessage::getSrc () const [inline, virtual]
Definition at line 513 of file PubSubMessage_m.h.
Referenced by getSrc().
{return const_cast<PubSubUnsubscriptionMessage*>(this)->getSrc();}
virtual int PubSubUnsubscriptionMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleUnsubscriptionMessage().
PubSubUnsubscriptionMessage& PubSubUnsubscriptionMessage::operator= (const PubSubUnsubscriptionMessage & other)
bool PubSubUnsubscriptionMessage::operator== (const PubSubUnsubscriptionMessage &) [protected]
virtual void PubSubUnsubscriptionMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubUnsubscriptionMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubUnsubscriptionMessage::setSrc (const NodeHandle & src) [virtual]
Referenced by PubSubMMOG::handleMove().
virtual void PubSubUnsubscriptionMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleMove().
Member Data Documentation
NodeHandle PubSubUnsubscriptionMessage::src_var [protected]
Definition at line 491 of file PubSubMessage_m.h.
int PubSubUnsubscriptionMessage::subspaceId_var [protected]
Definition at line 490 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h