OverSim: HGetChildrenResponse Class Reference
HGetChildrenResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HGetChildrenResponse (const char *name=NULL, int kind=0)
HGetChildrenResponse (const HGetChildrenResponse &other)
virtual ~HGetChildrenResponse ()
HGetChildrenResponse & operator= (const HGetChildrenResponse &other)
virtual HGetChildrenResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setChildrenArraySize (unsigned int size)
virtual unsigned int getChildrenArraySize () const
virtual NodeHandle & getChildren (unsigned int k)
virtual const NodeHandle & getChildren (unsigned int k) const
virtual void setChildren (unsigned int k, const NodeHandle &children)
Protected Member Functions
bool operator== (const HGetChildrenResponse &)
Protected Attributes
NodeHandle * children_var
unsigned int children_arraysize
Private Member Functions
void copy (const HGetChildrenResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HGetChildrenResponse extends BaseResponseMessage {
     NodeHandle children[];
 }
Definition at line 760 of file HMessage_m.h.
Constructor & Destructor Documentation
HGetChildrenResponse::HGetChildrenResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HGetChildrenResponse::HGetChildrenResponse (const HGetChildrenResponse & other)
virtual HGetChildrenResponse::~HGetChildrenResponse () [virtual]
Member Function Documentation
void HGetChildrenResponse::copy (const HGetChildrenResponse & other) [private]
virtual HGetChildrenResponse* HGetChildrenResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 778 of file HMessage_m.h.
{return new HGetChildrenResponse(*this);}
virtual NodeHandle& HGetChildrenResponse::getChildren (unsigned int k) [virtual]
Referenced by HTopology::setNodesOneUp().
virtual const NodeHandle& HGetChildrenResponse::getChildren (unsigned int k) const [inline, virtual]
Definition at line 786 of file HMessage_m.h.
Referenced by getChildren().
{return const_cast<HGetChildrenResponse*>(this)->getChildren(k);}
virtual unsigned int HGetChildrenResponse::getChildrenArraySize () const [virtual]
Referenced by HTopology::setNodesOneUp().
HGetChildrenResponse& HGetChildrenResponse::operator= (const HGetChildrenResponse & other)
bool HGetChildrenResponse::operator== (const HGetChildrenResponse &) [protected]
virtual void HGetChildrenResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HGetChildrenResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HGetChildrenResponse::setChildren (unsigned int k, const NodeHandle & children) [virtual]
Referenced by HTopology::sendChildren().
virtual void HGetChildrenResponse::setChildrenArraySize (unsigned int size) [virtual]
Referenced by HTopology::sendChildren().
Member Data Documentation
unsigned int HGetChildrenResponse::children_arraysize [protected]
Definition at line 764 of file HMessage_m.h.
NodeHandle* HGetChildrenResponse::children_var [protected]
Definition at line 763 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h