OverSim: VastDiscardMessage Class Reference
VastDiscardMessage Class Reference
Class generated from overlay/vast/Vast.msg by opp_msgc.
#include <Vast_m.h>
Public Member Functions
VastDiscardMessage (const char *name=NULL, int kind=0)
VastDiscardMessage (const VastDiscardMessage &other)
virtual ~VastDiscardMessage ()
VastDiscardMessage & operator= (const VastDiscardMessage &other)
virtual VastDiscardMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getDiscardNode ()
virtual const NodeHandle & getDiscardNode () const
virtual void setDiscardNode (const NodeHandle &discardNode)
Protected Member Functions
bool operator== (const VastDiscardMessage &)
Protected Attributes
NodeHandle discardNode_var
Private Member Functions
void copy (const VastDiscardMessage &other)
Detailed Description
Class generated from overlay/vast/Vast.msg by opp_msgc.
 packet VastDiscardMessage extends VastMessage
 {
     NodeHandle discardNode;
 }
Definition at line 237 of file Vast_m.h.
Constructor & Destructor Documentation
VastDiscardMessage::VastDiscardMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
VastDiscardMessage::VastDiscardMessage (const VastDiscardMessage & other)
virtual VastDiscardMessage::~VastDiscardMessage () [virtual]
Member Function Documentation
void VastDiscardMessage::copy (const VastDiscardMessage & other) [private]
virtual VastDiscardMessage* VastDiscardMessage::dup () const [inline, virtual]
Reimplemented from VastMessage.
Definition at line 254 of file Vast_m.h.
{return new VastDiscardMessage(*this);}
virtual NodeHandle& VastDiscardMessage::getDiscardNode () [virtual]
Referenced by Vast::handleDiscardNode().
virtual const NodeHandle& VastDiscardMessage::getDiscardNode () const [inline, virtual]
Definition at line 260 of file Vast_m.h.
Referenced by getDiscardNode().
{return const_cast<VastDiscardMessage*>(this)->getDiscardNode();}
VastDiscardMessage& VastDiscardMessage::operator= (const VastDiscardMessage & other)
bool VastDiscardMessage::operator== (const VastDiscardMessage &) [protected]
virtual void VastDiscardMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doPacking().
virtual void VastDiscardMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doUnpacking().
virtual void VastDiscardMessage::setDiscardNode (const NodeHandle & discardNode) [virtual]
Referenced by Vast::sendDiscardNode().
Member Data Documentation
NodeHandle VastDiscardMessage::discardNode_var [protected]
Definition at line 240 of file Vast_m.h.
The documentation for this class was generated from the following file:
Vast_m.h