OverSim: HScheduleSegmentsResponse Class Reference
HScheduleSegmentsResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HScheduleSegmentsResponse (const char *name=NULL, int kind=0)
HScheduleSegmentsResponse (const HScheduleSegmentsResponse &other)
virtual ~HScheduleSegmentsResponse ()
HScheduleSegmentsResponse & operator= (const HScheduleSegmentsResponse &other)
virtual HScheduleSegmentsResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setSegmentsArraySize (unsigned int size)
virtual unsigned int getSegmentsArraySize () const
virtual HVideoSegment & getSegments (unsigned int k)
virtual const HVideoSegment & getSegments (unsigned int k) const
virtual void setSegments (unsigned int k, const HVideoSegment &segments)
Protected Member Functions
bool operator== (const HScheduleSegmentsResponse &)
Protected Attributes
HVideoSegment * segments_var
unsigned int segments_arraysize
Private Member Functions
void copy (const HScheduleSegmentsResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HScheduleSegmentsResponse extends BaseResponseMessage {
     HVideoSegment segments[];
 }
Definition at line 653 of file HMessage_m.h.
Constructor & Destructor Documentation
HScheduleSegmentsResponse::HScheduleSegmentsResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HScheduleSegmentsResponse::HScheduleSegmentsResponse (const HScheduleSegmentsResponse & other)
virtual HScheduleSegmentsResponse::~HScheduleSegmentsResponse () [virtual]
Member Function Documentation
void HScheduleSegmentsResponse::copy (const HScheduleSegmentsResponse & other) [private]
virtual HScheduleSegmentsResponse* HScheduleSegmentsResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 671 of file HMessage_m.h.
{return new HScheduleSegmentsResponse(*this);}
virtual HVideoSegment& HScheduleSegmentsResponse::getSegments (unsigned int k) [virtual]
Referenced by HTopology::handleScheduleSegmentsResponse().
virtual const HVideoSegment& HScheduleSegmentsResponse::getSegments (unsigned int k) const [inline, virtual]
Definition at line 679 of file HMessage_m.h.
Referenced by getSegments().
{return const_cast<HScheduleSegmentsResponse*>(this)->getSegments(k);}
virtual unsigned int HScheduleSegmentsResponse::getSegmentsArraySize () const [virtual]
Referenced by HTopology::handleScheduleSegmentsResponse().
HScheduleSegmentsResponse& HScheduleSegmentsResponse::operator= (const HScheduleSegmentsResponse & other)
bool HScheduleSegmentsResponse::operator== (const HScheduleSegmentsResponse &) [protected]
virtual void HScheduleSegmentsResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HScheduleSegmentsResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HScheduleSegmentsResponse::setSegments (unsigned int k, const HVideoSegment & segments) [virtual]
Referenced by HTopology::handleScheduleSegmentsCall().
virtual void HScheduleSegmentsResponse::setSegmentsArraySize (unsigned int size) [virtual]
Referenced by HTopology::handleScheduleSegmentsCall().
Member Data Documentation
unsigned int HScheduleSegmentsResponse::segments_arraysize [protected]
Definition at line 657 of file HMessage_m.h.
HVideoSegment* HScheduleSegmentsResponse::segments_var [protected]
Definition at line 656 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h