OverSim: RealWorldTestMessage Class Reference
RealWorldTestMessage Class Reference
Class generated from applications/realworldtestapp/RealWorldTestMessage.msg by opp_msgc.
#include <RealWorldTestMessage_m.h>
Public Member Functions
RealWorldTestMessage (const char *name=NULL, int kind=0)
RealWorldTestMessage (const RealWorldTestMessage &other)
virtual ~RealWorldTestMessage ()
RealWorldTestMessage & operator= (const RealWorldTestMessage &other)
virtual RealWorldTestMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getMsg () const
virtual void setMsg (const char *msg)
Protected Member Functions
bool operator== (const RealWorldTestMessage &)
Protected Attributes
opp_string msg_var
Private Member Functions
void copy (const RealWorldTestMessage &other)
Detailed Description
Class generated from applications/realworldtestapp/RealWorldTestMessage.msg by opp_msgc.
 packet RealWorldTestMessage
 {
     string msg;
 }
Definition at line 27 of file RealWorldTestMessage_m.h.
Constructor & Destructor Documentation
RealWorldTestMessage::RealWorldTestMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
RealWorldTestMessage::RealWorldTestMessage (const RealWorldTestMessage & other)
virtual RealWorldTestMessage::~RealWorldTestMessage () [virtual]
Member Function Documentation
void RealWorldTestMessage::copy (const RealWorldTestMessage & other) [private]
virtual RealWorldTestMessage* RealWorldTestMessage::dup () const [inline, virtual]
Definition at line 44 of file RealWorldTestMessage_m.h.
{return new RealWorldTestMessage(*this);}
virtual const char* RealWorldTestMessage::getMsg () const [virtual]
Referenced by RealWorldTestApp::deliver(), and RealWorldTestApp::handleUpperMessage().
RealWorldTestMessage& RealWorldTestMessage::operator= (const RealWorldTestMessage & other)
bool RealWorldTestMessage::operator== (const RealWorldTestMessage &) [protected]
virtual void RealWorldTestMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void RealWorldTestMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void RealWorldTestMessage::setMsg (const char * msg) [virtual]
Referenced by RealWorldTestPacketParser::decapsulatePayload(), and RealWorldTestApp::deliver().
Member Data Documentation
opp_string RealWorldTestMessage::msg_var [protected]
Definition at line 30 of file RealWorldTestMessage_m.h.
The documentation for this class was generated from the following file:
RealWorldTestMessage_m.h