OverSim: PastryJoinCall Class Reference
PastryJoinCall Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
PastryJoinCall (const char *name=NULL, int kind=0)
PastryJoinCall (const PastryJoinCall &other)
virtual ~PastryJoinCall ()
PastryJoinCall & operator= (const PastryJoinCall &other)
virtual PastryJoinCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const PastryJoinCall &)
Private Member Functions
void copy (const PastryJoinCall &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet PastryJoinCall extends BaseCallMessage
 {
 }
Definition at line 296 of file PastryMessage_m.h.
Constructor & Destructor Documentation
PastryJoinCall::PastryJoinCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PastryJoinCall::PastryJoinCall (const PastryJoinCall & other)
virtual PastryJoinCall::~PastryJoinCall () [virtual]
Member Function Documentation
void PastryJoinCall::copy (const PastryJoinCall & other) [private]
virtual PastryJoinCall* PastryJoinCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 312 of file PastryMessage_m.h.
{return new PastryJoinCall(*this);}
PastryJoinCall& PastryJoinCall::operator= (const PastryJoinCall & other)
bool PastryJoinCall::operator== (const PastryJoinCall &) [protected]
virtual void PastryJoinCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PastryJoinCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h