OverSim: TreeTestStrategyCall Class Reference
TreeTestStrategyCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
TreeTestStrategyCall (const char *name=NULL, int kind=0)
TreeTestStrategyCall (const TreeTestStrategyCall &other)
virtual ~TreeTestStrategyCall ()
TreeTestStrategyCall & operator= (const TreeTestStrategyCall &other)
virtual TreeTestStrategyCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getNodeCount () const
virtual void setNodeCount (int nodeCount)
Protected Member Functions
bool operator== (const TreeTestStrategyCall &)
Protected Attributes
int nodeCount_var
Private Member Functions
void copy (const TreeTestStrategyCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet TreeTestStrategyCall extends GlobalViewBuilderCall
 {
     int nodeCount;
 }
Definition at line 532 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
TreeTestStrategyCall::TreeTestStrategyCall (const char * name = NULL, int kind = 0)
Referenced by dup().
TreeTestStrategyCall::TreeTestStrategyCall (const TreeTestStrategyCall & other)
virtual TreeTestStrategyCall::~TreeTestStrategyCall () [virtual]
Member Function Documentation
void TreeTestStrategyCall::copy (const TreeTestStrategyCall & other) [private]
virtual TreeTestStrategyCall* TreeTestStrategyCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 549 of file TreeManagementMessage_m.h.
{return new TreeTestStrategyCall(*this);}
virtual int TreeTestStrategyCall::getNodeCount () const [virtual]
Referenced by StrategyTreeTest::handleCoordinateRpcCall().
TreeTestStrategyCall& TreeTestStrategyCall::operator= (const TreeTestStrategyCall & other)
bool TreeTestStrategyCall::operator== (const TreeTestStrategyCall &) [protected]
virtual void TreeTestStrategyCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void TreeTestStrategyCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void TreeTestStrategyCall::setNodeCount (int nodeCount) [virtual]
Referenced by StrategyTreeTest::getCoordinateMessage().
Member Data Documentation
int TreeTestStrategyCall::nodeCount_var [protected]
Definition at line 535 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h