OverSim: PubSubIntermediateCall Class Reference
PubSubIntermediateCall Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubIntermediateCall (const char *name=NULL, int kind=0)
PubSubIntermediateCall (const PubSubIntermediateCall &other)
virtual ~PubSubIntermediateCall ()
PubSubIntermediateCall & operator= (const PubSubIntermediateCall &other)
virtual PubSubIntermediateCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
Protected Member Functions
bool operator== (const PubSubIntermediateCall &)
Protected Attributes
int subspaceId_var
Private Member Functions
void copy (const PubSubIntermediateCall &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubIntermediateCall extends BaseCallMessage
 {
         int subspaceId;
 }
Definition at line 618 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubIntermediateCall::PubSubIntermediateCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubIntermediateCall::PubSubIntermediateCall (const PubSubIntermediateCall & other)
virtual PubSubIntermediateCall::~PubSubIntermediateCall () [virtual]
Member Function Documentation
void PubSubIntermediateCall::copy (const PubSubIntermediateCall & other) [private]
virtual PubSubIntermediateCall* PubSubIntermediateCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 635 of file PubSubMessage_m.h.
{return new PubSubIntermediateCall(*this);}
virtual int PubSubIntermediateCall::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleIntermediateCall().
PubSubIntermediateCall& PubSubIntermediateCall::operator= (const PubSubIntermediateCall & other)
bool PubSubIntermediateCall::operator== (const PubSubIntermediateCall &) [protected]
virtual void PubSubIntermediateCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PubSubIntermediateCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void PubSubIntermediateCall::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
Member Data Documentation
int PubSubIntermediateCall::subspaceId_var [protected]
Definition at line 621 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h