OverSim: PubSubPingResponse Class Reference
PubSubPingResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubPingResponse (const char *name=NULL, int kind=0)
PubSubPingResponse (const PubSubPingResponse &other)
virtual ~PubSubPingResponse ()
PubSubPingResponse & operator= (const PubSubPingResponse &other)
virtual PubSubPingResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
Protected Member Functions
bool operator== (const PubSubPingResponse &)
Protected Attributes
int subspaceId_var
Private Member Functions
void copy (const PubSubPingResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubPingResponse extends BaseResponseMessage
 {
         int subspaceId;
 }
Definition at line 835 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubPingResponse::PubSubPingResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubPingResponse::PubSubPingResponse (const PubSubPingResponse & other)
virtual PubSubPingResponse::~PubSubPingResponse () [virtual]
Member Function Documentation
void PubSubPingResponse::copy (const PubSubPingResponse & other) [private]
virtual PubSubPingResponse* PubSubPingResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 852 of file PubSubMessage_m.h.
{return new PubSubPingResponse(*this);}
virtual int PubSubPingResponse::getSubspaceId () const [virtual]
PubSubPingResponse& PubSubPingResponse::operator= (const PubSubPingResponse & other)
bool PubSubPingResponse::operator== (const PubSubPingResponse &) [protected]
virtual void PubSubPingResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubPingResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubPingResponse::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handlePingCall().
Member Data Documentation
int PubSubPingResponse::subspaceId_var [protected]
Definition at line 838 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h