OverSim: GiaIDMessage Class Reference
GiaIDMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
GiaIDMessage (const char *name=NULL, int kind=0)
GiaIDMessage (const GiaIDMessage &other)
virtual ~GiaIDMessage ()
GiaIDMessage & operator= (const GiaIDMessage &other)
virtual GiaIDMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual OverlayKey & getID ()
virtual const OverlayKey & getID () const
virtual void setID (const OverlayKey &ID)
Protected Member Functions
bool operator== (const GiaIDMessage &)
Protected Attributes
OverlayKey destKey_var
OverlayKey ID_var
Private Member Functions
void copy (const GiaIDMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message GiaIDMessage extends GiaMessage
 {
         OverlayKey destKey;
         OverlayKey ID;
 };
Definition at line 229 of file GiaMessage_m.h.
Constructor & Destructor Documentation
GiaIDMessage::GiaIDMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GiaIDMessage::GiaIDMessage (const GiaIDMessage & other)
virtual GiaIDMessage::~GiaIDMessage () [virtual]
Member Function Documentation
void GiaIDMessage::copy (const GiaIDMessage & other) [private]
virtual GiaIDMessage* GiaIDMessage::dup () const [inline, virtual]
Reimplemented from GiaMessage.
Reimplemented in SearchResponseMessage, SearchMessage, and GiaRouteMessage.
Definition at line 247 of file GiaMessage_m.h.
{return new GiaIDMessage(*this);}
virtual OverlayKey& GiaIDMessage::getDestKey () [virtual]
Referenced by Gia::forwardMessage().
virtual const OverlayKey& GiaIDMessage::getDestKey () const [inline, virtual]
Definition at line 253 of file GiaMessage_m.h.
Referenced by getDestKey().
{return const_cast<GiaIDMessage*>(this)->getDestKey();}
virtual OverlayKey& GiaIDMessage::getID () [virtual]
Referenced by GiaMessageBookkeeping::addMessage(), GiaMessageBookkeeping::contains(), Gia::forwardMessage(), GiaMessageBookkeeping::getNextHop(), and GiaMessageBookkeeping::removeMessage().
virtual const OverlayKey& GiaIDMessage::getID () const [inline, virtual]
Definition at line 256 of file GiaMessage_m.h.
Referenced by getID().
{return const_cast<GiaIDMessage*>(this)->getID();}
GiaIDMessage& GiaIDMessage::operator= (const GiaIDMessage & other)
bool GiaIDMessage::operator== (const GiaIDMessage &) [protected]
virtual void GiaIDMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Reimplemented in SearchResponseMessage, SearchMessage, and GiaRouteMessage.
Referenced by doPacking().
virtual void GiaIDMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Reimplemented in SearchResponseMessage, SearchMessage, and GiaRouteMessage.
Referenced by doUnpacking().
virtual void GiaIDMessage::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by Gia::forwardSearchResponseMessage(), and Gia::getRoute().
virtual void GiaIDMessage::setID (const OverlayKey & ID) [virtual]
Referenced by Gia::getRoute(), and Gia::sendSearchResponseMessage().
Member Data Documentation
OverlayKey GiaIDMessage::destKey_var [protected]
Definition at line 232 of file GiaMessage_m.h.
OverlayKey GiaIDMessage::ID_var [protected]
Definition at line 233 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h