OverSim: JoinResponse Class Reference
JoinResponse Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
JoinResponse (const char *name=NULL, int kind=0)
JoinResponse (const JoinResponse &other)
virtual ~JoinResponse ()
JoinResponse & operator= (const JoinResponse &other)
virtual JoinResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSucNum () const
virtual void setSucNum (int sucNum)
virtual void setSucNodeArraySize (unsigned int size)
virtual unsigned int getSucNodeArraySize () const
virtual NodeHandle & getSucNode (unsigned int k)
virtual const NodeHandle & getSucNode (unsigned int k) const
virtual void setSucNode (unsigned int k, const NodeHandle &sucNode)
virtual NodeHandle & getPreNode ()
virtual const NodeHandle & getPreNode () const
virtual void setPreNode (const NodeHandle &preNode)
Protected Member Functions
bool operator== (const JoinResponse &)
Protected Attributes
int sucNum_var
NodeHandle * sucNode_var
unsigned int sucNode_arraysize
NodeHandle preNode_var
Private Member Functions
void copy (const JoinResponse &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet JoinResponse extends BaseResponseMessage
 {
     int sucNum;
     NodeHandle sucNode[];
     NodeHandle preNode;
 }
Definition at line 288 of file ChordMessage_m.h.
Constructor & Destructor Documentation
JoinResponse::JoinResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
JoinResponse::JoinResponse (const JoinResponse & other)
virtual JoinResponse::~JoinResponse () [virtual]
Member Function Documentation
void JoinResponse::copy (const JoinResponse & other) [private]
virtual JoinResponse* JoinResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 308 of file ChordMessage_m.h.
{return new JoinResponse(*this);}
virtual NodeHandle& JoinResponse::getPreNode () [virtual]
Referenced by oversim::Chord::handleRpcJoinResponse().
virtual const NodeHandle& JoinResponse::getPreNode () const [inline, virtual]
Definition at line 321 of file ChordMessage_m.h.
Referenced by getPreNode().
{return const_cast<JoinResponse*>(this)->getPreNode();}
virtual NodeHandle& JoinResponse::getSucNode (unsigned int k) [virtual]
Referenced by oversim::Chord::handleRpcJoinResponse().
virtual const NodeHandle& JoinResponse::getSucNode (unsigned int k) const [inline, virtual]
Definition at line 318 of file ChordMessage_m.h.
Referenced by getSucNode().
{return const_cast<JoinResponse*>(this)->getSucNode(k);}
virtual unsigned int JoinResponse::getSucNodeArraySize () const [virtual]
virtual int JoinResponse::getSucNum () const [virtual]
Referenced by oversim::Chord::handleRpcJoinResponse().
JoinResponse& JoinResponse::operator= (const JoinResponse & other)
bool JoinResponse::operator== (const JoinResponse &) [protected]
virtual void JoinResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void JoinResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void JoinResponse::setPreNode (const NodeHandle & preNode) [virtual]
Referenced by oversim::Chord::rpcJoin().
virtual void JoinResponse::setSucNode (unsigned int k, const NodeHandle & sucNode) [virtual]
Referenced by oversim::Chord::rpcJoin().
virtual void JoinResponse::setSucNodeArraySize (unsigned int size) [virtual]
Referenced by oversim::Chord::rpcJoin().
virtual void JoinResponse::setSucNum (int sucNum) [virtual]
Referenced by oversim::Chord::rpcJoin().
Member Data Documentation
NodeHandle JoinResponse::preNode_var [protected]
Definition at line 294 of file ChordMessage_m.h.
unsigned int JoinResponse::sucNode_arraysize [protected]
Definition at line 293 of file ChordMessage_m.h.
NodeHandle* JoinResponse::sucNode_var [protected]
Definition at line 292 of file ChordMessage_m.h.
int JoinResponse::sucNum_var [protected]
Definition at line 291 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h