OverSim: HJoinCall Class Reference
HJoinCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HJoinCall (const char *name=NULL, int kind=0)
HJoinCall (const HJoinCall &other)
virtual ~HJoinCall ()
HJoinCall & operator= (const HJoinCall &other)
virtual HJoinCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const HJoinCall &)
Private Member Functions
void copy (const HJoinCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HJoinCall extends BaseCallMessage {
 }
Definition at line 326 of file HMessage_m.h.
Constructor & Destructor Documentation
HJoinCall::HJoinCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HJoinCall::HJoinCall (const HJoinCall & other)
virtual HJoinCall::~HJoinCall () [virtual]
Member Function Documentation
void HJoinCall::copy (const HJoinCall & other) [private]
virtual HJoinCall* HJoinCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 342 of file HMessage_m.h.
{return new HJoinCall(*this);}
HJoinCall& HJoinCall::operator= (const HJoinCall & other)
bool HJoinCall::operator== (const HJoinCall &) [protected]
virtual void HJoinCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HJoinCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
HMessage_m.h