OverSim: ChildCheckResponse Class Reference
ChildCheckResponse Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
ChildCheckResponse (const char *name=NULL, int kind=0)
ChildCheckResponse (const ChildCheckResponse &other)
virtual ~ChildCheckResponse ()
ChildCheckResponse & operator= (const ChildCheckResponse &other)
virtual ChildCheckResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ChildCheckResponse &)
Private Member Functions
void copy (const ChildCheckResponse &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet ChildCheckResponse extends BaseResponseMessage
 {
 }
Definition at line 380 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
ChildCheckResponse::ChildCheckResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
ChildCheckResponse::ChildCheckResponse (const ChildCheckResponse & other)
virtual ChildCheckResponse::~ChildCheckResponse () [virtual]
Member Function Documentation
void ChildCheckResponse::copy (const ChildCheckResponse & other) [private]
virtual ChildCheckResponse* ChildCheckResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 396 of file TreeManagementMessage_m.h.
{return new ChildCheckResponse(*this);}
ChildCheckResponse& ChildCheckResponse::operator= (const ChildCheckResponse & other)
bool ChildCheckResponse::operator== (const ChildCheckResponse &) [protected]
virtual void ChildCheckResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void ChildCheckResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h