OverSim: VastListMessage Class Reference
VastListMessage Class Reference
Class generated from overlay/vast/Vast.msg by opp_msgc.
#include <Vast_m.h>
Public Member Functions
VastListMessage (const char *name=NULL, int kind=0)
VastListMessage (const VastListMessage &other)
virtual ~VastListMessage ()
VastListMessage & operator= (const VastListMessage &other)
virtual VastListMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setNeighborNodeArraySize (unsigned int size)
virtual unsigned int getNeighborNodeArraySize () const
virtual NodeHandle & getNeighborNode (unsigned int k)
virtual const NodeHandle & getNeighborNode (unsigned int k) const
virtual void setNeighborNode (unsigned int k, const NodeHandle &neighborNode)
virtual void setNeighborPosArraySize (unsigned int size)
virtual unsigned int getNeighborPosArraySize () const
virtual Vector2D & getNeighborPos (unsigned int k)
virtual const Vector2D & getNeighborPos (unsigned int k) const
virtual void setNeighborPos (unsigned int k, const Vector2D &neighborPos)
virtual bool getRequestEnclosingNeighbors () const
virtual void setRequestEnclosingNeighbors (bool requestEnclosingNeighbors)
Protected Member Functions
bool operator== (const VastListMessage &)
Protected Attributes
NodeHandle * neighborNode_var
unsigned int neighborNode_arraysize
Vector2D * neighborPos_var
unsigned int neighborPos_arraysize
bool requestEnclosingNeighbors_var
Private Member Functions
void copy (const VastListMessage &other)
Detailed Description
Class generated from overlay/vast/Vast.msg by opp_msgc.
 packet VastListMessage extends VastMessage
 {
     NodeHandle neighborNode[];
     Vector2D neighborPos[];
     bool requestEnclosingNeighbors = false;
 }
Definition at line 138 of file Vast_m.h.
Constructor & Destructor Documentation
VastListMessage::VastListMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
VastListMessage::VastListMessage (const VastListMessage & other)
virtual VastListMessage::~VastListMessage () [virtual]
Member Function Documentation
void VastListMessage::copy (const VastListMessage & other) [private]
virtual VastListMessage* VastListMessage::dup () const [inline, virtual]
Reimplemented from VastMessage.
Definition at line 159 of file Vast_m.h.
{return new VastListMessage(*this);}
virtual NodeHandle& VastListMessage::getNeighborNode (unsigned int k) [virtual]
Referenced by Vast::handleBackupNeighbors(), Vast::handleJoinAcknowledge(), Vast::handleNewNeighbors(), and Vast::handleNodeLeave().
virtual const NodeHandle& VastListMessage::getNeighborNode (unsigned int k) const [inline, virtual]
Definition at line 167 of file Vast_m.h.
Referenced by getNeighborNode().
{return const_cast<VastListMessage*>(this)->getNeighborNode(k);}
virtual unsigned int VastListMessage::getNeighborNodeArraySize () const [virtual]
Referenced by Vast::handleBackupNeighbors(), Vast::handleEnclosingNeighborsRequest(), Vast::handleJoinAcknowledge(), Vast::handleNewNeighbors(), Vast::handleNodeGracefulLeaveNotification(), Vast::handleNodeLeave(), and Vast::handleNodeMove().
virtual Vector2D& VastListMessage::getNeighborPos (unsigned int k) [virtual]
Referenced by Vast::handleJoinAcknowledge(), Vast::handleNewNeighbors(), and Vast::handleNodeLeave().
virtual const Vector2D& VastListMessage::getNeighborPos (unsigned int k) const [inline, virtual]
Definition at line 172 of file Vast_m.h.
Referenced by getNeighborPos().
{return const_cast<VastListMessage*>(this)->getNeighborPos(k);}
virtual unsigned int VastListMessage::getNeighborPosArraySize () const [virtual]
virtual bool VastListMessage::getRequestEnclosingNeighbors () const [virtual]
Referenced by Vast::handleNewNeighbors().
VastListMessage& VastListMessage::operator= (const VastListMessage & other)
bool VastListMessage::operator== (const VastListMessage &) [protected]
virtual void VastListMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doPacking().
virtual void VastListMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doUnpacking().
virtual void VastListMessage::setNeighborNode (unsigned int k, const NodeHandle & neighborNode) [virtual]
Referenced by Vast::handleEnclosingNeighborsRequest(), Vast::handleJoinRequest(), Vast::handleNodeGracefulLeaveNotification(), Vast::handleNodeMove(), and Vast::processCheckCriticalTimer().
virtual void VastListMessage::setNeighborNodeArraySize (unsigned int size) [virtual]
Referenced by Vast::handleEnclosingNeighborsRequest(), Vast::handleJoinRequest(), Vast::handleNodeGracefulLeaveNotification(), Vast::handleNodeMove(), and Vast::processCheckCriticalTimer().
virtual void VastListMessage::setNeighborPos (unsigned int k, const Vector2D & neighborPos) [virtual]
Referenced by Vast::handleEnclosingNeighborsRequest(), Vast::handleJoinRequest(), Vast::handleNodeGracefulLeaveNotification(), Vast::handleNodeMove(), and Vast::processCheckCriticalTimer().
virtual void VastListMessage::setNeighborPosArraySize (unsigned int size) [virtual]
Referenced by Vast::handleEnclosingNeighborsRequest(), Vast::handleJoinRequest(), Vast::handleNodeGracefulLeaveNotification(), Vast::handleNodeMove(), and Vast::processCheckCriticalTimer().
virtual void VastListMessage::setRequestEnclosingNeighbors (bool requestEnclosingNeighbors) [virtual]
Referenced by Vast::handleNodeMove().
Member Data Documentation
unsigned int VastListMessage::neighborNode_arraysize [protected]
Definition at line 142 of file Vast_m.h.
NodeHandle* VastListMessage::neighborNode_var [protected]
Definition at line 141 of file Vast_m.h.
unsigned int VastListMessage::neighborPos_arraysize [protected]
Definition at line 144 of file Vast_m.h.
Vector2D* VastListMessage::neighborPos_var [protected]
Definition at line 143 of file Vast_m.h.
bool VastListMessage::requestEnclosingNeighbors_var [protected]
Definition at line 145 of file Vast_m.h.
The documentation for this class was generated from the following file:
Vast_m.h