OverSim: GameAPIListMessage Class Reference
GameAPIListMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
GameAPIListMessage (const char *name=NULL, int kind=0)
GameAPIListMessage (const GameAPIListMessage &other)
virtual ~GameAPIListMessage ()
GameAPIListMessage & operator= (const GameAPIListMessage &other)
virtual GameAPIListMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setRemoveNeighborArraySize (unsigned int size)
virtual unsigned int getRemoveNeighborArraySize () const
virtual NodeHandle & getRemoveNeighbor (unsigned int k)
virtual const NodeHandle & getRemoveNeighbor (unsigned int k) const
virtual void setRemoveNeighbor (unsigned int k, const NodeHandle &removeNeighbor)
virtual void setAddNeighborArraySize (unsigned int size)
virtual unsigned int getAddNeighborArraySize () const
virtual NodeHandle & getAddNeighbor (unsigned int k)
virtual const NodeHandle & getAddNeighbor (unsigned int k) const
virtual void setAddNeighbor (unsigned int k, const NodeHandle &addNeighbor)
virtual void setNeighborPositionArraySize (unsigned int size)
virtual unsigned int getNeighborPositionArraySize () const
virtual Vector2D & getNeighborPosition (unsigned int k)
virtual const Vector2D & getNeighborPosition (unsigned int k) const
virtual void setNeighborPosition (unsigned int k, const Vector2D &neighborPosition)
Protected Member Functions
bool operator== (const GameAPIListMessage &)
Protected Attributes
NodeHandle * removeNeighbor_var
unsigned int removeNeighbor_arraysize
NodeHandle * addNeighbor_var
unsigned int addNeighbor_arraysize
Vector2D * neighborPosition_var
unsigned int neighborPosition_arraysize
Private Member Functions
void copy (const GameAPIListMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet GameAPIListMessage extends GameAPIMessage
 {
     NodeHandle removeNeighbor[];
     NodeHandle addNeighbor[];
     Vector2D neighborPosition[];
 }
Definition at line 2380 of file CommonMessages_m.h.
Constructor & Destructor Documentation
GameAPIListMessage::GameAPIListMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GameAPIListMessage::GameAPIListMessage (const GameAPIListMessage & other)
virtual GameAPIListMessage::~GameAPIListMessage () [virtual]
Member Function Documentation
void GameAPIListMessage::copy (const GameAPIListMessage & other) [private]
virtual GameAPIListMessage* GameAPIListMessage::dup () const [inline, virtual]
Reimplemented from GameAPIMessage.
Definition at line 2402 of file CommonMessages_m.h.
{return new GameAPIListMessage(*this);}
virtual NodeHandle& GameAPIListMessage::getAddNeighbor (unsigned int k) [virtual]
Referenced by SimpleGameClient::updateNeighbors().
virtual const NodeHandle& GameAPIListMessage::getAddNeighbor (unsigned int k) const [inline, virtual]
Definition at line 2415 of file CommonMessages_m.h.
Referenced by getAddNeighbor().
{return const_cast<GameAPIListMessage*>(this)->getAddNeighbor(k);}
virtual unsigned int GameAPIListMessage::getAddNeighborArraySize () const [virtual]
Referenced by Vast::synchronizeApp(), and SimpleGameClient::updateNeighbors().
virtual Vector2D& GameAPIListMessage::getNeighborPosition (unsigned int k) [virtual]
Referenced by SimpleGameClient::updateNeighbors().
virtual const Vector2D& GameAPIListMessage::getNeighborPosition (unsigned int k) const [inline, virtual]
Definition at line 2420 of file CommonMessages_m.h.
Referenced by getNeighborPosition().
{return const_cast<GameAPIListMessage*>(this)->getNeighborPosition(k);}
virtual unsigned int GameAPIListMessage::getNeighborPositionArraySize () const [virtual]
virtual NodeHandle& GameAPIListMessage::getRemoveNeighbor (unsigned int k) [virtual]
Referenced by SimpleGameClient::updateNeighbors().
virtual const NodeHandle& GameAPIListMessage::getRemoveNeighbor (unsigned int k) const [inline, virtual]
Definition at line 2410 of file CommonMessages_m.h.
Referenced by getRemoveNeighbor().
{return const_cast<GameAPIListMessage*>(this)->getRemoveNeighbor(k);}
virtual unsigned int GameAPIListMessage::getRemoveNeighborArraySize () const [virtual]
Referenced by Vast::synchronizeApp(), and SimpleGameClient::updateNeighbors().
GameAPIListMessage& GameAPIListMessage::operator= (const GameAPIListMessage & other)
bool GameAPIListMessage::operator== (const GameAPIListMessage &) [protected]
virtual void GameAPIListMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doPacking().
virtual void GameAPIListMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doUnpacking().
virtual void GameAPIListMessage::setAddNeighbor (unsigned int k, const NodeHandle & addNeighbor) [virtual]
Referenced by PubSubMMOG::handleMoveListMessage(), NTree::handleMoveMessage(), SimMud::handleOtherPlayerMove(), Vast::synchronizeApp(), and Quon::synchronizeAppNeighbors().
virtual void GameAPIListMessage::setAddNeighborArraySize (unsigned int size) [virtual]
Referenced by Quon::deleteAppNeighbor(), PubSubMMOG::handleMoveListMessage(), NTree::handleMoveMessage(), SimMud::handleOtherPlayerMove(), Vast::synchronizeApp(), and Quon::synchronizeAppNeighbors().
virtual void GameAPIListMessage::setNeighborPosition (unsigned int k, const Vector2D & neighborPosition) [virtual]
Referenced by PubSubMMOG::handleMoveListMessage(), NTree::handleMoveMessage(), SimMud::handleOtherPlayerMove(), Vast::synchronizeApp(), and Quon::synchronizeAppNeighbors().
virtual void GameAPIListMessage::setNeighborPositionArraySize (unsigned int size) [virtual]
Referenced by Quon::deleteAppNeighbor(), PubSubMMOG::handleMoveListMessage(), NTree::handleMoveMessage(), SimMud::handleOtherPlayerMove(), Vast::synchronizeApp(), and Quon::synchronizeAppNeighbors().
virtual void GameAPIListMessage::setRemoveNeighbor (unsigned int k, const NodeHandle & removeNeighbor) [virtual]
Referenced by Quon::deleteAppNeighbor(), NTree::handleLeaveMessage(), SimMud::handleOtherPlayerMove(), SimMud::handleTimerEvent(), Vast::synchronizeApp(), and Quon::synchronizeAppNeighbors().
virtual void GameAPIListMessage::setRemoveNeighborArraySize (unsigned int size) [virtual]
Referenced by Quon::deleteAppNeighbor(), NTree::handleLeaveMessage(), SimMud::handleOtherPlayerMove(), SimMud::handleTimerEvent(), Vast::synchronizeApp(), and Quon::synchronizeAppNeighbors().
Member Data Documentation
unsigned int GameAPIListMessage::addNeighbor_arraysize [protected]
Definition at line 2386 of file CommonMessages_m.h.
NodeHandle* GameAPIListMessage::addNeighbor_var [protected]
Definition at line 2385 of file CommonMessages_m.h.
unsigned int GameAPIListMessage::neighborPosition_arraysize [protected]
Definition at line 2388 of file CommonMessages_m.h.
Vector2D* GameAPIListMessage::neighborPosition_var [protected]
Definition at line 2387 of file CommonMessages_m.h.
unsigned int GameAPIListMessage::removeNeighbor_arraysize [protected]
Definition at line 2384 of file CommonMessages_m.h.
NodeHandle* GameAPIListMessage::removeNeighbor_var [protected]
Definition at line 2383 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h