OverSim: AbstractSendStrategy Class Reference
AbstractSendStrategy Class Reference
#include <AbstractSendStrategy.h>
Public Member Functions
AbstractSendStrategy ()
.cc
virtual ~AbstractSendStrategy ()
virtual void initialize (GlobalViewBuilder *globalViewBuilder)
set a pointer to the neighborCache to access the optional parameters for the strategies
virtual void initializeStrategy ()
stub method to initialize the concrete strategy
virtual void handleCoordinateRpcCall (GlobalViewBuilderCall *globalViewBuilderCall)
virtual GlobalViewBuilderCall * getCoordinateMessage ()
virtual void setMyCoordinates (const AbstractNcsNodeInfo &ncsInfo)
virtual std::vector
< std::vector< double > > getGlobalViewData ()=0
return the decodes global View Data
virtual void setThisNode (const NodeHandle thisNode)
Set the Nodehandle of the own node to identify the own coordinates.
virtual std::string getStrategyDataStatus ()
return a short status of the running send strategy
virtual std::string getStrategyCombinedParams ()=0
return a string of the currently used strategy params
virtual void cleanUpCoordData (const treeNodeMap &currentTreeChildNodes)
cleanup the coordinate map and remove data of nodes which are not longer in the branch
Protected Attributes
NodeHandle thisNode
GlobalViewBuilder * globalViewBuilder
int lastSendCount
the quantity of coordinates sent by last message
Detailed Description
Definition at line 35 of file AbstractSendStrategy.h.
Constructor & Destructor Documentation
AbstractSendStrategy::AbstractSendStrategy ()
.cc
Author:
Daniel Lienert
Definition at line 27 of file AbstractSendStrategy.cc.
{
        // TODO Auto-generated constructor stub
}
AbstractSendStrategy::~AbstractSendStrategy () [virtual]
Definition at line 31 of file AbstractSendStrategy.cc.
{
        // TODO Auto-generated destructor stub
}
Member Function Documentation
void AbstractSendStrategy::cleanUpCoordData (const treeNodeMap & currentTreeChildNodes) [virtual]
cleanup the coordinate map and remove data of nodes which are not longer in the branch
Reimplemented in StrategyTreeTest, StrategyRegions, StrategySimplifyCoords, and StrategySendAll.
Definition at line 63 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::cleanup(), and GlobalViewBuilder::handleCoordSendTimer().
{
}
GlobalViewBuilderCall * AbstractSendStrategy::getCoordinateMessage () [virtual]
Reimplemented in StrategyTreeTest, StrategySendAll, StrategyRegions, StrategySimplifyCoords, and StrategyRemoveCoords.
Definition at line 47 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::handleCoordSendTimer().
{
        return new GlobalViewBuilderCall;
}
virtual std::vector<std::vector<double> > AbstractSendStrategy::getGlobalViewData () [pure virtual]
return the decodes global View Data
Implemented in StrategyTreeTest, StrategySendAll, StrategyRegions, and StrategySimplifyCoords.
Referenced by GlobalViewBuilder::spreadGlobalView().
virtual std::string AbstractSendStrategy::getStrategyCombinedParams () [pure virtual]
return a string of the currently used strategy params
Implemented in StrategyTreeTest, StrategyRegions, StrategySimplifyCoords, StrategySendAll, and StrategyRemoveCoords.
std::string AbstractSendStrategy::getStrategyDataStatus () [virtual]
return a short status of the running send strategy
Reimplemented in StrategyTreeTest, StrategySendAll, StrategyRegions, and StrategySimplifyCoords.
Definition at line 59 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::handleCoordSendTimer().
{
        return "-";
}
void AbstractSendStrategy::handleCoordinateRpcCall (GlobalViewBuilderCall * globalViewBuilderCall) [virtual]
Reimplemented in StrategyTreeTest, StrategySendAll, StrategyRegions, and StrategySimplifyCoords.
Definition at line 44 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::handleCoordinateRpcCall().
{
}
void AbstractSendStrategy::initialize (GlobalViewBuilder * globalViewBuilder) [virtual]
set a pointer to the neighborCache to access the optional parameters for the strategies
Parameters:
neighborCache
Definition at line 35 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::initializeViewBuilder().
{
        this->globalViewBuilder = globalViewBuilder;
        initializeStrategy();
}
void AbstractSendStrategy::initializeStrategy () [virtual]
stub method to initialize the concrete strategy
Definition at line 41 of file AbstractSendStrategy.cc.
Referenced by initialize().
{
}
void AbstractSendStrategy::setMyCoordinates (const AbstractNcsNodeInfo & ncsInfo) [virtual]
Reimplemented in StrategyTreeTest, StrategyRegions, StrategySimplifyCoords, StrategySendAll, and StrategyRemoveInaccurate.
Definition at line 51 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::cleanup(), and GlobalViewBuilder::handleCoordSendTimer().
{
}
void AbstractSendStrategy::setThisNode (const NodeHandle thisNode) [virtual]
Set the Nodehandle of the own node to identify the own coordinates.
Definition at line 66 of file AbstractSendStrategy.cc.
Referenced by GlobalViewBuilder::cleanup(), and GlobalViewBuilder::handleCoordSendTimer().
{
        this->thisNode = thisNode;
}
Member Data Documentation
GlobalViewBuilder* AbstractSendStrategy::globalViewBuilder [protected]
Definition at line 83 of file AbstractSendStrategy.h.
Referenced by StrategySimplifyCoords::decode(), StrategyRegions::getMaxSpread(), StrategyRegions::getSizePerDim(), StrategyRemoveCoords::getStrategyCombinedParams(), StrategyRegions::getStrategyCombinedParams(), StrategySimplifyCoords::getStrategyCombinedParams(), initialize(), StrategyRemoveCoords::processCoordinates(), and StrategySimplifyCoords::simplify().
int AbstractSendStrategy::lastSendCount [protected]
the quantity of coordinates sent by last message
Definition at line 88 of file AbstractSendStrategy.h.
Referenced by StrategyRemoveCoords::getCoordinateMessage(), StrategySendAll::getCoordinateMessage(), StrategySendAll::getStrategyDataStatus(), StrategyRemoveCoords::StrategyRemoveCoords(), and StrategySendAll::StrategySendAll().
NodeHandle AbstractSendStrategy::thisNode [protected]
Definition at line 82 of file AbstractSendStrategy.h.
Referenced by StrategySendAll::cleanUpCoordData(), StrategySimplifyCoords::cleanUpCoordData(), StrategyRegions::cleanUpCoordData(), StrategyTreeTest::cleanUpCoordData(), StrategyRemoveInaccurate::setMyCoordinates(), StrategySendAll::setMyCoordinates(), StrategySimplifyCoords::setMyCoordinates(), StrategyRegions::setMyCoordinates(), StrategyTreeTest::setMyCoordinates(), and setThisNode().
The documentation for this class was generated from the following files:
AbstractSendStrategy.h
AbstractSendStrategy.cc