OverSim: VastMoveMessage Class Reference
VastMoveMessage Class Reference
Class generated from overlay/vast/Vast.msg by opp_msgc.
#include <Vast_m.h>
Public Member Functions
VastMoveMessage (const char *name=NULL, int kind=0)
VastMoveMessage (const VastMoveMessage &other)
virtual ~VastMoveMessage ()
VastMoveMessage & operator= (const VastMoveMessage &other)
virtual VastMoveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getNewPos ()
virtual const Vector2D & getNewPos () const
virtual void setNewPos (const Vector2D &newPos)
virtual bool getIs_boundary () const
virtual void setIs_boundary (bool is_boundary)
virtual bool getRequest_list () const
virtual void setRequest_list (bool request_list)
Protected Member Functions
bool operator== (const VastMoveMessage &)
Protected Attributes
Vector2D newPos_var
bool is_boundary_var
bool request_list_var
Private Member Functions
void copy (const VastMoveMessage &other)
Detailed Description
Class generated from overlay/vast/Vast.msg by opp_msgc.
 packet VastMoveMessage extends VastMessage
 {
     Vector2D newPos;
     bool is_boundary = false;
     bool request_list = false;
 }
Definition at line 192 of file Vast_m.h.
Constructor & Destructor Documentation
VastMoveMessage::VastMoveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
VastMoveMessage::VastMoveMessage (const VastMoveMessage & other)
virtual VastMoveMessage::~VastMoveMessage () [virtual]
Member Function Documentation
void VastMoveMessage::copy (const VastMoveMessage & other) [private]
virtual VastMoveMessage* VastMoveMessage::dup () const [inline, virtual]
Reimplemented from VastMessage.
Definition at line 211 of file Vast_m.h.
{return new VastMoveMessage(*this);}
virtual bool VastMoveMessage::getIs_boundary () const [virtual]
Referenced by Vast::handleNodeMove().
virtual Vector2D& VastMoveMessage::getNewPos () [virtual]
Referenced by Vast::handleNodeMove(), and Vast::synchronizeApp().
virtual const Vector2D& VastMoveMessage::getNewPos () const [inline, virtual]
Definition at line 217 of file Vast_m.h.
Referenced by getNewPos().
{return const_cast<VastMoveMessage*>(this)->getNewPos();}
virtual bool VastMoveMessage::getRequest_list () const [virtual]
Referenced by Vast::handleNodeMove().
VastMoveMessage& VastMoveMessage::operator= (const VastMoveMessage & other)
bool VastMoveMessage::operator== (const VastMoveMessage &) [protected]
virtual void VastMoveMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doPacking().
virtual void VastMoveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doUnpacking().
virtual void VastMoveMessage::setIs_boundary (bool is_boundary) [virtual]
Referenced by Vast::handleJoinAcknowledge(), and Vast::handleMove().
virtual void VastMoveMessage::setNewPos (const Vector2D & newPos) [virtual]
Referenced by Vast::handleJoinAcknowledge(), Vast::handleMove(), and Vast::processDiscoveryTimer().
virtual void VastMoveMessage::setRequest_list (bool request_list) [virtual]
Referenced by Vast::handleJoinAcknowledge(), and Vast::processDiscoveryTimer().
Member Data Documentation
bool VastMoveMessage::is_boundary_var [protected]
Definition at line 196 of file Vast_m.h.
Vector2D VastMoveMessage::newPos_var [protected]
Definition at line 195 of file Vast_m.h.
bool VastMoveMessage::request_list_var [protected]
Definition at line 197 of file Vast_m.h.
The documentation for this class was generated from the following file:
Vast_m.h