OverSim: CommonAPIMessage Class Reference
CommonAPIMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
CommonAPIMessage (const char *name=NULL, int kind=0)
CommonAPIMessage (const CommonAPIMessage &other)
virtual ~CommonAPIMessage ()
CommonAPIMessage & operator= (const CommonAPIMessage &other)
virtual CommonAPIMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type)
Protected Member Functions
bool operator== (const CommonAPIMessage &)
Protected Attributes
int type_var
Private Member Functions
void copy (const CommonAPIMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet CommonAPIMessage
 {
     int type enum(CommonAPIMessageType) = COMMON_API_UNDEFINED;
 }
Definition at line 1101 of file CommonMessages_m.h.
Constructor & Destructor Documentation
CommonAPIMessage::CommonAPIMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
CommonAPIMessage::CommonAPIMessage (const CommonAPIMessage & other)
virtual CommonAPIMessage::~CommonAPIMessage () [virtual]
Member Function Documentation
void CommonAPIMessage::copy (const CommonAPIMessage & other) [private]
virtual CommonAPIMessage* CommonAPIMessage::dup () const [inline, virtual]
Reimplemented in KBRupdate, KBRdeliver, KBRforward, and KBRroute.
Definition at line 1118 of file CommonMessages_m.h.
{return new CommonAPIMessage(*this);}
virtual int CommonAPIMessage::getType () const [virtual]
Referenced by BaseApp::handleCommonAPIMessage().
CommonAPIMessage& CommonAPIMessage::operator= (const CommonAPIMessage & other)
bool CommonAPIMessage::operator== (const CommonAPIMessage &) [protected]
virtual void CommonAPIMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in KBRupdate, KBRdeliver, KBRforward, and KBRroute.
Referenced by doPacking().
virtual void CommonAPIMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in KBRupdate, KBRdeliver, KBRforward, and KBRroute.
Referenced by doUnpacking().
virtual void CommonAPIMessage::setType (int type) [virtual]
Referenced by BaseOverlay::callDeliver(), BaseOverlay::callForward(), BaseApp::callRoute(), and BaseOverlay::callUpdate().
Member Data Documentation
int CommonAPIMessage::type_var [protected]
Definition at line 1104 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h