OverSim: BaseResponseMessage Class Reference
BaseResponseMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BaseResponseMessage (const char *name=NULL, int kind=0)
BaseResponseMessage (const BaseResponseMessage &other)
virtual ~BaseResponseMessage ()
BaseResponseMessage & operator= (const BaseResponseMessage &other)
virtual BaseResponseMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCallHopCount () const
virtual void setCallHopCount (int callHopCount)
virtual void setNcsInfoArraySize (unsigned int size)
virtual unsigned int getNcsInfoArraySize () const
virtual double getNcsInfo (unsigned int k) const
virtual void setNcsInfo (unsigned int k, double ncsInfo)
Protected Member Functions
bool operator== (const BaseResponseMessage &)
Protected Attributes
int callHopCount_var
double * ncsInfo_var
unsigned int ncsInfo_arraysize
Private Member Functions
void copy (const BaseResponseMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet BaseResponseMessage extends BaseRpcMessage
 {
     int callHopCount = 0;
     double ncsInfo[];
 }
Definition at line 558 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BaseResponseMessage::BaseResponseMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BaseResponseMessage::BaseResponseMessage (const BaseResponseMessage & other)
virtual BaseResponseMessage::~BaseResponseMessage () [virtual]
Member Function Documentation
void BaseResponseMessage::copy (const BaseResponseMessage & other) [private]
virtual BaseResponseMessage* BaseResponseMessage::dup () const [inline, virtual]
Reimplemented from BaseRpcMessage.
Reimplemented in P2pnsResolveResponse, P2pnsRegisterResponse, LookupResponse, DHTdumpResponse, DHTgetCAPIResponse, DHTputCAPIResponse, PubSubAdoptChildResponse, NextHopResponse, PingResponse, PubSubPingResponse, FailedNodeResponse, HGetChildrenResponse, PubSubBackupResponse, CapReqResponse, FindNodeResponse, PubSubIntermediateResponse, HScheduleSegmentsResponse, RequestRoutingRowResponse, DeBruijnResponse, PubSubHelpResponse, RequestLeafSetResponse, HLeaveOverlayResponse, RequestRepairResponse, FixfingersResponse, PubSubSubscriptionResponse, RequestStateResponse, ChildCheckResponse, HJoinResponse, StabilizeResponse, PubSubTakeOverSubspaceResponse, NTreeNodePingResponse, PastryJoinResponse, NTreePingResponse, ChildReleaseResponse, JoinResponse, PubSubResponsibleNodeResponse, HSelectParentResponse, GlobalViewBuilderResponse, DHTGetResponse, PubSubJoinResponse, HGetParametersResponse, NotifyResponse, UnderlayTestResponse, ScribePublishResponse, NTreeDivideResponse, TreeAppResponse, DHTPutResponse, RttToNodeResponse, BucketResponse, HCapacityResponse, KbrTestResponse, CoordsOfNodeResponse, ScribeJoinResponse, ParentRequestResponse, ProxFindNodeResponse, NTreeJoinResponse, DiscoveryResponse, MyNeighborResponse, CoordsReqResponse, and CBRDHTGetResponse.
Definition at line 577 of file CommonMessages_m.h.
{return new BaseResponseMessage(*this);}
virtual int BaseResponseMessage::getCallHopCount () const [virtual]
Referenced by KBRTestApp::handleRpcResponse(), and BaseRpc::internalHandleRpcMessage().
virtual double BaseResponseMessage::getNcsInfo (unsigned int k) const [virtual]
Referenced by Nps::coordsReqRpcResponse(), and BaseRpc::internalHandleRpcMessage().
virtual unsigned int BaseResponseMessage::getNcsInfoArraySize () const [virtual]
Referenced by Nps::coordsReqRpcResponse(), and BaseRpc::internalHandleRpcMessage().
BaseResponseMessage& BaseResponseMessage::operator= (const BaseResponseMessage & other)
bool BaseResponseMessage::operator== (const BaseResponseMessage &) [protected]
virtual void BaseResponseMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseRpcMessage.
Reimplemented in P2pnsResolveResponse, P2pnsRegisterResponse, LookupResponse, DHTdumpResponse, DHTgetCAPIResponse, DHTputCAPIResponse, PubSubAdoptChildResponse, NextHopResponse, PingResponse, PubSubPingResponse, FailedNodeResponse, HGetChildrenResponse, PubSubBackupResponse, CapReqResponse, FindNodeResponse, PubSubIntermediateResponse, HScheduleSegmentsResponse, RequestRoutingRowResponse, DeBruijnResponse, PubSubHelpResponse, RequestLeafSetResponse, HLeaveOverlayResponse, RequestRepairResponse, FixfingersResponse, PubSubSubscriptionResponse, RequestStateResponse, ChildCheckResponse, HJoinResponse, StabilizeResponse, PubSubTakeOverSubspaceResponse, NTreeNodePingResponse, PastryJoinResponse, NTreePingResponse, ChildReleaseResponse, JoinResponse, PubSubResponsibleNodeResponse, HSelectParentResponse, GlobalViewBuilderResponse, DHTGetResponse, PubSubJoinResponse, HGetParametersResponse, NotifyResponse, UnderlayTestResponse, ScribePublishResponse, NTreeDivideResponse, TreeAppResponse, DHTPutResponse, RttToNodeResponse, BucketResponse, HCapacityResponse, KbrTestResponse, CoordsOfNodeResponse, ScribeJoinResponse, ParentRequestResponse, ProxFindNodeResponse, NTreeJoinResponse, DiscoveryResponse, MyNeighborResponse, CoordsReqResponse, and CBRDHTGetResponse.
Referenced by doPacking().
virtual void BaseResponseMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseRpcMessage.
Reimplemented in P2pnsResolveResponse, P2pnsRegisterResponse, LookupResponse, DHTdumpResponse, DHTgetCAPIResponse, DHTputCAPIResponse, PubSubAdoptChildResponse, NextHopResponse, PingResponse, PubSubPingResponse, FailedNodeResponse, HGetChildrenResponse, PubSubBackupResponse, CapReqResponse, FindNodeResponse, PubSubIntermediateResponse, HScheduleSegmentsResponse, RequestRoutingRowResponse, DeBruijnResponse, PubSubHelpResponse, RequestLeafSetResponse, HLeaveOverlayResponse, RequestRepairResponse, FixfingersResponse, PubSubSubscriptionResponse, RequestStateResponse, ChildCheckResponse, HJoinResponse, StabilizeResponse, PubSubTakeOverSubspaceResponse, NTreeNodePingResponse, PastryJoinResponse, NTreePingResponse, ChildReleaseResponse, JoinResponse, PubSubResponsibleNodeResponse, HSelectParentResponse, GlobalViewBuilderResponse, DHTGetResponse, PubSubJoinResponse, HGetParametersResponse, NotifyResponse, UnderlayTestResponse, ScribePublishResponse, NTreeDivideResponse, TreeAppResponse, DHTPutResponse, RttToNodeResponse, BucketResponse, HCapacityResponse, KbrTestResponse, CoordsOfNodeResponse, ScribeJoinResponse, ParentRequestResponse, ProxFindNodeResponse, NTreeJoinResponse, DiscoveryResponse, MyNeighborResponse, CoordsReqResponse, and CBRDHTGetResponse.
Referenced by doUnpacking().
virtual void BaseResponseMessage::setCallHopCount (int callHopCount) [virtual]
Referenced by BaseRpc::sendRpcResponse().
virtual void BaseResponseMessage::setNcsInfo (unsigned int k, double ncsInfo) [virtual]
Referenced by Nps::coordsReqRpc(), and BaseRpc::sendRpcResponse().
virtual void BaseResponseMessage::setNcsInfoArraySize (unsigned int size) [virtual]
Referenced by Nps::coordsReqRpc(), and BaseRpc::sendRpcResponse().
Member Data Documentation
int BaseResponseMessage::callHopCount_var [protected]
Definition at line 561 of file CommonMessages_m.h.
unsigned int BaseResponseMessage::ncsInfo_arraysize [protected]
Definition at line 563 of file CommonMessages_m.h.
double* BaseResponseMessage::ncsInfo_var [protected]
Definition at line 562 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h