OverSim: PubSubHelpResponse Class Reference
PubSubHelpResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubHelpResponse (const char *name=NULL, int kind=0)
PubSubHelpResponse (const PubSubHelpResponse &other)
virtual ~PubSubHelpResponse ()
PubSubHelpResponse & operator= (const PubSubHelpResponse &other)
virtual PubSubHelpResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual int getHelpType () const
virtual void setHelpType (int helpType)
virtual NodeHandle & getNode ()
virtual const NodeHandle & getNode () const
virtual void setNode (const NodeHandle &node)
Protected Member Functions
bool operator== (const PubSubHelpResponse &)
Protected Attributes
int subspaceId_var
int helpType_var
NodeHandle node_var
Private Member Functions
void copy (const PubSubHelpResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubHelpResponse extends BaseResponseMessage
 {
         int subspaceId;
         int helpType enum(PubSubHelpType);
         NodeHandle node;
 }
Definition at line 573 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubHelpResponse::PubSubHelpResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubHelpResponse::PubSubHelpResponse (const PubSubHelpResponse & other)
virtual PubSubHelpResponse::~PubSubHelpResponse () [virtual]
Member Function Documentation
void PubSubHelpResponse::copy (const PubSubHelpResponse & other) [private]
virtual PubSubHelpResponse* PubSubHelpResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 592 of file PubSubMessage_m.h.
{return new PubSubHelpResponse(*this);}
virtual int PubSubHelpResponse::getHelpType () const [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual NodeHandle& PubSubHelpResponse::getNode () [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
virtual const NodeHandle& PubSubHelpResponse::getNode () const [inline, virtual]
Definition at line 602 of file PubSubMessage_m.h.
Referenced by getNode().
{return const_cast<PubSubHelpResponse*>(this)->getNode();}
virtual int PubSubHelpResponse::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleHelpResponse().
PubSubHelpResponse& PubSubHelpResponse::operator= (const PubSubHelpResponse & other)
bool PubSubHelpResponse::operator== (const PubSubHelpResponse &) [protected]
virtual void PubSubHelpResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubHelpResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubHelpResponse::setHelpType (int helpType) [virtual]
Referenced by PubSubLobby::handleHelpCall().
virtual void PubSubHelpResponse::setNode (const NodeHandle & node) [virtual]
Referenced by PubSubLobby::handleHelpCall(), and PubSubLobby::handleJoin().
virtual void PubSubHelpResponse::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubLobby::handleHelpCall(), and PubSubLobby::handleJoin().
Member Data Documentation
int PubSubHelpResponse::helpType_var [protected]
Definition at line 577 of file PubSubMessage_m.h.
NodeHandle PubSubHelpResponse::node_var [protected]
Definition at line 578 of file PubSubMessage_m.h.
int PubSubHelpResponse::subspaceId_var [protected]
Definition at line 576 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h