OverSim: QuonEventMessage Class Reference
QuonEventMessage Class Reference
Class generated from overlay/quon/Quon.msg by opp_msgc.
#include <Quon_m.h>
Public Member Functions
QuonEventMessage (const char *name=NULL, int kind=0)
QuonEventMessage (const QuonEventMessage &other)
virtual ~QuonEventMessage ()
QuonEventMessage & operator= (const QuonEventMessage &other)
virtual QuonEventMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const QuonEventMessage &)
Private Member Functions
void copy (const QuonEventMessage &other)
Detailed Description
Class generated from overlay/quon/Quon.msg by opp_msgc.
 packet QuonEventMessage extends QuonMessage
 {
 }
Definition at line 252 of file Quon_m.h.
Constructor & Destructor Documentation
QuonEventMessage::QuonEventMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
QuonEventMessage::QuonEventMessage (const QuonEventMessage & other)
virtual QuonEventMessage::~QuonEventMessage () [virtual]
Member Function Documentation
void QuonEventMessage::copy (const QuonEventMessage & other) [private]
virtual QuonEventMessage* QuonEventMessage::dup () const [inline, virtual]
Reimplemented from QuonMessage.
Definition at line 268 of file Quon_m.h.
{return new QuonEventMessage(*this);}
QuonEventMessage& QuonEventMessage::operator= (const QuonEventMessage & other)
bool QuonEventMessage::operator== (const QuonEventMessage &) [protected]
virtual void QuonEventMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from QuonMessage.
Referenced by doPacking().
virtual void QuonEventMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from QuonMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Quon_m.h