OverSim: NewSuccessorHintMessage Class Reference
NewSuccessorHintMessage Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
NewSuccessorHintMessage (const char *name=NULL, int kind=0)
NewSuccessorHintMessage (const NewSuccessorHintMessage &other)
virtual ~NewSuccessorHintMessage ()
NewSuccessorHintMessage & operator= (const NewSuccessorHintMessage &other)
virtual NewSuccessorHintMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrcNode ()
virtual const NodeHandle & getSrcNode () const
virtual void setSrcNode (const NodeHandle &srcNode)
virtual NodeHandle & getPreNode ()
virtual const NodeHandle & getPreNode () const
virtual void setPreNode (const NodeHandle &preNode)
Protected Member Functions
bool operator== (const NewSuccessorHintMessage &)
Protected Attributes
NodeHandle srcNode_var
NodeHandle preNode_var
Private Member Functions
void copy (const NewSuccessorHintMessage &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet NewSuccessorHintMessage extends ChordMessage
 {
     NodeHandle srcNode;
     NodeHandle preNode;
 }
Definition at line 115 of file ChordMessage_m.h.
Constructor & Destructor Documentation
NewSuccessorHintMessage::NewSuccessorHintMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NewSuccessorHintMessage::NewSuccessorHintMessage (const NewSuccessorHintMessage & other)
virtual NewSuccessorHintMessage::~NewSuccessorHintMessage () [virtual]
Member Function Documentation
void NewSuccessorHintMessage::copy (const NewSuccessorHintMessage & other) [private]
virtual NewSuccessorHintMessage* NewSuccessorHintMessage::dup () const [inline, virtual]
Reimplemented from ChordMessage.
Definition at line 133 of file ChordMessage_m.h.
{return new NewSuccessorHintMessage(*this);}
virtual NodeHandle& NewSuccessorHintMessage::getPreNode () [virtual]
Referenced by oversim::Chord::handleNewSuccessorHint().
virtual const NodeHandle& NewSuccessorHintMessage::getPreNode () const [inline, virtual]
Definition at line 142 of file ChordMessage_m.h.
Referenced by getPreNode().
{return const_cast<NewSuccessorHintMessage*>(this)->getPreNode();}
virtual NodeHandle& NewSuccessorHintMessage::getSrcNode () [virtual]
virtual const NodeHandle& NewSuccessorHintMessage::getSrcNode () const [inline, virtual]
Definition at line 139 of file ChordMessage_m.h.
Referenced by getSrcNode().
{return const_cast<NewSuccessorHintMessage*>(this)->getSrcNode();}
NewSuccessorHintMessage& NewSuccessorHintMessage::operator= (const NewSuccessorHintMessage & other)
bool NewSuccessorHintMessage::operator== (const NewSuccessorHintMessage &) [protected]
virtual void NewSuccessorHintMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ChordMessage.
Referenced by doPacking().
virtual void NewSuccessorHintMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ChordMessage.
Referenced by doUnpacking().
virtual void NewSuccessorHintMessage::setPreNode (const NodeHandle & preNode) [virtual]
Referenced by oversim::Chord::handleRpcJoinResponse(), oversim::Chord::rpcJoin(), and oversim::Chord::rpcNotify().
virtual void NewSuccessorHintMessage::setSrcNode (const NodeHandle & srcNode) [virtual]
Referenced by oversim::Chord::handleRpcJoinResponse(), oversim::Chord::rpcJoin(), and oversim::Chord::rpcNotify().
Member Data Documentation
NodeHandle NewSuccessorHintMessage::preNode_var [protected]
Definition at line 119 of file ChordMessage_m.h.
NodeHandle NewSuccessorHintMessage::srcNode_var [protected]
Definition at line 118 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h