OverSim: HSwitchToRescueModeCall Class Reference
HSwitchToRescueModeCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HSwitchToRescueModeCall (const char *name=NULL, int kind=0)
HSwitchToRescueModeCall (const HSwitchToRescueModeCall &other)
virtual ~HSwitchToRescueModeCall ()
HSwitchToRescueModeCall & operator= (const HSwitchToRescueModeCall &other)
virtual HSwitchToRescueModeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const HSwitchToRescueModeCall &)
Private Member Functions
void copy (const HSwitchToRescueModeCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HSwitchToRescueModeCall extends BaseCallMessage {
 }
Definition at line 693 of file HMessage_m.h.
Constructor & Destructor Documentation
HSwitchToRescueModeCall::HSwitchToRescueModeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HSwitchToRescueModeCall::HSwitchToRescueModeCall (const HSwitchToRescueModeCall & other)
virtual HSwitchToRescueModeCall::~HSwitchToRescueModeCall () [virtual]
Member Function Documentation
void HSwitchToRescueModeCall::copy (const HSwitchToRescueModeCall & other) [private]
virtual HSwitchToRescueModeCall* HSwitchToRescueModeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 709 of file HMessage_m.h.
{return new HSwitchToRescueModeCall(*this);}
HSwitchToRescueModeCall& HSwitchToRescueModeCall::operator= (const HSwitchToRescueModeCall & other)
bool HSwitchToRescueModeCall::operator== (const HSwitchToRescueModeCall &) [protected]
virtual void HSwitchToRescueModeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HSwitchToRescueModeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
HMessage_m.h