OverSim: CapReqCall Class Reference
CapReqCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
CapReqCall (const char *name=NULL, int kind=0)
CapReqCall (const CapReqCall &other)
virtual ~CapReqCall ()
CapReqCall & operator= (const CapReqCall &other)
virtual CapReqCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const CapReqCall &)
Private Member Functions
void copy (const CapReqCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet CapReqCall extends BaseCallMessage
 {
 }
Definition at line 687 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
CapReqCall::CapReqCall (const char * name = NULL, int kind = 0)
Referenced by dup().
CapReqCall::CapReqCall (const CapReqCall & other)
virtual CapReqCall::~CapReqCall () [virtual]
Member Function Documentation
void CapReqCall::copy (const CapReqCall & other) [private]
virtual CapReqCall* CapReqCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 703 of file TreeManagementMessage_m.h.
{return new CapReqCall(*this);}
CapReqCall& CapReqCall::operator= (const CapReqCall & other)
bool CapReqCall::operator== (const CapReqCall &) [protected]
virtual void CapReqCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void CapReqCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h