OverSim: HSelectParentResponse Class Reference
HSelectParentResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HSelectParentResponse (const char *name=NULL, int kind=0)
HSelectParentResponse (const HSelectParentResponse &other)
virtual ~HSelectParentResponse ()
HSelectParentResponse & operator= (const HSelectParentResponse &other)
virtual HSelectParentResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getRespondingNode ()
virtual const NodeHandle & getRespondingNode () const
virtual void setRespondingNode (const NodeHandle &respondingNode)
Protected Member Functions
bool operator== (const HSelectParentResponse &)
Protected Attributes
NodeHandle respondingNode_var
Private Member Functions
void copy (const HSelectParentResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HSelectParentResponse extends BaseResponseMessage {
     NodeHandle respondingNode;
 };
Definition at line 289 of file HMessage_m.h.
Constructor & Destructor Documentation
HSelectParentResponse::HSelectParentResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HSelectParentResponse::HSelectParentResponse (const HSelectParentResponse & other)
virtual HSelectParentResponse::~HSelectParentResponse () [virtual]
Member Function Documentation
void HSelectParentResponse::copy (const HSelectParentResponse & other) [private]
virtual HSelectParentResponse* HSelectParentResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 306 of file HMessage_m.h.
{return new HSelectParentResponse(*this);}
virtual NodeHandle& HSelectParentResponse::getRespondingNode () [virtual]
virtual const NodeHandle& HSelectParentResponse::getRespondingNode () const [inline, virtual]
Definition at line 312 of file HMessage_m.h.
Referenced by getRespondingNode().
{return const_cast<HSelectParentResponse*>(this)->getRespondingNode();}
HSelectParentResponse& HSelectParentResponse::operator= (const HSelectParentResponse & other)
bool HSelectParentResponse::operator== (const HSelectParentResponse &) [protected]
virtual void HSelectParentResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HSelectParentResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HSelectParentResponse::setRespondingNode (const NodeHandle & respondingNode) [virtual]
Member Data Documentation
NodeHandle HSelectParentResponse::respondingNode_var [protected]
Definition at line 292 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h