OverSim: ProxNodeHandle Class Reference
ProxNodeHandle Class Reference
#include <ProxNodeHandle.h>
Public Member Functions
ProxNodeHandle ()
ProxNodeHandle (const NodeHandle &nodeHandle)
ProxNodeHandle (const NodeHandle &nodeHandle, const Prox &prox)
virtual ~ProxNodeHandle ()
void setProx (Prox prox)
Prox getProx () const
Static Public Attributes
static const ProxNodeHandle UNSPECIFIED_NODE
the unspecified ProxNodeHandle
Protected Attributes
Prox prox
Detailed Description
Definition at line 65 of file ProxNodeHandle.h.
Constructor & Destructor Documentation
ProxNodeHandle::ProxNodeHandle () [inline]
Definition at line 72 of file ProxNodeHandle.h.
{ };
ProxNodeHandle::ProxNodeHandle (const NodeHandle & nodeHandle)
Definition at line 53 of file ProxNodeHandle.cc.
: NodeHandle(nodeHandle), prox(prox)
{
    //...
}
ProxNodeHandle::ProxNodeHandle (const NodeHandle & nodeHandle, const Prox & prox)
Definition at line 59 of file ProxNodeHandle.cc.
: NodeHandle(nodeHandle), prox(prox)
{
    //...
}
virtual ProxNodeHandle::~ProxNodeHandle () [inline, virtual]
Definition at line 75 of file ProxNodeHandle.h.
{ };
Member Function Documentation
Prox ProxNodeHandle::getProx () const [inline]
Definition at line 78 of file ProxNodeHandle.h.
Referenced by KademliaBucketEntry::getRtt(), ProxExtractor< KademliaBucketEntry >::prox(), ProxExtractor< ProxNodeHandle >::prox(), and Kademlia::routingAdd().
{ return prox; };
void ProxNodeHandle::setProx (Prox prox) [inline]
Definition at line 77 of file ProxNodeHandle.h.
Referenced by Kademlia::findNode(), and Kademlia::routingAdd().
{ this->prox = prox; };
Member Data Documentation
Prox ProxNodeHandle::prox [protected]
Definition at line 68 of file ProxNodeHandle.h.
Referenced by getProx(), KademliaBucketEntry::KademliaBucketEntry(), setProx(), and KademliaBucketEntry::setRtt().
const ProxNodeHandle ProxNodeHandle::UNSPECIFIED_NODE [static]
the unspecified ProxNodeHandle
Reimplemented from NodeHandle.
Definition at line 71 of file ProxNodeHandle.h.
The documentation for this class was generated from the following files:
ProxNodeHandle.h
ProxNodeHandle.cc