OverSim: NTreeLeaveMessage Class Reference
NTreeLeaveMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeLeaveMessage (const char *name=NULL, int kind=0)
NTreeLeaveMessage (const NTreeLeaveMessage &other)
virtual ~NTreeLeaveMessage ()
NTreeLeaveMessage & operator= (const NTreeLeaveMessage &other)
virtual NTreeLeaveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getPlayer ()
virtual const NodeHandle & getPlayer () const
virtual void setPlayer (const NodeHandle &player)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
Protected Member Functions
bool operator== (const NTreeLeaveMessage &)
Protected Attributes
NodeHandle player_var
Vector2D position_var
Private Member Functions
void copy (const NTreeLeaveMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeLeaveMessage extends BaseOverlayMessage
 {
         NodeHandle player;
         Vector2D position;
 }
Definition at line 498 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeLeaveMessage::NTreeLeaveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeLeaveMessage::NTreeLeaveMessage (const NTreeLeaveMessage & other)
virtual NTreeLeaveMessage::~NTreeLeaveMessage () [virtual]
Member Function Documentation
void NTreeLeaveMessage::copy (const NTreeLeaveMessage & other) [private]
virtual NTreeLeaveMessage* NTreeLeaveMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 516 of file NTree_m.h.
{return new NTreeLeaveMessage(*this);}
virtual NodeHandle& NTreeLeaveMessage::getPlayer () [virtual]
Referenced by NTree::handleLeaveMessage().
virtual const NodeHandle& NTreeLeaveMessage::getPlayer () const [inline, virtual]
Definition at line 522 of file NTree_m.h.
Referenced by getPlayer().
{return const_cast<NTreeLeaveMessage*>(this)->getPlayer();}
virtual Vector2D& NTreeLeaveMessage::getPosition () [virtual]
Referenced by NTree::handleLeaveMessage().
virtual const Vector2D& NTreeLeaveMessage::getPosition () const [inline, virtual]
Definition at line 525 of file NTree_m.h.
Referenced by getPosition().
{return const_cast<NTreeLeaveMessage*>(this)->getPosition();}
NTreeLeaveMessage& NTreeLeaveMessage::operator= (const NTreeLeaveMessage & other)
bool NTreeLeaveMessage::operator== (const NTreeLeaveMessage &) [protected]
virtual void NTreeLeaveMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeLeaveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeLeaveMessage::setPlayer (const NodeHandle & player) [virtual]
Referenced by NTree::handlePingCallTimeout(), and NTree::leaveGroup().
virtual void NTreeLeaveMessage::setPosition (const Vector2D & position) [virtual]
Referenced by NTree::handlePingCallTimeout(), and NTree::leaveGroup().
Member Data Documentation
NodeHandle NTreeLeaveMessage::player_var [protected]
Definition at line 501 of file NTree_m.h.
Vector2D NTreeLeaveMessage::position_var [protected]
Definition at line 502 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h