OverSim: PingCall Class Reference
PingCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
PingCall (const char *name=NULL, int kind=0)
PingCall (const PingCall &other)
virtual ~PingCall ()
PingCall & operator= (const PingCall &other)
virtual PingCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const PingCall &)
Private Member Functions
void copy (const PingCall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet PingCall extends BaseCallMessage
 {
 }
Definition at line 810 of file CommonMessages_m.h.
Constructor & Destructor Documentation
PingCall::PingCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PingCall::PingCall (const PingCall & other)
virtual PingCall::~PingCall () [virtual]
Member Function Documentation
void PingCall::copy (const PingCall & other) [private]
virtual PingCall* PingCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 826 of file CommonMessages_m.h.
{return new PingCall(*this);}
PingCall& PingCall::operator= (const PingCall & other)
bool PingCall::operator== (const PingCall &) [protected]
virtual void PingCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PingCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h