OverSim: DHTgetCAPIResponse Class Reference
DHTgetCAPIResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
DHTgetCAPIResponse (const char *name=NULL, int kind=0)
DHTgetCAPIResponse (const DHTgetCAPIResponse &other)
virtual ~DHTgetCAPIResponse ()
DHTgetCAPIResponse & operator= (const DHTgetCAPIResponse &other)
virtual DHTgetCAPIResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setResultArraySize (unsigned int size)
virtual unsigned int getResultArraySize () const
virtual DhtDumpEntry & getResult (unsigned int k)
virtual const DhtDumpEntry & getResult (unsigned int k) const
virtual void setResult (unsigned int k, const DhtDumpEntry &result)
virtual bool getIsSuccess () const
virtual void setIsSuccess (bool isSuccess)
Protected Member Functions
bool operator== (const DHTgetCAPIResponse &)
Protected Attributes
DhtDumpEntry * result_var
unsigned int result_arraysize
bool isSuccess_var
Private Member Functions
void copy (const DHTgetCAPIResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet DHTgetCAPIResponse extends BaseResponseMessage
 {
     DhtDumpEntry result[];
     bool isSuccess;
 }
Definition at line 1539 of file CommonMessages_m.h.
Constructor & Destructor Documentation
DHTgetCAPIResponse::DHTgetCAPIResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTgetCAPIResponse::DHTgetCAPIResponse (const DHTgetCAPIResponse & other)
virtual DHTgetCAPIResponse::~DHTgetCAPIResponse () [virtual]
Member Function Documentation
void DHTgetCAPIResponse::copy (const DHTgetCAPIResponse & other) [private]
virtual DHTgetCAPIResponse* DHTgetCAPIResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 1558 of file CommonMessages_m.h.
{return new DHTgetCAPIResponse(*this);}
virtual bool DHTgetCAPIResponse::getIsSuccess () const [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and DHTTestApp::handleGetResponse().
virtual DhtDumpEntry& DHTgetCAPIResponse::getResult (unsigned int k) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and DHTTestApp::handleGetResponse().
virtual const DhtDumpEntry& DHTgetCAPIResponse::getResult (unsigned int k) const [inline, virtual]
Definition at line 1566 of file CommonMessages_m.h.
Referenced by getResult().
{return const_cast<DHTgetCAPIResponse*>(this)->getResult(k);}
virtual unsigned int DHTgetCAPIResponse::getResultArraySize () const [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and DHTTestApp::handleGetResponse().
DHTgetCAPIResponse& DHTgetCAPIResponse::operator= (const DHTgetCAPIResponse & other)
bool DHTgetCAPIResponse::operator== (const DHTgetCAPIResponse &) [protected]
virtual void DHTgetCAPIResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void DHTgetCAPIResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void DHTgetCAPIResponse::setIsSuccess (bool isSuccess) [virtual]
Referenced by CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handleRpcTimeout(), and DHT::handleRpcTimeout().
virtual void DHTgetCAPIResponse::setResult (unsigned int k, const DhtDumpEntry & result) [virtual]
Referenced by CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), and CBRDHT::handleRpcTimeout().
virtual void DHTgetCAPIResponse::setResultArraySize (unsigned int size) [virtual]
Referenced by CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), and CBRDHT::handleRpcTimeout().
Member Data Documentation
bool DHTgetCAPIResponse::isSuccess_var [protected]
Definition at line 1544 of file CommonMessages_m.h.
unsigned int DHTgetCAPIResponse::result_arraysize [protected]
Definition at line 1543 of file CommonMessages_m.h.
DhtDumpEntry* DHTgetCAPIResponse::result_var [protected]
Definition at line 1542 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h