OverSim: SingleHostUnderlayPacketNotification Class Reference
SingleHostUnderlayPacketNotification Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
SingleHostUnderlayPacketNotification (const char *name=NULL, int kind=0)
SingleHostUnderlayPacketNotification (const SingleHostUnderlayPacketNotification &other)
virtual ~SingleHostUnderlayPacketNotification ()
SingleHostUnderlayPacketNotification & operator= (const SingleHostUnderlayPacketNotification &other)
virtual
SingleHostUnderlayPacketNotification * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const SingleHostUnderlayPacketNotification &)
Private Member Functions
void copy (const SingleHostUnderlayPacketNotification &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 message SingleHostUnderlayPacketNotification
 {
 }
Definition at line 1027 of file CommonMessages_m.h.
Constructor & Destructor Documentation
SingleHostUnderlayPacketNotification::SingleHostUnderlayPacketNotification (const char * name = NULL, int kind = 0)
Referenced by dup().
SingleHostUnderlayPacketNotification::SingleHostUnderlayPacketNotification (const SingleHostUnderlayPacketNotification & other)
virtual SingleHostUnderlayPacketNotification::~SingleHostUnderlayPacketNotification () [virtual]
Member Function Documentation
void SingleHostUnderlayPacketNotification::copy (const SingleHostUnderlayPacketNotification & other) [private]
virtual SingleHostUnderlayPacketNotification* SingleHostUnderlayPacketNotification::dup () const [inline, virtual]
Definition at line 1043 of file CommonMessages_m.h.
{return new SingleHostUnderlayPacketNotification(*this);}
SingleHostUnderlayPacketNotification& SingleHostUnderlayPacketNotification::operator= (const SingleHostUnderlayPacketNotification & other)
bool SingleHostUnderlayPacketNotification::operator== (const SingleHostUnderlayPacketNotification &) [protected]
virtual void SingleHostUnderlayPacketNotification::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SingleHostUnderlayPacketNotification::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h