OverSim: RescueNode Class Reference
RescueNode Class Reference
#include <HStructs.h>
Public Member Functions
void setHandle (NodeHandle &node)
NodeHandle & getHandle ()
void setRankingParameters (RankingParameters params)
RankingParameters & getRankingParameters ()
double getRank () const
Private Member Functions
void calculateRank ()
Private Attributes
RankingParameters parameters
double rank
NodeHandle node
Detailed Description
Definition at line 43 of file HStructs.h.
Member Function Documentation
void RescueNode::calculateRank () [inline, private]
Definition at line 49 of file HStructs.h.
Referenced by setRankingParameters().
{
        rank =    RankingFactors.bandwidth * parameters.bandwidth
                + RankingFactors.rtt * parameters.rtt
                + RankingFactors.rescueCapacity * parameters.rescueCapacity
                + RankingFactors.capacity * parameters.capacity;
    }
NodeHandle& RescueNode::getHandle () [inline]
Definition at line 57 of file HStructs.h.
Referenced by HTopology::handleJoinCall().
{ return this->node; }
double RescueNode::getRank () const [inline]
Definition at line 62 of file HStructs.h.
Referenced by compareRescueNodes().
{ return rank; }
RankingParameters& RescueNode::getRankingParameters () [inline]
Definition at line 60 of file HStructs.h.
{ return parameters; }
void RescueNode::setHandle (NodeHandle & node) [inline]
Definition at line 56 of file HStructs.h.
Referenced by HTopology::handleRpcResponse(), and HTopology::setNodesOneUp().
{ this->node = node; }
void RescueNode::setRankingParameters (RankingParameters params) [inline]
Definition at line 59 of file HStructs.h.
{this->parameters = params; calculateRank();}
Member Data Documentation
NodeHandle RescueNode::node [private]
Definition at line 47 of file HStructs.h.
Referenced by getHandle(), and setHandle().
RankingParameters RescueNode::parameters [private]
Definition at line 45 of file HStructs.h.
Referenced by calculateRank(), getRankingParameters(), and setRankingParameters().
double RescueNode::rank [private]
Definition at line 46 of file HStructs.h.
Referenced by calculateRank(), and getRank().
The documentation for this class was generated from the following file:
HStructs.h