OverSim: MyMessage Class Reference
MyMessage Class Reference
Class generated from applications/myapplication/MyMessage.msg by opp_msgc.
#include <MyMessage_m.h>
Public Member Functions
MyMessage (const char *name=NULL, int kind=0)
MyMessage (const MyMessage &other)
virtual ~MyMessage ()
MyMessage & operator= (const MyMessage &other)
virtual MyMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type)
virtual TransportAddress & getSenderAddress ()
virtual const TransportAddress & getSenderAddress () const
virtual void setSenderAddress (const TransportAddress &senderAddress)
Protected Member Functions
bool operator== (const MyMessage &)
Protected Attributes
int type_var
TransportAddress senderAddress_var
Private Member Functions
void copy (const MyMessage &other)
Detailed Description
Class generated from applications/myapplication/MyMessage.msg by opp_msgc.
 packet MyMessage
 {
     int type enum(MessageType);
     TransportAddress senderAddress;
 }
Definition at line 47 of file MyMessage_m.h.
Constructor & Destructor Documentation
MyMessage::MyMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
MyMessage::MyMessage (const MyMessage & other)
virtual MyMessage::~MyMessage () [virtual]
Member Function Documentation
void MyMessage::copy (const MyMessage & other) [private]
virtual MyMessage* MyMessage::dup () const [inline, virtual]
Definition at line 65 of file MyMessage_m.h.
{return new MyMessage(*this);}
virtual TransportAddress& MyMessage::getSenderAddress () [virtual]
Referenced by MyApplication::deliver().
virtual const TransportAddress& MyMessage::getSenderAddress () const [inline, virtual]
Definition at line 73 of file MyMessage_m.h.
Referenced by getSenderAddress().
{return const_cast<MyMessage*>(this)->getSenderAddress();}
virtual int MyMessage::getType () const [virtual]
Referenced by MyApplication::deliver(), and MyApplication::handleUDPMessage().
MyMessage& MyMessage::operator= (const MyMessage & other)
bool MyMessage::operator== (const MyMessage &) [protected]
virtual void MyMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void MyMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void MyMessage::setSenderAddress (const TransportAddress & senderAddress) [virtual]
Referenced by MyApplication::handleTimerEvent().
virtual void MyMessage::setType (int type) [virtual]
Referenced by MyApplication::deliver(), and MyApplication::handleTimerEvent().
Member Data Documentation
TransportAddress MyMessage::senderAddress_var [protected]
Definition at line 51 of file MyMessage_m.h.
int MyMessage::type_var [protected]
Definition at line 50 of file MyMessage_m.h.
The documentation for this class was generated from the following file:
MyMessage_m.h