OverSim: FailedNodeCall Class Reference
FailedNodeCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
FailedNodeCall (const char *name=NULL, int kind=0)
FailedNodeCall (const FailedNodeCall &other)
virtual ~FailedNodeCall ()
FailedNodeCall & operator= (const FailedNodeCall &other)
virtual FailedNodeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getFailedNode ()
virtual const TransportAddress & getFailedNode () const
virtual void setFailedNode (const TransportAddress &failedNode)
Protected Member Functions
bool operator== (const FailedNodeCall &)
Protected Attributes
TransportAddress failedNode_var
Private Member Functions
void copy (const FailedNodeCall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet FailedNodeCall extends BaseCallMessage
 {
     TransportAddress failedNode;
 }
Definition at line 734 of file CommonMessages_m.h.
Constructor & Destructor Documentation
FailedNodeCall::FailedNodeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
FailedNodeCall::FailedNodeCall (const FailedNodeCall & other)
virtual FailedNodeCall::~FailedNodeCall () [virtual]
Member Function Documentation
void FailedNodeCall::copy (const FailedNodeCall & other) [private]
virtual FailedNodeCall* FailedNodeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 751 of file CommonMessages_m.h.
Referenced by Kademlia::handleNodeGracefulLeaveNotification().
{return new FailedNodeCall(*this);}
virtual TransportAddress& FailedNodeCall::getFailedNode () [virtual]
Referenced by BaseOverlay::failedNodeRpc().
virtual const TransportAddress& FailedNodeCall::getFailedNode () const [inline, virtual]
Definition at line 757 of file CommonMessages_m.h.
Referenced by getFailedNode().
{return const_cast<FailedNodeCall*>(this)->getFailedNode();}
FailedNodeCall& FailedNodeCall::operator= (const FailedNodeCall & other)
bool FailedNodeCall::operator== (const FailedNodeCall &) [protected]
virtual void FailedNodeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void FailedNodeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void FailedNodeCall::setFailedNode (const TransportAddress & failedNode) [virtual]
Referenced by Kademlia::handleNodeGracefulLeaveNotification(), and IterativePathLookup::handleTimeout().
Member Data Documentation
TransportAddress FailedNodeCall::failedNode_var [protected]
Definition at line 737 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h