OverSim: ALMDeleteMessage Class Reference
ALMDeleteMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
ALMDeleteMessage (const char *name=NULL, int kind=0)
ALMDeleteMessage (const ALMDeleteMessage &other)
virtual ~ALMDeleteMessage ()
ALMDeleteMessage & operator= (const ALMDeleteMessage &other)
virtual ALMDeleteMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ALMDeleteMessage &)
Private Member Functions
void copy (const ALMDeleteMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet ALMDeleteMessage extends ALMMessage
 {
 }
Definition at line 2169 of file CommonMessages_m.h.
Constructor & Destructor Documentation
ALMDeleteMessage::ALMDeleteMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMDeleteMessage::ALMDeleteMessage (const ALMDeleteMessage & other)
virtual ALMDeleteMessage::~ALMDeleteMessage () [virtual]
Member Function Documentation
void ALMDeleteMessage::copy (const ALMDeleteMessage & other) [private]
virtual ALMDeleteMessage* ALMDeleteMessage::dup () const [inline, virtual]
Reimplemented from ALMMessage.
Definition at line 2185 of file CommonMessages_m.h.
{return new ALMDeleteMessage(*this);}
ALMDeleteMessage& ALMDeleteMessage::operator= (const ALMDeleteMessage & other)
bool ALMDeleteMessage::operator== (const ALMDeleteMessage &) [protected]
virtual void ALMDeleteMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doPacking().
virtual void ALMDeleteMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h