OverSim: HNewParentSelectedCall Class Reference
HNewParentSelectedCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HNewParentSelectedCall (const char *name=NULL, int kind=0)
HNewParentSelectedCall (const HNewParentSelectedCall &other)
virtual ~HNewParentSelectedCall ()
HNewParentSelectedCall & operator= (const HNewParentSelectedCall &other)
virtual HNewParentSelectedCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getParent ()
virtual const NodeHandle & getParent () const
virtual void setParent (const NodeHandle &parent)
Protected Member Functions
bool operator== (const HNewParentSelectedCall &)
Protected Attributes
NodeHandle parent_var
Private Member Functions
void copy (const HNewParentSelectedCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HNewParentSelectedCall extends BaseCallMessage {
     NodeHandle parent;
 }
Definition at line 528 of file HMessage_m.h.
Constructor & Destructor Documentation
HNewParentSelectedCall::HNewParentSelectedCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HNewParentSelectedCall::HNewParentSelectedCall (const HNewParentSelectedCall & other)
virtual HNewParentSelectedCall::~HNewParentSelectedCall () [virtual]
Member Function Documentation
void HNewParentSelectedCall::copy (const HNewParentSelectedCall & other) [private]
virtual HNewParentSelectedCall* HNewParentSelectedCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 545 of file HMessage_m.h.
{return new HNewParentSelectedCall(*this);}
virtual NodeHandle& HNewParentSelectedCall::getParent () [virtual]
Referenced by HTopology::handleNewParentSelectedCall().
virtual const NodeHandle& HNewParentSelectedCall::getParent () const [inline, virtual]
Definition at line 551 of file HMessage_m.h.
Referenced by getParent().
{return const_cast<HNewParentSelectedCall*>(this)->getParent();}
HNewParentSelectedCall& HNewParentSelectedCall::operator= (const HNewParentSelectedCall & other)
bool HNewParentSelectedCall::operator== (const HNewParentSelectedCall &) [protected]
virtual void HNewParentSelectedCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HNewParentSelectedCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void HNewParentSelectedCall::setParent (const NodeHandle & parent) [virtual]
Referenced by HTopology::goAheadWithRestSelectionProcess().
Member Data Documentation
NodeHandle HNewParentSelectedCall::parent_var [protected]
Definition at line 531 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h