OverSim: OverlayCtrlInfo Class Reference
OverlayCtrlInfo Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
OverlayCtrlInfo ()
OverlayCtrlInfo (const OverlayCtrlInfo &other)
virtual ~OverlayCtrlInfo ()
OverlayCtrlInfo & operator= (const OverlayCtrlInfo &other)
virtual OverlayCtrlInfo * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getLastHop ()
virtual const TransportAddress & getLastHop () const
virtual void setLastHop (const TransportAddress &lastHop)
virtual NodeHandle & getSrcNode ()
virtual const NodeHandle & getSrcNode () const
virtual void setSrcNode (const NodeHandle &srcNode)
virtual NodeHandle & getSrcRoute ()
virtual const NodeHandle & getSrcRoute () const
virtual void setSrcRoute (const NodeHandle &srcRoute)
virtual int getHopCount () const
virtual void setHopCount (int hopCount)
virtual void setVisitedHopsArraySize (unsigned int size)
virtual unsigned int getVisitedHopsArraySize () const
virtual TransportAddress & getVisitedHops (unsigned int k)
virtual const TransportAddress & getVisitedHops (unsigned int k) const
virtual void setVisitedHops (unsigned int k, const TransportAddress &visitedHops)
virtual int getSrcComp () const
virtual void setSrcComp (int srcComp)
virtual int getDestComp () const
virtual void setDestComp (int destComp)
virtual int getTransportType () const
virtual void setTransportType (int transportType)
virtual int getRoutingType () const
virtual void setRoutingType (int routingType)
Protected Member Functions
bool operator== (const OverlayCtrlInfo &)
Protected Attributes
TransportAddress lastHop_var
NodeHandle srcNode_var
NodeHandle srcRoute_var
int hopCount_var
TransportAddress * visitedHops_var
unsigned int visitedHops_arraysize
int srcComp_var
int destComp_var
int transportType_var
int routingType_var
Private Member Functions
void copy (const OverlayCtrlInfo &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 class OverlayCtrlInfo
 {
     TransportAddress lastHop;
     NodeHandle srcNode;
     NodeHandle srcRoute;
     int hopCount = 0;
     TransportAddress visitedHops[];
     int srcComp enum(CompType);
     int destComp enum(CompType);
     int transportType enum(TransportType) = INVALID_TRANSPORT;
     int routingType enum(RoutingType);
 }
Definition at line 1986 of file CommonMessages_m.h.
Constructor & Destructor Documentation
OverlayCtrlInfo::OverlayCtrlInfo ()
Referenced by dup().
OverlayCtrlInfo::OverlayCtrlInfo (const OverlayCtrlInfo & other)
virtual OverlayCtrlInfo::~OverlayCtrlInfo () [virtual]
Member Function Documentation
void OverlayCtrlInfo::copy (const OverlayCtrlInfo & other) [private]
virtual OverlayCtrlInfo* OverlayCtrlInfo::dup () const [inline, virtual]
Definition at line 2012 of file CommonMessages_m.h.
{return new OverlayCtrlInfo(*this);}
virtual int OverlayCtrlInfo::getDestComp () const [virtual]
Referenced by BaseOverlay::callDeliver(), and BaseOverlay::handleMessage().
virtual int OverlayCtrlInfo::getHopCount () const [virtual]
Referenced by BaseOverlay::handleMessage(), Pastry::handlePastryJoinCall(), and BaseRpc::sendRpcResponse().
virtual TransportAddress& OverlayCtrlInfo::getLastHop () [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleBaseOverlayMessage(), BaseRpc::internalHandleRpcMessage(), BaseApp::internalSendRpcResponse(), BaseOverlay::internalSendRpcResponse(), BaseOverlay::sendRouteMessage(), and BaseOverlay::sendToKey().
virtual const TransportAddress& OverlayCtrlInfo::getLastHop () const [inline, virtual]
Definition at line 2018 of file CommonMessages_m.h.
Referenced by getLastHop().
{return const_cast<OverlayCtrlInfo*>(this)->getLastHop();}
virtual int OverlayCtrlInfo::getRoutingType () const [virtual]
Referenced by BaseOverlay::handleMessage(), BaseApp::internalSendRpcResponse(), BaseOverlay::internalSendRpcResponse(), and BaseRpc::sendRpcResponse().
virtual int OverlayCtrlInfo::getSrcComp () const [virtual]
Referenced by BaseOverlay::handleMessage(), BaseApp::internalSendRpcResponse(), BaseOverlay::internalSendRpcResponse(), and BaseRpc::sendRpcResponse().
virtual NodeHandle& OverlayCtrlInfo::getSrcNode () [virtual]
Referenced by BaseOverlay::handleMessage(), BaseApp::internalSendRpcResponse(), and BaseOverlay::internalSendRpcResponse().
virtual const NodeHandle& OverlayCtrlInfo::getSrcNode () const [inline, virtual]
Definition at line 2021 of file CommonMessages_m.h.
Referenced by getSrcNode().
{return const_cast<OverlayCtrlInfo*>(this)->getSrcNode();}
virtual NodeHandle& OverlayCtrlInfo::getSrcRoute () [virtual]
Referenced by BaseApp::handleCommonAPIMessage(), Kademlia::handleRpcCall(), Kademlia::handleRpcResponse(), BaseRpc::internalHandleRpcMessage(), and P2pns::updateIdCacheWithNewTransport().
virtual const NodeHandle& OverlayCtrlInfo::getSrcRoute () const [inline, virtual]
Definition at line 2024 of file CommonMessages_m.h.
Referenced by getSrcRoute().
{return const_cast<OverlayCtrlInfo*>(this)->getSrcRoute();}
virtual int OverlayCtrlInfo::getTransportType () const [virtual]
Referenced by BaseApp::handleCommonAPIMessage(), BaseApp::internalSendRpcResponse(), BaseOverlay::internalSendRpcResponse(), and BaseRpc::sendRpcResponse().
virtual TransportAddress& OverlayCtrlInfo::getVisitedHops (unsigned int k) [virtual]
Referenced by BaseRpc::sendRpcResponse().
virtual const TransportAddress& OverlayCtrlInfo::getVisitedHops (unsigned int k) const [inline, virtual]
Definition at line 2031 of file CommonMessages_m.h.
Referenced by getVisitedHops().
{return const_cast<OverlayCtrlInfo*>(this)->getVisitedHops(k);}
virtual unsigned int OverlayCtrlInfo::getVisitedHopsArraySize () const [virtual]
Referenced by BaseRpc::sendRpcResponse().
OverlayCtrlInfo& OverlayCtrlInfo::operator= (const OverlayCtrlInfo & other)
bool OverlayCtrlInfo::operator== (const OverlayCtrlInfo &) [protected]
virtual void OverlayCtrlInfo::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void OverlayCtrlInfo::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void OverlayCtrlInfo::setDestComp (int destComp) [virtual]
Referenced by BaseOverlay::callDeliver(), BaseOverlay::callForward(), Gia::forwardMessage(), and BaseRpc::sendRpcMessageWithTransport().
virtual void OverlayCtrlInfo::setHopCount (int hopCount) [virtual]
Referenced by BaseOverlay::callForward(), Gia::deliverSearchResult(), Gia::forwardMessage(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), BaseOverlay::nextHopRpc(), and BaseOverlay::sendToKey().
virtual void OverlayCtrlInfo::setLastHop (const TransportAddress & lastHop) [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleMessage(), BaseOverlay::internalHandleRpcTimeout(), and BaseOverlay::sendToKey().
virtual void OverlayCtrlInfo::setRoutingType (int routingType) [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), and BaseOverlay::sendToKey().
virtual void OverlayCtrlInfo::setSrcComp (int srcComp) [virtual]
Referenced by BaseOverlay::callDeliver(), BaseOverlay::callForward(), Gia::forwardMessage(), and BaseRpc::sendRpcMessageWithTransport().
virtual void OverlayCtrlInfo::setSrcNode (const NodeHandle & srcNode) [virtual]
Referenced by BaseOverlay::callForward(), Gia::deliverSearchResult(), Gia::forwardMessage(), BaseOverlay::handleBaseOverlayMessage(), and BaseOverlay::internalHandleRpcTimeout().
virtual void OverlayCtrlInfo::setSrcRoute (const NodeHandle & srcRoute) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), and BaseRpc::internalHandleRpcMessage().
virtual void OverlayCtrlInfo::setTransportType (int transportType) [virtual]
Referenced by BaseOverlay::callForward(), Gia::deliverSearchResult(), Gia::forwardMessage(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), BaseRpc::sendRpcMessageWithTransport(), and BaseOverlay::sendToKey().
virtual void OverlayCtrlInfo::setVisitedHops (unsigned int k, const TransportAddress & visitedHops) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual void OverlayCtrlInfo::setVisitedHopsArraySize (unsigned int size) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), and BaseOverlay::internalSendRpcResponse().
Member Data Documentation
int OverlayCtrlInfo::destComp_var [protected]
Definition at line 1996 of file CommonMessages_m.h.
int OverlayCtrlInfo::hopCount_var [protected]
Definition at line 1992 of file CommonMessages_m.h.
TransportAddress OverlayCtrlInfo::lastHop_var [protected]
Definition at line 1989 of file CommonMessages_m.h.
int OverlayCtrlInfo::routingType_var [protected]
Definition at line 1998 of file CommonMessages_m.h.
int OverlayCtrlInfo::srcComp_var [protected]
Definition at line 1995 of file CommonMessages_m.h.
NodeHandle OverlayCtrlInfo::srcNode_var [protected]
Definition at line 1990 of file CommonMessages_m.h.
NodeHandle OverlayCtrlInfo::srcRoute_var [protected]
Definition at line 1991 of file CommonMessages_m.h.
int OverlayCtrlInfo::transportType_var [protected]
Definition at line 1997 of file CommonMessages_m.h.
unsigned int OverlayCtrlInfo::visitedHops_arraysize [protected]
Definition at line 1994 of file CommonMessages_m.h.
TransportAddress* OverlayCtrlInfo::visitedHops_var [protected]
Definition at line 1993 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h