OverSim: P2pnsKeepaliveTimer Class Reference
P2pnsKeepaliveTimer Class Reference
Class generated from tier2/p2pns/P2pnsMessage.msg by opp_msgc.
#include <P2pnsMessage_m.h>
Public Member Functions
P2pnsKeepaliveTimer (const char *name=NULL, int kind=0)
P2pnsKeepaliveTimer (const P2pnsKeepaliveTimer &other)
virtual ~P2pnsKeepaliveTimer ()
P2pnsKeepaliveTimer & operator= (const P2pnsKeepaliveTimer &other)
virtual P2pnsKeepaliveTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
Protected Member Functions
bool operator== (const P2pnsKeepaliveTimer &)
Protected Attributes
OverlayKey key_var
Private Member Functions
void copy (const P2pnsKeepaliveTimer &other)
Detailed Description
Class generated from tier2/p2pns/P2pnsMessage.msg by opp_msgc.
 message P2pnsKeepaliveTimer
 {
     OverlayKey key;
 }
Definition at line 82 of file P2pnsMessage_m.h.
Constructor & Destructor Documentation
P2pnsKeepaliveTimer::P2pnsKeepaliveTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
P2pnsKeepaliveTimer::P2pnsKeepaliveTimer (const P2pnsKeepaliveTimer & other)
virtual P2pnsKeepaliveTimer::~P2pnsKeepaliveTimer () [virtual]
Member Function Documentation
void P2pnsKeepaliveTimer::copy (const P2pnsKeepaliveTimer & other) [private]
virtual P2pnsKeepaliveTimer* P2pnsKeepaliveTimer::dup () const [inline, virtual]
Definition at line 99 of file P2pnsMessage_m.h.
{return new P2pnsKeepaliveTimer(*this);}
virtual OverlayKey& P2pnsKeepaliveTimer::getKey () [virtual]
Referenced by P2pns::handleTimerEvent().
virtual const OverlayKey& P2pnsKeepaliveTimer::getKey () const [inline, virtual]
Definition at line 105 of file P2pnsMessage_m.h.
Referenced by getKey().
{return const_cast<P2pnsKeepaliveTimer*>(this)->getKey();}
P2pnsKeepaliveTimer& P2pnsKeepaliveTimer::operator= (const P2pnsKeepaliveTimer & other)
bool P2pnsKeepaliveTimer::operator== (const P2pnsKeepaliveTimer &) [protected]
virtual void P2pnsKeepaliveTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void P2pnsKeepaliveTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void P2pnsKeepaliveTimer::setKey (const OverlayKey & key) [virtual]
Referenced by P2pns::handleTunnelLookupResponse(), and P2pns::updateIdCacheWithNewTransport().
Member Data Documentation
OverlayKey P2pnsKeepaliveTimer::key_var [protected]
Definition at line 85 of file P2pnsMessage_m.h.
The documentation for this class was generated from the following file:
P2pnsMessage_m.h