OverSim: LookupCall Class Reference
LookupCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
LookupCall (const char *name=NULL, int kind=0)
LookupCall (const LookupCall &other)
virtual ~LookupCall ()
LookupCall & operator= (const LookupCall &other)
virtual LookupCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual int getNumSiblings () const
virtual void setNumSiblings (int numSiblings)
virtual int getRoutingType () const
virtual void setRoutingType (int routingType)
Protected Member Functions
bool operator== (const LookupCall &)
Protected Attributes
OverlayKey key_var
int numSiblings_var
int routingType_var
Private Member Functions
void copy (const LookupCall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet LookupCall extends BaseCallMessage
 {
     OverlayKey key;
     int numSiblings;
     int routingType enum(RoutingType) = DEFAULT_ROUTING;
 }
Definition at line 1662 of file CommonMessages_m.h.
Constructor & Destructor Documentation
LookupCall::LookupCall (const char * name = NULL, int kind = 0)
Referenced by dup().
LookupCall::LookupCall (const LookupCall & other)
virtual LookupCall::~LookupCall () [virtual]
Member Function Documentation
void LookupCall::copy (const LookupCall & other) [private]
virtual LookupCall* LookupCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 1681 of file CommonMessages_m.h.
{return new LookupCall(*this);}
virtual OverlayKey& LookupCall::getKey () [virtual]
Referenced by SendToKeyListener::lookupFinished(), and BaseOverlay::lookupRpc().
virtual const OverlayKey& LookupCall::getKey () const [inline, virtual]
Definition at line 1687 of file CommonMessages_m.h.
Referenced by getKey().
{return const_cast<LookupCall*>(this)->getKey();}
virtual int LookupCall::getNumSiblings () const [virtual]
Referenced by BaseOverlay::lookupRpc().
virtual int LookupCall::getRoutingType () const [virtual]
Referenced by BaseOverlay::lookupRpc().
LookupCall& LookupCall::operator= (const LookupCall & other)
bool LookupCall::operator== (const LookupCall &) [protected]
virtual void LookupCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void LookupCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void LookupCall::setKey (const OverlayKey & key) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), DHT::handleGetCAPIRequest(), CBRDHT::handlePutCAPIRequest(), DHT::handlePutCAPIRequest(), P2pns::handleTimerEvent(), KBRTestApp::handleTimerEvent(), BootstrapList::locateBootstrapNode(), XmlRpcInterface::lookup(), P2pns::tunnel(), and CBRDHT::update().
virtual void LookupCall::setNumSiblings (int numSiblings) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), DHT::handleGetCAPIRequest(), CBRDHT::handlePutCAPIRequest(), DHT::handlePutCAPIRequest(), P2pns::handleTimerEvent(), KBRTestApp::handleTimerEvent(), BootstrapList::locateBootstrapNode(), XmlRpcInterface::lookup(), P2pns::tunnel(), and CBRDHT::update().
virtual void LookupCall::setRoutingType (int routingType) [virtual]
Referenced by P2pns::handleTimerEvent(), and XmlRpcInterface::lookup().
Member Data Documentation
OverlayKey LookupCall::key_var [protected]
Definition at line 1665 of file CommonMessages_m.h.
int LookupCall::numSiblings_var [protected]
Definition at line 1666 of file CommonMessages_m.h.
int LookupCall::routingType_var [protected]
Definition at line 1667 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h