OverSim: ALMMulticastMessage Class Reference
ALMMulticastMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
ALMMulticastMessage (const char *name=NULL, int kind=0)
ALMMulticastMessage (const ALMMulticastMessage &other)
virtual ~ALMMulticastMessage ()
ALMMulticastMessage & operator= (const ALMMulticastMessage &other)
virtual ALMMulticastMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ALMMulticastMessage &)
Private Member Functions
void copy (const ALMMulticastMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet ALMMulticastMessage extends ALMMessage
 {
 }
Definition at line 2271 of file CommonMessages_m.h.
Constructor & Destructor Documentation
ALMMulticastMessage::ALMMulticastMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMMulticastMessage::ALMMulticastMessage (const ALMMulticastMessage & other)
virtual ALMMulticastMessage::~ALMMulticastMessage () [virtual]
Member Function Documentation
void ALMMulticastMessage::copy (const ALMMulticastMessage & other) [private]
virtual ALMMulticastMessage* ALMMulticastMessage::dup () const [inline, virtual]
Reimplemented from ALMMessage.
Definition at line 2287 of file CommonMessages_m.h.
{return new ALMMulticastMessage(*this);}
ALMMulticastMessage& ALMMulticastMessage::operator= (const ALMMulticastMessage & other)
bool ALMMulticastMessage::operator== (const ALMMulticastMessage &) [protected]
virtual void ALMMulticastMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doPacking().
virtual void ALMMulticastMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h