OverSim: BaseCallMessage Class Reference
BaseCallMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BaseCallMessage (const char *name=NULL, int kind=0)
BaseCallMessage (const BaseCallMessage &other)
virtual ~BaseCallMessage ()
BaseCallMessage & operator= (const BaseCallMessage &other)
virtual BaseCallMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const BaseCallMessage &)
Private Member Functions
void copy (const BaseCallMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet BaseCallMessage extends BaseRpcMessage
 {
 }
Definition at line 522 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BaseCallMessage::BaseCallMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BaseCallMessage::BaseCallMessage (const BaseCallMessage & other)
virtual BaseCallMessage::~BaseCallMessage () [virtual]
Member Function Documentation
void BaseCallMessage::copy (const BaseCallMessage & other) [private]
virtual BaseCallMessage* BaseCallMessage::dup () const [inline, virtual]
Reimplemented from BaseRpcMessage.
Reimplemented in P2pnsResolveCall, P2pnsRegisterCall, LookupCall, DHTdumpCall, DHTgetCAPICall, DHTputCAPICall, PubSubAdoptChildCall, NextHopCall, PingCall, PubSubPingCall, FailedNodeCall, HGetChildrenCall, PubSubBackupCall, HSwitchToRescueModeCall, CapReqCall, AreaDataCall, FindNodeCall, PubSubIntermediateCall, HScheduleSegmentsCall, SimpleCoordStrategyCall, RegionsStrategyCall, HResponsibilityAsParentCall, RequestRoutingRowCall, DeBruijnCall, TreeTestStrategyCall, PubSubHelpCall, HNewParentSelectedCall, RequestLeafSetCall, RemoveRandomStrategyCall, HLeaveOverlayCall, SendAllStrategyCall, RequestRepairCall, HVideoSegmentCall, SendCoordinatesCall, FixfingersCall, PubSubSubscriptionCall, RequestStateCall, ChildCheckCall, StabilizeCall, PubSubTakeOverSubspaceCall, HJoinCall, PastryJoinCall, NTreeNodePingCall, ChildReleaseCall, JoinCall, HSelectParentCall, PubSubResponsibleNodeCall, NTreePingCall, GlobalViewBuilderCall, HGetParametersCall, PubSubJoinCall, NotifyCall, UnderlayTestCall, ScribePublishCall, NTreeDivideCall, TreeAppCall, DHTGetCall, BucketCall, HCapacityCall, KbrTestCall, RttToNodeCall, ScribeJoinCall, ParentRequestCall, DHTPutCall, ProxFindNodeCall, NTreeJoinCall, DiscoveryCall, CoordsOfNodeCall, CoordsReqCall, MyNeighborCall, and CBRDHTGetCall.
Definition at line 538 of file CommonMessages_m.h.
Referenced by TreeManagement::handleRpcTimeout(), BaseRpc::internalHandleRpcMessage(), PubSubMMOG::sendMessageToChildren(), TreeManagement::sendMessageToChildren(), and BaseRpc::sendRpcCall().
{return new BaseCallMessage(*this);}
BaseCallMessage& BaseCallMessage::operator= (const BaseCallMessage & other)
bool BaseCallMessage::operator== (const BaseCallMessage &) [protected]
virtual void BaseCallMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseRpcMessage.
Reimplemented in P2pnsResolveCall, P2pnsRegisterCall, LookupCall, DHTdumpCall, DHTgetCAPICall, DHTputCAPICall, PubSubAdoptChildCall, NextHopCall, PingCall, PubSubPingCall, FailedNodeCall, HGetChildrenCall, PubSubBackupCall, HSwitchToRescueModeCall, CapReqCall, AreaDataCall, FindNodeCall, PubSubIntermediateCall, HScheduleSegmentsCall, SimpleCoordStrategyCall, RegionsStrategyCall, HResponsibilityAsParentCall, RequestRoutingRowCall, DeBruijnCall, TreeTestStrategyCall, PubSubHelpCall, HNewParentSelectedCall, RequestLeafSetCall, RemoveRandomStrategyCall, HLeaveOverlayCall, SendAllStrategyCall, RequestRepairCall, HVideoSegmentCall, SendCoordinatesCall, FixfingersCall, PubSubSubscriptionCall, RequestStateCall, ChildCheckCall, StabilizeCall, PubSubTakeOverSubspaceCall, HJoinCall, PastryJoinCall, NTreeNodePingCall, ChildReleaseCall, JoinCall, HSelectParentCall, PubSubResponsibleNodeCall, NTreePingCall, GlobalViewBuilderCall, HGetParametersCall, PubSubJoinCall, NotifyCall, UnderlayTestCall, ScribePublishCall, NTreeDivideCall, TreeAppCall, DHTGetCall, BucketCall, HCapacityCall, KbrTestCall, RttToNodeCall, ScribeJoinCall, ParentRequestCall, DHTPutCall, ProxFindNodeCall, NTreeJoinCall, DiscoveryCall, CoordsOfNodeCall, CoordsReqCall, MyNeighborCall, and CBRDHTGetCall.
Referenced by doPacking().
virtual void BaseCallMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseRpcMessage.
Reimplemented in P2pnsResolveCall, P2pnsRegisterCall, LookupCall, DHTdumpCall, DHTgetCAPICall, DHTputCAPICall, PubSubAdoptChildCall, NextHopCall, PingCall, PubSubPingCall, FailedNodeCall, HGetChildrenCall, PubSubBackupCall, HSwitchToRescueModeCall, CapReqCall, AreaDataCall, FindNodeCall, PubSubIntermediateCall, HScheduleSegmentsCall, SimpleCoordStrategyCall, RegionsStrategyCall, HResponsibilityAsParentCall, RequestRoutingRowCall, DeBruijnCall, TreeTestStrategyCall, PubSubHelpCall, HNewParentSelectedCall, RequestLeafSetCall, RemoveRandomStrategyCall, HLeaveOverlayCall, SendAllStrategyCall, RequestRepairCall, HVideoSegmentCall, SendCoordinatesCall, FixfingersCall, PubSubSubscriptionCall, RequestStateCall, ChildCheckCall, StabilizeCall, PubSubTakeOverSubspaceCall, HJoinCall, PastryJoinCall, NTreeNodePingCall, ChildReleaseCall, JoinCall, HSelectParentCall, PubSubResponsibleNodeCall, NTreePingCall, GlobalViewBuilderCall, HGetParametersCall, PubSubJoinCall, NotifyCall, UnderlayTestCall, ScribePublishCall, NTreeDivideCall, TreeAppCall, DHTGetCall, BucketCall, HCapacityCall, KbrTestCall, RttToNodeCall, ScribeJoinCall, ParentRequestCall, DHTPutCall, ProxFindNodeCall, NTreeJoinCall, DiscoveryCall, CoordsOfNodeCall, CoordsReqCall, MyNeighborCall, and CBRDHTGetCall.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h