OverSim: BucketCall Class Reference
BucketCall Class Reference
Class generated from overlay/broose/BrooseMessage.msg by opp_msgc.
#include <BrooseMessage_m.h>
Public Member Functions
BucketCall (const char *name=NULL, int kind=0)
BucketCall (const BucketCall &other)
virtual ~BucketCall ()
BucketCall & operator= (const BucketCall &other)
virtual BucketCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getBucketType () const
virtual void setBucketType (int bucketType)
virtual int getBucketIndex () const
virtual void setBucketIndex (int bucketIndex)
virtual int getProState () const
virtual void setProState (int proState)
Protected Member Functions
bool operator== (const BucketCall &)
Protected Attributes
int bucketType_var
int bucketIndex_var
int proState_var
Private Member Functions
void copy (const BucketCall &other)
Detailed Description
Class generated from overlay/broose/BrooseMessage.msg by opp_msgc.
 packet BucketCall extends BaseCallMessage
 {
         int bucketType enum(BucketType);
         int bucketIndex;
         int proState enum(ProState);
 }
Definition at line 87 of file BrooseMessage_m.h.
Constructor & Destructor Documentation
BucketCall::BucketCall (const char * name = NULL, int kind = 0)
Referenced by dup().
BucketCall::BucketCall (const BucketCall & other)
virtual BucketCall::~BucketCall () [virtual]
Member Function Documentation
void BucketCall::copy (const BucketCall & other) [private]
virtual BucketCall* BucketCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 106 of file BrooseMessage_m.h.
{return new BucketCall(*this);}
virtual int BucketCall::getBucketIndex () const [virtual]
virtual int BucketCall::getBucketType () const [virtual]
Referenced by Broose::handleBucketRequestRpc(), and Broose::handleBucketResponseRpc().
virtual int BucketCall::getProState () const [virtual]
Referenced by Broose::handleBucketRequestRpc(), and Broose::handleBucketResponseRpc().
BucketCall& BucketCall::operator= (const BucketCall & other)
bool BucketCall::operator== (const BucketCall &) [protected]
virtual void BucketCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void BucketCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void BucketCall::setBucketIndex (int bucketIndex) [virtual]
Referenced by Broose::handleJoinTimerExpired().
virtual void BucketCall::setBucketType (int bucketType) [virtual]
Referenced by Broose::changeState(), and Broose::handleJoinTimerExpired().
virtual void BucketCall::setProState (int proState) [virtual]
Referenced by Broose::changeState(), and Broose::handleJoinTimerExpired().
Member Data Documentation
int BucketCall::bucketIndex_var [protected]
Definition at line 91 of file BrooseMessage_m.h.
int BucketCall::bucketType_var [protected]
Definition at line 90 of file BrooseMessage_m.h.
int BucketCall::proState_var [protected]
Definition at line 92 of file BrooseMessage_m.h.
The documentation for this class was generated from the following file:
BrooseMessage_m.h