OverSim: RemoveRandomStrategyCall Class Reference
RemoveRandomStrategyCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
RemoveRandomStrategyCall (const char *name=NULL, int kind=0)
RemoveRandomStrategyCall (const RemoveRandomStrategyCall &other)
virtual ~RemoveRandomStrategyCall ()
RemoveRandomStrategyCall & operator= (const RemoveRandomStrategyCall &other)
virtual RemoveRandomStrategyCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual CoordDataContainer & getCoordData ()
virtual const CoordDataContainer & getCoordData () const
virtual void setCoordData (const CoordDataContainer &coordData)
Protected Member Functions
bool operator== (const RemoveRandomStrategyCall &)
Protected Attributes
CoordDataContainer coordData_var
Private Member Functions
void copy (const RemoveRandomStrategyCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet RemoveRandomStrategyCall extends GlobalViewBuilderCall
 {
     CoordDataContainer coordData;
 }
Definition at line 493 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
RemoveRandomStrategyCall::RemoveRandomStrategyCall (const char * name = NULL, int kind = 0)
Referenced by dup().
RemoveRandomStrategyCall::RemoveRandomStrategyCall (const RemoveRandomStrategyCall & other)
virtual RemoveRandomStrategyCall::~RemoveRandomStrategyCall () [virtual]
Member Function Documentation
void RemoveRandomStrategyCall::copy (const RemoveRandomStrategyCall & other) [private]
virtual RemoveRandomStrategyCall* RemoveRandomStrategyCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 510 of file TreeManagementMessage_m.h.
{return new RemoveRandomStrategyCall(*this);}
virtual CoordDataContainer& RemoveRandomStrategyCall::getCoordData () [virtual]
virtual const CoordDataContainer& RemoveRandomStrategyCall::getCoordData () const [inline, virtual]
Definition at line 516 of file TreeManagementMessage_m.h.
Referenced by getCoordData().
{return const_cast<RemoveRandomStrategyCall*>(this)->getCoordData();}
RemoveRandomStrategyCall& RemoveRandomStrategyCall::operator= (const RemoveRandomStrategyCall & other)
bool RemoveRandomStrategyCall::operator== (const RemoveRandomStrategyCall &) [protected]
virtual void RemoveRandomStrategyCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void RemoveRandomStrategyCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void RemoveRandomStrategyCall::setCoordData (const CoordDataContainer & coordData) [virtual]
Member Data Documentation
CoordDataContainer RemoveRandomStrategyCall::coordData_var [protected]
Definition at line 496 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h