OverSim: ALMLeaveMessage Class Reference
ALMLeaveMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
ALMLeaveMessage (const char *name=NULL, int kind=0)
ALMLeaveMessage (const ALMLeaveMessage &other)
virtual ~ALMLeaveMessage ()
ALMLeaveMessage & operator= (const ALMLeaveMessage &other)
virtual ALMLeaveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ALMLeaveMessage &)
Private Member Functions
void copy (const ALMLeaveMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet ALMLeaveMessage extends ALMMessage
 {
 }
Definition at line 2237 of file CommonMessages_m.h.
Constructor & Destructor Documentation
ALMLeaveMessage::ALMLeaveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMLeaveMessage::ALMLeaveMessage (const ALMLeaveMessage & other)
virtual ALMLeaveMessage::~ALMLeaveMessage () [virtual]
Member Function Documentation
void ALMLeaveMessage::copy (const ALMLeaveMessage & other) [private]
virtual ALMLeaveMessage* ALMLeaveMessage::dup () const [inline, virtual]
Reimplemented from ALMMessage.
Definition at line 2253 of file CommonMessages_m.h.
{return new ALMLeaveMessage(*this);}
ALMLeaveMessage& ALMLeaveMessage::operator= (const ALMLeaveMessage & other)
bool ALMLeaveMessage::operator== (const ALMLeaveMessage &) [protected]
virtual void ALMLeaveMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doPacking().
virtual void ALMLeaveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h