OverSim: I3RemoveTriggerMessage_Base Class Reference
I3RemoveTriggerMessage_Base Class Reference
Class generated from applications/i3/I3Message.msg by opp_msgc.
#include <I3Message_m.h>
Public Member Functions
virtual ~I3RemoveTriggerMessage_Base ()
virtual
I3RemoveTriggerMessage_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual I3Trigger & getTrigger ()
virtual const I3Trigger & getTrigger () const
virtual void setTrigger (const I3Trigger &trigger)
Protected Member Functions
bool operator== (const I3RemoveTriggerMessage_Base &)
I3RemoveTriggerMessage_Base (const char *name=NULL, int kind=0)
I3RemoveTriggerMessage_Base (const I3RemoveTriggerMessage_Base &other)
I3RemoveTriggerMessage_Base & operator= (const I3RemoveTriggerMessage_Base &other)
Protected Attributes
I3Trigger trigger_var
Private Member Functions
void copy (const I3RemoveTriggerMessage_Base &other)
Detailed Description
Class generated from applications/i3/I3Message.msg by opp_msgc.
 packet I3RemoveTriggerMessage extends I3Message
 {
     (true);
         I3Trigger trigger;
 }
I3RemoveTriggerMessage_Base is only useful if it gets subclassed, and I3RemoveTriggerMessage is derived from it. The minimum code to be written for I3RemoveTriggerMessage is the following:
 class I3RemoveTriggerMessage : public I3RemoveTriggerMessage_Base
 {
   private:
     void copy(const I3RemoveTriggerMessage& other) { ... }
   public:
     I3RemoveTriggerMessage(const char *name=NULL, int kind=0) : I3RemoveTriggerMessage_Base(name,kind) {}
     I3RemoveTriggerMessage(const I3RemoveTriggerMessage& other) : I3RemoveTriggerMessage_Base(other) {copy(other);}
     I3RemoveTriggerMessage& operator=(const I3RemoveTriggerMessage& other) {if (this==&other) return *this; I3RemoveTriggerMessage_Base::operator=(other); copy(other); return *this;}
     virtual I3RemoveTriggerMessage *dup() const {return new I3RemoveTriggerMessage(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from I3RemoveTriggerMessage_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(I3RemoveTriggerMessage);
Definition at line 269 of file I3Message_m.h.
Constructor & Destructor Documentation
I3RemoveTriggerMessage_Base::I3RemoveTriggerMessage_Base (const char * name = NULL, int kind = 0) [protected]
I3RemoveTriggerMessage_Base::I3RemoveTriggerMessage_Base (const I3RemoveTriggerMessage_Base & other) [protected]
virtual I3RemoveTriggerMessage_Base::~I3RemoveTriggerMessage_Base () [virtual]
Member Function Documentation
void I3RemoveTriggerMessage_Base::copy (const I3RemoveTriggerMessage_Base & other) [private]
virtual I3RemoveTriggerMessage_Base* I3RemoveTriggerMessage_Base::dup () const [inline, virtual]
Reimplemented from I3Message.
Reimplemented in I3RemoveTriggerMessage.
Definition at line 288 of file I3Message_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class I3RemoveTriggerMessage");}
virtual I3Trigger& I3RemoveTriggerMessage_Base::getTrigger () [virtual]
Referenced by I3::deliver(), and I3::handleUDPMessage().
virtual const I3Trigger& I3RemoveTriggerMessage_Base::getTrigger () const [inline, virtual]
Definition at line 294 of file I3Message_m.h.
Referenced by getTrigger().
{return const_cast<I3RemoveTriggerMessage_Base*>(this)->getTrigger();}
I3RemoveTriggerMessage_Base& I3RemoveTriggerMessage_Base::operator= (const I3RemoveTriggerMessage_Base & other) [protected]
bool I3RemoveTriggerMessage_Base::operator== (const I3RemoveTriggerMessage_Base &) [protected]
virtual void I3RemoveTriggerMessage_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3RemoveTriggerMessage_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3RemoveTriggerMessage_Base::setTrigger (const I3Trigger & trigger) [virtual]
Referenced by I3BaseApp::removeTrigger().
Member Data Documentation
I3Trigger I3RemoveTriggerMessage_Base::trigger_var [protected]
Definition at line 272 of file I3Message_m.h.
The documentation for this class was generated from the following file:
I3Message_m.h