OverSim: TriggersHandshakeMsg Class Reference
TriggersHandshakeMsg Class Reference
Class generated from applications/i3/i3Apps/I3TriggersMessage.msg by opp_msgc.
#include <I3TriggersMessage_m.h>
Public Member Functions
TriggersHandshakeMsg (const char *name=NULL, int kind=0)
TriggersHandshakeMsg (const TriggersHandshakeMsg &other)
virtual ~TriggersHandshakeMsg ()
TriggersHandshakeMsg & operator= (const TriggersHandshakeMsg &other)
virtual TriggersHandshakeMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getValue () const
virtual void setValue (int value)
virtual I3Identifier & getTriggerId ()
virtual const I3Identifier & getTriggerId () const
virtual void setTriggerId (const I3Identifier &triggerId)
Protected Member Functions
bool operator== (const TriggersHandshakeMsg &)
Protected Attributes
int value_var
I3Identifier triggerId_var
Private Member Functions
void copy (const TriggersHandshakeMsg &other)
Detailed Description
Class generated from applications/i3/i3Apps/I3TriggersMessage.msg by opp_msgc.
 packet TriggersHandshakeMsg
 {
         int value;
         I3Identifier triggerId;
 }
Definition at line 32 of file I3TriggersMessage_m.h.
Constructor & Destructor Documentation
TriggersHandshakeMsg::TriggersHandshakeMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
TriggersHandshakeMsg::TriggersHandshakeMsg (const TriggersHandshakeMsg & other)
virtual TriggersHandshakeMsg::~TriggersHandshakeMsg () [virtual]
Member Function Documentation
void TriggersHandshakeMsg::copy (const TriggersHandshakeMsg & other) [private]
virtual TriggersHandshakeMsg* TriggersHandshakeMsg::dup () const [inline, virtual]
Definition at line 50 of file I3TriggersMessage_m.h.
{return new TriggersHandshakeMsg(*this);}
virtual I3Identifier& TriggersHandshakeMsg::getTriggerId () [virtual]
Referenced by I3Triggers::deliver().
virtual const I3Identifier& TriggersHandshakeMsg::getTriggerId () const [inline, virtual]
Definition at line 58 of file I3TriggersMessage_m.h.
Referenced by getTriggerId().
{return const_cast<TriggersHandshakeMsg*>(this)->getTriggerId();}
virtual int TriggersHandshakeMsg::getValue () const [virtual]
Referenced by I3Triggers::deliver().
TriggersHandshakeMsg& TriggersHandshakeMsg::operator= (const TriggersHandshakeMsg & other)
bool TriggersHandshakeMsg::operator== (const TriggersHandshakeMsg &) [protected]
virtual void TriggersHandshakeMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TriggersHandshakeMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void TriggersHandshakeMsg::setTriggerId (const I3Identifier & triggerId) [virtual]
Referenced by I3Triggers::deliver(), and I3Triggers::handleTimerEvent().
virtual void TriggersHandshakeMsg::setValue (int value) [virtual]
Referenced by I3Triggers::deliver(), and I3Triggers::handleTimerEvent().
Member Data Documentation
I3Identifier TriggersHandshakeMsg::triggerId_var [protected]
Definition at line 36 of file I3TriggersMessage_m.h.
int TriggersHandshakeMsg::value_var [protected]
Definition at line 35 of file I3TriggersMessage_m.h.
The documentation for this class was generated from the following file:
I3TriggersMessage_m.h