OverSim: PubSubBackupUnsubscribeMessage Class Reference
PubSubBackupUnsubscribeMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubBackupUnsubscribeMessage (const char *name=NULL, int kind=0)
PubSubBackupUnsubscribeMessage (const PubSubBackupUnsubscribeMessage &other)
virtual ~PubSubBackupUnsubscribeMessage ()
PubSubBackupUnsubscribeMessage & operator= (const PubSubBackupUnsubscribeMessage &other)
virtual
PubSubBackupUnsubscribeMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getChild ()
virtual const NodeHandle & getChild () const
virtual void setChild (const NodeHandle &child)
virtual NodeHandle & getIntermediate ()
virtual const NodeHandle & getIntermediate () const
virtual void setIntermediate (const NodeHandle &intermediate)
Protected Member Functions
bool operator== (const PubSubBackupUnsubscribeMessage &)
Protected Attributes
int subspaceId_var
NodeHandle child_var
NodeHandle intermediate_var
Private Member Functions
void copy (const PubSubBackupUnsubscribeMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubBackupUnsubscribeMessage extends BaseOverlayMessage
 {
         int subspaceId;
         NodeHandle child;
         NodeHandle intermediate;
 }
Definition at line 1267 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubBackupUnsubscribeMessage::PubSubBackupUnsubscribeMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubBackupUnsubscribeMessage::PubSubBackupUnsubscribeMessage (const PubSubBackupUnsubscribeMessage & other)
virtual PubSubBackupUnsubscribeMessage::~PubSubBackupUnsubscribeMessage () [virtual]
Member Function Documentation
void PubSubBackupUnsubscribeMessage::copy (const PubSubBackupUnsubscribeMessage & other) [private]
virtual PubSubBackupUnsubscribeMessage* PubSubBackupUnsubscribeMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 1286 of file PubSubMessage_m.h.
{return new PubSubBackupUnsubscribeMessage(*this);}
virtual NodeHandle& PubSubBackupUnsubscribeMessage::getChild () [virtual]
Referenced by PubSubMMOG::handleUnsubscribeBackup().
virtual const NodeHandle& PubSubBackupUnsubscribeMessage::getChild () const [inline, virtual]
Definition at line 1294 of file PubSubMessage_m.h.
Referenced by getChild().
{return const_cast<PubSubBackupUnsubscribeMessage*>(this)->getChild();}
virtual NodeHandle& PubSubBackupUnsubscribeMessage::getIntermediate () [virtual]
Referenced by PubSubMMOG::handleUnsubscribeBackup().
virtual const NodeHandle& PubSubBackupUnsubscribeMessage::getIntermediate () const [inline, virtual]
Definition at line 1297 of file PubSubMessage_m.h.
Referenced by getIntermediate().
{return const_cast<PubSubBackupUnsubscribeMessage*>(this)->getIntermediate();}
virtual int PubSubBackupUnsubscribeMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleUnsubscribeBackup().
PubSubBackupUnsubscribeMessage& PubSubBackupUnsubscribeMessage::operator= (const PubSubBackupUnsubscribeMessage & other)
bool PubSubBackupUnsubscribeMessage::operator== (const PubSubBackupUnsubscribeMessage &) [protected]
virtual void PubSubBackupUnsubscribeMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubBackupUnsubscribeMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubBackupUnsubscribeMessage::setChild (const NodeHandle & child) [virtual]
Referenced by PubSubMMOG::unsubscribeChild().
virtual void PubSubBackupUnsubscribeMessage::setIntermediate (const NodeHandle & intermediate) [virtual]
Referenced by PubSubMMOG::unsubscribeChild().
virtual void PubSubBackupUnsubscribeMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::unsubscribeChild().
Member Data Documentation
NodeHandle PubSubBackupUnsubscribeMessage::child_var [protected]
Definition at line 1271 of file PubSubMessage_m.h.
NodeHandle PubSubBackupUnsubscribeMessage::intermediate_var [protected]
Definition at line 1272 of file PubSubMessage_m.h.
int PubSubBackupUnsubscribeMessage::subspaceId_var [protected]
Definition at line 1270 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h