OverSim: QuonSelfMessage Class Reference
QuonSelfMessage Class Reference
Class generated from overlay/quon/Quon.msg by opp_msgc.
#include <Quon_m.h>
Public Member Functions
QuonSelfMessage (const char *name=NULL, int kind=0)
QuonSelfMessage (const QuonSelfMessage &other)
virtual ~QuonSelfMessage ()
QuonSelfMessage & operator= (const QuonSelfMessage &other)
virtual QuonSelfMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
Protected Member Functions
bool operator== (const QuonSelfMessage &)
Protected Attributes
OverlayKey key_var
Private Member Functions
void copy (const QuonSelfMessage &other)
Detailed Description
Class generated from overlay/quon/Quon.msg by opp_msgc.
 message QuonSelfMessage
 {
     OverlayKey key;
 }
Definition at line 69 of file Quon_m.h.
Constructor & Destructor Documentation
QuonSelfMessage::QuonSelfMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
QuonSelfMessage::QuonSelfMessage (const QuonSelfMessage & other)
virtual QuonSelfMessage::~QuonSelfMessage () [virtual]
Member Function Documentation
void QuonSelfMessage::copy (const QuonSelfMessage & other) [private]
virtual QuonSelfMessage* QuonSelfMessage::dup () const [inline, virtual]
Definition at line 86 of file Quon_m.h.
{return new QuonSelfMessage(*this);}
virtual OverlayKey& QuonSelfMessage::getKey () [virtual]
Referenced by Quon::processDeleteTimer().
virtual const OverlayKey& QuonSelfMessage::getKey () const [inline, virtual]
Definition at line 92 of file Quon_m.h.
Referenced by getKey().
{return const_cast<QuonSelfMessage*>(this)->getKey();}
QuonSelfMessage& QuonSelfMessage::operator= (const QuonSelfMessage & other)
bool QuonSelfMessage::operator== (const QuonSelfMessage &) [protected]
virtual void QuonSelfMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void QuonSelfMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void QuonSelfMessage::setKey (const OverlayKey & key) [virtual]
Referenced by Quon::processAliveTimer().
Member Data Documentation
OverlayKey QuonSelfMessage::key_var [protected]
Definition at line 72 of file Quon_m.h.
The documentation for this class was generated from the following file:
Quon_m.h