OverSim: ChurnMessage Class Reference
ChurnMessage Class Reference
Class generated from common/Churn.msg by opp_msgc.
#include <Churn_m.h>
Public Member Functions
ChurnMessage (const char *name=NULL, int kind=0)
ChurnMessage (const ChurnMessage &other)
virtual ~ChurnMessage ()
ChurnMessage & operator= (const ChurnMessage &other)
virtual ChurnMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getCreateNode () const
virtual void setCreateNode (bool createNode)
virtual double getLifetime () const
virtual void setLifetime (double lifetime)
virtual int getContextPos () const
virtual void setContextPos (int contextPos)
virtual TransportAddress & getAddr ()
virtual const TransportAddress & getAddr () const
virtual void setAddr (const TransportAddress &addr)
Protected Member Functions
bool operator== (const ChurnMessage &)
Protected Attributes
bool createNode_var
double lifetime_var
int contextPos_var
TransportAddress addr_var
Private Member Functions
void copy (const ChurnMessage &other)
Detailed Description
Class generated from common/Churn.msg by opp_msgc.
 packet ChurnMessage
 {
     bool createNode;
     double lifetime;
     int contextPos;
     TransportAddress addr;
 }
Definition at line 34 of file Churn_m.h.
Constructor & Destructor Documentation
ChurnMessage::ChurnMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ChurnMessage::ChurnMessage (const ChurnMessage & other)
virtual ChurnMessage::~ChurnMessage () [virtual]
Member Function Documentation
void ChurnMessage::copy (const ChurnMessage & other) [private]
virtual ChurnMessage* ChurnMessage::dup () const [inline, virtual]
Reimplemented in ParetoChurnMessage.
Definition at line 54 of file Churn_m.h.
{return new ChurnMessage(*this);}
virtual TransportAddress& ChurnMessage::getAddr () [virtual]
Referenced by LifetimeChurn::handleMessage(), and ParetoChurn::handleMessage().
virtual const TransportAddress& ChurnMessage::getAddr () const [inline, virtual]
Definition at line 66 of file Churn_m.h.
Referenced by getAddr().
{return const_cast<ChurnMessage*>(this)->getAddr();}
virtual int ChurnMessage::getContextPos () const [virtual]
Referenced by LifetimeChurn::handleMessage().
virtual bool ChurnMessage::getCreateNode () const [virtual]
Referenced by LifetimeChurn::handleMessage(), and ParetoChurn::handleMessage().
virtual double ChurnMessage::getLifetime () const [virtual]
Referenced by LifetimeChurn::handleMessage(), and ParetoChurn::handleMessage().
ChurnMessage& ChurnMessage::operator= (const ChurnMessage & other)
bool ChurnMessage::operator== (const ChurnMessage &) [protected]
virtual void ChurnMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in ParetoChurnMessage.
Referenced by doPacking().
virtual void ChurnMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in ParetoChurnMessage.
Referenced by doUnpacking().
virtual void ChurnMessage::setAddr (const TransportAddress & addr) [virtual]
Referenced by LifetimeChurn::createNode(), and ParetoChurn::createNode().
virtual void ChurnMessage::setContextPos (int contextPos) [virtual]
Referenced by LifetimeChurn::createNode(), and LifetimeChurn::scheduleCreateNodeAt().
virtual void ChurnMessage::setCreateNode (bool createNode) [virtual]
Referenced by LifetimeChurn::createNode(), ParetoChurn::createNode(), LifetimeChurn::scheduleCreateNodeAt(), and ParetoChurn::scheduleCreateNodeAt().
virtual void ChurnMessage::setLifetime (double lifetime) [virtual]
Referenced by LifetimeChurn::scheduleCreateNodeAt(), and ParetoChurn::scheduleCreateNodeAt().
Member Data Documentation
TransportAddress ChurnMessage::addr_var [protected]
Definition at line 40 of file Churn_m.h.
int ChurnMessage::contextPos_var [protected]
Definition at line 39 of file Churn_m.h.
bool ChurnMessage::createNode_var [protected]
Definition at line 37 of file Churn_m.h.
double ChurnMessage::lifetime_var [protected]
Definition at line 38 of file Churn_m.h.
The documentation for this class was generated from the following file:
Churn_m.h