OverSim: P2pnsRegisterResponse Class Reference
P2pnsRegisterResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
P2pnsRegisterResponse (const char *name=NULL, int kind=0)
P2pnsRegisterResponse (const P2pnsRegisterResponse &other)
virtual ~P2pnsRegisterResponse ()
P2pnsRegisterResponse & operator= (const P2pnsRegisterResponse &other)
virtual P2pnsRegisterResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual BinaryValue & getP2pName ()
virtual const BinaryValue & getP2pName () const
virtual void setP2pName (const BinaryValue &p2pName)
virtual BinaryValue & getAddress ()
virtual const BinaryValue & getAddress () const
virtual void setAddress (const BinaryValue &address)
virtual bool getIsSuccess () const
virtual void setIsSuccess (bool isSuccess)
Protected Member Functions
bool operator== (const P2pnsRegisterResponse &)
Protected Attributes
BinaryValue p2pName_var
BinaryValue address_var
bool isSuccess_var
Private Member Functions
void copy (const P2pnsRegisterResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet P2pnsRegisterResponse extends BaseResponseMessage
 {
     BinaryValue p2pName;
     BinaryValue address;
     bool isSuccess;
 }
Definition at line 1820 of file CommonMessages_m.h.
Constructor & Destructor Documentation
P2pnsRegisterResponse::P2pnsRegisterResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
P2pnsRegisterResponse::P2pnsRegisterResponse (const P2pnsRegisterResponse & other)
virtual P2pnsRegisterResponse::~P2pnsRegisterResponse () [virtual]
Member Function Documentation
void P2pnsRegisterResponse::copy (const P2pnsRegisterResponse & other) [private]
virtual P2pnsRegisterResponse* P2pnsRegisterResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 1839 of file CommonMessages_m.h.
{return new P2pnsRegisterResponse(*this);}
virtual BinaryValue& P2pnsRegisterResponse::getAddress () [virtual]
virtual const BinaryValue& P2pnsRegisterResponse::getAddress () const [inline, virtual]
Definition at line 1848 of file CommonMessages_m.h.
Referenced by getAddress().
{return const_cast<P2pnsRegisterResponse*>(this)->getAddress();}
virtual bool P2pnsRegisterResponse::getIsSuccess () const [virtual]
virtual BinaryValue& P2pnsRegisterResponse::getP2pName () [virtual]
virtual const BinaryValue& P2pnsRegisterResponse::getP2pName () const [inline, virtual]
Definition at line 1845 of file CommonMessages_m.h.
Referenced by getP2pName().
{return const_cast<P2pnsRegisterResponse*>(this)->getP2pName();}
P2pnsRegisterResponse& P2pnsRegisterResponse::operator= (const P2pnsRegisterResponse & other)
bool P2pnsRegisterResponse::operator== (const P2pnsRegisterResponse &) [protected]
virtual void P2pnsRegisterResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void P2pnsRegisterResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void P2pnsRegisterResponse::setAddress (const BinaryValue & address) [virtual]
Referenced by P2pns::handleDHTputCAPIResponse().
virtual void P2pnsRegisterResponse::setIsSuccess (bool isSuccess) [virtual]
Referenced by P2pns::handleDHTputCAPIResponse().
virtual void P2pnsRegisterResponse::setP2pName (const BinaryValue & p2pName) [virtual]
Referenced by P2pns::handleDHTputCAPIResponse().
Member Data Documentation
BinaryValue P2pnsRegisterResponse::address_var [protected]
Definition at line 1824 of file CommonMessages_m.h.
bool P2pnsRegisterResponse::isSuccess_var [protected]
Definition at line 1825 of file CommonMessages_m.h.
BinaryValue P2pnsRegisterResponse::p2pName_var [protected]
Definition at line 1823 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h