OverSim: CoordsReqCall Class Reference
CoordsReqCall Class Reference
Class generated from common/Nps.msg by opp_msgc.
#include <Nps_m.h>
Public Member Functions
CoordsReqCall (const char *name=NULL, int kind=0)
CoordsReqCall (const CoordsReqCall &other)
virtual ~CoordsReqCall ()
CoordsReqCall & operator= (const CoordsReqCall &other)
virtual CoordsReqCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const CoordsReqCall &)
Private Member Functions
void copy (const CoordsReqCall &other)
Detailed Description
Class generated from common/Nps.msg by opp_msgc.
 packet CoordsReqCall extends BaseCallMessage
 {
 }
Definition at line 36 of file Nps_m.h.
Constructor & Destructor Documentation
CoordsReqCall::CoordsReqCall (const char * name = NULL, int kind = 0)
Referenced by dup().
CoordsReqCall::CoordsReqCall (const CoordsReqCall & other)
virtual CoordsReqCall::~CoordsReqCall () [virtual]
Member Function Documentation
void CoordsReqCall::copy (const CoordsReqCall & other) [private]
virtual CoordsReqCall* CoordsReqCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 52 of file Nps_m.h.
{return new CoordsReqCall(*this);}
CoordsReqCall& CoordsReqCall::operator= (const CoordsReqCall & other)
bool CoordsReqCall::operator== (const CoordsReqCall &) [protected]
virtual void CoordsReqCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void CoordsReqCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Nps_m.h