OverSim: KBRroute Class Reference
KBRroute Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
KBRroute (const char *name=NULL, int kind=0)
KBRroute (const KBRroute &other)
virtual ~KBRroute ()
KBRroute & operator= (const KBRroute &other)
virtual KBRroute * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual int getDestComp () const
virtual void setDestComp (int destComp)
virtual int getSrcComp () const
virtual void setSrcComp (int srcComp)
virtual void setSourceRouteArraySize (unsigned int size)
virtual unsigned int getSourceRouteArraySize () const
virtual TransportAddress & getSourceRoute (unsigned int k)
virtual const TransportAddress & getSourceRoute (unsigned int k) const
virtual void setSourceRoute (unsigned int k, const TransportAddress &sourceRoute)
virtual int getRoutingType () const
virtual void setRoutingType (int routingType)
Protected Member Functions
bool operator== (const KBRroute &)
Protected Attributes
OverlayKey destKey_var
int destComp_var
int srcComp_var
TransportAddress * sourceRoute_var
unsigned int sourceRoute_arraysize
int routingType_var
Private Member Functions
void copy (const KBRroute &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet KBRroute extends CommonAPIMessage
 {
     OverlayKey destKey;
     int destComp enum(CompType);
     int srcComp enum(CompType);
     TransportAddress sourceRoute[];
     int routingType enum(RoutingType);
 }
Definition at line 1143 of file CommonMessages_m.h.
Constructor & Destructor Documentation
KBRroute::KBRroute (const char * name = NULL, int kind = 0)
Referenced by dup().
KBRroute::KBRroute (const KBRroute & other)
virtual KBRroute::~KBRroute () [virtual]
Member Function Documentation
void KBRroute::copy (const KBRroute & other) [private]
virtual KBRroute* KBRroute::dup () const [inline, virtual]
Reimplemented from CommonAPIMessage.
Definition at line 1165 of file CommonMessages_m.h.
{return new KBRroute(*this);}
virtual int KBRroute::getDestComp () const [virtual]
Referenced by BaseOverlay::handleMessage().
virtual OverlayKey& KBRroute::getDestKey () [virtual]
Referenced by BaseOverlay::handleMessage().
virtual const OverlayKey& KBRroute::getDestKey () const [inline, virtual]
Definition at line 1171 of file CommonMessages_m.h.
Referenced by getDestKey().
{return const_cast<KBRroute*>(this)->getDestKey();}
virtual int KBRroute::getRoutingType () const [virtual]
virtual TransportAddress& KBRroute::getSourceRoute (unsigned int k) [virtual]
Referenced by BaseOverlay::handleMessage().
virtual const TransportAddress& KBRroute::getSourceRoute (unsigned int k) const [inline, virtual]
Definition at line 1180 of file CommonMessages_m.h.
Referenced by getSourceRoute().
{return const_cast<KBRroute*>(this)->getSourceRoute(k);}
virtual unsigned int KBRroute::getSourceRouteArraySize () const [virtual]
Referenced by BaseOverlay::handleMessage().
virtual int KBRroute::getSrcComp () const [virtual]
Referenced by BaseOverlay::handleMessage().
KBRroute& KBRroute::operator= (const KBRroute & other)
bool KBRroute::operator== (const KBRroute &) [protected]
virtual void KBRroute::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from CommonAPIMessage.
Referenced by doPacking().
virtual void KBRroute::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from CommonAPIMessage.
Referenced by doUnpacking().
virtual void KBRroute::setDestComp (int destComp) [virtual]
Referenced by BaseApp::callRoute().
virtual void KBRroute::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by BaseApp::callRoute().
virtual void KBRroute::setRoutingType (int routingType) [virtual]
Referenced by BaseApp::callRoute().
virtual void KBRroute::setSourceRoute (unsigned int k, const TransportAddress & sourceRoute) [virtual]
Referenced by BaseApp::callRoute().
virtual void KBRroute::setSourceRouteArraySize (unsigned int size) [virtual]
Referenced by BaseApp::callRoute().
virtual void KBRroute::setSrcComp (int srcComp) [virtual]
Referenced by BaseApp::callRoute().
Member Data Documentation
int KBRroute::destComp_var [protected]
Definition at line 1147 of file CommonMessages_m.h.
OverlayKey KBRroute::destKey_var [protected]
Definition at line 1146 of file CommonMessages_m.h.
int KBRroute::routingType_var [protected]
Definition at line 1151 of file CommonMessages_m.h.
unsigned int KBRroute::sourceRoute_arraysize [protected]
Definition at line 1150 of file CommonMessages_m.h.
TransportAddress* KBRroute::sourceRoute_var [protected]
Definition at line 1149 of file CommonMessages_m.h.
int KBRroute::srcComp_var [protected]
Definition at line 1148 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h