OverSim: BinaryValueArray Class Reference
BinaryValueArray Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BinaryValueArray ()
BinaryValueArray (const BinaryValueArray &other)
virtual ~BinaryValueArray ()
BinaryValueArray & operator= (const BinaryValueArray &other)
virtual BinaryValueArray * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setValuesArraySize (uint16_t size)
virtual uint16_t getValuesArraySize () const
virtual BinaryValue & getValues (uint16_t k)
virtual const BinaryValue & getValues (uint16_t k) const
virtual void setValues (uint16_t k, const BinaryValue &values)
Protected Member Functions
bool operator== (const BinaryValueArray &)
Protected Attributes
BinaryValue * values_var
uint16_t values_arraysize
Private Member Functions
void copy (const BinaryValueArray &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 class BinaryValueArray
 {
     BinaryValue values[] (uint16_t);
 }
Definition at line 2055 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BinaryValueArray::BinaryValueArray ()
Referenced by dup().
BinaryValueArray::BinaryValueArray (const BinaryValueArray & other)
virtual BinaryValueArray::~BinaryValueArray () [virtual]
Member Function Documentation
void BinaryValueArray::copy (const BinaryValueArray & other) [private]
virtual BinaryValueArray* BinaryValueArray::dup () const [inline, virtual]
Definition at line 2073 of file CommonMessages_m.h.
{return new BinaryValueArray(*this);}
virtual BinaryValue& BinaryValueArray::getValues (uint16_t k) [virtual]
virtual const BinaryValue& BinaryValueArray::getValues (uint16_t k) const [inline, virtual]
Definition at line 2081 of file CommonMessages_m.h.
Referenced by getValues().
{return const_cast<BinaryValueArray*>(this)->getValues(k);}
virtual uint16_t BinaryValueArray::getValuesArraySize () const [virtual]
BinaryValueArray& BinaryValueArray::operator= (const BinaryValueArray & other)
bool BinaryValueArray::operator== (const BinaryValueArray &) [protected]
virtual void BinaryValueArray::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void BinaryValueArray::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void BinaryValueArray::setValues (uint16_t k, const BinaryValue & values) [virtual]
virtual void BinaryValueArray::setValuesArraySize (uint16_t size) [virtual]
Member Data Documentation
uint16_t BinaryValueArray::values_arraysize [protected]
Definition at line 2059 of file CommonMessages_m.h.
BinaryValue* BinaryValueArray::values_var [protected]
Definition at line 2058 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h