OverSim: ProxFindNodeResponse Class Reference
ProxFindNodeResponse Class Reference
Class generated from common/ProximityLookupMessages.msg by opp_msgc.
#include <ProximityLookupMessages_m.h>
Public Member Functions
ProxFindNodeResponse (const char *name=NULL, int kind=0)
ProxFindNodeResponse (const ProxFindNodeResponse &other)
virtual ~ProxFindNodeResponse ()
ProxFindNodeResponse & operator= (const ProxFindNodeResponse &other)
virtual ProxFindNodeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setNextHopNcsInfosArraySize (unsigned int size)
virtual unsigned int getNextHopNcsInfosArraySize () const
virtual double getNextHopNcsInfos (unsigned int k) const
virtual void setNextHopNcsInfos (unsigned int k, double nextHopNcsInfos)
Protected Member Functions
bool operator== (const ProxFindNodeResponse &)
Protected Attributes
double * nextHopNcsInfos_var
unsigned int nextHopNcsInfos_arraysize
Private Member Functions
void copy (const ProxFindNodeResponse &other)
Detailed Description
Class generated from common/ProximityLookupMessages.msg by opp_msgc.
 packet ProxFindNodeResponse extends FindNodeResponse
 {
         double nextHopNcsInfos[];
 }
Definition at line 96 of file ProximityLookupMessages_m.h.
Constructor & Destructor Documentation
ProxFindNodeResponse::ProxFindNodeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
ProxFindNodeResponse::ProxFindNodeResponse (const ProxFindNodeResponse & other)
virtual ProxFindNodeResponse::~ProxFindNodeResponse () [virtual]
Member Function Documentation
void ProxFindNodeResponse::copy (const ProxFindNodeResponse & other) [private]
virtual ProxFindNodeResponse* ProxFindNodeResponse::dup () const [inline, virtual]
Reimplemented from FindNodeResponse.
Definition at line 114 of file ProximityLookupMessages_m.h.
{return new ProxFindNodeResponse(*this);}
virtual double ProxFindNodeResponse::getNextHopNcsInfos (unsigned int k) const [virtual]
virtual unsigned int ProxFindNodeResponse::getNextHopNcsInfosArraySize () const [virtual]
ProxFindNodeResponse& ProxFindNodeResponse::operator= (const ProxFindNodeResponse & other)
bool ProxFindNodeResponse::operator== (const ProxFindNodeResponse &) [protected]
virtual void ProxFindNodeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from FindNodeResponse.
Referenced by doPacking().
virtual void ProxFindNodeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from FindNodeResponse.
Referenced by doUnpacking().
virtual void ProxFindNodeResponse::setNextHopNcsInfos (unsigned int k, double nextHopNcsInfos) [virtual]
virtual void ProxFindNodeResponse::setNextHopNcsInfosArraySize (unsigned int size) [virtual]
Member Data Documentation
unsigned int ProxFindNodeResponse::nextHopNcsInfos_arraysize [protected]
Definition at line 100 of file ProximityLookupMessages_m.h.
double* ProxFindNodeResponse::nextHopNcsInfos_var [protected]
Definition at line 99 of file ProximityLookupMessages_m.h.
The documentation for this class was generated from the following file:
ProximityLookupMessages_m.h