OverSim: TriggersMsg Class Reference
TriggersMsg Class Reference
Class generated from applications/i3/i3Apps/I3TriggersMessage.msg by opp_msgc.
#include <I3TriggersMessage_m.h>
Public Member Functions
TriggersMsg (const char *name=NULL, int kind=0)
TriggersMsg (const TriggersMsg &other)
virtual ~TriggersMsg ()
TriggersMsg & operator= (const TriggersMsg &other)
virtual TriggersMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getValue () const
virtual void setValue (int value)
Protected Member Functions
bool operator== (const TriggersMsg &)
Protected Attributes
int value_var
Private Member Functions
void copy (const TriggersMsg &other)
Detailed Description
Class generated from applications/i3/i3Apps/I3TriggersMessage.msg by opp_msgc.
 packet TriggersMsg
 {
         int value;
 }
Definition at line 74 of file I3TriggersMessage_m.h.
Constructor & Destructor Documentation
TriggersMsg::TriggersMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
TriggersMsg::TriggersMsg (const TriggersMsg & other)
virtual TriggersMsg::~TriggersMsg () [virtual]
Member Function Documentation
void TriggersMsg::copy (const TriggersMsg & other) [private]
virtual TriggersMsg* TriggersMsg::dup () const [inline, virtual]
Definition at line 91 of file I3TriggersMessage_m.h.
{return new TriggersMsg(*this);}
virtual int TriggersMsg::getValue () const [virtual]
Referenced by I3Triggers::deliver().
TriggersMsg& TriggersMsg::operator= (const TriggersMsg & other)
bool TriggersMsg::operator== (const TriggersMsg &) [protected]
virtual void TriggersMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TriggersMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void TriggersMsg::setValue (int value) [virtual]
Referenced by I3Triggers::deliver(), and I3Triggers::handleTimerEvent().
Member Data Documentation
int TriggersMsg::value_var [protected]
Definition at line 77 of file I3TriggersMessage_m.h.
The documentation for this class was generated from the following file:
I3TriggersMessage_m.h