OverSim: P2pnsResolveResponse Class Reference
P2pnsResolveResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
P2pnsResolveResponse (const char *name=NULL, int kind=0)
P2pnsResolveResponse (const P2pnsResolveResponse &other)
virtual ~P2pnsResolveResponse ()
P2pnsResolveResponse & operator= (const P2pnsResolveResponse &other)
virtual P2pnsResolveResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual BinaryValue & getP2pName ()
virtual const BinaryValue & getP2pName () const
virtual void setP2pName (const BinaryValue &p2pName)
virtual void setAddressArraySize (unsigned int size)
virtual unsigned int getAddressArraySize () const
virtual BinaryValue & getAddress (unsigned int k)
virtual const BinaryValue & getAddress (unsigned int k) const
virtual void setAddress (unsigned int k, const BinaryValue &address)
virtual void setKindArraySize (unsigned int size)
virtual unsigned int getKindArraySize () const
virtual uint32_t getKind (unsigned int k) const
virtual void setKind (unsigned int k, uint32_t kind)
virtual void setIdArraySize (unsigned int size)
virtual unsigned int getIdArraySize () const
virtual uint32_t getId (unsigned int k) const
virtual void setId (unsigned int k, uint32_t id)
virtual bool getIsSuccess () const
virtual void setIsSuccess (bool isSuccess)
Protected Member Functions
bool operator== (const P2pnsResolveResponse &)
Protected Attributes
BinaryValue p2pName_var
BinaryValue * address_var
unsigned int address_arraysize
uint32_t * kind_var
unsigned int kind_arraysize
uint32_t * id_var
unsigned int id_arraysize
bool isSuccess_var
Private Member Functions
void copy (const P2pnsResolveResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet P2pnsResolveResponse extends BaseResponseMessage
 {
     BinaryValue p2pName;
     BinaryValue address[];
     uint32_t kind[];
     uint32_t id[];
     bool isSuccess;
 }
Definition at line 1917 of file CommonMessages_m.h.
Constructor & Destructor Documentation
P2pnsResolveResponse::P2pnsResolveResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
P2pnsResolveResponse::P2pnsResolveResponse (const P2pnsResolveResponse & other)
virtual P2pnsResolveResponse::~P2pnsResolveResponse () [virtual]
Member Function Documentation
void P2pnsResolveResponse::copy (const P2pnsResolveResponse & other) [private]
virtual P2pnsResolveResponse* P2pnsResolveResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 1941 of file CommonMessages_m.h.
{return new P2pnsResolveResponse(*this);}
virtual BinaryValue& P2pnsResolveResponse::getAddress (unsigned int k) [virtual]
virtual const BinaryValue& P2pnsResolveResponse::getAddress (unsigned int k) const [inline, virtual]
Definition at line 1952 of file CommonMessages_m.h.
Referenced by getAddress().
{return const_cast<P2pnsResolveResponse*>(this)->getAddress(k);}
virtual unsigned int P2pnsResolveResponse::getAddressArraySize () const [virtual]
virtual uint32_t P2pnsResolveResponse::getId (unsigned int k) const [virtual]
virtual unsigned int P2pnsResolveResponse::getIdArraySize () const [virtual]
virtual bool P2pnsResolveResponse::getIsSuccess () const [virtual]
virtual uint32_t P2pnsResolveResponse::getKind (unsigned int k) const [virtual]
virtual unsigned int P2pnsResolveResponse::getKindArraySize () const [virtual]
virtual BinaryValue& P2pnsResolveResponse::getP2pName () [virtual]
virtual const BinaryValue& P2pnsResolveResponse::getP2pName () const [inline, virtual]
Definition at line 1947 of file CommonMessages_m.h.
Referenced by getP2pName().
{return const_cast<P2pnsResolveResponse*>(this)->getP2pName();}
P2pnsResolveResponse& P2pnsResolveResponse::operator= (const P2pnsResolveResponse & other)
bool P2pnsResolveResponse::operator== (const P2pnsResolveResponse &) [protected]
virtual void P2pnsResolveResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void P2pnsResolveResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void P2pnsResolveResponse::setAddress (unsigned int k, const BinaryValue & address) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setAddressArraySize (unsigned int size) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setId (unsigned int k, uint32_t id) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setIdArraySize (unsigned int size) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setIsSuccess (bool isSuccess) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setKind (unsigned int k, uint32_t kind) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setKindArraySize (unsigned int size) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
virtual void P2pnsResolveResponse::setP2pName (const BinaryValue & p2pName) [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), and P2pns::handleLookupResponse().
Member Data Documentation
unsigned int P2pnsResolveResponse::address_arraysize [protected]
Definition at line 1922 of file CommonMessages_m.h.
BinaryValue* P2pnsResolveResponse::address_var [protected]
Definition at line 1921 of file CommonMessages_m.h.
unsigned int P2pnsResolveResponse::id_arraysize [protected]
Definition at line 1926 of file CommonMessages_m.h.
uint32_t* P2pnsResolveResponse::id_var [protected]
Definition at line 1925 of file CommonMessages_m.h.
bool P2pnsResolveResponse::isSuccess_var [protected]
Definition at line 1927 of file CommonMessages_m.h.
unsigned int P2pnsResolveResponse::kind_arraysize [protected]
Definition at line 1924 of file CommonMessages_m.h.
uint32_t* P2pnsResolveResponse::kind_var [protected]
Definition at line 1923 of file CommonMessages_m.h.
BinaryValue P2pnsResolveResponse::p2pName_var [protected]
Definition at line 1920 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h