OverSim: LookupResponse Class Reference
LookupResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
LookupResponse (const char *name=NULL, int kind=0)
LookupResponse (const LookupResponse &other)
virtual ~LookupResponse ()
LookupResponse & operator= (const LookupResponse &other)
virtual LookupResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual int getHopCount () const
virtual void setHopCount (int hopCount)
virtual bool getIsValid () const
virtual void setIsValid (bool isValid)
virtual void setSiblingsArraySize (unsigned int size)
virtual unsigned int getSiblingsArraySize () const
virtual NodeHandle & getSiblings (unsigned int k)
virtual const NodeHandle & getSiblings (unsigned int k) const
virtual void setSiblings (unsigned int k, const NodeHandle &siblings)
Protected Member Functions
bool operator== (const LookupResponse &)
Protected Attributes
OverlayKey key_var
int hopCount_var
bool isValid_var
NodeHandle * siblings_var
unsigned int siblings_arraysize
Private Member Functions
void copy (const LookupResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet LookupResponse extends BaseResponseMessage
 {
     OverlayKey key;
     int hopCount = 0;
     bool isValid;
     NodeHandle siblings[];
 }
Definition at line 1710 of file CommonMessages_m.h.
Constructor & Destructor Documentation
LookupResponse::LookupResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
LookupResponse::LookupResponse (const LookupResponse & other)
virtual LookupResponse::~LookupResponse () [virtual]
Member Function Documentation
void LookupResponse::copy (const LookupResponse & other) [private]
virtual LookupResponse* LookupResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 1731 of file CommonMessages_m.h.
{return new LookupResponse(*this);}
virtual int LookupResponse::getHopCount () const [virtual]
Referenced by KBRTestApp::handleLookupResponse().
virtual bool LookupResponse::getIsValid () const [virtual]
Referenced by CBRDHT::handleLookupResponse(), P2pns::handleLookupResponse(), DHT::handleLookupResponse(), KBRTestApp::handleLookupResponse(), BootstrapList::handleLookupResponse(), and P2pns::handleTunnelLookupResponse().
virtual OverlayKey& LookupResponse::getKey () [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), KBRTestApp::handleLookupResponse(), BootstrapList::handleLookupResponse(), and P2pns::handleTunnelLookupResponse().
virtual const OverlayKey& LookupResponse::getKey () const [inline, virtual]
Definition at line 1737 of file CommonMessages_m.h.
Referenced by getKey().
{return const_cast<LookupResponse*>(this)->getKey();}
virtual NodeHandle& LookupResponse::getSiblings (unsigned int k) [virtual]
Referenced by CBRDHT::handleLookupResponse(), P2pns::handleLookupResponse(), DHT::handleLookupResponse(), KBRTestApp::handleLookupResponse(), BootstrapList::handleLookupResponse(), and P2pns::handleTunnelLookupResponse().
virtual const NodeHandle& LookupResponse::getSiblings (unsigned int k) const [inline, virtual]
Definition at line 1746 of file CommonMessages_m.h.
Referenced by getSiblings().
{return const_cast<LookupResponse*>(this)->getSiblings(k);}
virtual unsigned int LookupResponse::getSiblingsArraySize () const [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), KBRTestApp::handleLookupResponse(), and BootstrapList::handleLookupResponse().
LookupResponse& LookupResponse::operator= (const LookupResponse & other)
bool LookupResponse::operator== (const LookupResponse &) [protected]
virtual void LookupResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void LookupResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void LookupResponse::setHopCount (int hopCount) [virtual]
Referenced by SendToKeyListener::lookupFinished().
virtual void LookupResponse::setIsValid (bool isValid) [virtual]
Referenced by SendToKeyListener::lookupFinished(), and BaseOverlay::lookupRpc().
virtual void LookupResponse::setKey (const OverlayKey & key) [virtual]
Referenced by SendToKeyListener::lookupFinished(), and BaseOverlay::lookupRpc().
virtual void LookupResponse::setSiblings (unsigned int k, const NodeHandle & siblings) [virtual]
Referenced by SendToKeyListener::lookupFinished().
virtual void LookupResponse::setSiblingsArraySize (unsigned int size) [virtual]
Referenced by SendToKeyListener::lookupFinished().
Member Data Documentation
int LookupResponse::hopCount_var [protected]
Definition at line 1714 of file CommonMessages_m.h.
bool LookupResponse::isValid_var [protected]
Definition at line 1715 of file CommonMessages_m.h.
OverlayKey LookupResponse::key_var [protected]
Definition at line 1713 of file CommonMessages_m.h.
unsigned int LookupResponse::siblings_arraysize [protected]
Definition at line 1717 of file CommonMessages_m.h.
NodeHandle* LookupResponse::siblings_var [protected]
Definition at line 1716 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h