OverSim: QuonListMessage Class Reference
QuonListMessage Class Reference
Class generated from overlay/quon/Quon.msg by opp_msgc.
#include <Quon_m.h>
Public Member Functions
QuonListMessage (const char *name=NULL, int kind=0)
QuonListMessage (const QuonListMessage &other)
virtual ~QuonListMessage ()
QuonListMessage & operator= (const QuonListMessage &other)
virtual QuonListMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setNeighborHandleArraySize (unsigned int size)
virtual unsigned int getNeighborHandleArraySize () const
virtual NodeHandle & getNeighborHandle (unsigned int k)
virtual const NodeHandle & getNeighborHandle (unsigned int k) const
virtual void setNeighborHandle (unsigned int k, const NodeHandle &neighborHandle)
virtual void setNeighborPositionArraySize (unsigned int size)
virtual unsigned int getNeighborPositionArraySize () const
virtual Vector2D & getNeighborPosition (unsigned int k)
virtual const Vector2D & getNeighborPosition (unsigned int k) const
virtual void setNeighborPosition (unsigned int k, const Vector2D &neighborPosition)
Protected Member Functions
bool operator== (const QuonListMessage &)
Protected Attributes
NodeHandle * neighborHandle_var
unsigned int neighborHandle_arraysize
Vector2D * neighborPosition_var
unsigned int neighborPosition_arraysize
Private Member Functions
void copy (const QuonListMessage &other)
Detailed Description
Class generated from overlay/quon/Quon.msg by opp_msgc.
 packet QuonListMessage extends QuonMessage
 {
     NodeHandle neighborHandle[];
     Vector2D neighborPosition[];
 }
Definition at line 161 of file Quon_m.h.
Constructor & Destructor Documentation
QuonListMessage::QuonListMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
QuonListMessage::QuonListMessage (const QuonListMessage & other)
virtual QuonListMessage::~QuonListMessage () [virtual]
Member Function Documentation
void QuonListMessage::copy (const QuonListMessage & other) [private]
virtual QuonListMessage* QuonListMessage::dup () const [inline, virtual]
Reimplemented from QuonMessage.
Reimplemented in QuonMoveMessage.
Definition at line 181 of file Quon_m.h.
{return new QuonListMessage(*this);}
virtual NodeHandle& QuonListMessage::getNeighborHandle (unsigned int k) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinAcknowledge(), Quon::handleNewNeighbors(), Quon::handleNodeLeave(), and Quon::handleNodeMove().
virtual const NodeHandle& QuonListMessage::getNeighborHandle (unsigned int k) const [inline, virtual]
Definition at line 189 of file Quon_m.h.
Referenced by getNeighborHandle().
{return const_cast<QuonListMessage*>(this)->getNeighborHandle(k);}
virtual unsigned int QuonListMessage::getNeighborHandleArraySize () const [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinAcknowledge(), Quon::handleNewNeighbors(), Quon::handleNodeLeave(), and Quon::handleNodeMove().
virtual Vector2D& QuonListMessage::getNeighborPosition (unsigned int k) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinAcknowledge(), Quon::handleNewNeighbors(), Quon::handleNodeLeave(), and Quon::handleNodeMove().
virtual const Vector2D& QuonListMessage::getNeighborPosition (unsigned int k) const [inline, virtual]
Definition at line 194 of file Quon_m.h.
Referenced by getNeighborPosition().
{return const_cast<QuonListMessage*>(this)->getNeighborPosition(k);}
virtual unsigned int QuonListMessage::getNeighborPositionArraySize () const [virtual]
QuonListMessage& QuonListMessage::operator= (const QuonListMessage & other)
bool QuonListMessage::operator== (const QuonListMessage &) [protected]
virtual void QuonListMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from QuonMessage.
Reimplemented in QuonMoveMessage.
Referenced by doPacking().
virtual void QuonListMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from QuonMessage.
Reimplemented in QuonMoveMessage.
Referenced by doUnpacking().
virtual void QuonListMessage::setNeighborHandle (unsigned int k, const NodeHandle & neighborHandle) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), and Quon::handleNodeMove().
virtual void QuonListMessage::setNeighborHandleArraySize (unsigned int size) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), and Quon::handleNodeMove().
virtual void QuonListMessage::setNeighborPosition (unsigned int k, const Vector2D & neighborPosition) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), and Quon::handleNodeMove().
virtual void QuonListMessage::setNeighborPositionArraySize (unsigned int size) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), and Quon::handleNodeMove().
Member Data Documentation
unsigned int QuonListMessage::neighborHandle_arraysize [protected]
Definition at line 165 of file Quon_m.h.
NodeHandle* QuonListMessage::neighborHandle_var [protected]
Definition at line 164 of file Quon_m.h.
unsigned int QuonListMessage::neighborPosition_arraysize [protected]
Definition at line 167 of file Quon_m.h.
Vector2D* QuonListMessage::neighborPosition_var [protected]
Definition at line 166 of file Quon_m.h.
The documentation for this class was generated from the following file:
Quon_m.h