OverSim: PastrySendState Class Reference
PastrySendState Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
PastrySendState (const char *name=NULL, int kind=0)
PastrySendState (const PastrySendState &other)
virtual ~PastrySendState ()
PastrySendState & operator= (const PastrySendState &other)
virtual PastrySendState * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getDest ()
virtual const TransportAddress & getDest () const
virtual void setDest (const TransportAddress &dest)
Protected Member Functions
bool operator== (const PastrySendState &)
Protected Attributes
TransportAddress dest_var
Private Member Functions
void copy (const PastrySendState &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 message PastrySendState
 {
     TransportAddress dest = TransportAddress::UNSPECIFIED_NODE;
 }
Definition at line 258 of file PastryMessage_m.h.
Constructor & Destructor Documentation
PastrySendState::PastrySendState (const char * name = NULL, int kind = 0)
Referenced by dup().
PastrySendState::PastrySendState (const PastrySendState & other)
virtual PastrySendState::~PastrySendState () [virtual]
Member Function Documentation
void PastrySendState::copy (const PastrySendState & other) [private]
virtual PastrySendState* PastrySendState::dup () const [inline, virtual]
Definition at line 275 of file PastryMessage_m.h.
{return new PastrySendState(*this);}
virtual TransportAddress& PastrySendState::getDest () [virtual]
Referenced by Pastry::handleTimerEvent().
virtual const TransportAddress& PastrySendState::getDest () const [inline, virtual]
Definition at line 281 of file PastryMessage_m.h.
Referenced by getDest().
{return const_cast<PastrySendState*>(this)->getDest();}
PastrySendState& PastrySendState::operator= (const PastrySendState & other)
bool PastrySendState::operator== (const PastrySendState &) [protected]
virtual void PastrySendState::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PastrySendState::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void PastrySendState::setDest (const TransportAddress & dest) [virtual]
Referenced by Pastry::sendStateDelayed().
Member Data Documentation
TransportAddress PastrySendState::dest_var [protected]
Definition at line 261 of file PastryMessage_m.h.
The documentation for this class was generated from the following file:
PastryMessage_m.h