OverSim: ParentRequestCall Class Reference
ParentRequestCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
ParentRequestCall (const char *name=NULL, int kind=0)
ParentRequestCall (const ParentRequestCall &other)
virtual ~ParentRequestCall ()
ParentRequestCall & operator= (const ParentRequestCall &other)
virtual ParentRequestCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDomainKey ()
virtual const OverlayKey & getDomainKey () const
virtual void setDomainKey (const OverlayKey &domainKey)
Protected Member Functions
bool operator== (const ParentRequestCall &)
Protected Attributes
OverlayKey domainKey_var
Private Member Functions
void copy (const ParentRequestCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet ParentRequestCall extends BaseCallMessage
 {
     OverlayKey domainKey;
 }
Definition at line 66 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
ParentRequestCall::ParentRequestCall (const char * name = NULL, int kind = 0)
Referenced by dup().
ParentRequestCall::ParentRequestCall (const ParentRequestCall & other)
virtual ParentRequestCall::~ParentRequestCall () [virtual]
Member Function Documentation
void ParentRequestCall::copy (const ParentRequestCall & other) [private]
virtual ParentRequestCall* ParentRequestCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 83 of file TreeManagementMessage_m.h.
{return new ParentRequestCall(*this);}
virtual OverlayKey& ParentRequestCall::getDomainKey () [virtual]
virtual const OverlayKey& ParentRequestCall::getDomainKey () const [inline, virtual]
Definition at line 89 of file TreeManagementMessage_m.h.
Referenced by getDomainKey().
{return const_cast<ParentRequestCall*>(this)->getDomainKey();}
ParentRequestCall& ParentRequestCall::operator= (const ParentRequestCall & other)
bool ParentRequestCall::operator== (const ParentRequestCall &) [protected]
virtual void ParentRequestCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void ParentRequestCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void ParentRequestCall::setDomainKey (const OverlayKey & domainKey) [virtual]
Referenced by TreeManagement::registerAtParent().
Member Data Documentation
OverlayKey ParentRequestCall::domainKey_var [protected]
Definition at line 69 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h