OverSim: CBRDHTGetCall Class Reference
CBRDHTGetCall Class Reference
Class generated from common/cbr/CBR-DHTMessage.msg by opp_msgc.
#include <CBR-DHTMessage_m.h>
Public Member Functions
CBRDHTGetCall (const char *name=NULL, int kind=0)
CBRDHTGetCall (const CBRDHTGetCall &other)
virtual ~CBRDHTGetCall ()
CBRDHTGetCall & operator= (const CBRDHTGetCall &other)
virtual CBRDHTGetCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getOriginalKey ()
virtual const OverlayKey & getOriginalKey () const
virtual void setOriginalKey (const OverlayKey &originalKey)
Protected Member Functions
bool operator== (const CBRDHTGetCall &)
Protected Attributes
OverlayKey originalKey_var
Private Member Functions
void copy (const CBRDHTGetCall &other)
Detailed Description
Class generated from common/cbr/CBR-DHTMessage.msg by opp_msgc.
 packet CBRDHTGetCall extends DHTGetCall
 {
     OverlayKey originalKey;
 }
Definition at line 32 of file CBR-DHTMessage_m.h.
Constructor & Destructor Documentation
CBRDHTGetCall::CBRDHTGetCall (const char * name = NULL, int kind = 0)
Referenced by dup().
CBRDHTGetCall::CBRDHTGetCall (const CBRDHTGetCall & other)
virtual CBRDHTGetCall::~CBRDHTGetCall () [virtual]
Member Function Documentation
void CBRDHTGetCall::copy (const CBRDHTGetCall & other) [private]
virtual CBRDHTGetCall* CBRDHTGetCall::dup () const [inline, virtual]
Reimplemented from DHTGetCall.
Definition at line 49 of file CBR-DHTMessage_m.h.
{return new CBRDHTGetCall(*this);}
virtual OverlayKey& CBRDHTGetCall::getOriginalKey () [virtual]
Referenced by CBRDHT::handleGetRequest().
virtual const OverlayKey& CBRDHTGetCall::getOriginalKey () const [inline, virtual]
Definition at line 55 of file CBR-DHTMessage_m.h.
Referenced by getOriginalKey().
{return const_cast<CBRDHTGetCall*>(this)->getOriginalKey();}
CBRDHTGetCall& CBRDHTGetCall::operator= (const CBRDHTGetCall & other)
bool CBRDHTGetCall::operator== (const CBRDHTGetCall &) [protected]
virtual void CBRDHTGetCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from DHTGetCall.
Referenced by doPacking().
virtual void CBRDHTGetCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from DHTGetCall.
Referenced by doUnpacking().
virtual void CBRDHTGetCall::setOriginalKey (const OverlayKey & originalKey) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), CBRDHT::handleGetResponse(), CBRDHT::handleLookupResponse(), and CBRDHT::handleRpcTimeout().
Member Data Documentation
OverlayKey CBRDHTGetCall::originalKey_var [protected]
Definition at line 35 of file CBR-DHTMessage_m.h.
The documentation for this class was generated from the following file:
CBR-DHTMessage_m.h