OverSim: NTreePingResponse Class Reference
NTreePingResponse Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreePingResponse (const char *name=NULL, int kind=0)
NTreePingResponse (const NTreePingResponse &other)
virtual ~NTreePingResponse ()
NTreePingResponse & operator= (const NTreePingResponse &other)
virtual NTreePingResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const NTreePingResponse &)
Private Member Functions
void copy (const NTreePingResponse &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreePingResponse extends BaseResponseMessage
 {
 }
Definition at line 319 of file NTree_m.h.
Constructor & Destructor Documentation
NTreePingResponse::NTreePingResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreePingResponse::NTreePingResponse (const NTreePingResponse & other)
virtual NTreePingResponse::~NTreePingResponse () [virtual]
Member Function Documentation
void NTreePingResponse::copy (const NTreePingResponse & other) [private]
virtual NTreePingResponse* NTreePingResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in NTreeNodePingResponse.
Definition at line 335 of file NTree_m.h.
{return new NTreePingResponse(*this);}
NTreePingResponse& NTreePingResponse::operator= (const NTreePingResponse & other)
bool NTreePingResponse::operator== (const NTreePingResponse &) [protected]
virtual void NTreePingResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in NTreeNodePingResponse.
Referenced by doPacking().
virtual void NTreePingResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in NTreeNodePingResponse.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
NTree_m.h