OverSim: PastryNewLeafsMessage Class Reference
PastryNewLeafsMessage Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
PastryNewLeafsMessage (const char *name=NULL, int kind=0)
PastryNewLeafsMessage (const PastryNewLeafsMessage &other)
virtual ~PastryNewLeafsMessage ()
PastryNewLeafsMessage & operator= (const PastryNewLeafsMessage &other)
virtual PastryNewLeafsMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setLeafsArraySize (unsigned int size)
virtual unsigned int getLeafsArraySize () const
virtual NodeHandle & getLeafs (unsigned int k)
virtual const NodeHandle & getLeafs (unsigned int k) const
virtual void setLeafs (unsigned int k, const NodeHandle &leafs)
Protected Member Functions
bool operator== (const PastryNewLeafsMessage &)
Protected Attributes
NodeHandle * leafs_var
unsigned int leafs_arraysize
Private Member Functions
void copy (const PastryNewLeafsMessage &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet PastryNewLeafsMessage
 {
     NodeHandle leafs[];
 }
Definition at line 216 of file PastryMessage_m.h.
Constructor & Destructor Documentation
PastryNewLeafsMessage::PastryNewLeafsMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PastryNewLeafsMessage::PastryNewLeafsMessage (const PastryNewLeafsMessage & other)
virtual PastryNewLeafsMessage::~PastryNewLeafsMessage () [virtual]
Member Function Documentation
void PastryNewLeafsMessage::copy (const PastryNewLeafsMessage & other) [private]
virtual PastryNewLeafsMessage* PastryNewLeafsMessage::dup () const [inline, virtual]
Definition at line 234 of file PastryMessage_m.h.
{return new PastryNewLeafsMessage(*this);}
virtual NodeHandle& PastryNewLeafsMessage::getLeafs (unsigned int k) [virtual]
virtual const NodeHandle& PastryNewLeafsMessage::getLeafs (unsigned int k) const [inline, virtual]
Definition at line 242 of file PastryMessage_m.h.
Referenced by getLeafs().
{return const_cast<PastryNewLeafsMessage*>(this)->getLeafs(k);}
virtual unsigned int PastryNewLeafsMessage::getLeafsArraySize () const [virtual]
PastryNewLeafsMessage& PastryNewLeafsMessage::operator= (const PastryNewLeafsMessage & other)
bool PastryNewLeafsMessage::operator== (const PastryNewLeafsMessage &) [protected]
virtual void PastryNewLeafsMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PastryNewLeafsMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void PastryNewLeafsMessage::setLeafs (unsigned int k, const NodeHandle & leafs) [virtual]
Referenced by PastryLeafSet::getNewLeafsMessage().
virtual void PastryNewLeafsMessage::setLeafsArraySize (unsigned int size) [virtual]
Referenced by PastryLeafSet::getNewLeafsMessage().
Member Data Documentation
unsigned int PastryNewLeafsMessage::leafs_arraysize [protected]
Definition at line 220 of file PastryMessage_m.h.
NodeHandle* PastryNewLeafsMessage::leafs_var [protected]
Definition at line 219 of file PastryMessage_m.h.
The documentation for this class was generated from the following file:
PastryMessage_m.h