OverSim: RequestLeafSetCall Class Reference
RequestLeafSetCall Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestLeafSetCall (const char *name=NULL, int kind=0)
RequestLeafSetCall (const RequestLeafSetCall &other)
virtual ~RequestLeafSetCall ()
RequestLeafSetCall & operator= (const RequestLeafSetCall &other)
virtual RequestLeafSetCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RequestLeafSetCall &)
Private Member Functions
void copy (const RequestLeafSetCall &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestLeafSetCall extends BaseCallMessage
 {
 }
Definition at line 500 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestLeafSetCall::RequestLeafSetCall (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestLeafSetCall::RequestLeafSetCall (const RequestLeafSetCall & other)
virtual RequestLeafSetCall::~RequestLeafSetCall () [virtual]
Member Function Documentation
void RequestLeafSetCall::copy (const RequestLeafSetCall & other) [private]
virtual RequestLeafSetCall* RequestLeafSetCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 516 of file PastryMessage_m.h.
{return new RequestLeafSetCall(*this);}
RequestLeafSetCall& RequestLeafSetCall::operator= (const RequestLeafSetCall & other)
bool RequestLeafSetCall::operator== (const RequestLeafSetCall &) [protected]
virtual void RequestLeafSetCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void RequestLeafSetCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h