OverSim: AbstractNcs Class Reference
AbstractNcs Class Reference
#include <CoordinateSystem.h>
Public Member Functions
virtual ~AbstractNcs ()
virtual void init (NeighborCache *neighorCache)=0
virtual bool isReady ()
virtual AbstractNcsNodeInfo * getUnvalidNcsInfo () const =0
virtual Prox getCoordinateBasedProx (const AbstractNcsNodeInfo &node) const =0
virtual void processCoordinates (const simtime_t &rtt, const AbstractNcsNodeInfo &nodeInfo)
virtual const AbstractNcsNodeInfo & getOwnNcsInfo () const =0
virtual AbstractNcsNodeInfo * createNcsInfo (const Coords &coords) const =0
virtual void handleTimerEvent (cMessage *msg)
virtual bool handleRpcCall (BaseCallMessage *msg)
Detailed Description
Definition at line 180 of file CoordinateSystem.h.
Constructor & Destructor Documentation
virtual AbstractNcs::~AbstractNcs () [inline, virtual]
Definition at line 182 of file CoordinateSystem.h.
{ };
Member Function Documentation
virtual AbstractNcsNodeInfo* AbstractNcs::createNcsInfo (const Coords & coords) const [pure virtual]
Implemented in Nps, Vivaldi, SimpleNcs, and SimpleUnderlayNCS.
Referenced by BaseRpc::internalHandleRpcMessage().
virtual Prox AbstractNcs::getCoordinateBasedProx (const AbstractNcsNodeInfo & node) const [pure virtual]
Implemented in Nps, Vivaldi, SimpleNcs, and SimpleUnderlayNCS.
Referenced by NeighborCache::getCoordinateBasedProx().
virtual const AbstractNcsNodeInfo& AbstractNcs::getOwnNcsInfo () const [pure virtual]
Implemented in Nps, Vivaldi, SimpleNcs, and SimpleUnderlayNCS.
Referenced by GlobalViewBuilder::cleanup(), NeighborCache::getAvgAbsPredictionError(), GlobalViewBuilder::handleCoordSendTimer(), BaseRpc::sendRpcResponse(), and NeighborCache::setCbrNodeId().
virtual AbstractNcsNodeInfo* AbstractNcs::getUnvalidNcsInfo () const [pure virtual]
Implemented in Nps, Vivaldi, SimpleNcs, and SimpleUnderlayNCS.
virtual bool AbstractNcs::handleRpcCall (BaseCallMessage * msg) [inline, virtual]
Reimplemented in Nps.
Definition at line 197 of file CoordinateSystem.h.
Referenced by NeighborCache::handleRpcCall().
{ return false; };
virtual void AbstractNcs::handleTimerEvent (cMessage * msg) [inline, virtual]
Reimplemented in Nps.
Definition at line 196 of file CoordinateSystem.h.
Referenced by NeighborCache::handleTimerEvent().
{ };
virtual void AbstractNcs::init (NeighborCache * neighorCache) [pure virtual]
Implemented in Nps, Vivaldi, SimpleNcs, SVivaldi, and SimpleUnderlayNCS.
Referenced by NeighborCache::initializeApp().
virtual bool AbstractNcs::isReady () [inline, virtual]
Reimplemented in Nps.
Definition at line 185 of file CoordinateSystem.h.
Referenced by NeighborCache::prepareOverlay().
{return true; };
virtual void AbstractNcs::processCoordinates (const simtime_t & rtt, const AbstractNcsNodeInfo & nodeInfo) [inline, virtual]
Reimplemented in Vivaldi.
Definition at line 190 of file CoordinateSystem.h.
Referenced by NeighborCache::updateNode().
                                                                         { };
The documentation for this class was generated from the following file:
CoordinateSystem.h