OverSim: NiceLeaderHeartbeat Class Reference
NiceLeaderHeartbeat Class Reference
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
#include <NiceMessage_m.h>
Public Member Functions
NiceLeaderHeartbeat (const char *name=NULL, int kind=0)
NiceLeaderHeartbeat (const NiceLeaderHeartbeat &other)
virtual ~NiceLeaderHeartbeat ()
NiceLeaderHeartbeat & operator= (const NiceLeaderHeartbeat &other)
virtual NiceLeaderHeartbeat * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getSupercluster_leader ()
virtual const TransportAddress & getSupercluster_leader () const
virtual void setSupercluster_leader (const TransportAddress &supercluster_leader)
virtual void setSupercluster_membersArraySize (unsigned int size)
virtual unsigned int getSupercluster_membersArraySize () const
virtual TransportAddress & getSupercluster_members (unsigned int k)
virtual const TransportAddress & getSupercluster_members (unsigned int k) const
virtual void setSupercluster_members (unsigned int k, const TransportAddress &supercluster_members)
virtual unsigned int getK () const
virtual void setK (unsigned int k)
virtual unsigned int getSc_tolerance () const
virtual void setSc_tolerance (unsigned int sc_tolerance)
Protected Member Functions
bool operator== (const NiceLeaderHeartbeat &)
Protected Attributes
TransportAddress supercluster_leader_var
TransportAddress * supercluster_members_var
unsigned int supercluster_members_arraysize
unsigned int k_var
unsigned int sc_tolerance_var
Private Member Functions
void copy (const NiceLeaderHeartbeat &other)
Detailed Description
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
 message NiceLeaderHeartbeat extends NiceHeartbeat
 {
     TransportAddress supercluster_leader;
     TransportAddress supercluster_members[];
     unsigned int k;
     unsigned int sc_tolerance;
 }
Definition at line 288 of file NiceMessage_m.h.
Constructor & Destructor Documentation
NiceLeaderHeartbeat::NiceLeaderHeartbeat (const char * name = NULL, int kind = 0)
Referenced by dup().
NiceLeaderHeartbeat::NiceLeaderHeartbeat (const NiceLeaderHeartbeat & other)
virtual NiceLeaderHeartbeat::~NiceLeaderHeartbeat () [virtual]
Member Function Documentation
void NiceLeaderHeartbeat::copy (const NiceLeaderHeartbeat & other) [private]
virtual NiceLeaderHeartbeat* NiceLeaderHeartbeat::dup () const [inline, virtual]
Reimplemented from NiceHeartbeat.
Definition at line 309 of file NiceMessage_m.h.
Referenced by oversim::Nice::sendHeartbeats().
{return new NiceLeaderHeartbeat(*this);}
virtual unsigned int NiceLeaderHeartbeat::getK () const [virtual]
virtual unsigned int NiceLeaderHeartbeat::getSc_tolerance () const [virtual]
virtual TransportAddress& NiceLeaderHeartbeat::getSupercluster_leader () [virtual]
Referenced by oversim::Nice::handleNiceLeaderHeartbeat(), and oversim::Nice::handleNiceLeaderTransfer().
virtual const TransportAddress& NiceLeaderHeartbeat::getSupercluster_leader () const [inline, virtual]
Definition at line 315 of file NiceMessage_m.h.
Referenced by getSupercluster_leader().
{return const_cast<NiceLeaderHeartbeat*>(this)->getSupercluster_leader();}
virtual TransportAddress& NiceLeaderHeartbeat::getSupercluster_members (unsigned int k) [virtual]
Referenced by oversim::Nice::handleNiceLeaderHeartbeat(), and oversim::Nice::handleNiceLeaderTransfer().
virtual const TransportAddress& NiceLeaderHeartbeat::getSupercluster_members (unsigned int k) const [inline, virtual]
Definition at line 320 of file NiceMessage_m.h.
Referenced by getSupercluster_members().
{return const_cast<NiceLeaderHeartbeat*>(this)->getSupercluster_members(k);}
virtual unsigned int NiceLeaderHeartbeat::getSupercluster_membersArraySize () const [virtual]
Referenced by oversim::Nice::handleNiceLeaderHeartbeat(), and oversim::Nice::handleNiceLeaderTransfer().
NiceLeaderHeartbeat& NiceLeaderHeartbeat::operator= (const NiceLeaderHeartbeat & other)
bool NiceLeaderHeartbeat::operator== (const NiceLeaderHeartbeat &) [protected]
virtual void NiceLeaderHeartbeat::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from NiceHeartbeat.
Referenced by doPacking().
virtual void NiceLeaderHeartbeat::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from NiceHeartbeat.
Referenced by doUnpacking().
virtual void NiceLeaderHeartbeat::setK (unsigned int k) [virtual]
Referenced by oversim::Nice::sendHeartbeats().
virtual void NiceLeaderHeartbeat::setSc_tolerance (unsigned int sc_tolerance) [virtual]
Referenced by oversim::Nice::sendHeartbeats().
virtual void NiceLeaderHeartbeat::setSupercluster_leader (const TransportAddress & supercluster_leader) [virtual]
Referenced by oversim::Nice::LeaderTransfer(), oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceLeaderHeartbeat::setSupercluster_members (unsigned int k, const TransportAddress & supercluster_members) [virtual]
Referenced by oversim::Nice::LeaderTransfer(), oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
virtual void NiceLeaderHeartbeat::setSupercluster_membersArraySize (unsigned int size) [virtual]
Referenced by oversim::Nice::LeaderTransfer(), oversim::Nice::sendHeartbeats(), and oversim::Nice::sendHeartbeatTo().
Member Data Documentation
unsigned int NiceLeaderHeartbeat::k_var [protected]
Definition at line 294 of file NiceMessage_m.h.
unsigned int NiceLeaderHeartbeat::sc_tolerance_var [protected]
Definition at line 295 of file NiceMessage_m.h.
TransportAddress NiceLeaderHeartbeat::supercluster_leader_var [protected]
Definition at line 291 of file NiceMessage_m.h.
unsigned int NiceLeaderHeartbeat::supercluster_members_arraysize [protected]
Definition at line 293 of file NiceMessage_m.h.
TransportAddress* NiceLeaderHeartbeat::supercluster_members_var [protected]
Definition at line 292 of file NiceMessage_m.h.
The documentation for this class was generated from the following file:
NiceMessage_m.h