OverSim: TreeAppResponse Class Reference
TreeAppResponse Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
TreeAppResponse (const char *name=NULL, int kind=0)
TreeAppResponse (const TreeAppResponse &other)
virtual ~TreeAppResponse ()
TreeAppResponse & operator= (const TreeAppResponse &other)
virtual TreeAppResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const TreeAppResponse &)
Private Member Functions
void copy (const TreeAppResponse &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet TreeAppResponse extends BaseResponseMessage
 {
 }
Definition at line 172 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
TreeAppResponse::TreeAppResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
TreeAppResponse::TreeAppResponse (const TreeAppResponse & other)
virtual TreeAppResponse::~TreeAppResponse () [virtual]
Member Function Documentation
void TreeAppResponse::copy (const TreeAppResponse & other) [private]
virtual TreeAppResponse* TreeAppResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in GlobalViewBuilderResponse.
Definition at line 188 of file TreeManagementMessage_m.h.
{return new TreeAppResponse(*this);}
TreeAppResponse& TreeAppResponse::operator= (const TreeAppResponse & other)
bool TreeAppResponse::operator== (const TreeAppResponse &) [protected]
virtual void TreeAppResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in GlobalViewBuilderResponse.
Referenced by doPacking().
virtual void TreeAppResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in GlobalViewBuilderResponse.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h