OverSim: BootstrapLookupMessage Class Reference
BootstrapLookupMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BootstrapLookupMessage (const char *name=NULL, int kind=0)
BootstrapLookupMessage (const BootstrapLookupMessage &other)
virtual ~BootstrapLookupMessage ()
BootstrapLookupMessage & operator= (const BootstrapLookupMessage &other)
virtual BootstrapLookupMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const BootstrapLookupMessage &)
Private Member Functions
void copy (const BootstrapLookupMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet BootstrapLookupMessage extends BaseOverlayMessage
 {
 }
Definition at line 925 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BootstrapLookupMessage::BootstrapLookupMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BootstrapLookupMessage::BootstrapLookupMessage (const BootstrapLookupMessage & other)
virtual BootstrapLookupMessage::~BootstrapLookupMessage () [virtual]
Member Function Documentation
void BootstrapLookupMessage::copy (const BootstrapLookupMessage & other) [private]
virtual BootstrapLookupMessage* BootstrapLookupMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 941 of file CommonMessages_m.h.
{return new BootstrapLookupMessage(*this);}
BootstrapLookupMessage& BootstrapLookupMessage::operator= (const BootstrapLookupMessage & other)
bool BootstrapLookupMessage::operator== (const BootstrapLookupMessage &) [protected]
virtual void BootstrapLookupMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void BootstrapLookupMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h