OverSim: PubSubJoinCall Class Reference
PubSubJoinCall Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubJoinCall (const char *name=NULL, int kind=0)
PubSubJoinCall (const PubSubJoinCall &other)
virtual ~PubSubJoinCall ()
PubSubJoinCall & operator= (const PubSubJoinCall &other)
virtual PubSubJoinCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
virtual int getRessources () const
virtual void setRessources (int ressources)
Protected Member Functions
bool operator== (const PubSubJoinCall &)
Protected Attributes
Vector2D position_var
int ressources_var
Private Member Functions
void copy (const PubSubJoinCall &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubJoinCall extends BaseCallMessage
 {
         Vector2D position;
         int ressources;
 }
Definition at line 168 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubJoinCall::PubSubJoinCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubJoinCall::PubSubJoinCall (const PubSubJoinCall & other)
virtual PubSubJoinCall::~PubSubJoinCall () [virtual]
Member Function Documentation
void PubSubJoinCall::copy (const PubSubJoinCall & other) [private]
virtual PubSubJoinCall* PubSubJoinCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 186 of file PubSubMessage_m.h.
{return new PubSubJoinCall(*this);}
virtual Vector2D& PubSubJoinCall::getPosition () [virtual]
Referenced by PubSubLobby::handleJoin().
virtual const Vector2D& PubSubJoinCall::getPosition () const [inline, virtual]
Definition at line 192 of file PubSubMessage_m.h.
Referenced by getPosition().
{return const_cast<PubSubJoinCall*>(this)->getPosition();}
virtual int PubSubJoinCall::getRessources () const [virtual]
Referenced by PubSubLobby::handleJoin().
PubSubJoinCall& PubSubJoinCall::operator= (const PubSubJoinCall & other)
bool PubSubJoinCall::operator== (const PubSubJoinCall &) [protected]
virtual void PubSubJoinCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PubSubJoinCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void PubSubJoinCall::setPosition (const Vector2D & position) [virtual]
Referenced by PubSubMMOG::handleAppMessage().
virtual void PubSubJoinCall::setRessources (int ressources) [virtual]
Referenced by PubSubMMOG::handleAppMessage().
Member Data Documentation
Vector2D PubSubJoinCall::position_var [protected]
Definition at line 171 of file PubSubMessage_m.h.
int PubSubJoinCall::ressources_var [protected]
Definition at line 172 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h