OverSim: TokenMessage Class Reference
TokenMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
TokenMessage (const char *name=NULL, int kind=0)
TokenMessage (const TokenMessage &other)
virtual ~TokenMessage ()
TokenMessage & operator= (const TokenMessage &other)
virtual TokenMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSrcTokenNr () const
virtual void setSrcTokenNr (int srcTokenNr)
virtual int getDstTokenNr () const
virtual void setDstTokenNr (int dstTokenNr)
Protected Member Functions
bool operator== (const TokenMessage &)
Protected Attributes
int srcTokenNr_var
int dstTokenNr_var
Private Member Functions
void copy (const TokenMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message TokenMessage extends GiaMessage
 {
        int srcTokenNr;
        int dstTokenNr;
 };
Definition at line 187 of file GiaMessage_m.h.
Constructor & Destructor Documentation
TokenMessage::TokenMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
TokenMessage::TokenMessage (const TokenMessage & other)
virtual TokenMessage::~TokenMessage () [virtual]
Member Function Documentation
void TokenMessage::copy (const TokenMessage & other) [private]
virtual TokenMessage* TokenMessage::dup () const [inline, virtual]
Reimplemented from GiaMessage.
Definition at line 205 of file GiaMessage_m.h.
{return new TokenMessage(*this);}
virtual int TokenMessage::getDstTokenNr () const [virtual]
virtual int TokenMessage::getSrcTokenNr () const [virtual]
TokenMessage& TokenMessage::operator= (const TokenMessage & other)
bool TokenMessage::operator== (const TokenMessage &) [protected]
virtual void TokenMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Referenced by doPacking().
virtual void TokenMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Referenced by doUnpacking().
virtual void TokenMessage::setDstTokenNr (int dstTokenNr) [virtual]
Referenced by Gia::sendToken().
virtual void TokenMessage::setSrcTokenNr (int srcTokenNr) [virtual]
Referenced by Gia::sendToken().
Member Data Documentation
int TokenMessage::dstTokenNr_var [protected]
Definition at line 191 of file GiaMessage_m.h.
int TokenMessage::srcTokenNr_var [protected]
Definition at line 190 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h