OverSim: SimpleCoordStrategyCall Class Reference
SimpleCoordStrategyCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
SimpleCoordStrategyCall (const char *name=NULL, int kind=0)
SimpleCoordStrategyCall (const SimpleCoordStrategyCall &other)
virtual ~SimpleCoordStrategyCall ()
SimpleCoordStrategyCall & operator= (const SimpleCoordStrategyCall &other)
virtual SimpleCoordStrategyCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual SimpleCoordDataContainer & getCoordData ()
virtual const
SimpleCoordDataContainer & getCoordData () const
virtual void setCoordData (const SimpleCoordDataContainer &coordData)
Protected Member Functions
bool operator== (const SimpleCoordStrategyCall &)
Protected Attributes
SimpleCoordDataContainer coordData_var
Private Member Functions
void copy (const SimpleCoordStrategyCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet SimpleCoordStrategyCall extends GlobalViewBuilderCall
 {
     SimpleCoordDataContainer coordData;
 }
Definition at line 609 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
SimpleCoordStrategyCall::SimpleCoordStrategyCall (const char * name = NULL, int kind = 0)
Referenced by dup().
SimpleCoordStrategyCall::SimpleCoordStrategyCall (const SimpleCoordStrategyCall & other)
virtual SimpleCoordStrategyCall::~SimpleCoordStrategyCall () [virtual]
Member Function Documentation
void SimpleCoordStrategyCall::copy (const SimpleCoordStrategyCall & other) [private]
virtual SimpleCoordStrategyCall* SimpleCoordStrategyCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 626 of file TreeManagementMessage_m.h.
{return new SimpleCoordStrategyCall(*this);}
virtual SimpleCoordDataContainer& SimpleCoordStrategyCall::getCoordData () [virtual]
Referenced by StrategySimplifyCoords::handleCoordinateRpcCall().
virtual const SimpleCoordDataContainer& SimpleCoordStrategyCall::getCoordData () const [inline, virtual]
Definition at line 632 of file TreeManagementMessage_m.h.
Referenced by getCoordData().
{return const_cast<SimpleCoordStrategyCall*>(this)->getCoordData();}
SimpleCoordStrategyCall& SimpleCoordStrategyCall::operator= (const SimpleCoordStrategyCall & other)
bool SimpleCoordStrategyCall::operator== (const SimpleCoordStrategyCall &) [protected]
virtual void SimpleCoordStrategyCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void SimpleCoordStrategyCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void SimpleCoordStrategyCall::setCoordData (const SimpleCoordDataContainer & coordData) [virtual]
Referenced by StrategySimplifyCoords::getCoordinateMessage().
Member Data Documentation
SimpleCoordDataContainer SimpleCoordStrategyCall::coordData_var [protected]
Definition at line 612 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h