OverSim: KademliaRoutingInfoMessage Class Reference
KademliaRoutingInfoMessage Class Reference
Class generated from overlay/kademlia/KademliaMessage.msg by opp_msgc.
#include <KademliaMessage_m.h>
Public Member Functions
KademliaRoutingInfoMessage (const char *name=NULL, int kind=0)
KademliaRoutingInfoMessage (const KademliaRoutingInfoMessage &other)
virtual ~KademliaRoutingInfoMessage ()
KademliaRoutingInfoMessage & operator= (const KademliaRoutingInfoMessage &other)
virtual
KademliaRoutingInfoMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrcNode ()
virtual const NodeHandle & getSrcNode () const
virtual void setSrcNode (const NodeHandle &srcNode)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual void setNextHopsArraySize (unsigned int size)
virtual unsigned int getNextHopsArraySize () const
virtual MarkedNodeHandle & getNextHops (unsigned int k)
virtual const MarkedNodeHandle & getNextHops (unsigned int k) const
virtual void setNextHops (unsigned int k, const MarkedNodeHandle &nextHops)
Protected Member Functions
bool operator== (const KademliaRoutingInfoMessage &)
Protected Attributes
NodeHandle srcNode_var
OverlayKey destKey_var
MarkedNodeHandle * nextHops_var
unsigned int nextHops_arraysize
Private Member Functions
void copy (const KademliaRoutingInfoMessage &other)
Detailed Description
Class generated from overlay/kademlia/KademliaMessage.msg by opp_msgc.
 packet KademliaRoutingInfoMessage extends BaseOverlayMessage
 {
         NodeHandle srcNode;
         OverlayKey destKey = OverlayKey::UNSPECIFIED_KEY;
         MarkedNodeHandle nextHops[];
 }
Definition at line 43 of file KademliaMessage_m.h.
Constructor & Destructor Documentation
KademliaRoutingInfoMessage::KademliaRoutingInfoMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
KademliaRoutingInfoMessage::KademliaRoutingInfoMessage (const KademliaRoutingInfoMessage & other)
virtual KademliaRoutingInfoMessage::~KademliaRoutingInfoMessage () [virtual]
Member Function Documentation
void KademliaRoutingInfoMessage::copy (const KademliaRoutingInfoMessage & other) [private]
virtual KademliaRoutingInfoMessage* KademliaRoutingInfoMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 63 of file KademliaMessage_m.h.
{return new KademliaRoutingInfoMessage(*this);}
virtual OverlayKey& KademliaRoutingInfoMessage::getDestKey () [virtual]
Referenced by Kademlia::recursiveRoutingHook().
virtual const OverlayKey& KademliaRoutingInfoMessage::getDestKey () const [inline, virtual]
Definition at line 72 of file KademliaMessage_m.h.
Referenced by getDestKey().
{return const_cast<KademliaRoutingInfoMessage*>(this)->getDestKey();}
virtual MarkedNodeHandle& KademliaRoutingInfoMessage::getNextHops (unsigned int k) [virtual]
Referenced by Kademlia::recursiveRoutingHook().
virtual const MarkedNodeHandle& KademliaRoutingInfoMessage::getNextHops (unsigned int k) const [inline, virtual]
Definition at line 77 of file KademliaMessage_m.h.
Referenced by getNextHops().
{return const_cast<KademliaRoutingInfoMessage*>(this)->getNextHops(k);}
virtual unsigned int KademliaRoutingInfoMessage::getNextHopsArraySize () const [virtual]
Referenced by Kademlia::recursiveRoutingHook().
virtual NodeHandle& KademliaRoutingInfoMessage::getSrcNode () [virtual]
virtual const NodeHandle& KademliaRoutingInfoMessage::getSrcNode () const [inline, virtual]
Definition at line 69 of file KademliaMessage_m.h.
Referenced by getSrcNode().
{return const_cast<KademliaRoutingInfoMessage*>(this)->getSrcNode();}
KademliaRoutingInfoMessage& KademliaRoutingInfoMessage::operator= (const KademliaRoutingInfoMessage & other)
bool KademliaRoutingInfoMessage::operator== (const KademliaRoutingInfoMessage &) [protected]
virtual void KademliaRoutingInfoMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void KademliaRoutingInfoMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void KademliaRoutingInfoMessage::setDestKey (const OverlayKey & destKey) [virtual]
virtual void KademliaRoutingInfoMessage::setNextHops (unsigned int k, const MarkedNodeHandle & nextHops) [virtual]
Referenced by Kademlia::recursiveRoutingHook().
virtual void KademliaRoutingInfoMessage::setNextHopsArraySize (unsigned int size) [virtual]
Referenced by Kademlia::recursiveRoutingHook().
virtual void KademliaRoutingInfoMessage::setSrcNode (const NodeHandle & srcNode) [virtual]
Member Data Documentation
OverlayKey KademliaRoutingInfoMessage::destKey_var [protected]
Definition at line 47 of file KademliaMessage_m.h.
unsigned int KademliaRoutingInfoMessage::nextHops_arraysize [protected]
Definition at line 49 of file KademliaMessage_m.h.
MarkedNodeHandle* KademliaRoutingInfoMessage::nextHops_var [protected]
Definition at line 48 of file KademliaMessage_m.h.
NodeHandle KademliaRoutingInfoMessage::srcNode_var [protected]
Definition at line 46 of file KademliaMessage_m.h.
The documentation for this class was generated from the following file:
KademliaMessage_m.h