OverSim: DhtTestEntryTimer Class Reference
DhtTestEntryTimer Class Reference
Class generated from tier2/dhttestapp/DHTTestAppMessages.msg by opp_msgc.
#include <DHTTestAppMessages_m.h>
Public Member Functions
DhtTestEntryTimer (const char *name=NULL, int kind=0)
DhtTestEntryTimer (const DhtTestEntryTimer &other)
virtual ~DhtTestEntryTimer ()
DhtTestEntryTimer & operator= (const DhtTestEntryTimer &other)
virtual DhtTestEntryTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
Protected Member Functions
bool operator== (const DhtTestEntryTimer &)
Protected Attributes
OverlayKey key_var
Private Member Functions
void copy (const DhtTestEntryTimer &other)
Detailed Description
Class generated from tier2/dhttestapp/DHTTestAppMessages.msg by opp_msgc.
 message DhtTestEntryTimer
 {
     OverlayKey key;
 }
Definition at line 32 of file DHTTestAppMessages_m.h.
Constructor & Destructor Documentation
DhtTestEntryTimer::DhtTestEntryTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
DhtTestEntryTimer::DhtTestEntryTimer (const DhtTestEntryTimer & other)
virtual DhtTestEntryTimer::~DhtTestEntryTimer () [virtual]
Member Function Documentation
void DhtTestEntryTimer::copy (const DhtTestEntryTimer & other) [private]
virtual DhtTestEntryTimer* DhtTestEntryTimer::dup () const [inline, virtual]
Definition at line 49 of file DHTTestAppMessages_m.h.
{return new DhtTestEntryTimer(*this);}
virtual OverlayKey& DhtTestEntryTimer::getKey () [virtual]
Referenced by GlobalDhtTestMap::handleMessage().
virtual const OverlayKey& DhtTestEntryTimer::getKey () const [inline, virtual]
Definition at line 55 of file DHTTestAppMessages_m.h.
Referenced by getKey().
{return const_cast<DhtTestEntryTimer*>(this)->getKey();}
DhtTestEntryTimer& DhtTestEntryTimer::operator= (const DhtTestEntryTimer & other)
bool DhtTestEntryTimer::operator== (const DhtTestEntryTimer &) [protected]
virtual void DhtTestEntryTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void DhtTestEntryTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void DhtTestEntryTimer::setKey (const OverlayKey & key) [virtual]
Referenced by GlobalDhtTestMap::insertEntry().
Member Data Documentation
OverlayKey DhtTestEntryTimer::key_var [protected]
Definition at line 35 of file DHTTestAppMessages_m.h.
The documentation for this class was generated from the following file:
DHTTestAppMessages_m.h