OverSim: VastEventMessage Class Reference
VastEventMessage Class Reference
Class generated from overlay/vast/Vast.msg by opp_msgc.
#include <Vast_m.h>
Public Member Functions
VastEventMessage (const char *name=NULL, int kind=0)
VastEventMessage (const VastEventMessage &other)
virtual ~VastEventMessage ()
VastEventMessage & operator= (const VastEventMessage &other)
virtual VastEventMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const VastEventMessage &)
Private Member Functions
void copy (const VastEventMessage &other)
Detailed Description
Class generated from overlay/vast/Vast.msg by opp_msgc.
 packet VastEventMessage extends VastMessage
 {
 }
Definition at line 275 of file Vast_m.h.
Constructor & Destructor Documentation
VastEventMessage::VastEventMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
VastEventMessage::VastEventMessage (const VastEventMessage & other)
virtual VastEventMessage::~VastEventMessage () [virtual]
Member Function Documentation
void VastEventMessage::copy (const VastEventMessage & other) [private]
virtual VastEventMessage* VastEventMessage::dup () const [inline, virtual]
Reimplemented from VastMessage.
Definition at line 291 of file Vast_m.h.
{return new VastEventMessage(*this);}
VastEventMessage& VastEventMessage::operator= (const VastEventMessage & other)
bool VastEventMessage::operator== (const VastEventMessage &) [protected]
virtual void VastEventMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doPacking().
virtual void VastEventMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from VastMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
Vast_m.h