OverSim: HGetParametersResponse Class Reference
HGetParametersResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HGetParametersResponse (const char *name=NULL, int kind=0)
HGetParametersResponse (const HGetParametersResponse &other)
virtual ~HGetParametersResponse ()
HGetParametersResponse & operator= (const HGetParametersResponse &other)
virtual HGetParametersResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCapacity () const
virtual void setCapacity (int capacity)
virtual int getRescueCapacity () const
virtual void setRescueCapacity (int rescueCapacity)
virtual double getBandwidth () const
virtual void setBandwidth (double bandwidth)
Protected Member Functions
bool operator== (const HGetParametersResponse &)
Protected Attributes
int capacity_var
int rescueCapacity_var
double bandwidth_var
Private Member Functions
void copy (const HGetParametersResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HGetParametersResponse extends BaseResponseMessage {
     int capacity;
     int rescueCapacity;
     double bandwidth;
 };
Definition at line 207 of file HMessage_m.h.
Constructor & Destructor Documentation
HGetParametersResponse::HGetParametersResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HGetParametersResponse::HGetParametersResponse (const HGetParametersResponse & other)
virtual HGetParametersResponse::~HGetParametersResponse () [virtual]
Member Function Documentation
void HGetParametersResponse::copy (const HGetParametersResponse & other) [private]
virtual HGetParametersResponse* HGetParametersResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 226 of file HMessage_m.h.
{return new HGetParametersResponse(*this);}
virtual double HGetParametersResponse::getBandwidth () const [virtual]
Referenced by HTopology::handleGetParametersResponse().
virtual int HGetParametersResponse::getCapacity () const [virtual]
Referenced by HTopology::handleGetParametersResponse().
virtual int HGetParametersResponse::getRescueCapacity () const [virtual]
Referenced by HTopology::handleGetParametersResponse().
HGetParametersResponse& HGetParametersResponse::operator= (const HGetParametersResponse & other)
bool HGetParametersResponse::operator== (const HGetParametersResponse &) [protected]
virtual void HGetParametersResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HGetParametersResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HGetParametersResponse::setBandwidth (double bandwidth) [virtual]
Referenced by HTopology::handleGetParametersCall().
virtual void HGetParametersResponse::setCapacity (int capacity) [virtual]
Referenced by HTopology::handleGetParametersCall().
virtual void HGetParametersResponse::setRescueCapacity (int rescueCapacity) [virtual]
Referenced by HTopology::handleGetParametersCall().
Member Data Documentation
double HGetParametersResponse::bandwidth_var [protected]
Definition at line 212 of file HMessage_m.h.
int HGetParametersResponse::capacity_var [protected]
Definition at line 210 of file HMessage_m.h.
int HGetParametersResponse::rescueCapacity_var [protected]
Definition at line 211 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h