OverSim: HVideoSegmentCall Class Reference
HVideoSegmentCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HVideoSegmentCall (const char *name=NULL, int kind=0)
HVideoSegmentCall (const HVideoSegmentCall &other)
virtual ~HVideoSegmentCall ()
HVideoSegmentCall & operator= (const HVideoSegmentCall &other)
virtual HVideoSegmentCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual HVideoSegment & getSegment ()
virtual const HVideoSegment & getSegment () const
virtual void setSegment (const HVideoSegment &segment)
Protected Member Functions
bool operator== (const HVideoSegmentCall &)
Protected Attributes
HVideoSegment segment_var
Private Member Functions
void copy (const HVideoSegmentCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HVideoSegmentCall extends BaseCallMessage {
     HVideoSegment segment;
 }
Definition at line 420 of file HMessage_m.h.
Constructor & Destructor Documentation
HVideoSegmentCall::HVideoSegmentCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HVideoSegmentCall::HVideoSegmentCall (const HVideoSegmentCall & other)
virtual HVideoSegmentCall::~HVideoSegmentCall () [virtual]
Member Function Documentation
void HVideoSegmentCall::copy (const HVideoSegmentCall & other) [private]
virtual HVideoSegmentCall* HVideoSegmentCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 437 of file HMessage_m.h.
{return new HVideoSegmentCall(*this);}
virtual HVideoSegment& HVideoSegmentCall::getSegment () [virtual]
Referenced by HTopology::handleVideoSegment().
virtual const HVideoSegment& HVideoSegmentCall::getSegment () const [inline, virtual]
Definition at line 443 of file HMessage_m.h.
Referenced by getSegment().
{return const_cast<HVideoSegmentCall*>(this)->getSegment();}
HVideoSegmentCall& HVideoSegmentCall::operator= (const HVideoSegmentCall & other)
bool HVideoSegmentCall::operator== (const HVideoSegmentCall &) [protected]
virtual void HVideoSegmentCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HVideoSegmentCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void HVideoSegmentCall::setSegment (const HVideoSegment & segment) [virtual]
Referenced by HTopology::handlePacketGenerationTimer().
Member Data Documentation
HVideoSegment HVideoSegmentCall::segment_var [protected]
Definition at line 423 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h