OverSim: GiaRouteMessage Class Reference
GiaRouteMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
GiaRouteMessage (const char *name=NULL, int kind=0)
GiaRouteMessage (const GiaRouteMessage &other)
virtual ~GiaRouteMessage ()
GiaRouteMessage & operator= (const GiaRouteMessage &other)
virtual GiaRouteMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getOriginatorKey ()
virtual const OverlayKey & getOriginatorKey () const
virtual void setOriginatorKey (const OverlayKey &originatorKey)
virtual IPvXAddress & getOriginatorIP ()
virtual const IPvXAddress & getOriginatorIP () const
virtual void setOriginatorIP (const IPvXAddress &originatorIP)
virtual int getOriginatorPort () const
virtual void setOriginatorPort (int originatorPort)
Protected Member Functions
bool operator== (const GiaRouteMessage &)
Protected Attributes
OverlayKey originatorKey_var
IPvXAddress originatorIP_var
int originatorPort_var
Private Member Functions
void copy (const GiaRouteMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message GiaRouteMessage extends GiaIDMessage
 {
         OverlayKey originatorKey;
         IPvXAddress originatorIP;
         int originatorPort;
 };
Definition at line 274 of file GiaMessage_m.h.
Constructor & Destructor Documentation
GiaRouteMessage::GiaRouteMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GiaRouteMessage::GiaRouteMessage (const GiaRouteMessage & other)
virtual GiaRouteMessage::~GiaRouteMessage () [virtual]
Member Function Documentation
void GiaRouteMessage::copy (const GiaRouteMessage & other) [private]
virtual GiaRouteMessage* GiaRouteMessage::dup () const [inline, virtual]
Reimplemented from GiaIDMessage.
Definition at line 293 of file GiaMessage_m.h.
{return new GiaRouteMessage(*this);}
virtual IPvXAddress& GiaRouteMessage::getOriginatorIP () [virtual]
virtual const IPvXAddress& GiaRouteMessage::getOriginatorIP () const [inline, virtual]
Definition at line 302 of file GiaMessage_m.h.
Referenced by getOriginatorIP().
{return const_cast<GiaRouteMessage*>(this)->getOriginatorIP();}
virtual OverlayKey& GiaRouteMessage::getOriginatorKey () [virtual]
virtual const OverlayKey& GiaRouteMessage::getOriginatorKey () const [inline, virtual]
Definition at line 299 of file GiaMessage_m.h.
Referenced by getOriginatorKey().
{return const_cast<GiaRouteMessage*>(this)->getOriginatorKey();}
virtual int GiaRouteMessage::getOriginatorPort () const [virtual]
GiaRouteMessage& GiaRouteMessage::operator= (const GiaRouteMessage & other)
bool GiaRouteMessage::operator== (const GiaRouteMessage &) [protected]
virtual void GiaRouteMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaIDMessage.
Referenced by doPacking().
virtual void GiaRouteMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaIDMessage.
Referenced by doUnpacking().
virtual void GiaRouteMessage::setOriginatorIP (const IPvXAddress & originatorIP) [virtual]
Referenced by Gia::getRoute().
virtual void GiaRouteMessage::setOriginatorKey (const OverlayKey & originatorKey) [virtual]
Referenced by Gia::getRoute().
virtual void GiaRouteMessage::setOriginatorPort (int originatorPort) [virtual]
Referenced by Gia::getRoute().
Member Data Documentation
IPvXAddress GiaRouteMessage::originatorIP_var [protected]
Definition at line 278 of file GiaMessage_m.h.
OverlayKey GiaRouteMessage::originatorKey_var [protected]
Definition at line 277 of file GiaMessage_m.h.
int GiaRouteMessage::originatorPort_var [protected]
Definition at line 279 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h