OverSim: HCapacityCall Class Reference
HCapacityCall Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HCapacityCall (const char *name=NULL, int kind=0)
HCapacityCall (const HCapacityCall &other)
virtual ~HCapacityCall ()
HCapacityCall & operator= (const HCapacityCall &other)
virtual HCapacityCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestinationKey ()
virtual const OverlayKey & getDestinationKey () const
virtual void setDestinationKey (const OverlayKey &destinationKey)
Protected Member Functions
bool operator== (const HCapacityCall &)
Protected Attributes
OverlayKey destinationKey_var
Private Member Functions
void copy (const HCapacityCall &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HCapacityCall extends BaseCallMessage {
     OverlayKey destinationKey;
 };
Definition at line 87 of file HMessage_m.h.
Constructor & Destructor Documentation
HCapacityCall::HCapacityCall (const char * name = NULL, int kind = 0)
Referenced by dup().
HCapacityCall::HCapacityCall (const HCapacityCall & other)
virtual HCapacityCall::~HCapacityCall () [virtual]
Member Function Documentation
void HCapacityCall::copy (const HCapacityCall & other) [private]
virtual HCapacityCall* HCapacityCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 104 of file HMessage_m.h.
{return new HCapacityCall(*this);}
virtual OverlayKey& HCapacityCall::getDestinationKey () [virtual]
virtual const OverlayKey& HCapacityCall::getDestinationKey () const [inline, virtual]
Definition at line 110 of file HMessage_m.h.
Referenced by getDestinationKey().
{return const_cast<HCapacityCall*>(this)->getDestinationKey();}
HCapacityCall& HCapacityCall::operator= (const HCapacityCall & other)
bool HCapacityCall::operator== (const HCapacityCall &) [protected]
virtual void HCapacityCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void HCapacityCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void HCapacityCall::setDestinationKey (const OverlayKey & destinationKey) [virtual]
Referenced by HTopology::getParametersForSelectionAlgo().
Member Data Documentation
OverlayKey HCapacityCall::destinationKey_var [protected]
Definition at line 90 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h