OverSim: StrategyTreeTest Class Reference
StrategyTreeTest Class Reference
#include <StrategyTreeTest.h>
Public Member Functions
StrategyTreeTest ()
.cc
virtual ~StrategyTreeTest ()
virtual void handleCoordinateRpcCall (GlobalViewBuilderCall *globalViewBuilderCall)
virtual void setMyCoordinates (const AbstractNcsNodeInfo &ncsInfo)
virtual GlobalViewBuilderCall * getCoordinateMessage ()
virtual std::vector
< std::vector< double > > getGlobalViewData ()
return the decodes global View Data
virtual std::string getStrategyDataStatus ()
return a short status of the running send strategy
virtual void cleanUpCoordData (const treeNodeMap &currentTreeChildNodes)
cleanup the coordinate map and remove data of nodes which are not longer in the branch
virtual std::string getStrategyCombinedParams ()
return a string of the currently used strategy params
Protected Member Functions
void setBranchCount (const NodeHandle &treeNode, int count)
int getNodeCount ()
Private Types
typedef std::pair
< TransportAddress, int > branchCount
typedef UNORDERED_MAP
< TransportAddress, int,
TransportAddress::hashFcn > nodeCountMap
Private Attributes
nodeCountMap branchCountMap
Detailed Description
Definition at line 40 of file StrategyTreeTest.h.
Member Typedef Documentation
typedef std::pair<TransportAddress, int> StrategyTreeTest::branchCount [private]
Definition at line 44 of file StrategyTreeTest.h.
typedef UNORDERED_MAP<TransportAddress, int, TransportAddress::hashFcn> StrategyTreeTest::nodeCountMap [private]
Definition at line 45 of file StrategyTreeTest.h.
Constructor & Destructor Documentation
StrategyTreeTest::StrategyTreeTest ()
.cc
Author:
Daniel Lienert
Definition at line 27 of file StrategyTreeTest.cc.
{
        // TODO Auto-generated constructor stub
}
StrategyTreeTest::~StrategyTreeTest () [virtual]
Definition at line 31 of file StrategyTreeTest.cc.
{
        // TODO Auto-generated destructor stub
}
Member Function Documentation
void StrategyTreeTest::cleanUpCoordData (const treeNodeMap & currentTreeChildNodes) [virtual]
cleanup the coordinate map and remove data of nodes which are not longer in the branch
Reimplemented from AbstractSendStrategy.
Definition at line 80 of file StrategyTreeTest.cc.
{
        nodeCountMap::const_iterator branchIterator = branchCountMap.begin();
        while(branchIterator != branchCountMap.end()) {
                if(currentTreeChildNodes.find(branchIterator->first) == currentTreeChildNodes.end() && branchIterator->first != thisNode) {
                        branchCountMap.erase(branchIterator);
                }
                branchIterator++;
        }
}
GlobalViewBuilderCall * StrategyTreeTest::getCoordinateMessage () [virtual]
Reimplemented from AbstractSendStrategy.
Definition at line 43 of file StrategyTreeTest.cc.
{
        TreeTestStrategyCall* msg = new TreeTestStrategyCall("TreeTestStrategyCall");
        msg->setNodeCount(getNodeCount());
        msg->setBitLength(TREETESTSTRATEGYCALL_L(msg));
        return msg;
}
std::vector< std::vector< double > > StrategyTreeTest::getGlobalViewData () [virtual]
return the decodes global View Data
Implements AbstractSendStrategy.
Definition at line 113 of file StrategyTreeTest.cc.
{
        std::vector<std::vector<double> > test;
        return test;
}
int StrategyTreeTest::getNodeCount () [protected]
Definition at line 95 of file StrategyTreeTest.cc.
Referenced by getCoordinateMessage(), and getStrategyDataStatus().
{
        int nodeCount = 0;
        nodeCountMap::const_iterator branchCountMapIterator = branchCountMap.begin();
        while(branchCountMapIterator != branchCountMap.end()) {
                nodeCount += branchCountMapIterator->second;
                ++branchCountMapIterator;
        }
        return nodeCount;
}
std::string StrategyTreeTest::getStrategyCombinedParams () [virtual]
return a string of the currently used strategy params
Implements AbstractSendStrategy.
Definition at line 62 of file StrategyTreeTest.cc.
{
        std::stringstream tempStr;
        tempStr << "treeTest";
        return tempStr.str();
}
std::string StrategyTreeTest::getStrategyDataStatus () [virtual]
return a short status of the running send strategy
Reimplemented from AbstractSendStrategy.
Definition at line 53 of file StrategyTreeTest.cc.
{
        std::stringstream tempStr;
        tempStr << "BNC: " << getNodeCount() << " | BC: " << branchCountMap.size();
        return tempStr.str();
}
void StrategyTreeTest::handleCoordinateRpcCall (GlobalViewBuilderCall * globalViewBuilderCall) [virtual]
Reimplemented from AbstractSendStrategy.
Definition at line 35 of file StrategyTreeTest.cc.
{
        TreeTestStrategyCall* treeTestStrategyCall = dynamic_cast<TreeTestStrategyCall*>(globalViewBuilderCall);
        setBranchCount(treeTestStrategyCall->getSrcNode(),treeTestStrategyCall->getNodeCount());
}
void StrategyTreeTest::setBranchCount (const NodeHandle & treeNode, int count) [protected]
Definition at line 70 of file StrategyTreeTest.cc.
Referenced by handleCoordinateRpcCall(), and setMyCoordinates().
{
        if(branchCountMap.find(treeNode) != branchCountMap.end()) {
                branchCountMap.find(treeNode)->second = count;
        } else {
                branchCountMap.insert(branchCount(treeNode, count));
        }
}
void StrategyTreeTest::setMyCoordinates (const AbstractNcsNodeInfo & ncsInfo) [virtual]
Reimplemented from AbstractSendStrategy.
Definition at line 109 of file StrategyTreeTest.cc.
{
        setBranchCount(thisNode, 1);
}
Member Data Documentation
nodeCountMap StrategyTreeTest::branchCountMap [private]
Definition at line 47 of file StrategyTreeTest.h.
Referenced by cleanUpCoordData(), getNodeCount(), getStrategyDataStatus(), and setBranchCount().
The documentation for this class was generated from the following files:
StrategyTreeTest.h
StrategyTreeTest.cc