OverSim: CoordsOfNodeCall Class Reference
CoordsOfNodeCall Class Reference
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
#include <CoordMessages_m.h>
Public Member Functions
CoordsOfNodeCall (const char *name=NULL, int kind=0)
CoordsOfNodeCall (const CoordsOfNodeCall &other)
virtual ~CoordsOfNodeCall ()
CoordsOfNodeCall & operator= (const CoordsOfNodeCall &other)
virtual CoordsOfNodeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const CoordsOfNodeCall &)
Private Member Functions
void copy (const CoordsOfNodeCall &other)
Detailed Description
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
 packet CoordsOfNodeCall extends BaseCallMessage
 {
 }
Definition at line 36 of file CoordMessages_m.h.
Constructor & Destructor Documentation
CoordsOfNodeCall::CoordsOfNodeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
CoordsOfNodeCall::CoordsOfNodeCall (const CoordsOfNodeCall & other)
virtual CoordsOfNodeCall::~CoordsOfNodeCall () [virtual]
Member Function Documentation
void CoordsOfNodeCall::copy (const CoordsOfNodeCall & other) [private]
virtual CoordsOfNodeCall* CoordsOfNodeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 52 of file CoordMessages_m.h.
{return new CoordsOfNodeCall(*this);}
CoordsOfNodeCall& CoordsOfNodeCall::operator= (const CoordsOfNodeCall & other)
bool CoordsOfNodeCall::operator== (const CoordsOfNodeCall &) [protected]
virtual void CoordsOfNodeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void CoordsOfNodeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CoordMessages_m.h