OverSim: GlobalViewBuilderResponse Class Reference
GlobalViewBuilderResponse Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
GlobalViewBuilderResponse (const char *name=NULL, int kind=0)
GlobalViewBuilderResponse (const GlobalViewBuilderResponse &other)
virtual ~GlobalViewBuilderResponse ()
GlobalViewBuilderResponse & operator= (const GlobalViewBuilderResponse &other)
virtual GlobalViewBuilderResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const GlobalViewBuilderResponse &)
Private Member Functions
void copy (const GlobalViewBuilderResponse &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet GlobalViewBuilderResponse extends TreeAppResponse
 {
 }
Definition at line 240 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
GlobalViewBuilderResponse::GlobalViewBuilderResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
GlobalViewBuilderResponse::GlobalViewBuilderResponse (const GlobalViewBuilderResponse & other)
virtual GlobalViewBuilderResponse::~GlobalViewBuilderResponse () [virtual]
Member Function Documentation
void GlobalViewBuilderResponse::copy (const GlobalViewBuilderResponse & other) [private]
virtual GlobalViewBuilderResponse* GlobalViewBuilderResponse::dup () const [inline, virtual]
Reimplemented from TreeAppResponse.
Definition at line 256 of file TreeManagementMessage_m.h.
{return new GlobalViewBuilderResponse(*this);}
GlobalViewBuilderResponse& GlobalViewBuilderResponse::operator= (const GlobalViewBuilderResponse & other)
bool GlobalViewBuilderResponse::operator== (const GlobalViewBuilderResponse &) [protected]
virtual void GlobalViewBuilderResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TreeAppResponse.
Referenced by doPacking().
virtual void GlobalViewBuilderResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TreeAppResponse.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h