OverSim: KbrRpcContext Class Reference
KbrRpcContext Class Reference
Class generated from applications/kbrtestapp/KBRTestMessage.msg by opp_msgc.
#include <KBRTestMessage_m.h>
Public Member Functions
KbrRpcContext ()
KbrRpcContext (const KbrRpcContext &other)
virtual ~KbrRpcContext ()
KbrRpcContext & operator= (const KbrRpcContext &other)
virtual KbrRpcContext * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual TransportAddress & getDestAddr ()
virtual const TransportAddress & getDestAddr () const
virtual void setDestAddr (const TransportAddress &destAddr)
virtual bool getMeasurementPhase () const
virtual void setMeasurementPhase (bool measurementPhase)
Protected Member Functions
bool operator== (const KbrRpcContext &)
Protected Attributes
OverlayKey destKey_var
TransportAddress destAddr_var
bool measurementPhase_var
Private Member Functions
void copy (const KbrRpcContext &other)
Detailed Description
Class generated from applications/kbrtestapp/KBRTestMessage.msg by opp_msgc.
 class KbrRpcContext
 {
     OverlayKey destKey = OverlayKey::UNSPECIFIED_KEY;
     TransportAddress destAddr = TransportAddress::UNSPECIFIED_NODE;
     bool measurementPhase;
 }
Definition at line 233 of file KBRTestMessage_m.h.
Constructor & Destructor Documentation
KbrRpcContext::KbrRpcContext ()
Referenced by dup().
KbrRpcContext::KbrRpcContext (const KbrRpcContext & other)
virtual KbrRpcContext::~KbrRpcContext () [virtual]
Member Function Documentation
void KbrRpcContext::copy (const KbrRpcContext & other) [private]
virtual KbrRpcContext* KbrRpcContext::dup () const [inline, virtual]
Definition at line 252 of file KBRTestMessage_m.h.
{return new KbrRpcContext(*this);}
virtual TransportAddress& KbrRpcContext::getDestAddr () [virtual]
Referenced by KBRTestApp::handleLookupResponse(), and KBRTestApp::handleRpcResponse().
virtual const TransportAddress& KbrRpcContext::getDestAddr () const [inline, virtual]
Definition at line 261 of file KBRTestMessage_m.h.
Referenced by getDestAddr().
{return const_cast<KbrRpcContext*>(this)->getDestAddr();}
virtual OverlayKey& KbrRpcContext::getDestKey () [virtual]
Referenced by KBRTestApp::handleRpcResponse().
virtual const OverlayKey& KbrRpcContext::getDestKey () const [inline, virtual]
Definition at line 258 of file KBRTestMessage_m.h.
Referenced by getDestKey().
{return const_cast<KbrRpcContext*>(this)->getDestKey();}
virtual bool KbrRpcContext::getMeasurementPhase () const [virtual]
Referenced by KBRTestApp::handleLookupResponse(), KBRTestApp::handleRpcResponse(), and KBRTestApp::handleRpcTimeout().
KbrRpcContext& KbrRpcContext::operator= (const KbrRpcContext & other)
bool KbrRpcContext::operator== (const KbrRpcContext &) [protected]
virtual void KbrRpcContext::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void KbrRpcContext::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void KbrRpcContext::setDestAddr (const TransportAddress & destAddr) [virtual]
Referenced by KBRTestApp::handleTimerEvent().
virtual void KbrRpcContext::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by KBRTestApp::handleTimerEvent().
virtual void KbrRpcContext::setMeasurementPhase (bool measurementPhase) [virtual]
Referenced by KBRTestApp::handleTimerEvent().
Member Data Documentation
TransportAddress KbrRpcContext::destAddr_var [protected]
Definition at line 237 of file KBRTestMessage_m.h.
OverlayKey KbrRpcContext::destKey_var [protected]
Definition at line 236 of file KBRTestMessage_m.h.
bool KbrRpcContext::measurementPhase_var [protected]
Definition at line 238 of file KBRTestMessage_m.h.
The documentation for this class was generated from the following file:
KBRTestMessage_m.h