OverSim: ParentRequestResponse Class Reference
ParentRequestResponse Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
ParentRequestResponse (const char *name=NULL, int kind=0)
ParentRequestResponse (const ParentRequestResponse &other)
virtual ~ParentRequestResponse ()
ParentRequestResponse & operator= (const ParentRequestResponse &other)
virtual ParentRequestResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ParentRequestResponse &)
Private Member Functions
void copy (const ParentRequestResponse &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet ParentRequestResponse extends BaseResponseMessage
 {
 }
Definition at line 104 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
ParentRequestResponse::ParentRequestResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
ParentRequestResponse::ParentRequestResponse (const ParentRequestResponse & other)
virtual ParentRequestResponse::~ParentRequestResponse () [virtual]
Member Function Documentation
void ParentRequestResponse::copy (const ParentRequestResponse & other) [private]
virtual ParentRequestResponse* ParentRequestResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 120 of file TreeManagementMessage_m.h.
{return new ParentRequestResponse(*this);}
ParentRequestResponse& ParentRequestResponse::operator= (const ParentRequestResponse & other)
bool ParentRequestResponse::operator== (const ParentRequestResponse &) [protected]
virtual void ParentRequestResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void ParentRequestResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h