OverSim: PubSubMoveListMessage Class Reference
PubSubMoveListMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubMoveListMessage (const char *name=NULL, int kind=0)
PubSubMoveListMessage (const PubSubMoveListMessage &other)
virtual ~PubSubMoveListMessage ()
PubSubMoveListMessage & operator= (const PubSubMoveListMessage &other)
virtual PubSubMoveListMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
virtual void setPlayerArraySize (unsigned int size)
virtual unsigned int getPlayerArraySize () const
virtual NodeHandle & getPlayer (unsigned int k)
virtual const NodeHandle & getPlayer (unsigned int k) const
virtual void setPlayer (unsigned int k, const NodeHandle &player)
virtual void setPositionArraySize (unsigned int size)
virtual unsigned int getPositionArraySize () const
virtual Vector2D & getPosition (unsigned int k)
virtual const Vector2D & getPosition (unsigned int k) const
virtual void setPosition (unsigned int k, const Vector2D &position)
virtual void setPositionAgeArraySize (unsigned int size)
virtual unsigned int getPositionAgeArraySize () const
virtual simtime_t getPositionAge (unsigned int k) const
virtual void setPositionAge (unsigned int k, simtime_t positionAge)
Protected Member Functions
bool operator== (const PubSubMoveListMessage &)
Protected Attributes
int subspaceId_var
simtime_t timestamp_var
NodeHandle * player_var
unsigned int player_arraysize
Vector2D * position_var
unsigned int position_arraysize
simtime_t * positionAge_var
unsigned int positionAge_arraysize
Private Member Functions
void copy (const PubSubMoveListMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubMoveListMessage extends BaseOverlayMessage
 {
         int subspaceId;
         simtime_t timestamp;
         NodeHandle player[];
         Vector2D position[];
         simtime_t positionAge[];
 }
Definition at line 1369 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubMoveListMessage::PubSubMoveListMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubMoveListMessage::PubSubMoveListMessage (const PubSubMoveListMessage & other)
virtual PubSubMoveListMessage::~PubSubMoveListMessage () [virtual]
Member Function Documentation
void PubSubMoveListMessage::copy (const PubSubMoveListMessage & other) [private]
virtual PubSubMoveListMessage* PubSubMoveListMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 1393 of file PubSubMessage_m.h.
Referenced by PubSubMMOG::handleMoveListMessage(), and PubSubMMOG::publishEvents().
{return new PubSubMoveListMessage(*this);}
virtual NodeHandle& PubSubMoveListMessage::getPlayer (unsigned int k) [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
virtual const NodeHandle& PubSubMoveListMessage::getPlayer (unsigned int k) const [inline, virtual]
Definition at line 1405 of file PubSubMessage_m.h.
Referenced by getPlayer().
{return const_cast<PubSubMoveListMessage*>(this)->getPlayer(k);}
virtual unsigned int PubSubMoveListMessage::getPlayerArraySize () const [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
virtual Vector2D& PubSubMoveListMessage::getPosition (unsigned int k) [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
virtual const Vector2D& PubSubMoveListMessage::getPosition (unsigned int k) const [inline, virtual]
Definition at line 1410 of file PubSubMessage_m.h.
Referenced by getPosition().
{return const_cast<PubSubMoveListMessage*>(this)->getPosition(k);}
virtual simtime_t PubSubMoveListMessage::getPositionAge (unsigned int k) const [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
virtual unsigned int PubSubMoveListMessage::getPositionAgeArraySize () const [virtual]
virtual unsigned int PubSubMoveListMessage::getPositionArraySize () const [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
virtual int PubSubMoveListMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
virtual simtime_t PubSubMoveListMessage::getTimestamp () const [virtual]
Referenced by PubSubMMOG::handleMoveListMessage().
PubSubMoveListMessage& PubSubMoveListMessage::operator= (const PubSubMoveListMessage & other)
bool PubSubMoveListMessage::operator== (const PubSubMoveListMessage &) [protected]
virtual void PubSubMoveListMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubMoveListMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubMoveListMessage::setPlayer (unsigned int k, const NodeHandle & player) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setPlayerArraySize (unsigned int size) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setPosition (unsigned int k, const Vector2D & position) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setPositionAge (unsigned int k, simtime_t positionAge) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setPositionAgeArraySize (unsigned int size) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setPositionArraySize (unsigned int size) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::publishEvents().
virtual void PubSubMoveListMessage::setTimestamp (simtime_t timestamp) [virtual]
Referenced by PubSubMMOG::publishEvents().
Member Data Documentation
unsigned int PubSubMoveListMessage::player_arraysize [protected]
Definition at line 1375 of file PubSubMessage_m.h.
NodeHandle* PubSubMoveListMessage::player_var [protected]
Definition at line 1374 of file PubSubMessage_m.h.
unsigned int PubSubMoveListMessage::position_arraysize [protected]
Definition at line 1377 of file PubSubMessage_m.h.
Vector2D* PubSubMoveListMessage::position_var [protected]
Definition at line 1376 of file PubSubMessage_m.h.
unsigned int PubSubMoveListMessage::positionAge_arraysize [protected]
Definition at line 1379 of file PubSubMessage_m.h.
simtime_t* PubSubMoveListMessage::positionAge_var [protected]
Definition at line 1378 of file PubSubMessage_m.h.
int PubSubMoveListMessage::subspaceId_var [protected]
Definition at line 1372 of file PubSubMessage_m.h.
simtime_t PubSubMoveListMessage::timestamp_var [protected]
Definition at line 1373 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h