OverSim: CapReqResponse Class Reference
CapReqResponse Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
CapReqResponse (const char *name=NULL, int kind=0)
CapReqResponse (const CapReqResponse &other)
virtual ~CapReqResponse ()
CapReqResponse & operator= (const CapReqResponse &other)
virtual CapReqResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual AreaDataContainer & getAreaData ()
virtual const AreaDataContainer & getAreaData () const
virtual void setAreaData (const AreaDataContainer &areaData)
Protected Member Functions
bool operator== (const CapReqResponse &)
Protected Attributes
AreaDataContainer areaData_var
Private Member Functions
void copy (const CapReqResponse &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet CapReqResponse extends BaseResponseMessage
 {
     AreaDataContainer areaData;
 }
Definition at line 722 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
CapReqResponse::CapReqResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
CapReqResponse::CapReqResponse (const CapReqResponse & other)
virtual CapReqResponse::~CapReqResponse () [virtual]
Member Function Documentation
void CapReqResponse::copy (const CapReqResponse & other) [private]
virtual CapReqResponse* CapReqResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 739 of file TreeManagementMessage_m.h.
{return new CapReqResponse(*this);}
virtual AreaDataContainer& CapReqResponse::getAreaData () [virtual]
virtual const AreaDataContainer& CapReqResponse::getAreaData () const [inline, virtual]
Definition at line 745 of file TreeManagementMessage_m.h.
Referenced by getAreaData().
{return const_cast<CapReqResponse*>(this)->getAreaData();}
CapReqResponse& CapReqResponse::operator= (const CapReqResponse & other)
bool CapReqResponse::operator== (const CapReqResponse &) [protected]
virtual void CapReqResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void CapReqResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void CapReqResponse::setAreaData (const AreaDataContainer & areaData) [virtual]
Referenced by GlobalViewBuilder::handleCapReqRpcCall().
Member Data Documentation
AreaDataContainer CapReqResponse::areaData_var [protected]
Definition at line 725 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h