OverSim: SendAllStrategyCall Class Reference
SendAllStrategyCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
SendAllStrategyCall (const char *name=NULL, int kind=0)
SendAllStrategyCall (const SendAllStrategyCall &other)
virtual ~SendAllStrategyCall ()
SendAllStrategyCall & operator= (const SendAllStrategyCall &other)
virtual SendAllStrategyCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual CoordDataContainer & getCoordData ()
virtual const CoordDataContainer & getCoordData () const
virtual void setCoordData (const CoordDataContainer &coordData)
Protected Member Functions
bool operator== (const SendAllStrategyCall &)
Protected Attributes
CoordDataContainer coordData_var
Private Member Functions
void copy (const SendAllStrategyCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet SendAllStrategyCall extends GlobalViewBuilderCall
 {
     CoordDataContainer coordData;
 }
Definition at line 454 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
SendAllStrategyCall::SendAllStrategyCall (const char * name = NULL, int kind = 0)
Referenced by dup().
SendAllStrategyCall::SendAllStrategyCall (const SendAllStrategyCall & other)
virtual SendAllStrategyCall::~SendAllStrategyCall () [virtual]
Member Function Documentation
void SendAllStrategyCall::copy (const SendAllStrategyCall & other) [private]
virtual SendAllStrategyCall* SendAllStrategyCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 471 of file TreeManagementMessage_m.h.
{return new SendAllStrategyCall(*this);}
virtual CoordDataContainer& SendAllStrategyCall::getCoordData () [virtual]
Referenced by StrategySendAll::handleCoordinateRpcCall().
virtual const CoordDataContainer& SendAllStrategyCall::getCoordData () const [inline, virtual]
Definition at line 477 of file TreeManagementMessage_m.h.
Referenced by getCoordData().
{return const_cast<SendAllStrategyCall*>(this)->getCoordData();}
SendAllStrategyCall& SendAllStrategyCall::operator= (const SendAllStrategyCall & other)
bool SendAllStrategyCall::operator== (const SendAllStrategyCall &) [protected]
virtual void SendAllStrategyCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void SendAllStrategyCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void SendAllStrategyCall::setCoordData (const CoordDataContainer & coordData) [virtual]
Referenced by StrategyRemoveCoords::getCoordinateMessage(), and StrategySendAll::getCoordinateMessage().
Member Data Documentation
CoordDataContainer SendAllStrategyCall::coordData_var [protected]
Definition at line 457 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h