OverSim: NiceMessage Class Reference
NiceMessage Class Reference
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
#include <NiceMessage_m.h>
Public Member Functions
NiceMessage (const char *name=NULL, int kind=0)
NiceMessage (const NiceMessage &other)
virtual ~NiceMessage ()
NiceMessage & operator= (const NiceMessage &other)
virtual NiceMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCommand () const
virtual void setCommand (int command)
virtual TransportAddress & getSrcNode ()
virtual const TransportAddress & getSrcNode () const
virtual void setSrcNode (const TransportAddress &srcNode)
virtual short getLayer () const
virtual void setLayer (short layer)
Protected Member Functions
bool operator== (const NiceMessage &)
Protected Attributes
int command_var
TransportAddress srcNode_var
short layer_var
Private Member Functions
void copy (const NiceMessage &other)
Detailed Description
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
 message NiceMessage extends BaseOverlayMessage
 {
     int command enum(NICECommand);
     TransportAddress srcNode;
     short layer;
 }
Definition at line 98 of file NiceMessage_m.h.
Constructor & Destructor Documentation
NiceMessage::NiceMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NiceMessage::NiceMessage (const NiceMessage & other)
virtual NiceMessage::~NiceMessage () [virtual]
Member Function Documentation
void NiceMessage::copy (const NiceMessage & other) [private]
virtual NiceMessage* NiceMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in NiceMulticastMessage, NiceLeaderHeartbeat, NiceHeartbeat, NiceClusterMerge, and NiceMemberMessage.
Definition at line 117 of file NiceMessage_m.h.
Referenced by oversim::Nice::handleNiceJoinCluster(), oversim::Nice::handleNiceQuery(), oversim::Nice::handleNiceQueryResponse(), oversim::Nice::handleNiceRemove(), and oversim::Nice::sendHeartbeats().
{return new NiceMessage(*this);}
virtual int NiceMessage::getCommand () const [virtual]
Referenced by oversim::Nice::handleUDPMessage().
virtual short NiceMessage::getLayer () const [virtual]
Referenced by oversim::Nice::checkLeaderHeartbeatsForCollisions(), oversim::Nice::handleNiceClusterMergeRequest(), oversim::Nice::handleNiceForceMerge(), oversim::Nice::handleNiceJoinCluster(), oversim::Nice::handleNiceJoineval(), oversim::Nice::handleNiceJoinevalResponse(), oversim::Nice::handleNiceLeaderHeartbeat(), oversim::Nice::handleNiceLeaderTransfer(), oversim::Nice::handleNicePingProbe(), oversim::Nice::handleNicePingProbeResponse(), oversim::Nice::handleNiceQuery(), oversim::Nice::handleNiceQueryResponse(), oversim::Nice::handleNiceRemove(), and oversim::Nice::sendDataToOverlay().
virtual TransportAddress& NiceMessage::getSrcNode () [virtual]
Referenced by oversim::Nice::checkLeaderHeartbeatsForCollisions(), oversim::Nice::handleNiceClusterMergeRequest(), oversim::Nice::handleNiceForceMerge(), oversim::Nice::handleNiceHeartbeat(), oversim::Nice::handleNiceJoinCluster(), oversim::Nice::handleNiceJoineval(), oversim::Nice::handleNiceJoinevalResponse(), oversim::Nice::handleNiceLeaderHeartbeat(), oversim::Nice::handleNiceLeaderTransfer(), oversim::Nice::handleNiceMulticast(), oversim::Nice::handleNicePeerTemporary(), oversim::Nice::handleNicePeerTemporaryRelease(), oversim::Nice::handleNicePingProbe(), oversim::Nice::handleNicePingProbeResponse(), oversim::Nice::handleNicePollRp(), oversim::Nice::handleNiceQuery(), oversim::Nice::handleNiceQueryResponse(), oversim::Nice::handleNiceRemove(), oversim::Nice::handleUDPMessage(), and oversim::Nice::sendDataToOverlay().
virtual const TransportAddress& NiceMessage::getSrcNode () const [inline, virtual]
Definition at line 125 of file NiceMessage_m.h.
Referenced by getSrcNode().
{return const_cast<NiceMessage*>(this)->getSrcNode();}
NiceMessage& NiceMessage::operator= (const NiceMessage & other)
bool NiceMessage::operator== (const NiceMessage &) [protected]
virtual void NiceMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in NiceMulticastMessage, NiceLeaderHeartbeat, NiceHeartbeat, NiceClusterMerge, and NiceMemberMessage.
Referenced by doPacking().
virtual void NiceMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in NiceMulticastMessage, NiceLeaderHeartbeat, NiceHeartbeat, NiceClusterMerge, and NiceMemberMessage.
Referenced by doUnpacking().
virtual void NiceMessage::setCommand (int command) [virtual]
Referenced by oversim::Nice::BasicJoinLayer(), oversim::Nice::checkLeaderHeartbeatsForCollisions(), oversim::Nice::ClusterMergeRequest(), oversim::Nice::handleAppMessage(), oversim::Nice::handleNiceJoineval(), oversim::Nice::handleNicePingProbe(), oversim::Nice::handleNicePollRp(), oversim::Nice::handleNiceQuery(), oversim::Nice::handleNiceQueryResponse(), oversim::Nice::JoinCluster(), oversim::Nice::LeaderTransfer(), oversim::Nice::pollRP(), oversim::Nice::Query(), oversim::Nice::Remove(), oversim::Nice::sendHeartbeats(), oversim::Nice::sendHeartbeatTo(), and oversim::Nice::sendRemoveTo().
virtual void NiceMessage::setLayer (short layer) [virtual]
Referenced by oversim::Nice::BasicJoinLayer(), oversim::Nice::checkLeaderHeartbeatsForCollisions(), oversim::Nice::ClusterMergeRequest(), oversim::Nice::handleAppMessage(), oversim::Nice::handleNiceJoineval(), oversim::Nice::handleNicePingProbe(), oversim::Nice::handleNicePollRp(), oversim::Nice::handleNiceQuery(), oversim::Nice::handleNiceQueryResponse(), oversim::Nice::JoinCluster(), oversim::Nice::LeaderTransfer(), oversim::Nice::pollRP(), oversim::Nice::Query(), oversim::Nice::Remove(), oversim::Nice::sendDataToOverlay(), oversim::Nice::sendHeartbeats(), oversim::Nice::sendHeartbeatTo(), and oversim::Nice::sendRemoveTo().
virtual void NiceMessage::setSrcNode (const TransportAddress & srcNode) [virtual]
Referenced by oversim::Nice::BasicJoinLayer(), oversim::Nice::checkLeaderHeartbeatsForCollisions(), oversim::Nice::ClusterMergeRequest(), oversim::Nice::handleAppMessage(), oversim::Nice::handleNiceJoineval(), oversim::Nice::handleNicePingProbe(), oversim::Nice::handleNicePollRp(), oversim::Nice::handleNiceQuery(), oversim::Nice::handleNiceQueryResponse(), oversim::Nice::JoinCluster(), oversim::Nice::LeaderTransfer(), oversim::Nice::pollRP(), oversim::Nice::Query(), oversim::Nice::Remove(), oversim::Nice::sendDataToOverlay(), oversim::Nice::sendHeartbeats(), oversim::Nice::sendHeartbeatTo(), and oversim::Nice::sendRemoveTo().
Member Data Documentation
int NiceMessage::command_var [protected]
Definition at line 101 of file NiceMessage_m.h.
short NiceMessage::layer_var [protected]
Definition at line 103 of file NiceMessage_m.h.
TransportAddress NiceMessage::srcNode_var [protected]
Definition at line 102 of file NiceMessage_m.h.
The documentation for this class was generated from the following file:
NiceMessage_m.h