OverSim: I3Message Class Reference
I3Message Class Reference
Class generated from applications/i3/I3Message.msg by opp_msgc.
#include <I3Message_m.h>
Public Member Functions
I3Message (const char *name=NULL, int kind=0)
I3Message (const I3Message &other)
virtual ~I3Message ()
I3Message & operator= (const I3Message &other)
virtual I3Message * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type)
Protected Member Functions
bool operator== (const I3Message &)
Protected Attributes
int type_var
Private Member Functions
void copy (const I3Message &other)
Detailed Description
Class generated from applications/i3/I3Message.msg by opp_msgc.
 packet I3Message
 {
         int type enum(I3MessageType);
 }
Definition at line 62 of file I3Message_m.h.
Constructor & Destructor Documentation
I3Message::I3Message (const char * name = NULL, int kind = 0)
Referenced by dup().
I3Message::I3Message (const I3Message & other)
virtual I3Message::~I3Message () [virtual]
Member Function Documentation
void I3Message::copy (const I3Message & other) [private]
virtual I3Message* I3Message::dup () const [inline, virtual]
Reimplemented in I3SendPacketMessage_Base, I3RemoveTriggerMessage_Base, I3QueryReplyMessage_Base, I3InsertTriggerMessage_Base, I3QueryReplyMessage, I3SendPacketMessage, I3RemoveTriggerMessage, and I3InsertTriggerMessage.
Definition at line 79 of file I3Message_m.h.
{return new I3Message(*this);}
virtual int I3Message::getType () const [virtual]
Referenced by I3::deliver(), I3::handleUDPMessage(), and I3BaseApp::handleUDPMessage().
I3Message& I3Message::operator= (const I3Message & other)
bool I3Message::operator== (const I3Message &) [protected]
virtual void I3Message::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in I3SendPacketMessage_Base, I3RemoveTriggerMessage_Base, I3QueryReplyMessage_Base, and I3InsertTriggerMessage_Base.
Referenced by doPacking().
virtual void I3Message::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in I3SendPacketMessage_Base, I3RemoveTriggerMessage_Base, I3QueryReplyMessage_Base, and I3InsertTriggerMessage_Base.
Referenced by doUnpacking().
virtual void I3Message::setType (int type) [virtual]
Referenced by I3InsertTriggerMessage::I3InsertTriggerMessage(), I3QueryReplyMessage::I3QueryReplyMessage(), I3RemoveTriggerMessage::I3RemoveTriggerMessage(), and I3SendPacketMessage::I3SendPacketMessage().
Member Data Documentation
int I3Message::type_var [protected]
Definition at line 65 of file I3Message_m.h.
The documentation for this class was generated from the following file:
I3Message_m.h