OverSim: SCSnowTimer Class Reference
SCSnowTimer Class Reference
Class generated from applications/simplegameclient/SimpleGameClient.msg by opp_msgc.
#include <SimpleGameClient_m.h>
Public Member Functions
SCSnowTimer (const char *name=NULL, int kind=0)
SCSnowTimer (const SCSnowTimer &other)
virtual ~SCSnowTimer ()
SCSnowTimer & operator= (const SCSnowTimer &other)
virtual SCSnowTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
virtual unsigned int getIp () const
virtual void setIp (unsigned int ip)
Protected Member Functions
bool operator== (const SCSnowTimer &)
Protected Attributes
Vector2D position_var
unsigned int ip_var
Private Member Functions
void copy (const SCSnowTimer &other)
Detailed Description
Class generated from applications/simplegameclient/SimpleGameClient.msg by opp_msgc.
 message SCSnowTimer
 {
         Vector2D position;
         unsigned int ip;
 }
Definition at line 34 of file SimpleGameClient_m.h.
Constructor & Destructor Documentation
SCSnowTimer::SCSnowTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
SCSnowTimer::SCSnowTimer (const SCSnowTimer & other)
virtual SCSnowTimer::~SCSnowTimer () [virtual]
Member Function Documentation
void SCSnowTimer::copy (const SCSnowTimer & other) [private]
virtual SCSnowTimer* SCSnowTimer::dup () const [inline, virtual]
Definition at line 52 of file SimpleGameClient_m.h.
{return new SCSnowTimer(*this);}
virtual unsigned int SCSnowTimer::getIp () const [virtual]
Referenced by SimpleGameClient::handleTimerEvent().
virtual Vector2D& SCSnowTimer::getPosition () [virtual]
Referenced by SimpleGameClient::handleTimerEvent().
virtual const Vector2D& SCSnowTimer::getPosition () const [inline, virtual]
Definition at line 58 of file SimpleGameClient_m.h.
Referenced by getPosition().
{return const_cast<SCSnowTimer*>(this)->getPosition();}
SCSnowTimer& SCSnowTimer::operator= (const SCSnowTimer & other)
bool SCSnowTimer::operator== (const SCSnowTimer &) [protected]
virtual void SCSnowTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SCSnowTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SCSnowTimer::setIp (unsigned int ip) [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual void SCSnowTimer::setPosition (const Vector2D & position) [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
Member Data Documentation
unsigned int SCSnowTimer::ip_var [protected]
Definition at line 38 of file SimpleGameClient_m.h.
Vector2D SCSnowTimer::position_var [protected]
Definition at line 37 of file SimpleGameClient_m.h.
The documentation for this class was generated from the following file:
SimpleGameClient_m.h