OverSim: ScribeTimer Class Reference
ScribeTimer Class Reference
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
#include <ScribeMessage_m.h>
Public Member Functions
ScribeTimer (const char *name=NULL, int kind=0)
ScribeTimer (const ScribeTimer &other)
virtual ~ScribeTimer ()
ScribeTimer & operator= (const ScribeTimer &other)
virtual ScribeTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getTimerType () const
virtual void setTimerType (int timerType)
virtual NodeHandle & getChild ()
virtual const NodeHandle & getChild () const
virtual void setChild (const NodeHandle &child)
virtual OverlayKey & getGroup ()
virtual const OverlayKey & getGroup () const
virtual void setGroup (const OverlayKey &group)
Protected Member Functions
bool operator== (const ScribeTimer &)
Protected Attributes
int timerType_var
NodeHandle child_var
OverlayKey group_var
Private Member Functions
void copy (const ScribeTimer &other)
Detailed Description
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
 message ScribeTimer
 {
         int timerType enum(ScribeTimerType);
         NodeHandle child;
         OverlayKey group;
 }
Definition at line 323 of file ScribeMessage_m.h.
Constructor & Destructor Documentation
ScribeTimer::ScribeTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
ScribeTimer::ScribeTimer (const ScribeTimer & other)
virtual ScribeTimer::~ScribeTimer () [virtual]
Member Function Documentation
void ScribeTimer::copy (const ScribeTimer & other) [private]
virtual ScribeTimer* ScribeTimer::dup () const [inline, virtual]
Definition at line 342 of file ScribeMessage_m.h.
{return new ScribeTimer(*this);}
virtual NodeHandle& ScribeTimer::getChild () [virtual]
Referenced by Scribe::removeChildFromGroup().
virtual const NodeHandle& ScribeTimer::getChild () const [inline, virtual]
Definition at line 350 of file ScribeMessage_m.h.
Referenced by getChild().
{return const_cast<ScribeTimer*>(this)->getChild();}
virtual OverlayKey& ScribeTimer::getGroup () [virtual]
Referenced by Scribe::handleTimerEvent(), and Scribe::removeChildFromGroup().
virtual const OverlayKey& ScribeTimer::getGroup () const [inline, virtual]
Definition at line 353 of file ScribeMessage_m.h.
Referenced by getGroup().
{return const_cast<ScribeTimer*>(this)->getGroup();}
virtual int ScribeTimer::getTimerType () const [virtual]
Referenced by Scribe::handleTimerEvent(), and Scribe::startTimer().
ScribeTimer& ScribeTimer::operator= (const ScribeTimer & other)
bool ScribeTimer::operator== (const ScribeTimer &) [protected]
virtual void ScribeTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ScribeTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ScribeTimer::setChild (const NodeHandle & child) [virtual]
Referenced by Scribe::addChildToGroup().
virtual void ScribeTimer::setGroup (const OverlayKey & group) [virtual]
Referenced by Scribe::addChildToGroup(), Scribe::handleJoinMessage(), and Scribe::handleJoinResponse().
virtual void ScribeTimer::setTimerType (int timerType) [virtual]
Referenced by Scribe::addChildToGroup(), Scribe::handleJoinMessage(), and Scribe::handleJoinResponse().
Member Data Documentation
NodeHandle ScribeTimer::child_var [protected]
Definition at line 327 of file ScribeMessage_m.h.
OverlayKey ScribeTimer::group_var [protected]
Definition at line 328 of file ScribeMessage_m.h.
int ScribeTimer::timerType_var [protected]
Definition at line 326 of file ScribeMessage_m.h.
The documentation for this class was generated from the following file:
ScribeMessage_m.h