OverSim: XmlRpc::XmlRpcLogHandler Class Reference
XmlRpc::XmlRpcLogHandler Class Reference
An interface allowing custom handling of informational message reporting.
#include <XmlRpc.h>
Public Member Functions
virtual ~XmlRpcLogHandler ()
virtual void log (int level, const char *msg)=0
Output a message. Custom error handlers should define this method.
Static Public Member Functions
static XmlRpcLogHandler * getLogHandler ()
Returns a pointer to the currently installed message reporting object.
static void setLogHandler (XmlRpcLogHandler *lh)
Specifies the message handler.
static int getVerbosity ()
Returns the level of verbosity of informational messages. 0 is no output, 5 is very verbose.
static void setVerbosity (int v)
Specify the level of verbosity of informational messages. 0 is no output, 5 is very verbose.
Static Protected Attributes
static XmlRpcLogHandler * _logHandler = &defaultLogHandler
static int _verbosity = 0
Detailed Description
An interface allowing custom handling of informational message reporting.
Definition at line 67 of file XmlRpc.h.
Constructor & Destructor Documentation
virtual XmlRpc::XmlRpcLogHandler::~XmlRpcLogHandler () [inline, virtual]
Definition at line 69 of file XmlRpc.h.
{};
Member Function Documentation
static XmlRpcLogHandler* XmlRpc::XmlRpcLogHandler::getLogHandler () [inline, static]
Returns a pointer to the currently installed message reporting object.
Definition at line 72 of file XmlRpc.h.
Referenced by XmlRpc::XmlRpcUtil::log().
    { return _logHandler; }
static int XmlRpc::XmlRpcLogHandler::getVerbosity () [inline, static]
Returns the level of verbosity of informational messages. 0 is no output, 5 is very verbose.
Definition at line 80 of file XmlRpc.h.
Referenced by XmlRpc::getVerbosity(), and XmlRpc::XmlRpcUtil::log().
    { return _verbosity; }
virtual void XmlRpc::XmlRpcLogHandler::log (int level, const char * msg) [pure virtual]
Output a message. Custom error handlers should define this method.
Implemented in DefaultLogHandler.
Referenced by XmlRpc::XmlRpcUtil::log().
static void XmlRpc::XmlRpcLogHandler::setLogHandler (XmlRpcLogHandler * lh) [inline, static]
Specifies the message handler.
Definition at line 76 of file XmlRpc.h.
    { _logHandler = lh; }
static void XmlRpc::XmlRpcLogHandler::setVerbosity (int v) [inline, static]
Specify the level of verbosity of informational messages. 0 is no output, 5 is very verbose.
Definition at line 84 of file XmlRpc.h.
Referenced by XmlRpc::setVerbosity().
    { _verbosity = v; }
Member Data Documentation
XmlRpcLogHandler * XmlRpcLogHandler::_logHandler = &defaultLogHandler [static, protected]
Definition at line 91 of file XmlRpc.h.
Referenced by getLogHandler(), and setLogHandler().
int XmlRpcLogHandler::_verbosity = 0 [static, protected]
Definition at line 92 of file XmlRpc.h.
Referenced by getVerbosity(), and setVerbosity().
The documentation for this class was generated from the following files:
XmlRpc.h
XmlRpcUtil.cc