OverSim: StrategyRemoveCoords Class Reference
StrategyRemoveCoords Class Reference
#include <StrategyRemoveCoords.h>
Public Member Functions
StrategyRemoveCoords ()
virtual ~StrategyRemoveCoords ()
virtual GlobalViewBuilderCall * getCoordinateMessage ()
virtual std::string getStrategyCombinedParams ()
return a string of the currently used strategy params
Protected Member Functions
void processCoordinates (coordinatesVector *coords)
void removeCoordinatesByPercentage (coordinatesVector *coords, int percentage)
void removeCoordinatesByCoordLimit (coordinatesVector *coords, int coordLimit)
void removeCoordinatesByTrafficLimit (coordinatesVector *coords, int trafficLimit)
virtual void removeCoordinates (coordinatesVector *coords, int entrysToRemove)
Detailed Description
Definition at line 15 of file StrategyRemoveCoords.h.
Constructor & Destructor Documentation
StrategyRemoveCoords::StrategyRemoveCoords ()
Definition at line 11 of file StrategyRemoveCoords.cc.
{
        lastSendCount = 0;
}
StrategyRemoveCoords::~StrategyRemoveCoords () [virtual]
Definition at line 15 of file StrategyRemoveCoords.cc.
{
        // TODO Auto-generated destructor stub
}
Member Function Documentation
GlobalViewBuilderCall * StrategyRemoveCoords::getCoordinateMessage () [virtual]
Reimplemented from StrategySendAll.
Definition at line 19 of file StrategyRemoveCoords.cc.
{
        SendAllStrategyCall* msg = new SendAllStrategyCall("sendAllStrategyCall");
        CoordDataContainer tmpCoordContainer;
        coordinatesVector sendCoordsVector = getCombinedCoordsVector();
        processCoordinates(&sendCoordsVector);
        tmpCoordContainer.coordinatesVector = sendCoordsVector;
        lastSendCount = tmpCoordContainer.coordinatesVector.size();
        msg->setCoordData(tmpCoordContainer);
        msg->setBitLength(REMOVERANDOMSTRATEGYCALL_L(msg));
        return msg;
}
std::string StrategyRemoveCoords::getStrategyCombinedParams () [virtual]
return a string of the currently used strategy params
Reimplemented from StrategySendAll.
Definition at line 81 of file StrategyRemoveCoords.cc.
{
        std::string strategyMode = globalViewBuilder->parProxy("gvbStrategyRemoveCoordsMode").stdstringValue();
        std::stringstream tempStr;
        tempStr << globalViewBuilder->parProxy("gvbSendStrategy").stdstringValue();
        tempStr << "/";
        tempStr << strategyMode;
        tempStr << "/";
        if(strategyMode == "limitCoords") {
                tempStr << globalViewBuilder->parProxy("gvbStrategyRemoveCoordsCoordsLimit").longValue();
        } else if (strategyMode == "limitTraffic") {
                tempStr << globalViewBuilder->parProxy("gvbStrategyRemoveCoordsTrafficLimit").longValue();
        } else if (strategyMode == "percentage") {
                tempStr << globalViewBuilder->parProxy("gvbStrategyRemoveCoordsPercentage").longValue();
        }
        return tempStr.str();
}
void StrategyRemoveCoords::processCoordinates (coordinatesVector * coords) [protected]
Definition at line 39 of file StrategyRemoveCoords.cc.
Referenced by getCoordinateMessage().
{
        std::string strategyMode = globalViewBuilder->parProxy("gvbStrategyRemoveCoordsMode").stdstringValue();
        if(strategyMode == "limitCoords") {
                int coordLimit = globalViewBuilder->parProxy("gvbStrategyRemoveCoordsCoordsLimit");
                removeCoordinatesByCoordLimit(coords, coordLimit);
        } else if (strategyMode == "limitTraffic") {
                int trafficLimit = globalViewBuilder->parProxy("gvbStrategyRemoveCoordsTrafficLimit");
                removeCoordinatesByTrafficLimit(coords, trafficLimit);
        } else if (strategyMode == "percentage") {
                int percentage = globalViewBuilder->parProxy("gvbStrategyRemoveCoordsPercentage");
                removeCoordinatesByPercentage(coords, percentage);
        } else if (strategyMode == "") {
                throw cRuntimeError("StrategyRemoveCoordinates::processCoordinates(): No Strategy Mode given.");
        } else {
                throw cRuntimeError("StrategyRemoveCoordinates::processCoordinates(): Unknown Strategy Mode given.");
        }
}
void StrategyRemoveCoords::removeCoordinates (coordinatesVector * coords, int entrysToRemove) [protected, virtual]
Reimplemented in StrategyRemoveInaccurate, and StrategyRemoveRandom.
Definition at line 62 of file StrategyRemoveCoords.cc.
Referenced by removeCoordinatesByCoordLimit(), and removeCoordinatesByPercentage().
{
        throw cRuntimeError("StrategyRemoveCoordinates::processCoordinates(): Choice Strategy not implemented.");
}
void StrategyRemoveCoords::removeCoordinatesByCoordLimit (coordinatesVector * coords, int coordLimit) [protected]
Definition at line 71 of file StrategyRemoveCoords.cc.
Referenced by processCoordinates(), and removeCoordinatesByTrafficLimit().
{
        int entrysToRemove = coords->size() - coordLimit;
        removeCoordinates(coords, entrysToRemove);
}
void StrategyRemoveCoords::removeCoordinatesByPercentage (coordinatesVector * coords, int percentage) [protected]
Definition at line 66 of file StrategyRemoveCoords.cc.
Referenced by processCoordinates().
{
        int entrysToRemove = static_cast<int>(coords->size() * (percentage / 100));
        removeCoordinates(coords, entrysToRemove);
}
void StrategyRemoveCoords::removeCoordinatesByTrafficLimit (coordinatesVector * coords, int trafficLimit) [protected]
Definition at line 76 of file StrategyRemoveCoords.cc.
Referenced by processCoordinates().
{
        int coordLimit = (int)(trafficLimit / getSizeOfSingleCoordinate(*coords));
        removeCoordinatesByCoordLimit(coords, coordLimit);
}
The documentation for this class was generated from the following files:
StrategyRemoveCoords.h
StrategyRemoveCoords.cc