OverSim: ALMSubscribeMessage Class Reference
ALMSubscribeMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
ALMSubscribeMessage (const char *name=NULL, int kind=0)
ALMSubscribeMessage (const ALMSubscribeMessage &other)
virtual ~ALMSubscribeMessage ()
ALMSubscribeMessage & operator= (const ALMSubscribeMessage &other)
virtual ALMSubscribeMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ALMSubscribeMessage &)
Private Member Functions
void copy (const ALMSubscribeMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet ALMSubscribeMessage extends ALMMessage
 {
 }
Definition at line 2203 of file CommonMessages_m.h.
Constructor & Destructor Documentation
ALMSubscribeMessage::ALMSubscribeMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMSubscribeMessage::ALMSubscribeMessage (const ALMSubscribeMessage & other)
virtual ALMSubscribeMessage::~ALMSubscribeMessage () [virtual]
Member Function Documentation
void ALMSubscribeMessage::copy (const ALMSubscribeMessage & other) [private]
virtual ALMSubscribeMessage* ALMSubscribeMessage::dup () const [inline, virtual]
Reimplemented from ALMMessage.
Definition at line 2219 of file CommonMessages_m.h.
{return new ALMSubscribeMessage(*this);}
ALMSubscribeMessage& ALMSubscribeMessage::operator= (const ALMSubscribeMessage & other)
bool ALMSubscribeMessage::operator== (const ALMSubscribeMessage &) [protected]
virtual void ALMSubscribeMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doPacking().
virtual void ALMSubscribeMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h