OverSim: BaseRouteMessage Class Reference
BaseRouteMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BaseRouteMessage (const char *name=NULL, int kind=0)
BaseRouteMessage (const BaseRouteMessage &other)
virtual ~BaseRouteMessage ()
BaseRouteMessage & operator= (const BaseRouteMessage &other)
virtual BaseRouteMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual NodeHandle & getSrcNode ()
virtual const NodeHandle & getSrcNode () const
virtual void setSrcNode (const NodeHandle &srcNode)
virtual int getRoutingType () const
virtual void setRoutingType (int routingType)
virtual int getHopCount () const
virtual void setHopCount (int hopCount)
virtual void setVisitedHopsArraySize (unsigned int size)
virtual unsigned int getVisitedHopsArraySize () const
virtual TransportAddress & getVisitedHops (unsigned int k)
virtual const TransportAddress & getVisitedHops (unsigned int k) const
virtual void setVisitedHops (unsigned int k, const TransportAddress &visitedHops)
virtual void setNextHopsArraySize (unsigned int size)
virtual unsigned int getNextHopsArraySize () const
virtual TransportAddress & getNextHops (unsigned int k)
virtual const TransportAddress & getNextHops (unsigned int k) const
virtual void setNextHops (unsigned int k, const TransportAddress &nextHops)
virtual simtime_t getHopStamp () const
virtual void setHopStamp (simtime_t hopStamp)
virtual void setHopDelayArraySize (unsigned int size)
virtual unsigned int getHopDelayArraySize () const
virtual simtime_t getHopDelay (unsigned int k) const
virtual void setHopDelay (unsigned int k, simtime_t hopDelay)
Protected Member Functions
bool operator== (const BaseRouteMessage &)
Protected Attributes
OverlayKey destKey_var
NodeHandle srcNode_var
int routingType_var
int hopCount_var
TransportAddress * visitedHops_var
unsigned int visitedHops_arraysize
TransportAddress * nextHops_var
unsigned int nextHops_arraysize
simtime_t hopStamp_var
simtime_t * hopDelay_var
unsigned int hopDelay_arraysize
Private Member Functions
void copy (const BaseRouteMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet BaseRouteMessage extends BaseOverlayMessage
 {
     OverlayKey destKey;
     NodeHandle srcNode;
     int routingType enum(RoutingType);
     int hopCount = 0;
     TransportAddress visitedHops[];
     TransportAddress nextHops[];
     simtime_t hopStamp;
     simtime_t hopDelay[];
 }
Definition at line 358 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BaseRouteMessage::BaseRouteMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BaseRouteMessage::BaseRouteMessage (const BaseRouteMessage & other)
virtual BaseRouteMessage::~BaseRouteMessage () [virtual]
Member Function Documentation
void BaseRouteMessage::copy (const BaseRouteMessage & other) [private]
virtual BaseRouteMessage* BaseRouteMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 385 of file CommonMessages_m.h.
Referenced by SendToKeyListener::lookupFinished().
{return new BaseRouteMessage(*this);}
virtual OverlayKey& BaseRouteMessage::getDestKey () [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), BaseOverlay::nextHopRpc(), Kademlia::recursiveRoutingHook(), and BaseOverlay::sendToKey().
virtual const OverlayKey& BaseRouteMessage::getDestKey () const [inline, virtual]
Definition at line 391 of file CommonMessages_m.h.
Referenced by getDestKey().
{return const_cast<BaseRouteMessage*>(this)->getDestKey();}
virtual int BaseRouteMessage::getHopCount () const [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), SendToKeyListener::lookupFinished(), BaseOverlay::nextHopRpc(), BaseOverlay::sendRouteMessage(), and BaseOverlay::sendToKey().
virtual simtime_t BaseRouteMessage::getHopDelay (unsigned int k) const [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual unsigned int BaseRouteMessage::getHopDelayArraySize () const [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual simtime_t BaseRouteMessage::getHopStamp () const [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual TransportAddress& BaseRouteMessage::getNextHops (unsigned int k) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), and BaseOverlay::internalHandleRpcTimeout().
virtual const TransportAddress& BaseRouteMessage::getNextHops (unsigned int k) const [inline, virtual]
Definition at line 408 of file CommonMessages_m.h.
Referenced by getNextHops().
{return const_cast<BaseRouteMessage*>(this)->getNextHops(k);}
virtual unsigned int BaseRouteMessage::getNextHopsArraySize () const [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), and BaseOverlay::sendToKey().
virtual int BaseRouteMessage::getRoutingType () const [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), BaseOverlay::nextHopRpc(), and BaseOverlay::sendToKey().
virtual NodeHandle& BaseRouteMessage::getSrcNode () [virtual]
Referenced by BaseOverlay::callForward(), BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), BaseOverlay::nextHopRpc(), Kademlia::recursiveRoutingHook(), and BaseOverlay::sendToKey().
virtual const NodeHandle& BaseRouteMessage::getSrcNode () const [inline, virtual]
Definition at line 394 of file CommonMessages_m.h.
Referenced by getSrcNode().
{return const_cast<BaseRouteMessage*>(this)->getSrcNode();}
virtual TransportAddress& BaseRouteMessage::getVisitedHops (unsigned int k) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), Kademlia::recursiveRoutingHook(), and BaseOverlay::sendToKey().
virtual const TransportAddress& BaseRouteMessage::getVisitedHops (unsigned int k) const [inline, virtual]
Definition at line 403 of file CommonMessages_m.h.
Referenced by getVisitedHops().
{return const_cast<BaseRouteMessage*>(this)->getVisitedHops(k);}
virtual unsigned int BaseRouteMessage::getVisitedHopsArraySize () const [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), Kademlia::recursiveRoutingHook(), and BaseOverlay::sendToKey().
BaseRouteMessage& BaseRouteMessage::operator= (const BaseRouteMessage & other)
bool BaseRouteMessage::operator== (const BaseRouteMessage &) [protected]
virtual void BaseRouteMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void BaseRouteMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void BaseRouteMessage::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by BaseOverlay::handleMessage().
virtual void BaseRouteMessage::setHopCount (int hopCount) [virtual]
Referenced by BaseOverlay::handleMessage(), SendToKeyListener::lookupFinished(), and BaseOverlay::sendRouteMessage().
virtual void BaseRouteMessage::setHopDelay (unsigned int k, simtime_t hopDelay) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual void BaseRouteMessage::setHopDelayArraySize (unsigned int size) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual void BaseRouteMessage::setHopStamp (simtime_t hopStamp) [virtual]
Referenced by BaseOverlay::sendToKey().
virtual void BaseRouteMessage::setNextHops (unsigned int k, const TransportAddress & nextHops) [virtual]
Referenced by BaseOverlay::internalHandleRpcTimeout(), and BaseOverlay::sendToKey().
virtual void BaseRouteMessage::setNextHopsArraySize (unsigned int size) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage(), BaseOverlay::internalHandleRpcTimeout(), and BaseOverlay::sendToKey().
virtual void BaseRouteMessage::setRoutingType (int routingType) [virtual]
Referenced by BaseOverlay::handleMessage().
virtual void BaseRouteMessage::setSrcNode (const NodeHandle & srcNode) [virtual]
Referenced by BaseOverlay::handleMessage().
virtual void BaseRouteMessage::setVisitedHops (unsigned int k, const TransportAddress & visitedHops) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
virtual void BaseRouteMessage::setVisitedHopsArraySize (unsigned int size) [virtual]
Referenced by BaseOverlay::handleBaseOverlayMessage().
Member Data Documentation
OverlayKey BaseRouteMessage::destKey_var [protected]
Definition at line 361 of file CommonMessages_m.h.
int BaseRouteMessage::hopCount_var [protected]
Definition at line 364 of file CommonMessages_m.h.
unsigned int BaseRouteMessage::hopDelay_arraysize [protected]
Definition at line 371 of file CommonMessages_m.h.
simtime_t* BaseRouteMessage::hopDelay_var [protected]
Definition at line 370 of file CommonMessages_m.h.
simtime_t BaseRouteMessage::hopStamp_var [protected]
Definition at line 369 of file CommonMessages_m.h.
unsigned int BaseRouteMessage::nextHops_arraysize [protected]
Definition at line 368 of file CommonMessages_m.h.
TransportAddress* BaseRouteMessage::nextHops_var [protected]
Definition at line 367 of file CommonMessages_m.h.
int BaseRouteMessage::routingType_var [protected]
Definition at line 363 of file CommonMessages_m.h.
NodeHandle BaseRouteMessage::srcNode_var [protected]
Definition at line 362 of file CommonMessages_m.h.
unsigned int BaseRouteMessage::visitedHops_arraysize [protected]
Definition at line 366 of file CommonMessages_m.h.
TransportAddress* BaseRouteMessage::visitedHops_var [protected]
Definition at line 365 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h