OverSim: CBRDHTGetResponse Class Reference
CBRDHTGetResponse Class Reference
Class generated from common/cbr/CBR-DHTMessage.msg by opp_msgc.
#include <CBR-DHTMessage_m.h>
Public Member Functions
CBRDHTGetResponse (const char *name=NULL, int kind=0)
CBRDHTGetResponse (const CBRDHTGetResponse &other)
virtual ~CBRDHTGetResponse ()
CBRDHTGetResponse & operator= (const CBRDHTGetResponse &other)
virtual CBRDHTGetResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getOriginalKey ()
virtual const OverlayKey & getOriginalKey () const
virtual void setOriginalKey (const OverlayKey &originalKey)
Protected Member Functions
bool operator== (const CBRDHTGetResponse &)
Protected Attributes
OverlayKey originalKey_var
Private Member Functions
void copy (const CBRDHTGetResponse &other)
Detailed Description
Class generated from common/cbr/CBR-DHTMessage.msg by opp_msgc.
 packet CBRDHTGetResponse extends DHTGetResponse
 {
     OverlayKey originalKey;
 }
Definition at line 71 of file CBR-DHTMessage_m.h.
Constructor & Destructor Documentation
CBRDHTGetResponse::CBRDHTGetResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
CBRDHTGetResponse::CBRDHTGetResponse (const CBRDHTGetResponse & other)
virtual CBRDHTGetResponse::~CBRDHTGetResponse () [virtual]
Member Function Documentation
void CBRDHTGetResponse::copy (const CBRDHTGetResponse & other) [private]
virtual CBRDHTGetResponse* CBRDHTGetResponse::dup () const [inline, virtual]
Reimplemented from DHTGetResponse.
Definition at line 88 of file CBR-DHTMessage_m.h.
{return new CBRDHTGetResponse(*this);}
virtual OverlayKey& CBRDHTGetResponse::getOriginalKey () [virtual]
Referenced by CBRDHT::handleGetResponse().
virtual const OverlayKey& CBRDHTGetResponse::getOriginalKey () const [inline, virtual]
Definition at line 94 of file CBR-DHTMessage_m.h.
Referenced by getOriginalKey().
{return const_cast<CBRDHTGetResponse*>(this)->getOriginalKey();}
CBRDHTGetResponse& CBRDHTGetResponse::operator= (const CBRDHTGetResponse & other)
bool CBRDHTGetResponse::operator== (const CBRDHTGetResponse &) [protected]
virtual void CBRDHTGetResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from DHTGetResponse.
Referenced by doPacking().
virtual void CBRDHTGetResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from DHTGetResponse.
Referenced by doUnpacking().
virtual void CBRDHTGetResponse::setOriginalKey (const OverlayKey & originalKey) [virtual]
Referenced by CBRDHT::handleGetRequest().
Member Data Documentation
OverlayKey CBRDHTGetResponse::originalKey_var [protected]
Definition at line 74 of file CBR-DHTMessage_m.h.
The documentation for this class was generated from the following file:
CBR-DHTMessage_m.h