OverSim: PubSubAdoptChildResponse Class Reference
PubSubAdoptChildResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubAdoptChildResponse (const char *name=NULL, int kind=0)
PubSubAdoptChildResponse (const PubSubAdoptChildResponse &other)
virtual ~PubSubAdoptChildResponse ()
PubSubAdoptChildResponse & operator= (const PubSubAdoptChildResponse &other)
virtual PubSubAdoptChildResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getChild ()
virtual const NodeHandle & getChild () const
virtual void setChild (const NodeHandle &child)
Protected Member Functions
bool operator== (const PubSubAdoptChildResponse &)
Protected Attributes
int subspaceId_var
NodeHandle child_var
Private Member Functions
void copy (const PubSubAdoptChildResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubAdoptChildResponse extends BaseResponseMessage
 {
         int subspaceId;
         NodeHandle child;
 }
Definition at line 1042 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubAdoptChildResponse::PubSubAdoptChildResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubAdoptChildResponse::PubSubAdoptChildResponse (const PubSubAdoptChildResponse & other)
virtual PubSubAdoptChildResponse::~PubSubAdoptChildResponse () [virtual]
Member Function Documentation
void PubSubAdoptChildResponse::copy (const PubSubAdoptChildResponse & other) [private]
virtual PubSubAdoptChildResponse* PubSubAdoptChildResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 1060 of file PubSubMessage_m.h.
{return new PubSubAdoptChildResponse(*this);}
virtual NodeHandle& PubSubAdoptChildResponse::getChild () [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse().
virtual const NodeHandle& PubSubAdoptChildResponse::getChild () const [inline, virtual]
Definition at line 1068 of file PubSubMessage_m.h.
Referenced by getChild().
{return const_cast<PubSubAdoptChildResponse*>(this)->getChild();}
virtual int PubSubAdoptChildResponse::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse().
PubSubAdoptChildResponse& PubSubAdoptChildResponse::operator= (const PubSubAdoptChildResponse & other)
bool PubSubAdoptChildResponse::operator== (const PubSubAdoptChildResponse &) [protected]
virtual void PubSubAdoptChildResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubAdoptChildResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubAdoptChildResponse::setChild (const NodeHandle & child) [virtual]
Referenced by PubSubMMOG::handleAdoptChildCall().
virtual void PubSubAdoptChildResponse::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleAdoptChildCall().
Member Data Documentation
NodeHandle PubSubAdoptChildResponse::child_var [protected]
Definition at line 1046 of file PubSubMessage_m.h.
int PubSubAdoptChildResponse::subspaceId_var [protected]
Definition at line 1045 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h