OverSim: GameAPIFrozenMessage Class Reference
GameAPIFrozenMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
GameAPIFrozenMessage (const char *name=NULL, int kind=0)
GameAPIFrozenMessage (const GameAPIFrozenMessage &other)
virtual ~GameAPIFrozenMessage ()
GameAPIFrozenMessage & operator= (const GameAPIFrozenMessage &other)
virtual GameAPIFrozenMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrc ()
virtual const NodeHandle & getSrc () const
virtual void setSrc (const NodeHandle &src)
virtual int getThrower () const
virtual void setThrower (int thrower)
virtual int getTimeSec () const
virtual void setTimeSec (int timeSec)
virtual int getTimeUsec () const
virtual void setTimeUsec (int timeUsec)
Protected Member Functions
bool operator== (const GameAPIFrozenMessage &)
Protected Attributes
NodeHandle src_var
int thrower_var
int timeSec_var
int timeUsec_var
Private Member Functions
void copy (const GameAPIFrozenMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet GameAPIFrozenMessage extends GameAPIMessage
 {
     NodeHandle src;
     int thrower;
     int timeSec;
     int timeUsec;
 }
Definition at line 2616 of file CommonMessages_m.h.
Constructor & Destructor Documentation
GameAPIFrozenMessage::GameAPIFrozenMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GameAPIFrozenMessage::GameAPIFrozenMessage (const GameAPIFrozenMessage & other)
virtual GameAPIFrozenMessage::~GameAPIFrozenMessage () [virtual]
Member Function Documentation
void GameAPIFrozenMessage::copy (const GameAPIFrozenMessage & other) [private]
virtual GameAPIFrozenMessage* GameAPIFrozenMessage::dup () const [inline, virtual]
Reimplemented from GameAPIMessage.
Definition at line 2636 of file CommonMessages_m.h.
{return new GameAPIFrozenMessage(*this);}
virtual NodeHandle& GameAPIFrozenMessage::getSrc () [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual const NodeHandle& GameAPIFrozenMessage::getSrc () const [inline, virtual]
Definition at line 2642 of file CommonMessages_m.h.
Referenced by getSrc().
{return const_cast<GameAPIFrozenMessage*>(this)->getSrc();}
virtual int GameAPIFrozenMessage::getThrower () const [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual int GameAPIFrozenMessage::getTimeSec () const [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual int GameAPIFrozenMessage::getTimeUsec () const [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
GameAPIFrozenMessage& GameAPIFrozenMessage::operator= (const GameAPIFrozenMessage & other)
bool GameAPIFrozenMessage::operator== (const GameAPIFrozenMessage &) [protected]
virtual void GameAPIFrozenMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doPacking().
virtual void GameAPIFrozenMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doUnpacking().
virtual void GameAPIFrozenMessage::setSrc (const NodeHandle & src) [virtual]
Referenced by SimpleGameClient::handleTimerEvent().
virtual void GameAPIFrozenMessage::setThrower (int thrower) [virtual]
Referenced by SimpleGameClient::handleTimerEvent().
virtual void GameAPIFrozenMessage::setTimeSec (int timeSec) [virtual]
Referenced by SimpleGameClient::handleTimerEvent().
virtual void GameAPIFrozenMessage::setTimeUsec (int timeUsec) [virtual]
Referenced by SimpleGameClient::handleTimerEvent().
Member Data Documentation
NodeHandle GameAPIFrozenMessage::src_var [protected]
Definition at line 2619 of file CommonMessages_m.h.
int GameAPIFrozenMessage::thrower_var [protected]
Definition at line 2620 of file CommonMessages_m.h.
int GameAPIFrozenMessage::timeSec_var [protected]
Definition at line 2621 of file CommonMessages_m.h.
int GameAPIFrozenMessage::timeUsec_var [protected]
Definition at line 2622 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h