OverSim: NTreeJoinResponse Class Reference
NTreeJoinResponse Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeJoinResponse (const char *name=NULL, int kind=0)
NTreeJoinResponse (const NTreeJoinResponse &other)
virtual ~NTreeJoinResponse ()
NTreeJoinResponse & operator= (const NTreeJoinResponse &other)
virtual NTreeJoinResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual void setMembersArraySize (unsigned int size)
virtual unsigned int getMembersArraySize () const
virtual NodeHandle & getMembers (unsigned int k)
virtual const NodeHandle & getMembers (unsigned int k) const
virtual void setMembers (unsigned int k, const NodeHandle &members)
Protected Member Functions
bool operator== (const NTreeJoinResponse &)
Protected Attributes
Vector2D origin_var
double size_var
NodeHandle * members_var
unsigned int members_arraysize
Private Member Functions
void copy (const NTreeJoinResponse &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeJoinResponse extends BaseResponseMessage
 {
         Vector2D origin;
         double size;
         NodeHandle members[];
 }
Definition at line 94 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeJoinResponse::NTreeJoinResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeJoinResponse::NTreeJoinResponse (const NTreeJoinResponse & other)
virtual NTreeJoinResponse::~NTreeJoinResponse () [virtual]
Member Function Documentation
void NTreeJoinResponse::copy (const NTreeJoinResponse & other) [private]
virtual NTreeJoinResponse* NTreeJoinResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 114 of file NTree_m.h.
{return new NTreeJoinResponse(*this);}
virtual NodeHandle& NTreeJoinResponse::getMembers (unsigned int k) [virtual]
Referenced by NTree::handleJoinResponse().
virtual const NodeHandle& NTreeJoinResponse::getMembers (unsigned int k) const [inline, virtual]
Definition at line 127 of file NTree_m.h.
Referenced by getMembers().
{return const_cast<NTreeJoinResponse*>(this)->getMembers(k);}
virtual unsigned int NTreeJoinResponse::getMembersArraySize () const [virtual]
Referenced by NTree::handleJoinResponse().
virtual Vector2D& NTreeJoinResponse::getOrigin () [virtual]
Referenced by NTree::handleJoinResponse().
virtual const Vector2D& NTreeJoinResponse::getOrigin () const [inline, virtual]
Definition at line 120 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeJoinResponse*>(this)->getOrigin();}
virtual double NTreeJoinResponse::getSize () const [virtual]
Referenced by NTree::handleJoinResponse().
NTreeJoinResponse& NTreeJoinResponse::operator= (const NTreeJoinResponse & other)
bool NTreeJoinResponse::operator== (const NTreeJoinResponse &) [protected]
virtual void NTreeJoinResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void NTreeJoinResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void NTreeJoinResponse::setMembers (unsigned int k, const NodeHandle & members) [virtual]
Referenced by NTree::handleJoinCall().
virtual void NTreeJoinResponse::setMembersArraySize (unsigned int size) [virtual]
Referenced by NTree::handleJoinCall().
virtual void NTreeJoinResponse::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::handleJoinCall().
virtual void NTreeJoinResponse::setSize (double size) [virtual]
Referenced by NTree::handleJoinCall().
Member Data Documentation
unsigned int NTreeJoinResponse::members_arraysize [protected]
Definition at line 100 of file NTree_m.h.
NodeHandle* NTreeJoinResponse::members_var [protected]
Definition at line 99 of file NTree_m.h.
Vector2D NTreeJoinResponse::origin_var [protected]
Definition at line 97 of file NTree_m.h.
double NTreeJoinResponse::size_var [protected]
Definition at line 98 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h