OverSim: PastryJoinResponse Class Reference
PastryJoinResponse Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
PastryJoinResponse (const char *name=NULL, int kind=0)
PastryJoinResponse (const PastryJoinResponse &other)
virtual ~PastryJoinResponse ()
PastryJoinResponse & operator= (const PastryJoinResponse &other)
virtual PastryJoinResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const PastryJoinResponse &)
Private Member Functions
void copy (const PastryJoinResponse &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet PastryJoinResponse extends BaseResponseMessage
 {
 }
Definition at line 330 of file PastryMessage_m.h.
Constructor & Destructor Documentation
PastryJoinResponse::PastryJoinResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PastryJoinResponse::PastryJoinResponse (const PastryJoinResponse & other)
virtual PastryJoinResponse::~PastryJoinResponse () [virtual]
Member Function Documentation
void PastryJoinResponse::copy (const PastryJoinResponse & other) [private]
virtual PastryJoinResponse* PastryJoinResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 346 of file PastryMessage_m.h.
{return new PastryJoinResponse(*this);}
PastryJoinResponse& PastryJoinResponse::operator= (const PastryJoinResponse & other)
bool PastryJoinResponse::operator== (const PastryJoinResponse &) [protected]
virtual void PastryJoinResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PastryJoinResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h