OverSim: DHTGetCall Class Reference
DHTGetCall Class Reference
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
#include <DHTMessage_m.h>
Public Member Functions
DHTGetCall (const char *name=NULL, int kind=0)
DHTGetCall (const DHTGetCall &other)
virtual ~DHTGetCall ()
DHTGetCall & operator= (const DHTGetCall &other)
virtual DHTGetCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
virtual bool getIsHash () const
virtual void setIsHash (bool isHash)
Protected Member Functions
bool operator== (const DHTGetCall &)
Protected Attributes
OverlayKey key_var
uint32_t kind_var
uint32_t id_var
bool isHash_var
Private Member Functions
void copy (const DHTGetCall &other)
Detailed Description
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
 packet DHTGetCall extends BaseCallMessage
 {
     OverlayKey key;
     uint32_t kind;
     uint32_t id;
     bool isHash;
 }
Definition at line 120 of file DHTMessage_m.h.
Constructor & Destructor Documentation
DHTGetCall::DHTGetCall (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTGetCall::DHTGetCall (const DHTGetCall & other)
virtual DHTGetCall::~DHTGetCall () [virtual]
Member Function Documentation
void DHTGetCall::copy (const DHTGetCall & other) [private]
virtual DHTGetCall* DHTGetCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Reimplemented in CBRDHTGetCall.
Definition at line 140 of file DHTMessage_m.h.
{return new DHTGetCall(*this);}
virtual uint32_t DHTGetCall::getId () const [virtual]
Referenced by DHT::handleGetRequest().
virtual bool DHTGetCall::getIsHash () const [virtual]
Referenced by DHT::handleGetRequest().
virtual OverlayKey& DHTGetCall::getKey () [virtual]
Referenced by CBRDHT::handleGetRequest(), and DHT::handleGetRequest().
virtual const OverlayKey& DHTGetCall::getKey () const [inline, virtual]
Definition at line 146 of file DHTMessage_m.h.
Referenced by getKey().
{return const_cast<DHTGetCall*>(this)->getKey();}
virtual uint32_t DHTGetCall::getKind () const [virtual]
Referenced by DHT::handleGetRequest().
DHTGetCall& DHTGetCall::operator= (const DHTGetCall & other)
bool DHTGetCall::operator== (const DHTGetCall &) [protected]
virtual void DHTGetCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in CBRDHTGetCall.
Referenced by doPacking().
virtual void DHTGetCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in CBRDHTGetCall.
Referenced by doUnpacking().
virtual void DHTGetCall::setId (uint32_t id) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), and DHT::handleRpcTimeout().
virtual void DHTGetCall::setIsHash (bool isHash) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handleRpcTimeout(), and DHT::handleRpcTimeout().
virtual void DHTGetCall::setKey (const OverlayKey & key) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handleRpcTimeout(), and DHT::handleRpcTimeout().
virtual void DHTGetCall::setKind (uint32_t kind) [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), DHT::handleGetResponse(), CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), and DHT::handleRpcTimeout().
Member Data Documentation
uint32_t DHTGetCall::id_var [protected]
Definition at line 125 of file DHTMessage_m.h.
bool DHTGetCall::isHash_var [protected]
Definition at line 126 of file DHTMessage_m.h.
OverlayKey DHTGetCall::key_var [protected]
Definition at line 123 of file DHTMessage_m.h.
uint32_t DHTGetCall::kind_var [protected]
Definition at line 124 of file DHTMessage_m.h.
The documentation for this class was generated from the following file:
DHTMessage_m.h