OverSim: RegionsStrategyCall Class Reference
RegionsStrategyCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
RegionsStrategyCall (const char *name=NULL, int kind=0)
RegionsStrategyCall (const RegionsStrategyCall &other)
virtual ~RegionsStrategyCall ()
RegionsStrategyCall & operator= (const RegionsStrategyCall &other)
virtual RegionsStrategyCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual RegionDataContainer & getRegionData ()
virtual const RegionDataContainer & getRegionData () const
virtual void setRegionData (const RegionDataContainer &regionData)
Protected Member Functions
bool operator== (const RegionsStrategyCall &)
Protected Attributes
RegionDataContainer regionData_var
Private Member Functions
void copy (const RegionsStrategyCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet RegionsStrategyCall extends GlobalViewBuilderCall
 {
     RegionDataContainer regionData;
 }
Definition at line 570 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
RegionsStrategyCall::RegionsStrategyCall (const char * name = NULL, int kind = 0)
Referenced by dup().
RegionsStrategyCall::RegionsStrategyCall (const RegionsStrategyCall & other)
virtual RegionsStrategyCall::~RegionsStrategyCall () [virtual]
Member Function Documentation
void RegionsStrategyCall::copy (const RegionsStrategyCall & other) [private]
virtual RegionsStrategyCall* RegionsStrategyCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 587 of file TreeManagementMessage_m.h.
{return new RegionsStrategyCall(*this);}
virtual RegionDataContainer& RegionsStrategyCall::getRegionData () [virtual]
Referenced by StrategyRegions::handleCoordinateRpcCall().
virtual const RegionDataContainer& RegionsStrategyCall::getRegionData () const [inline, virtual]
Definition at line 593 of file TreeManagementMessage_m.h.
Referenced by getRegionData().
{return const_cast<RegionsStrategyCall*>(this)->getRegionData();}
RegionsStrategyCall& RegionsStrategyCall::operator= (const RegionsStrategyCall & other)
bool RegionsStrategyCall::operator== (const RegionsStrategyCall &) [protected]
virtual void RegionsStrategyCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void RegionsStrategyCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void RegionsStrategyCall::setRegionData (const RegionDataContainer & regionData) [virtual]
Referenced by StrategyRegions::getCoordinateMessage().
Member Data Documentation
RegionDataContainer RegionsStrategyCall::regionData_var [protected]
Definition at line 573 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h