OverSim: HJoinResponse Class Reference
HJoinResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HJoinResponse (const char *name=NULL, int kind=0)
HJoinResponse (const HJoinResponse &other)
virtual ~HJoinResponse ()
HJoinResponse & operator= (const HJoinResponse &other)
virtual HJoinResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setAncestorsArraySize (unsigned int size)
virtual unsigned int getAncestorsArraySize () const
virtual NodeHandle & getAncestors (unsigned int k)
virtual const NodeHandle & getAncestors (unsigned int k) const
virtual void setAncestors (unsigned int k, const NodeHandle &ancestors)
virtual NodeHandle & getSuccessorNode ()
virtual const NodeHandle & getSuccessorNode () const
virtual void setSuccessorNode (const NodeHandle &successorNode)
virtual NodeHandle & getPredecessorNode ()
virtual const NodeHandle & getPredecessorNode () const
virtual void setPredecessorNode (const NodeHandle &predecessorNode)
virtual int getJoined () const
virtual void setJoined (int joined)
Protected Member Functions
bool operator== (const HJoinResponse &)
Protected Attributes
NodeHandle * ancestors_var
unsigned int ancestors_arraysize
NodeHandle successorNode_var
NodeHandle predecessorNode_var
int joined_var
Private Member Functions
void copy (const HJoinResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HJoinResponse extends BaseResponseMessage {
     NodeHandle ancestors[];
     NodeHandle successorNode;
     NodeHandle predecessorNode;
     int joined;
 }
Definition at line 368 of file HMessage_m.h.
Constructor & Destructor Documentation
HJoinResponse::HJoinResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HJoinResponse::HJoinResponse (const HJoinResponse & other)
virtual HJoinResponse::~HJoinResponse () [virtual]
Member Function Documentation
void HJoinResponse::copy (const HJoinResponse & other) [private]
virtual HJoinResponse* HJoinResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 389 of file HMessage_m.h.
{return new HJoinResponse(*this);}
virtual NodeHandle& HJoinResponse::getAncestors (unsigned int k) [virtual]
Referenced by HTopology::handleRpcResponse().
virtual const NodeHandle& HJoinResponse::getAncestors (unsigned int k) const [inline, virtual]
Definition at line 397 of file HMessage_m.h.
Referenced by getAncestors().
{return const_cast<HJoinResponse*>(this)->getAncestors(k);}
virtual unsigned int HJoinResponse::getAncestorsArraySize () const [virtual]
Referenced by HTopology::handleRpcResponse().
virtual int HJoinResponse::getJoined () const [virtual]
Referenced by HTopology::handleRpcResponse().
virtual NodeHandle& HJoinResponse::getPredecessorNode () [virtual]
Referenced by HTopology::handleRpcResponse().
virtual const NodeHandle& HJoinResponse::getPredecessorNode () const [inline, virtual]
Definition at line 403 of file HMessage_m.h.
Referenced by getPredecessorNode().
{return const_cast<HJoinResponse*>(this)->getPredecessorNode();}
virtual NodeHandle& HJoinResponse::getSuccessorNode () [virtual]
Referenced by HTopology::handleRpcResponse().
virtual const NodeHandle& HJoinResponse::getSuccessorNode () const [inline, virtual]
Definition at line 400 of file HMessage_m.h.
Referenced by getSuccessorNode().
{return const_cast<HJoinResponse*>(this)->getSuccessorNode();}
HJoinResponse& HJoinResponse::operator= (const HJoinResponse & other)
bool HJoinResponse::operator== (const HJoinResponse &) [protected]
virtual void HJoinResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HJoinResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HJoinResponse::setAncestors (unsigned int k, const NodeHandle & ancestors) [virtual]
Referenced by HTopology::handleJoinCall().
virtual void HJoinResponse::setAncestorsArraySize (unsigned int size) [virtual]
Referenced by HTopology::handleJoinCall().
virtual void HJoinResponse::setJoined (int joined) [virtual]
Referenced by HTopology::handleJoinCall().
virtual void HJoinResponse::setPredecessorNode (const NodeHandle & predecessorNode) [virtual]
Referenced by HTopology::handleJoinCall().
virtual void HJoinResponse::setSuccessorNode (const NodeHandle & successorNode) [virtual]
Referenced by HTopology::handleJoinCall().
Member Data Documentation
unsigned int HJoinResponse::ancestors_arraysize [protected]
Definition at line 372 of file HMessage_m.h.
NodeHandle* HJoinResponse::ancestors_var [protected]
Definition at line 371 of file HMessage_m.h.
int HJoinResponse::joined_var [protected]
Definition at line 375 of file HMessage_m.h.
NodeHandle HJoinResponse::predecessorNode_var [protected]
Definition at line 374 of file HMessage_m.h.
NodeHandle HJoinResponse::successorNode_var [protected]
Definition at line 373 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h