OverSim: TreeAppCall Class Reference
TreeAppCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
TreeAppCall (const char *name=NULL, int kind=0)
TreeAppCall (const TreeAppCall &other)
virtual ~TreeAppCall ()
TreeAppCall & operator= (const TreeAppCall &other)
virtual TreeAppCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const TreeAppCall &)
Private Member Functions
void copy (const TreeAppCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet TreeAppCall extends BaseCallMessage
 {
 }
Definition at line 138 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
TreeAppCall::TreeAppCall (const char * name = NULL, int kind = 0)
Referenced by dup().
TreeAppCall::TreeAppCall (const TreeAppCall & other)
virtual TreeAppCall::~TreeAppCall () [virtual]
Member Function Documentation
void TreeAppCall::copy (const TreeAppCall & other) [private]
virtual TreeAppCall* TreeAppCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Reimplemented in AreaDataCall, SimpleCoordStrategyCall, RegionsStrategyCall, TreeTestStrategyCall, RemoveRandomStrategyCall, SendAllStrategyCall, SendCoordinatesCall, and GlobalViewBuilderCall.
Definition at line 154 of file TreeManagementMessage_m.h.
{return new TreeAppCall(*this);}
TreeAppCall& TreeAppCall::operator= (const TreeAppCall & other)
bool TreeAppCall::operator== (const TreeAppCall &) [protected]
virtual void TreeAppCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in AreaDataCall, SimpleCoordStrategyCall, RegionsStrategyCall, TreeTestStrategyCall, RemoveRandomStrategyCall, SendAllStrategyCall, SendCoordinatesCall, and GlobalViewBuilderCall.
Referenced by doPacking().
virtual void TreeAppCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in AreaDataCall, SimpleCoordStrategyCall, RegionsStrategyCall, TreeTestStrategyCall, RemoveRandomStrategyCall, SendAllStrategyCall, SendCoordinatesCall, and GlobalViewBuilderCall.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h