OverSim: TcpDataMessage Class Reference
TcpDataMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
TcpDataMessage (const char *name=NULL, int kind=0)
TcpDataMessage (const TcpDataMessage &other)
virtual ~TcpDataMessage ()
TcpDataMessage & operator= (const TcpDataMessage &other)
virtual TcpDataMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual BinaryValue & getData ()
virtual const BinaryValue & getData () const
virtual void setData (const BinaryValue &data)
Protected Member Functions
bool operator== (const TcpDataMessage &)
Protected Attributes
BinaryValue data_var
Private Member Functions
void copy (const TcpDataMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 message TcpDataMessage
 {
     BinaryValue data;
 }
Definition at line 1062 of file CommonMessages_m.h.
Constructor & Destructor Documentation
TcpDataMessage::TcpDataMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
TcpDataMessage::TcpDataMessage (const TcpDataMessage & other)
virtual TcpDataMessage::~TcpDataMessage () [virtual]
Member Function Documentation
void TcpDataMessage::copy (const TcpDataMessage & other) [private]
virtual TcpDataMessage* TcpDataMessage::dup () const [inline, virtual]
Definition at line 1079 of file CommonMessages_m.h.
{return new TcpDataMessage(*this);}
virtual BinaryValue& TcpDataMessage::getData () [virtual]
virtual const BinaryValue& TcpDataMessage::getData () const [inline, virtual]
Definition at line 1085 of file CommonMessages_m.h.
Referenced by getData().
{return const_cast<TcpDataMessage*>(this)->getData();}
TcpDataMessage& TcpDataMessage::operator= (const TcpDataMessage & other)
bool TcpDataMessage::operator== (const TcpDataMessage &) [protected]
virtual void TcpDataMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TcpDataMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void TcpDataMessage::setData (const BinaryValue & data) [virtual]
Member Data Documentation
BinaryValue TcpDataMessage::data_var [protected]
Definition at line 1065 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h