OverSim: RequestStateCall Class Reference
RequestStateCall Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestStateCall (const char *name=NULL, int kind=0)
RequestStateCall (const RequestStateCall &other)
virtual ~RequestStateCall ()
RequestStateCall & operator= (const RequestStateCall &other)
virtual RequestStateCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RequestStateCall &)
Private Member Functions
void copy (const RequestStateCall &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestStateCall extends BaseCallMessage
 {
 }
Definition at line 364 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestStateCall::RequestStateCall (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestStateCall::RequestStateCall (const RequestStateCall & other)
virtual RequestStateCall::~RequestStateCall () [virtual]
Member Function Documentation
void RequestStateCall::copy (const RequestStateCall & other) [private]
virtual RequestStateCall* RequestStateCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 380 of file PastryMessage_m.h.
{return new RequestStateCall(*this);}
RequestStateCall& RequestStateCall::operator= (const RequestStateCall & other)
bool RequestStateCall::operator== (const RequestStateCall &) [protected]
virtual void RequestStateCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void RequestStateCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h