OverSim: RequestRoutingRowResponse Class Reference
RequestRoutingRowResponse Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestRoutingRowResponse (const char *name=NULL, int kind=0)
RequestRoutingRowResponse (const RequestRoutingRowResponse &other)
virtual ~RequestRoutingRowResponse ()
RequestRoutingRowResponse & operator= (const RequestRoutingRowResponse &other)
virtual RequestRoutingRowResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RequestRoutingRowResponse &)
Private Member Functions
void copy (const RequestRoutingRowResponse &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestRoutingRowResponse extends BaseResponseMessage
 {
 }
Definition at line 606 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestRoutingRowResponse::RequestRoutingRowResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestRoutingRowResponse::RequestRoutingRowResponse (const RequestRoutingRowResponse & other)
virtual RequestRoutingRowResponse::~RequestRoutingRowResponse () [virtual]
Member Function Documentation
void RequestRoutingRowResponse::copy (const RequestRoutingRowResponse & other) [private]
virtual RequestRoutingRowResponse* RequestRoutingRowResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 622 of file PastryMessage_m.h.
{return new RequestRoutingRowResponse(*this);}
RequestRoutingRowResponse& RequestRoutingRowResponse::operator= (const RequestRoutingRowResponse & other)
bool RequestRoutingRowResponse::operator== (const RequestRoutingRowResponse &) [protected]
virtual void RequestRoutingRowResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void RequestRoutingRowResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h