OverSim: PastryStateMessage Class Reference
PastryStateMessage Class Reference
#include <PastryMessage_m.h>
Public Member Functions
PastryStateMessage (const char *name=NULL, int kind=0)
PastryStateMessage (const PastryStateMessage &other)
virtual ~PastryStateMessage ()
PastryStateMessage & operator= (const PastryStateMessage &other)
virtual PastryStateMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getPastryStateMsgType () const
virtual void setPastryStateMsgType (int pastryStateMsgType)
virtual NodeHandle & getSender ()
virtual const NodeHandle & getSender () const
virtual void setSender (const NodeHandle &sender)
virtual void setRoutingTableArraySize (unsigned int size)
virtual unsigned int getRoutingTableArraySize () const
virtual NodeHandle & getRoutingTable (unsigned int k)
virtual const NodeHandle & getRoutingTable (unsigned int k) const
virtual void setRoutingTable (unsigned int k, const NodeHandle &routingTable)
virtual void setLeafSetArraySize (unsigned int size)
virtual unsigned int getLeafSetArraySize () const
virtual NodeHandle & getLeafSet (unsigned int k)
virtual const NodeHandle & getLeafSet (unsigned int k) const
virtual void setLeafSet (unsigned int k, const NodeHandle &leafSet)
virtual void setNeighborhoodSetArraySize (unsigned int size)
virtual unsigned int getNeighborhoodSetArraySize () const
virtual NodeHandle & getNeighborhoodSet (unsigned int k)
virtual const NodeHandle & getNeighborhoodSet (unsigned int k) const
virtual void setNeighborhoodSet (unsigned int k, const NodeHandle &neighborhoodSet)
virtual int getRow () const
virtual void setRow (int row)
virtual bool getLastHop () const
virtual void setLastHop (bool lastHop)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
Protected Member Functions
bool operator== (const PastryStateMessage &)
Protected Attributes
int pastryStateMsgType_var
NodeHandle sender_var
NodeHandle * routingTable_var
unsigned int routingTable_arraysize
NodeHandle * leafSet_var
unsigned int leafSet_arraysize
NodeHandle * neighborhoodSet_var
unsigned int neighborhoodSet_arraysize
int row_var
bool lastHop_var
simtime_t timestamp_var
Private Member Functions
void copy (const PastryStateMessage &other)
Detailed Description
Definition at line 101 of file PastryMessage_m.h.
Constructor & Destructor Documentation
PastryStateMessage::PastryStateMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PastryStateMessage::PastryStateMessage (const PastryStateMessage & other)
virtual PastryStateMessage::~PastryStateMessage () [virtual]
Member Function Documentation
void PastryStateMessage::copy (const PastryStateMessage & other) [private]
virtual PastryStateMessage* PastryStateMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 128 of file PastryMessage_m.h.
{return new PastryStateMessage(*this);}
virtual bool PastryStateMessage::getLastHop () const [virtual]
Referenced by Pastry::handleStateMessage().
virtual NodeHandle& PastryStateMessage::getLeafSet (unsigned int k) [virtual]
Referenced by BasePastry::determineAliveTable(), Pastry::handleRequestLeafSetResponse(), PastryStateObject::mergeState(), BasePastry::pingNodes(), and BasePastry::prePing().
virtual const NodeHandle& PastryStateMessage::getLeafSet (unsigned int k) const [inline, virtual]
Definition at line 146 of file PastryMessage_m.h.
Referenced by getLeafSet().
{return const_cast<PastryStateMessage*>(this)->getLeafSet(k);}
virtual unsigned int PastryStateMessage::getLeafSetArraySize () const [virtual]
Referenced by BasePastry::determineAliveTable(), BasePastry::handleRequestLeafSetCall(), Bamboo::handleRequestLeafSetResponse(), Pastry::handleRequestLeafSetResponse(), PastryStateObject::mergeState(), BasePastry::pingNodes(), and BasePastry::prePing().
virtual NodeHandle& PastryStateMessage::getNeighborhoodSet (unsigned int k) [virtual]
Referenced by BasePastry::determineAliveTable(), PastryStateObject::mergeState(), BasePastry::pingNodes(), and BasePastry::prePing().
virtual const NodeHandle& PastryStateMessage::getNeighborhoodSet (unsigned int k) const [inline, virtual]
Definition at line 151 of file PastryMessage_m.h.
Referenced by getNeighborhoodSet().
{return const_cast<PastryStateMessage*>(this)->getNeighborhoodSet(k);}
virtual unsigned int PastryStateMessage::getNeighborhoodSetArraySize () const [virtual]
Referenced by BasePastry::determineAliveTable(), PastryStateObject::mergeState(), Pastry::mergeState(), BasePastry::pingNodes(), and BasePastry::prePing().
virtual int PastryStateMessage::getPastryStateMsgType () const [virtual]
Referenced by Pastry::checkProxCache(), Pastry::endProcessingState(), Pastry::handleStateMessage(), Pastry::handleUDPMessage(), and Pastry::processState().
virtual NodeHandle& PastryStateMessage::getRoutingTable (unsigned int k) [virtual]
Referenced by BasePastry::determineAliveTable(), Pastry::handleRequestRoutingRowResponse(), PastryStateObject::mergeState(), BasePastry::pingNodes(), and BasePastry::prePing().
virtual const NodeHandle& PastryStateMessage::getRoutingTable (unsigned int k) const [inline, virtual]
Definition at line 141 of file PastryMessage_m.h.
Referenced by getRoutingTable().
{return const_cast<PastryStateMessage*>(this)->getRoutingTable(k);}
virtual unsigned int PastryStateMessage::getRoutingTableArraySize () const [virtual]
Referenced by BasePastry::determineAliveTable(), Pastry::handleRequestRoutingRowResponse(), PastryStateObject::mergeState(), Pastry::mergeState(), BasePastry::pingNodes(), and BasePastry::prePing().
virtual int PastryStateMessage::getRow () const [virtual]
Referenced by Pastry::handleRequestRoutingRowResponse(), Pastry::handleStateMessage(), and stateMsgIsSmaller().
virtual NodeHandle& PastryStateMessage::getSender () [virtual]
Referenced by Pastry::checkProxCache(), Pastry::endProcessingState(), BasePastry::handleRequestLeafSetCall(), Bamboo::handleRequestLeafSetResponse(), Pastry::handleStateMessage(), Pastry::processState(), PastryRoutingTable::repair(), and PastryLeafSet::repair().
virtual const NodeHandle& PastryStateMessage::getSender () const [inline, virtual]
Definition at line 136 of file PastryMessage_m.h.
Referenced by getSender().
{return const_cast<PastryStateMessage*>(this)->getSender();}
virtual simtime_t PastryStateMessage::getTimestamp () const [virtual]
Referenced by Pastry::endProcessingState(), and Pastry::handleStateMessage().
PastryStateMessage& PastryStateMessage::operator= (const PastryStateMessage & other)
bool PastryStateMessage::operator== (const PastryStateMessage &) [protected]
virtual void PastryStateMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PastryStateMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PastryStateMessage::setLastHop (bool lastHop) [virtual]
Referenced by BasePastry::createStateMessage().
virtual void PastryStateMessage::setLeafSet (unsigned int k, const NodeHandle & leafSet) [virtual]
Referenced by PastryLeafSet::dumpToStateMessage(), BasePastry::handleRequestLeafSetCall(), and Bamboo::handleRequestLeafSetResponse().
virtual void PastryStateMessage::setLeafSetArraySize (unsigned int size) [virtual]
Referenced by BasePastry::createStateMessage(), PastryLeafSet::dumpToStateMessage(), BasePastry::handleRequestLeafSetCall(), and Bamboo::handleRequestLeafSetResponse().
virtual void PastryStateMessage::setNeighborhoodSet (unsigned int k, const NodeHandle & neighborhoodSet) [virtual]
Referenced by PastryNeighborhoodSet::dumpToStateMessage().
virtual void PastryStateMessage::setNeighborhoodSetArraySize (unsigned int size) [virtual]
Referenced by BasePastry::createStateMessage(), and PastryNeighborhoodSet::dumpToStateMessage().
virtual void PastryStateMessage::setPastryStateMsgType (int pastryStateMsgType) [virtual]
Referenced by BasePastry::createStateMessage().
virtual void PastryStateMessage::setRoutingTable (unsigned int k, const NodeHandle & routingTable) [virtual]
Referenced by PastryRoutingTable::dumpRowToMessage(), and PastryRoutingTable::dumpToStateMessage().
virtual void PastryStateMessage::setRoutingTableArraySize (unsigned int size) [virtual]
Referenced by PastryRoutingTable::dumpRowToMessage(), and PastryRoutingTable::dumpToStateMessage().
virtual void PastryStateMessage::setRow (int row) [virtual]
Referenced by BasePastry::createStateMessage().
virtual void PastryStateMessage::setSender (const NodeHandle & sender) [virtual]
Referenced by BasePastry::createStateMessage().
virtual void PastryStateMessage::setTimestamp (simtime_t timestamp) [virtual]
Referenced by BasePastry::createStateMessage().
Member Data Documentation
bool PastryStateMessage::lastHop_var [protected]
Definition at line 113 of file PastryMessage_m.h.
unsigned int PastryStateMessage::leafSet_arraysize [protected]
Definition at line 109 of file PastryMessage_m.h.
NodeHandle* PastryStateMessage::leafSet_var [protected]
Definition at line 108 of file PastryMessage_m.h.
unsigned int PastryStateMessage::neighborhoodSet_arraysize [protected]
Definition at line 111 of file PastryMessage_m.h.
NodeHandle* PastryStateMessage::neighborhoodSet_var [protected]
Definition at line 110 of file PastryMessage_m.h.
int PastryStateMessage::pastryStateMsgType_var [protected]
Definition at line 104 of file PastryMessage_m.h.
unsigned int PastryStateMessage::routingTable_arraysize [protected]
Definition at line 107 of file PastryMessage_m.h.
NodeHandle* PastryStateMessage::routingTable_var [protected]
Definition at line 106 of file PastryMessage_m.h.
int PastryStateMessage::row_var [protected]
Definition at line 112 of file PastryMessage_m.h.
NodeHandle PastryStateMessage::sender_var [protected]
Definition at line 105 of file PastryMessage_m.h.
simtime_t PastryStateMessage::timestamp_var [protected]
Definition at line 114 of file PastryMessage_m.h.
The documentation for this class was generated from the following file:
PastryMessage_m.h