OverSim: PubSubMoveMessage Class Reference
PubSubMoveMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubMoveMessage (const char *name=NULL, int kind=0)
PubSubMoveMessage (const PubSubMoveMessage &other)
virtual ~PubSubMoveMessage ()
PubSubMoveMessage & operator= (const PubSubMoveMessage &other)
virtual PubSubMoveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
virtual NodeHandle & getPlayer ()
virtual const NodeHandle & getPlayer () const
virtual void setPlayer (const NodeHandle &player)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
Protected Member Functions
bool operator== (const PubSubMoveMessage &)
Protected Attributes
int subspaceId_var
simtime_t timestamp_var
NodeHandle player_var
Vector2D position_var
Private Member Functions
void copy (const PubSubMoveMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubMoveMessage extends BaseOverlayMessage
 {
         int subspaceId;
         simtime_t timestamp;
         NodeHandle player;
         Vector2D position;
 }
Definition at line 1316 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubMoveMessage::PubSubMoveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubMoveMessage::PubSubMoveMessage (const PubSubMoveMessage & other)
virtual PubSubMoveMessage::~PubSubMoveMessage () [virtual]
Member Function Documentation
void PubSubMoveMessage::copy (const PubSubMoveMessage & other) [private]
virtual PubSubMoveMessage* PubSubMoveMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 1336 of file PubSubMessage_m.h.
{return new PubSubMoveMessage(*this);}
virtual NodeHandle& PubSubMoveMessage::getPlayer () [virtual]
virtual const NodeHandle& PubSubMoveMessage::getPlayer () const [inline, virtual]
Definition at line 1346 of file PubSubMessage_m.h.
Referenced by getPlayer().
{return const_cast<PubSubMoveMessage*>(this)->getPlayer();}
virtual Vector2D& PubSubMoveMessage::getPosition () [virtual]
virtual const Vector2D& PubSubMoveMessage::getPosition () const [inline, virtual]
Definition at line 1349 of file PubSubMessage_m.h.
Referenced by getPosition().
{return const_cast<PubSubMoveMessage*>(this)->getPosition();}
virtual int PubSubMoveMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleMoveMessage().
virtual simtime_t PubSubMoveMessage::getTimestamp () const [virtual]
Referenced by PubSubMMOG::handleMoveMessage().
PubSubMoveMessage& PubSubMoveMessage::operator= (const PubSubMoveMessage & other)
bool PubSubMoveMessage::operator== (const PubSubMoveMessage &) [protected]
virtual void PubSubMoveMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubMoveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubMoveMessage::setPlayer (const NodeHandle & player) [virtual]
Referenced by PubSubMMOG::handleMove().
virtual void PubSubMoveMessage::setPosition (const Vector2D & position) [virtual]
Referenced by PubSubMMOG::handleMove().
virtual void PubSubMoveMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleMove().
virtual void PubSubMoveMessage::setTimestamp (simtime_t timestamp) [virtual]
Referenced by PubSubMMOG::handleMove().
Member Data Documentation
NodeHandle PubSubMoveMessage::player_var [protected]
Definition at line 1321 of file PubSubMessage_m.h.
Vector2D PubSubMoveMessage::position_var [protected]
Definition at line 1322 of file PubSubMessage_m.h.
int PubSubMoveMessage::subspaceId_var [protected]
Definition at line 1319 of file PubSubMessage_m.h.
simtime_t PubSubMoveMessage::timestamp_var [protected]
Definition at line 1320 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h