OverSim: PubSubSubscriptionResponse Class Reference
PubSubSubscriptionResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubSubscriptionResponse (const char *name=NULL, int kind=0)
PubSubSubscriptionResponse (const PubSubSubscriptionResponse &other)
virtual ~PubSubSubscriptionResponse ()
PubSubSubscriptionResponse & operator= (const PubSubSubscriptionResponse &other)
virtual
PubSubSubscriptionResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getFailed () const
virtual void setFailed (bool failed)
Protected Member Functions
bool operator== (const PubSubSubscriptionResponse &)
Protected Attributes
bool failed_var
Private Member Functions
void copy (const PubSubSubscriptionResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubSubscriptionResponse extends BaseResponseMessage
 {
         bool failed = false;
 }
Definition at line 448 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubSubscriptionResponse::PubSubSubscriptionResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubSubscriptionResponse::PubSubSubscriptionResponse (const PubSubSubscriptionResponse & other)
virtual PubSubSubscriptionResponse::~PubSubSubscriptionResponse () [virtual]
Member Function Documentation
void PubSubSubscriptionResponse::copy (const PubSubSubscriptionResponse & other) [private]
virtual PubSubSubscriptionResponse* PubSubSubscriptionResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 465 of file PubSubMessage_m.h.
{return new PubSubSubscriptionResponse(*this);}
virtual bool PubSubSubscriptionResponse::getFailed () const [virtual]
Referenced by PubSubMMOG::handleSubscriptionResponse().
PubSubSubscriptionResponse& PubSubSubscriptionResponse::operator= (const PubSubSubscriptionResponse & other)
bool PubSubSubscriptionResponse::operator== (const PubSubSubscriptionResponse &) [protected]
virtual void PubSubSubscriptionResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubSubscriptionResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubSubscriptionResponse::setFailed (bool failed) [virtual]
Referenced by PubSubMMOG::handleSubscriptionCall().
Member Data Documentation
bool PubSubSubscriptionResponse::failed_var [protected]
Definition at line 451 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h