OverSim: GlobalNodeListAccess Class Reference
GlobalNodeListAccess Class Reference
Gives access to the GlobalNodeList.
#include <BootstrapListAccess.h>
Public Member Functions
GlobalNodeList * get ()
GlobalNodeList * get ()
Detailed Description
Gives access to the GlobalNodeList.
Definition at line 35 of file BootstrapListAccess.h.
Member Function Documentation
GlobalNodeList* GlobalNodeListAccess::get () [inline]
Definition at line 39 of file BootstrapListAccess.h.
Referenced by I3BaseApp::bootstrapI3(), SimpleUnderlayNCS::createNcsInfo(), TraceChurn::createNode(), PubSubLobby::failedNode(), SimpleUnderlayNCS::init(), SimpleNcs::init(), TreeManagement::init(), Nps::init(), GlobalTraceManager::initialize(), SimpleTCP::initialize(), BaseApp::initialize(), CoordBasedRouting::initialize(), UnderlayConfigurator::initialize(), SimpleUDP::initialize(), BaseOverlay::initialize(), DHTTestApp::initializeApp(), PubSubLobby::initializeOverlay(), TopologyVis::initVis(), and I3BaseApp::refreshTriggers().
    {
        return (GlobalNodeList*)
            simulation.getModuleByPath("globalObserver.globalNodeList");
    }
GlobalNodeList* GlobalNodeListAccess::get () [inline]
Definition at line 39 of file GlobalNodeListAccess.h.
    {
        return (GlobalNodeList*)
            simulation.getModuleByPath("globalObserver.globalNodeList");
    }
The documentation for this class was generated from the following files:
BootstrapListAccess.h
GlobalNodeListAccess.h