OverSim: PubSubFailedNodeMessage Class Reference
PubSubFailedNodeMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubFailedNodeMessage (const char *name=NULL, int kind=0)
PubSubFailedNodeMessage (const PubSubFailedNodeMessage &other)
virtual ~PubSubFailedNodeMessage ()
PubSubFailedNodeMessage & operator= (const PubSubFailedNodeMessage &other)
virtual PubSubFailedNodeMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getFailedNode ()
virtual const TransportAddress & getFailedNode () const
virtual void setFailedNode (const TransportAddress &failedNode)
Protected Member Functions
bool operator== (const PubSubFailedNodeMessage &)
Protected Attributes
TransportAddress failedNode_var
Private Member Functions
void copy (const PubSubFailedNodeMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubFailedNodeMessage extends BaseOverlayMessage
 {
         TransportAddress failedNode;
 }
Definition at line 916 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubFailedNodeMessage::PubSubFailedNodeMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubFailedNodeMessage::PubSubFailedNodeMessage (const PubSubFailedNodeMessage & other)
virtual PubSubFailedNodeMessage::~PubSubFailedNodeMessage () [virtual]
Member Function Documentation
void PubSubFailedNodeMessage::copy (const PubSubFailedNodeMessage & other) [private]
virtual PubSubFailedNodeMessage* PubSubFailedNodeMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 933 of file PubSubMessage_m.h.
{return new PubSubFailedNodeMessage(*this);}
virtual TransportAddress& PubSubFailedNodeMessage::getFailedNode () [virtual]
virtual const TransportAddress& PubSubFailedNodeMessage::getFailedNode () const [inline, virtual]
Definition at line 939 of file PubSubMessage_m.h.
Referenced by getFailedNode().
{return const_cast<PubSubFailedNodeMessage*>(this)->getFailedNode();}
PubSubFailedNodeMessage& PubSubFailedNodeMessage::operator= (const PubSubFailedNodeMessage & other)
bool PubSubFailedNodeMessage::operator== (const PubSubFailedNodeMessage &) [protected]
virtual void PubSubFailedNodeMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubFailedNodeMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubFailedNodeMessage::setFailedNode (const TransportAddress & failedNode) [virtual]
Referenced by PubSubMMOG::handleBackupCallTimeout(), PubSubMMOG::handlePingCallTimeout(), PubSubMMOG::handleSubscriptionCallTimeout(), and PubSubMMOG::takeOverSubspace().
Member Data Documentation
TransportAddress PubSubFailedNodeMessage::failedNode_var [protected]
Definition at line 919 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h