OverSim: DHTputCAPICall Class Reference
DHTputCAPICall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
DHTputCAPICall (const char *name=NULL, int kind=0)
DHTputCAPICall (const DHTputCAPICall &other)
virtual ~DHTputCAPICall ()
DHTputCAPICall & operator= (const DHTputCAPICall &other)
virtual DHTputCAPICall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
virtual BinaryValue & getValue ()
virtual const BinaryValue & getValue () const
virtual void setValue (const BinaryValue &value)
virtual int getTtl () const
virtual void setTtl (int ttl)
virtual bool getIsModifiable () const
virtual void setIsModifiable (bool isModifiable)
Protected Member Functions
bool operator== (const DHTputCAPICall &)
Protected Attributes
OverlayKey key_var
uint32_t kind_var
uint32_t id_var
BinaryValue value_var
int ttl_var
bool isModifiable_var
Private Member Functions
void copy (const DHTputCAPICall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet DHTputCAPICall extends BaseCallMessage
 {
     OverlayKey key;
     uint32_t kind = 1;
     uint32_t id = 1;
     BinaryValue value;
     int ttl;
     bool isModifiable;
 }
Definition at line 1398 of file CommonMessages_m.h.
Constructor & Destructor Documentation
DHTputCAPICall::DHTputCAPICall (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTputCAPICall::DHTputCAPICall (const DHTputCAPICall & other)
virtual DHTputCAPICall::~DHTputCAPICall () [virtual]
Member Function Documentation
void DHTputCAPICall::copy (const DHTputCAPICall & other) [private]
virtual DHTputCAPICall* DHTputCAPICall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 1420 of file CommonMessages_m.h.
{return new DHTputCAPICall(*this);}
virtual uint32_t DHTputCAPICall::getId () const [virtual]
Referenced by CBRDHT::handleLookupResponse(), and CBRDHT::handlePutCAPIRequest().
virtual bool DHTputCAPICall::getIsModifiable () const [virtual]
Referenced by CBRDHT::handleLookupResponse(), and CBRDHT::handlePutCAPIRequest().
virtual OverlayKey& DHTputCAPICall::getKey () [virtual]
Referenced by CBRDHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), and DHT::handlePutCAPIRequest().
virtual const OverlayKey& DHTputCAPICall::getKey () const [inline, virtual]
Definition at line 1426 of file CommonMessages_m.h.
Referenced by getKey().
{return const_cast<DHTputCAPICall*>(this)->getKey();}
virtual uint32_t DHTputCAPICall::getKind () const [virtual]
Referenced by CBRDHT::handleLookupResponse(), and CBRDHT::handlePutCAPIRequest().
virtual int DHTputCAPICall::getTtl () const [virtual]
Referenced by CBRDHT::handleLookupResponse(), and CBRDHT::handlePutCAPIRequest().
virtual BinaryValue& DHTputCAPICall::getValue () [virtual]
Referenced by CBRDHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), and DHTTestApp::handleTimerEvent().
virtual const BinaryValue& DHTputCAPICall::getValue () const [inline, virtual]
Definition at line 1433 of file CommonMessages_m.h.
Referenced by getValue().
{return const_cast<DHTputCAPICall*>(this)->getValue();}
DHTputCAPICall& DHTputCAPICall::operator= (const DHTputCAPICall & other)
bool DHTputCAPICall::operator== (const DHTputCAPICall &) [protected]
virtual void DHTputCAPICall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void DHTputCAPICall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void DHTputCAPICall::setId (uint32_t id) [virtual]
Referenced by P2pns::p2pnsRegisterRpc(), and P2pns::registerId().
virtual void DHTputCAPICall::setIsModifiable (bool isModifiable) [virtual]
Referenced by DHTTestApp::handleTimerEvent(), DHTTestApp::handleTraceMessage(), P2pns::p2pnsRegisterRpc(), XmlRpcInterface::put(), and P2pns::registerId().
virtual void DHTputCAPICall::setKey (const OverlayKey & key) [virtual]
Referenced by DHTTestApp::handleTimerEvent(), DHTTestApp::handleTraceMessage(), P2pns::p2pnsRegisterRpc(), XmlRpcInterface::put(), and P2pns::registerId().
virtual void DHTputCAPICall::setKind (uint32_t kind) [virtual]
Referenced by P2pns::p2pnsRegisterRpc(), and P2pns::registerId().
virtual void DHTputCAPICall::setTtl (int ttl) [virtual]
Referenced by DHTTestApp::handleTimerEvent(), DHTTestApp::handleTraceMessage(), P2pns::p2pnsRegisterRpc(), XmlRpcInterface::put(), and P2pns::registerId().
virtual void DHTputCAPICall::setValue (const BinaryValue & value) [virtual]
Referenced by DHTTestApp::handleTimerEvent(), DHTTestApp::handleTraceMessage(), P2pns::p2pnsRegisterRpc(), XmlRpcInterface::put(), and P2pns::registerId().
Member Data Documentation
uint32_t DHTputCAPICall::id_var [protected]
Definition at line 1403 of file CommonMessages_m.h.
bool DHTputCAPICall::isModifiable_var [protected]
Definition at line 1406 of file CommonMessages_m.h.
OverlayKey DHTputCAPICall::key_var [protected]
Definition at line 1401 of file CommonMessages_m.h.
uint32_t DHTputCAPICall::kind_var [protected]
Definition at line 1402 of file CommonMessages_m.h.
int DHTputCAPICall::ttl_var [protected]
Definition at line 1405 of file CommonMessages_m.h.
BinaryValue DHTputCAPICall::value_var [protected]
Definition at line 1404 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h