OverSim: DHTgetCAPICall Class Reference
DHTgetCAPICall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
DHTgetCAPICall (const char *name=NULL, int kind=0)
DHTgetCAPICall (const DHTgetCAPICall &other)
virtual ~DHTgetCAPICall ()
DHTgetCAPICall & operator= (const DHTgetCAPICall &other)
virtual DHTgetCAPICall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
Protected Member Functions
bool operator== (const DHTgetCAPICall &)
Protected Attributes
OverlayKey key_var
uint32_t kind_var
uint32_t id_var
Private Member Functions
void copy (const DHTgetCAPICall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet DHTgetCAPICall extends BaseCallMessage
 {
     OverlayKey key;
     uint32_t kind = 1;
     uint32_t id = 1;
 }
Definition at line 1455 of file CommonMessages_m.h.
Constructor & Destructor Documentation
DHTgetCAPICall::DHTgetCAPICall (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTgetCAPICall::DHTgetCAPICall (const DHTgetCAPICall & other)
virtual DHTgetCAPICall::~DHTgetCAPICall () [virtual]
Member Function Documentation
void DHTgetCAPICall::copy (const DHTgetCAPICall & other) [private]
virtual DHTgetCAPICall* DHTgetCAPICall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 1474 of file CommonMessages_m.h.
{return new DHTgetCAPICall(*this);}
virtual uint32_t DHTgetCAPICall::getId () const [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), and CBRDHT::handleLookupResponse().
virtual OverlayKey& DHTgetCAPICall::getKey () [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), DHT::handleGetCAPIRequest(), and CBRDHT::handleLookupResponse().
virtual const OverlayKey& DHTgetCAPICall::getKey () const [inline, virtual]
Definition at line 1480 of file CommonMessages_m.h.
Referenced by getKey().
{return const_cast<DHTgetCAPICall*>(this)->getKey();}
virtual uint32_t DHTgetCAPICall::getKind () const [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), and CBRDHT::handleLookupResponse().
DHTgetCAPICall& DHTgetCAPICall::operator= (const DHTgetCAPICall & other)
bool DHTgetCAPICall::operator== (const DHTgetCAPICall &) [protected]
virtual void DHTgetCAPICall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void DHTgetCAPICall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void DHTgetCAPICall::setId (uint32_t id) [virtual]
Referenced by P2pns::p2pnsResolveRpc().
virtual void DHTgetCAPICall::setKey (const OverlayKey & key) [virtual]
Referenced by XmlRpcInterface::get(), DHTTestApp::handleTimerEvent(), DHTTestApp::handleTraceMessage(), and P2pns::p2pnsResolveRpc().
virtual void DHTgetCAPICall::setKind (uint32_t kind) [virtual]
Referenced by P2pns::p2pnsResolveRpc().
Member Data Documentation
uint32_t DHTgetCAPICall::id_var [protected]
Definition at line 1460 of file CommonMessages_m.h.
OverlayKey DHTgetCAPICall::key_var [protected]
Definition at line 1458 of file CommonMessages_m.h.
uint32_t DHTgetCAPICall::kind_var [protected]
Definition at line 1459 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h