OverSim: P2pnsRegisterCall Class Reference
P2pnsRegisterCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
P2pnsRegisterCall (const char *name=NULL, int kind=0)
P2pnsRegisterCall (const P2pnsRegisterCall &other)
virtual ~P2pnsRegisterCall ()
P2pnsRegisterCall & operator= (const P2pnsRegisterCall &other)
virtual P2pnsRegisterCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual BinaryValue & getP2pName ()
virtual const BinaryValue & getP2pName () const
virtual void setP2pName (const BinaryValue &p2pName)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
virtual BinaryValue & getAddress ()
virtual const BinaryValue & getAddress () const
virtual void setAddress (const BinaryValue &address)
virtual int getTtl () const
virtual void setTtl (int ttl)
Protected Member Functions
bool operator== (const P2pnsRegisterCall &)
Protected Attributes
BinaryValue p2pName_var
uint32_t kind_var
uint32_t id_var
BinaryValue address_var
int ttl_var
Private Member Functions
void copy (const P2pnsRegisterCall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet P2pnsRegisterCall extends BaseCallMessage
 {
     BinaryValue p2pName;
     uint32_t kind = 1;
     uint32_t id = 1;
     BinaryValue address;
     int ttl;
 }
Definition at line 1766 of file CommonMessages_m.h.
Constructor & Destructor Documentation
P2pnsRegisterCall::P2pnsRegisterCall (const char * name = NULL, int kind = 0)
Referenced by dup().
P2pnsRegisterCall::P2pnsRegisterCall (const P2pnsRegisterCall & other)
virtual P2pnsRegisterCall::~P2pnsRegisterCall () [virtual]
Member Function Documentation
void P2pnsRegisterCall::copy (const P2pnsRegisterCall & other) [private]
virtual P2pnsRegisterCall* P2pnsRegisterCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 1787 of file CommonMessages_m.h.
{return new P2pnsRegisterCall(*this);}
virtual BinaryValue& P2pnsRegisterCall::getAddress () [virtual]
Referenced by P2pns::handleDHTputCAPIResponse(), and P2pns::p2pnsRegisterRpc().
virtual const BinaryValue& P2pnsRegisterCall::getAddress () const [inline, virtual]
Definition at line 1800 of file CommonMessages_m.h.
Referenced by getAddress().
{return const_cast<P2pnsRegisterCall*>(this)->getAddress();}
virtual uint32_t P2pnsRegisterCall::getId () const [virtual]
Referenced by P2pns::p2pnsRegisterRpc().
virtual uint32_t P2pnsRegisterCall::getKind () const [virtual]
Referenced by P2pns::p2pnsRegisterRpc().
virtual BinaryValue& P2pnsRegisterCall::getP2pName () [virtual]
Referenced by P2pns::handleDHTputCAPIResponse(), and P2pns::p2pnsRegisterRpc().
virtual const BinaryValue& P2pnsRegisterCall::getP2pName () const [inline, virtual]
Definition at line 1793 of file CommonMessages_m.h.
Referenced by getP2pName().
{return const_cast<P2pnsRegisterCall*>(this)->getP2pName();}
virtual int P2pnsRegisterCall::getTtl () const [virtual]
Referenced by P2pns::p2pnsRegisterRpc().
P2pnsRegisterCall& P2pnsRegisterCall::operator= (const P2pnsRegisterCall & other)
bool P2pnsRegisterCall::operator== (const P2pnsRegisterCall &) [protected]
virtual void P2pnsRegisterCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void P2pnsRegisterCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void P2pnsRegisterCall::setAddress (const BinaryValue & address) [virtual]
Referenced by XmlRpcInterface::p2pnsRegister().
virtual void P2pnsRegisterCall::setId (uint32_t id) [virtual]
Referenced by XmlRpcInterface::p2pnsRegister().
virtual void P2pnsRegisterCall::setKind (uint32_t kind) [virtual]
Referenced by XmlRpcInterface::p2pnsRegister().
virtual void P2pnsRegisterCall::setP2pName (const BinaryValue & p2pName) [virtual]
Referenced by XmlRpcInterface::p2pnsRegister().
virtual void P2pnsRegisterCall::setTtl (int ttl) [virtual]
Referenced by XmlRpcInterface::p2pnsRegister().
Member Data Documentation
BinaryValue P2pnsRegisterCall::address_var [protected]
Definition at line 1772 of file CommonMessages_m.h.
uint32_t P2pnsRegisterCall::id_var [protected]
Definition at line 1771 of file CommonMessages_m.h.
uint32_t P2pnsRegisterCall::kind_var [protected]
Definition at line 1770 of file CommonMessages_m.h.
BinaryValue P2pnsRegisterCall::p2pName_var [protected]
Definition at line 1769 of file CommonMessages_m.h.
int P2pnsRegisterCall::ttl_var [protected]
Definition at line 1773 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h