OverSim: AuthBlock Class Reference
AuthBlock Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
AuthBlock ()
AuthBlock (const AuthBlock &other)
virtual ~AuthBlock ()
AuthBlock & operator= (const AuthBlock &other)
virtual AuthBlock * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual BinaryValue & getSignature ()
virtual const BinaryValue & getSignature () const
virtual void setSignature (const BinaryValue &signature)
virtual BinaryValue & getPubKey ()
virtual const BinaryValue & getPubKey () const
virtual void setPubKey (const BinaryValue &pubKey)
virtual BinaryValue & getCert ()
virtual const BinaryValue & getCert () const
virtual void setCert (const BinaryValue &cert)
Protected Member Functions
bool operator== (const AuthBlock &)
Protected Attributes
BinaryValue signature_var
BinaryValue pubKey_var
BinaryValue cert_var
Private Member Functions
void copy (const AuthBlock &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 class AuthBlock
 {
     BinaryValue signature;
     BinaryValue pubKey;
     BinaryValue cert;
 }
Definition at line 262 of file CommonMessages_m.h.
Constructor & Destructor Documentation
AuthBlock::AuthBlock ()
Referenced by dup().
AuthBlock::AuthBlock (const AuthBlock & other)
virtual AuthBlock::~AuthBlock () [virtual]
Member Function Documentation
void AuthBlock::copy (const AuthBlock & other) [private]
virtual AuthBlock* AuthBlock::dup () const [inline, virtual]
Definition at line 281 of file CommonMessages_m.h.
{return new AuthBlock(*this);}
virtual BinaryValue& AuthBlock::getCert () [virtual]
virtual const BinaryValue& AuthBlock::getCert () const [inline, virtual]
Definition at line 293 of file CommonMessages_m.h.
Referenced by getCert().
{return const_cast<AuthBlock*>(this)->getCert();}
virtual BinaryValue& AuthBlock::getPubKey () [virtual]
virtual const BinaryValue& AuthBlock::getPubKey () const [inline, virtual]
Definition at line 290 of file CommonMessages_m.h.
Referenced by getPubKey().
{return const_cast<AuthBlock*>(this)->getPubKey();}
virtual BinaryValue& AuthBlock::getSignature () [virtual]
virtual const BinaryValue& AuthBlock::getSignature () const [inline, virtual]
Definition at line 287 of file CommonMessages_m.h.
Referenced by getSignature().
{return const_cast<AuthBlock*>(this)->getSignature();}
AuthBlock& AuthBlock::operator= (const AuthBlock & other)
bool AuthBlock::operator== (const AuthBlock &) [protected]
virtual void AuthBlock::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void AuthBlock::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void AuthBlock::setCert (const BinaryValue & cert) [virtual]
Referenced by CryptoModule::signMessage().
virtual void AuthBlock::setPubKey (const BinaryValue & pubKey) [virtual]
Referenced by CryptoModule::signMessage().
virtual void AuthBlock::setSignature (const BinaryValue & signature) [virtual]
Referenced by CryptoModule::signMessage().
Member Data Documentation
BinaryValue AuthBlock::cert_var [protected]
Definition at line 267 of file CommonMessages_m.h.
BinaryValue AuthBlock::pubKey_var [protected]
Definition at line 266 of file CommonMessages_m.h.
BinaryValue AuthBlock::signature_var [protected]
Definition at line 265 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h