OverSim: DeBruijnResponse Class Reference
DeBruijnResponse Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
DeBruijnResponse (const char *name=NULL, int kind=0)
DeBruijnResponse (const DeBruijnResponse &other)
virtual ~DeBruijnResponse ()
DeBruijnResponse & operator= (const DeBruijnResponse &other)
virtual DeBruijnResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getDBNode ()
virtual const NodeHandle & getDBNode () const
virtual void setDBNode (const NodeHandle &dBNode)
virtual int getSucNum () const
virtual void setSucNum (int sucNum)
virtual void setSucNodeArraySize (unsigned int size)
virtual unsigned int getSucNodeArraySize () const
virtual NodeHandle & getSucNode (unsigned int k)
virtual const NodeHandle & getSucNode (unsigned int k) const
virtual void setSucNode (unsigned int k, const NodeHandle &sucNode)
Protected Member Functions
bool operator== (const DeBruijnResponse &)
Protected Attributes
NodeHandle dBNode_var
int sucNum_var
NodeHandle * sucNode_var
unsigned int sucNode_arraysize
Private Member Functions
void copy (const DeBruijnResponse &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet DeBruijnResponse extends BaseResponseMessage
 {
     NodeHandle dBNode;
     int sucNum;
     NodeHandle sucNode[];
 }
Definition at line 578 of file ChordMessage_m.h.
Constructor & Destructor Documentation
DeBruijnResponse::DeBruijnResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
DeBruijnResponse::DeBruijnResponse (const DeBruijnResponse & other)
virtual DeBruijnResponse::~DeBruijnResponse () [virtual]
Member Function Documentation
void DeBruijnResponse::copy (const DeBruijnResponse & other) [private]
virtual DeBruijnResponse* DeBruijnResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 598 of file ChordMessage_m.h.
{return new DeBruijnResponse(*this);}
virtual NodeHandle& DeBruijnResponse::getDBNode () [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnResponse().
virtual const NodeHandle& DeBruijnResponse::getDBNode () const [inline, virtual]
Definition at line 604 of file ChordMessage_m.h.
Referenced by getDBNode().
{return const_cast<DeBruijnResponse*>(this)->getDBNode();}
virtual NodeHandle& DeBruijnResponse::getSucNode (unsigned int k) [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnResponse().
virtual const NodeHandle& DeBruijnResponse::getSucNode (unsigned int k) const [inline, virtual]
Definition at line 611 of file ChordMessage_m.h.
Referenced by getSucNode().
{return const_cast<DeBruijnResponse*>(this)->getSucNode(k);}
virtual unsigned int DeBruijnResponse::getSucNodeArraySize () const [virtual]
virtual int DeBruijnResponse::getSucNum () const [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnResponse().
DeBruijnResponse& DeBruijnResponse::operator= (const DeBruijnResponse & other)
bool DeBruijnResponse::operator== (const DeBruijnResponse &) [protected]
virtual void DeBruijnResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void DeBruijnResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void DeBruijnResponse::setDBNode (const NodeHandle & dBNode) [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnRequest().
virtual void DeBruijnResponse::setSucNode (unsigned int k, const NodeHandle & sucNode) [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnRequest().
virtual void DeBruijnResponse::setSucNodeArraySize (unsigned int size) [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnRequest().
virtual void DeBruijnResponse::setSucNum (int sucNum) [virtual]
Referenced by oversim::Koorde::handleRpcDeBruijnRequest().
Member Data Documentation
NodeHandle DeBruijnResponse::dBNode_var [protected]
Definition at line 581 of file ChordMessage_m.h.
unsigned int DeBruijnResponse::sucNode_arraysize [protected]
Definition at line 584 of file ChordMessage_m.h.
NodeHandle* DeBruijnResponse::sucNode_var [protected]
Definition at line 583 of file ChordMessage_m.h.
int DeBruijnResponse::sucNum_var [protected]
Definition at line 582 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h