OverSim: PubSubJoinResponse Class Reference
PubSubJoinResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubJoinResponse (const char *name=NULL, int kind=0)
PubSubJoinResponse (const PubSubJoinResponse &other)
virtual ~PubSubJoinResponse ()
PubSubJoinResponse & operator= (const PubSubJoinResponse &other)
virtual PubSubJoinResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getResponsibleNode ()
virtual const NodeHandle & getResponsibleNode () const
virtual void setResponsibleNode (const NodeHandle &responsibleNode)
Protected Member Functions
bool operator== (const PubSubJoinResponse &)
Protected Attributes
NodeHandle responsibleNode_var
Private Member Functions
void copy (const PubSubJoinResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubJoinResponse extends BaseResponseMessage
 {
         NodeHandle responsibleNode;
 }
Definition at line 211 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubJoinResponse::PubSubJoinResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubJoinResponse::PubSubJoinResponse (const PubSubJoinResponse & other)
virtual PubSubJoinResponse::~PubSubJoinResponse () [virtual]
Member Function Documentation
void PubSubJoinResponse::copy (const PubSubJoinResponse & other) [private]
virtual PubSubJoinResponse* PubSubJoinResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 228 of file PubSubMessage_m.h.
{return new PubSubJoinResponse(*this);}
virtual NodeHandle& PubSubJoinResponse::getResponsibleNode () [virtual]
Referenced by PubSubMMOG::handleJoinResponse().
virtual const NodeHandle& PubSubJoinResponse::getResponsibleNode () const [inline, virtual]
Definition at line 234 of file PubSubMessage_m.h.
Referenced by getResponsibleNode().
{return const_cast<PubSubJoinResponse*>(this)->getResponsibleNode();}
PubSubJoinResponse& PubSubJoinResponse::operator= (const PubSubJoinResponse & other)
bool PubSubJoinResponse::operator== (const PubSubJoinResponse &) [protected]
virtual void PubSubJoinResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubJoinResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubJoinResponse::setResponsibleNode (const NodeHandle & responsibleNode) [virtual]
Referenced by PubSubLobby::handleJoin().
Member Data Documentation
NodeHandle PubSubJoinResponse::responsibleNode_var [protected]
Definition at line 214 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h