OverSim: DHTPutCall Class Reference
DHTPutCall Class Reference
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
#include <DHTMessage_m.h>
Public Member Functions
DHTPutCall (const char *name=NULL, int kind=0)
DHTPutCall (const DHTPutCall &other)
virtual ~DHTPutCall ()
DHTPutCall & operator= (const DHTPutCall &other)
virtual DHTPutCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual BinaryValue & getValue ()
virtual const BinaryValue & getValue () const
virtual void setValue (const BinaryValue &value)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
virtual int getTtl () const
virtual void setTtl (int ttl)
virtual bool getIsModifiable () const
virtual void setIsModifiable (bool isModifiable)
virtual bool getMaintenance () const
virtual void setMaintenance (bool maintenance)
virtual NodeHandle & getOwnerNode ()
virtual const NodeHandle & getOwnerNode () const
virtual void setOwnerNode (const NodeHandle &ownerNode)
Protected Member Functions
bool operator== (const DHTPutCall &)
Protected Attributes
OverlayKey key_var
BinaryValue value_var
uint32_t kind_var
uint32_t id_var
int ttl_var
bool isModifiable_var
bool maintenance_var
NodeHandle ownerNode_var
Private Member Functions
void copy (const DHTPutCall &other)
Detailed Description
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
 packet DHTPutCall extends BaseCallMessage
 {
     OverlayKey key;
     BinaryValue value;
     uint32_t kind;
     uint32_t id;
     int ttl;
     bool isModifiable;
     bool maintenance;
     NodeHandle ownerNode;
 }
Definition at line 55 of file DHTMessage_m.h.
Constructor & Destructor Documentation
DHTPutCall::DHTPutCall (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTPutCall::DHTPutCall (const DHTPutCall & other)
virtual DHTPutCall::~DHTPutCall () [virtual]
Member Function Documentation
void DHTPutCall::copy (const DHTPutCall & other) [private]
virtual DHTPutCall* DHTPutCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 79 of file DHTMessage_m.h.
{return new DHTPutCall(*this);}
virtual uint32_t DHTPutCall::getId () const [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual bool DHTPutCall::getIsModifiable () const [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual OverlayKey& DHTPutCall::getKey () [virtual]
Referenced by CBRDHT::handlePutCAPIRequest(), CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual const OverlayKey& DHTPutCall::getKey () const [inline, virtual]
Definition at line 85 of file DHTMessage_m.h.
Referenced by getKey().
{return const_cast<DHTPutCall*>(this)->getKey();}
virtual uint32_t DHTPutCall::getKind () const [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual bool DHTPutCall::getMaintenance () const [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual NodeHandle& DHTPutCall::getOwnerNode () [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual const NodeHandle& DHTPutCall::getOwnerNode () const [inline, virtual]
Definition at line 101 of file DHTMessage_m.h.
Referenced by getOwnerNode().
{return const_cast<DHTPutCall*>(this)->getOwnerNode();}
virtual int DHTPutCall::getTtl () const [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual BinaryValue& DHTPutCall::getValue () [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual const BinaryValue& DHTPutCall::getValue () const [inline, virtual]
Definition at line 88 of file DHTMessage_m.h.
Referenced by getValue().
{return const_cast<DHTPutCall*>(this)->getValue();}
DHTPutCall& DHTPutCall::operator= (const DHTPutCall & other)
bool DHTPutCall::operator== (const DHTPutCall &) [protected]
virtual void DHTPutCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void DHTPutCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void DHTPutCall::setId (uint32_t id) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
virtual void DHTPutCall::setIsModifiable (bool isModifiable) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
virtual void DHTPutCall::setKey (const OverlayKey & key) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
virtual void DHTPutCall::setKind (uint32_t kind) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
virtual void DHTPutCall::setMaintenance (bool maintenance) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
virtual void DHTPutCall::setOwnerNode (const NodeHandle & ownerNode) [virtual]
virtual void DHTPutCall::setTtl (int ttl) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
virtual void DHTPutCall::setValue (const BinaryValue & value) [virtual]
Referenced by CBRDHT::handleLookupResponse(), DHT::handleLookupResponse(), CBRDHT::handlePutCAPIRequest(), DHT::sendMaintenancePutCall(), and CBRDHT::update().
Member Data Documentation
uint32_t DHTPutCall::id_var [protected]
Definition at line 61 of file DHTMessage_m.h.
bool DHTPutCall::isModifiable_var [protected]
Definition at line 63 of file DHTMessage_m.h.
OverlayKey DHTPutCall::key_var [protected]
Definition at line 58 of file DHTMessage_m.h.
uint32_t DHTPutCall::kind_var [protected]
Definition at line 60 of file DHTMessage_m.h.
bool DHTPutCall::maintenance_var [protected]
Definition at line 64 of file DHTMessage_m.h.
NodeHandle DHTPutCall::ownerNode_var [protected]
Definition at line 65 of file DHTMessage_m.h.
int DHTPutCall::ttl_var [protected]
Definition at line 62 of file DHTMessage_m.h.
BinaryValue DHTPutCall::value_var [protected]
Definition at line 59 of file DHTMessage_m.h.
The documentation for this class was generated from the following file:
DHTMessage_m.h