OverSim: GIAremove Class Reference
GIAremove Class Reference
Class generated from common/ExtAPIMessages.msg by opp_msgc.
#include <ExtAPIMessages_m.h>
Public Member Functions
GIAremove (const char *name=NULL, int kind=0)
GIAremove (const GIAremove &other)
virtual ~GIAremove ()
GIAremove & operator= (const GIAremove &other)
virtual GIAremove * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const GIAremove &)
Private Member Functions
void copy (const GIAremove &other)
Detailed Description
Class generated from common/ExtAPIMessages.msg by opp_msgc.
 packet GIAremove extends GIASearchAppMessage
 {
 }
Definition at line 134 of file ExtAPIMessages_m.h.
Constructor & Destructor Documentation
GIAremove::GIAremove (const char * name = NULL, int kind = 0)
Referenced by dup().
GIAremove::GIAremove (const GIAremove & other)
virtual GIAremove::~GIAremove () [virtual]
Member Function Documentation
void GIAremove::copy (const GIAremove & other) [private]
virtual GIAremove* GIAremove::dup () const [inline, virtual]
Reimplemented from GIASearchAppMessage.
Definition at line 150 of file ExtAPIMessages_m.h.
{return new GIAremove(*this);}
GIAremove& GIAremove::operator= (const GIAremove & other)
bool GIAremove::operator== (const GIAremove &) [protected]
virtual void GIAremove::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GIASearchAppMessage.
Referenced by doPacking().
virtual void GIAremove::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GIASearchAppMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
ExtAPIMessages_m.h