OverSim: ScribeSubscriptionRefreshMessage Class Reference
ScribeSubscriptionRefreshMessage Class Reference
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
#include <ScribeMessage_m.h>
Public Member Functions
ScribeSubscriptionRefreshMessage (const char *name=NULL, int kind=0)
ScribeSubscriptionRefreshMessage (const ScribeSubscriptionRefreshMessage &other)
virtual ~ScribeSubscriptionRefreshMessage ()
ScribeSubscriptionRefreshMessage & operator= (const ScribeSubscriptionRefreshMessage &other)
virtual
ScribeSubscriptionRefreshMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrc ()
virtual const NodeHandle & getSrc () const
virtual void setSrc (const NodeHandle &src)
virtual OverlayKey & getGroupId ()
virtual const OverlayKey & getGroupId () const
virtual void setGroupId (const OverlayKey &groupId)
Protected Member Functions
bool operator== (const ScribeSubscriptionRefreshMessage &)
Protected Attributes
NodeHandle src_var
OverlayKey groupId_var
Private Member Functions
void copy (const ScribeSubscriptionRefreshMessage &other)
Detailed Description
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
 packet ScribeSubscriptionRefreshMessage
 {
         NodeHandle src;
         OverlayKey groupId;
 }
Definition at line 234 of file ScribeMessage_m.h.
Constructor & Destructor Documentation
ScribeSubscriptionRefreshMessage::ScribeSubscriptionRefreshMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ScribeSubscriptionRefreshMessage::ScribeSubscriptionRefreshMessage (const ScribeSubscriptionRefreshMessage & other)
virtual ScribeSubscriptionRefreshMessage::~ScribeSubscriptionRefreshMessage () [virtual]
Member Function Documentation
void ScribeSubscriptionRefreshMessage::copy (const ScribeSubscriptionRefreshMessage & other) [private]
virtual ScribeSubscriptionRefreshMessage* ScribeSubscriptionRefreshMessage::dup () const [inline, virtual]
Definition at line 252 of file ScribeMessage_m.h.
{return new ScribeSubscriptionRefreshMessage(*this);}
virtual OverlayKey& ScribeSubscriptionRefreshMessage::getGroupId () [virtual]
virtual const OverlayKey& ScribeSubscriptionRefreshMessage::getGroupId () const [inline, virtual]
Definition at line 261 of file ScribeMessage_m.h.
Referenced by getGroupId().
{return const_cast<ScribeSubscriptionRefreshMessage*>(this)->getGroupId();}
virtual NodeHandle& ScribeSubscriptionRefreshMessage::getSrc () [virtual]
virtual const NodeHandle& ScribeSubscriptionRefreshMessage::getSrc () const [inline, virtual]
Definition at line 258 of file ScribeMessage_m.h.
Referenced by getSrc().
{return const_cast<ScribeSubscriptionRefreshMessage*>(this)->getSrc();}
ScribeSubscriptionRefreshMessage& ScribeSubscriptionRefreshMessage::operator= (const ScribeSubscriptionRefreshMessage & other)
bool ScribeSubscriptionRefreshMessage::operator== (const ScribeSubscriptionRefreshMessage &) [protected]
virtual void ScribeSubscriptionRefreshMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ScribeSubscriptionRefreshMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ScribeSubscriptionRefreshMessage::setGroupId (const OverlayKey & groupId) [virtual]
Referenced by Scribe::handleTimerEvent().
virtual void ScribeSubscriptionRefreshMessage::setSrc (const NodeHandle & src) [virtual]
Referenced by Scribe::handleTimerEvent().
Member Data Documentation
OverlayKey ScribeSubscriptionRefreshMessage::groupId_var [protected]
Definition at line 238 of file ScribeMessage_m.h.
NodeHandle ScribeSubscriptionRefreshMessage::src_var [protected]
Definition at line 237 of file ScribeMessage_m.h.
The documentation for this class was generated from the following file:
ScribeMessage_m.h