OverSim: ALMAnycastMessage Class Reference
ALMAnycastMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
ALMAnycastMessage (const char *name=NULL, int kind=0)
ALMAnycastMessage (const ALMAnycastMessage &other)
virtual ~ALMAnycastMessage ()
ALMAnycastMessage & operator= (const ALMAnycastMessage &other)
virtual ALMAnycastMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ALMAnycastMessage &)
Private Member Functions
void copy (const ALMAnycastMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet ALMAnycastMessage extends ALMMessage
 {
 }
Definition at line 2305 of file CommonMessages_m.h.
Constructor & Destructor Documentation
ALMAnycastMessage::ALMAnycastMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMAnycastMessage::ALMAnycastMessage (const ALMAnycastMessage & other)
virtual ALMAnycastMessage::~ALMAnycastMessage () [virtual]
Member Function Documentation
void ALMAnycastMessage::copy (const ALMAnycastMessage & other) [private]
virtual ALMAnycastMessage* ALMAnycastMessage::dup () const [inline, virtual]
Reimplemented from ALMMessage.
Definition at line 2321 of file CommonMessages_m.h.
{return new ALMAnycastMessage(*this);}
ALMAnycastMessage& ALMAnycastMessage::operator= (const ALMAnycastMessage & other)
bool ALMAnycastMessage::operator== (const ALMAnycastMessage &) [protected]
virtual void ALMAnycastMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doPacking().
virtual void ALMAnycastMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h