OverSim: GameAPISnowMessage Class Reference
GameAPISnowMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
GameAPISnowMessage (const char *name=NULL, int kind=0)
GameAPISnowMessage (const GameAPISnowMessage &other)
virtual ~GameAPISnowMessage ()
GameAPISnowMessage & operator= (const GameAPISnowMessage &other)
virtual GameAPISnowMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrc ()
virtual const NodeHandle & getSrc () const
virtual void setSrc (const NodeHandle &src)
virtual Vector2D & getStart ()
virtual const Vector2D & getStart () const
virtual void setStart (const Vector2D &start)
virtual Vector2D & getEnd ()
virtual const Vector2D & getEnd () const
virtual void setEnd (const Vector2D &end)
virtual int getTimeSec () const
virtual void setTimeSec (int timeSec)
virtual int getTimeUsec () const
virtual void setTimeUsec (int timeUsec)
Protected Member Functions
bool operator== (const GameAPISnowMessage &)
Protected Attributes
NodeHandle src_var
Vector2D start_var
Vector2D end_var
int timeSec_var
int timeUsec_var
Private Member Functions
void copy (const GameAPISnowMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet GameAPISnowMessage extends GameAPIMessage
 {
     NodeHandle src;
     Vector2D start;
     Vector2D end;
     int timeSec;
     int timeUsec;
 }
Definition at line 2560 of file CommonMessages_m.h.
Constructor & Destructor Documentation
GameAPISnowMessage::GameAPISnowMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GameAPISnowMessage::GameAPISnowMessage (const GameAPISnowMessage & other)
virtual GameAPISnowMessage::~GameAPISnowMessage () [virtual]
Member Function Documentation
void GameAPISnowMessage::copy (const GameAPISnowMessage & other) [private]
virtual GameAPISnowMessage* GameAPISnowMessage::dup () const [inline, virtual]
Reimplemented from GameAPIMessage.
Definition at line 2581 of file CommonMessages_m.h.
{return new GameAPISnowMessage(*this);}
virtual Vector2D& GameAPISnowMessage::getEnd () [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual const Vector2D& GameAPISnowMessage::getEnd () const [inline, virtual]
Definition at line 2593 of file CommonMessages_m.h.
Referenced by getEnd().
{return const_cast<GameAPISnowMessage*>(this)->getEnd();}
virtual NodeHandle& GameAPISnowMessage::getSrc () [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual const NodeHandle& GameAPISnowMessage::getSrc () const [inline, virtual]
Definition at line 2587 of file CommonMessages_m.h.
Referenced by getSrc().
{return const_cast<GameAPISnowMessage*>(this)->getSrc();}
virtual Vector2D& GameAPISnowMessage::getStart () [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual const Vector2D& GameAPISnowMessage::getStart () const [inline, virtual]
Definition at line 2590 of file CommonMessages_m.h.
Referenced by getStart().
{return const_cast<GameAPISnowMessage*>(this)->getStart();}
virtual int GameAPISnowMessage::getTimeSec () const [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
virtual int GameAPISnowMessage::getTimeUsec () const [virtual]
Referenced by SimpleGameClient::handleLowerMessage().
GameAPISnowMessage& GameAPISnowMessage::operator= (const GameAPISnowMessage & other)
bool GameAPISnowMessage::operator== (const GameAPISnowMessage &) [protected]
virtual void GameAPISnowMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doPacking().
virtual void GameAPISnowMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doUnpacking().
virtual void GameAPISnowMessage::setEnd (const Vector2D & end) [virtual]
Referenced by SimpleGameClient::handleRealworldPacket().
virtual void GameAPISnowMessage::setSrc (const NodeHandle & src) [virtual]
Referenced by SimpleGameClient::handleRealworldPacket().
virtual void GameAPISnowMessage::setStart (const Vector2D & start) [virtual]
Referenced by SimpleGameClient::handleRealworldPacket().
virtual void GameAPISnowMessage::setTimeSec (int timeSec) [virtual]
Referenced by SimpleGameClient::handleRealworldPacket().
virtual void GameAPISnowMessage::setTimeUsec (int timeUsec) [virtual]
Referenced by SimpleGameClient::handleRealworldPacket().
Member Data Documentation
Vector2D GameAPISnowMessage::end_var [protected]
Definition at line 2565 of file CommonMessages_m.h.
NodeHandle GameAPISnowMessage::src_var [protected]
Definition at line 2563 of file CommonMessages_m.h.
Vector2D GameAPISnowMessage::start_var [protected]
Definition at line 2564 of file CommonMessages_m.h.
int GameAPISnowMessage::timeSec_var [protected]
Definition at line 2566 of file CommonMessages_m.h.
int GameAPISnowMessage::timeUsec_var [protected]
Definition at line 2567 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h