OverSim: NotifyResponse Class Reference
NotifyResponse Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
NotifyResponse (const char *name=NULL, int kind=0)
NotifyResponse (const NotifyResponse &other)
virtual ~NotifyResponse ()
NotifyResponse & operator= (const NotifyResponse &other)
virtual NotifyResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSucNum () const
virtual void setSucNum (int sucNum)
virtual void setSucNodeArraySize (unsigned int size)
virtual unsigned int getSucNodeArraySize () const
virtual NodeHandle & getSucNode (unsigned int k)
virtual const NodeHandle & getSucNode (unsigned int k) const
virtual void setSucNode (unsigned int k, const NodeHandle &sucNode)
virtual NodeHandle & getPreNode ()
virtual const NodeHandle & getPreNode () const
virtual void setPreNode (const NodeHandle &preNode)
virtual bool getPreNodeSet () const
virtual void setPreNodeSet (bool preNodeSet)
Protected Member Functions
bool operator== (const NotifyResponse &)
Protected Attributes
int sucNum_var
NodeHandle * sucNode_var
unsigned int sucNode_arraysize
NodeHandle preNode_var
bool preNodeSet_var
Private Member Functions
void copy (const NotifyResponse &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet NotifyResponse extends BaseResponseMessage
 {
     int sucNum;
     NodeHandle sucNode[];
     NodeHandle preNode;
     bool preNodeSet;
 }
Definition at line 200 of file ChordMessage_m.h.
Constructor & Destructor Documentation
NotifyResponse::NotifyResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
NotifyResponse::NotifyResponse (const NotifyResponse & other)
virtual NotifyResponse::~NotifyResponse () [virtual]
Member Function Documentation
void NotifyResponse::copy (const NotifyResponse & other) [private]
virtual NotifyResponse* NotifyResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 221 of file ChordMessage_m.h.
{return new NotifyResponse(*this);}
virtual NodeHandle& NotifyResponse::getPreNode () [virtual]
Referenced by oversim::Chord::handleRpcNotifyResponse().
virtual const NodeHandle& NotifyResponse::getPreNode () const [inline, virtual]
Definition at line 234 of file ChordMessage_m.h.
Referenced by getPreNode().
{return const_cast<NotifyResponse*>(this)->getPreNode();}
virtual bool NotifyResponse::getPreNodeSet () const [virtual]
Referenced by oversim::Chord::handleRpcNotifyResponse().
virtual NodeHandle& NotifyResponse::getSucNode (unsigned int k) [virtual]
Referenced by oversim::ChordSuccessorList::updateList().
virtual const NodeHandle& NotifyResponse::getSucNode (unsigned int k) const [inline, virtual]
Definition at line 231 of file ChordMessage_m.h.
Referenced by getSucNode().
{return const_cast<NotifyResponse*>(this)->getSucNode(k);}
virtual unsigned int NotifyResponse::getSucNodeArraySize () const [virtual]
virtual int NotifyResponse::getSucNum () const [virtual]
Referenced by oversim::ChordSuccessorList::updateList().
NotifyResponse& NotifyResponse::operator= (const NotifyResponse & other)
bool NotifyResponse::operator== (const NotifyResponse &) [protected]
virtual void NotifyResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void NotifyResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void NotifyResponse::setPreNode (const NodeHandle & preNode) [virtual]
Referenced by oversim::Chord::rpcNotify().
virtual void NotifyResponse::setPreNodeSet (bool preNodeSet) [virtual]
Referenced by oversim::Chord::rpcNotify().
virtual void NotifyResponse::setSucNode (unsigned int k, const NodeHandle & sucNode) [virtual]
Referenced by oversim::Chord::rpcNotify().
virtual void NotifyResponse::setSucNodeArraySize (unsigned int size) [virtual]
Referenced by oversim::Chord::rpcNotify().
virtual void NotifyResponse::setSucNum (int sucNum) [virtual]
Referenced by oversim::Chord::rpcNotify().
Member Data Documentation
NodeHandle NotifyResponse::preNode_var [protected]
Definition at line 206 of file ChordMessage_m.h.
bool NotifyResponse::preNodeSet_var [protected]
Definition at line 207 of file ChordMessage_m.h.
unsigned int NotifyResponse::sucNode_arraysize [protected]
Definition at line 205 of file ChordMessage_m.h.
NodeHandle* NotifyResponse::sucNode_var [protected]
Definition at line 204 of file ChordMessage_m.h.
int NotifyResponse::sucNum_var [protected]
Definition at line 203 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h