OverSim: SimMudMoveMessage Class Reference
SimMudMoveMessage Class Reference
Class generated from tier2/simmud/SimMud.msg by opp_msgc.
#include <SimMud_m.h>
Public Member Functions
SimMudMoveMessage (const char *name=NULL, int kind=0)
SimMudMoveMessage (const SimMudMoveMessage &other)
virtual ~SimMudMoveMessage ()
SimMudMoveMessage & operator= (const SimMudMoveMessage &other)
virtual SimMudMoveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrc ()
virtual const NodeHandle & getSrc () const
virtual void setSrc (const NodeHandle &src)
virtual double getPosX () const
virtual void setPosX (double posX)
virtual double getPosY () const
virtual void setPosY (double posY)
virtual simtime_t getTimestamp () const
virtual void setTimestamp (simtime_t timestamp)
virtual bool getLeaveRegion () const
virtual void setLeaveRegion (bool leaveRegion)
Protected Member Functions
bool operator== (const SimMudMoveMessage &)
Protected Attributes
NodeHandle src_var
double posX_var
double posY_var
simtime_t timestamp_var
bool leaveRegion_var
Private Member Functions
void copy (const SimMudMoveMessage &other)
Detailed Description
Class generated from tier2/simmud/SimMud.msg by opp_msgc.
 packet SimMudMoveMessage
 {
         NodeHandle src;
         double posX;
         double posY;
         simtime_t timestamp;
         bool leaveRegion = false;
 }
Definition at line 38 of file SimMud_m.h.
Constructor & Destructor Documentation
SimMudMoveMessage::SimMudMoveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
SimMudMoveMessage::SimMudMoveMessage (const SimMudMoveMessage & other)
virtual SimMudMoveMessage::~SimMudMoveMessage () [virtual]
Member Function Documentation
void SimMudMoveMessage::copy (const SimMudMoveMessage & other) [private]
virtual SimMudMoveMessage* SimMudMoveMessage::dup () const [inline, virtual]
Definition at line 59 of file SimMud_m.h.
{return new SimMudMoveMessage(*this);}
virtual bool SimMudMoveMessage::getLeaveRegion () const [virtual]
Referenced by SimMud::handleOtherPlayerMove().
virtual double SimMudMoveMessage::getPosX () const [virtual]
Referenced by SimMud::handleOtherPlayerMove().
virtual double SimMudMoveMessage::getPosY () const [virtual]
Referenced by SimMud::handleOtherPlayerMove().
virtual NodeHandle& SimMudMoveMessage::getSrc () [virtual]
Referenced by SimMud::handleOtherPlayerMove().
virtual const NodeHandle& SimMudMoveMessage::getSrc () const [inline, virtual]
Definition at line 65 of file SimMud_m.h.
Referenced by getSrc().
{return const_cast<SimMudMoveMessage*>(this)->getSrc();}
virtual simtime_t SimMudMoveMessage::getTimestamp () const [virtual]
Referenced by SimMud::handleOtherPlayerMove().
SimMudMoveMessage& SimMudMoveMessage::operator= (const SimMudMoveMessage & other)
bool SimMudMoveMessage::operator== (const SimMudMoveMessage &) [protected]
virtual void SimMudMoveMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SimMudMoveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SimMudMoveMessage::setLeaveRegion (bool leaveRegion) [virtual]
Referenced by SimMud::handleMove().
virtual void SimMudMoveMessage::setPosX (double posX) [virtual]
Referenced by SimMud::handleMove().
virtual void SimMudMoveMessage::setPosY (double posY) [virtual]
Referenced by SimMud::handleMove().
virtual void SimMudMoveMessage::setSrc (const NodeHandle & src) [virtual]
Referenced by SimMud::handleMove().
virtual void SimMudMoveMessage::setTimestamp (simtime_t timestamp) [virtual]
Referenced by SimMud::handleMove().
Member Data Documentation
bool SimMudMoveMessage::leaveRegion_var [protected]
Definition at line 45 of file SimMud_m.h.
double SimMudMoveMessage::posX_var [protected]
Definition at line 42 of file SimMud_m.h.
double SimMudMoveMessage::posY_var [protected]
Definition at line 43 of file SimMud_m.h.
NodeHandle SimMudMoveMessage::src_var [protected]
Definition at line 41 of file SimMud_m.h.
simtime_t SimMudMoveMessage::timestamp_var [protected]
Definition at line 44 of file SimMud_m.h.
The documentation for this class was generated from the following file:
SimMud_m.h