OverSim: PingResponse Class Reference
PingResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
PingResponse (const char *name=NULL, int kind=0)
PingResponse (const PingResponse &other)
virtual ~PingResponse ()
PingResponse & operator= (const PingResponse &other)
virtual PingResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const PingResponse &)
Private Member Functions
void copy (const PingResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet PingResponse extends BaseResponseMessage
 {
 }
Definition at line 844 of file CommonMessages_m.h.
Constructor & Destructor Documentation
PingResponse::PingResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PingResponse::PingResponse (const PingResponse & other)
virtual PingResponse::~PingResponse () [virtual]
Member Function Documentation
void PingResponse::copy (const PingResponse & other) [private]
virtual PingResponse* PingResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 860 of file CommonMessages_m.h.
{return new PingResponse(*this);}
PingResponse& PingResponse::operator= (const PingResponse & other)
bool PingResponse::operator== (const PingResponse &) [protected]
virtual void PingResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PingResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h