OverSim: ChildReleaseResponse Class Reference
ChildReleaseResponse Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
ChildReleaseResponse (const char *name=NULL, int kind=0)
ChildReleaseResponse (const ChildReleaseResponse &other)
virtual ~ChildReleaseResponse ()
ChildReleaseResponse & operator= (const ChildReleaseResponse &other)
virtual ChildReleaseResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ChildReleaseResponse &)
Private Member Functions
void copy (const ChildReleaseResponse &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet ChildReleaseResponse extends BaseResponseMessage
 {
 }
Definition at line 310 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
ChildReleaseResponse::ChildReleaseResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
ChildReleaseResponse::ChildReleaseResponse (const ChildReleaseResponse & other)
virtual ChildReleaseResponse::~ChildReleaseResponse () [virtual]
Member Function Documentation
void ChildReleaseResponse::copy (const ChildReleaseResponse & other) [private]
virtual ChildReleaseResponse* ChildReleaseResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 326 of file TreeManagementMessage_m.h.
{return new ChildReleaseResponse(*this);}
ChildReleaseResponse& ChildReleaseResponse::operator= (const ChildReleaseResponse & other)
bool ChildReleaseResponse::operator== (const ChildReleaseResponse &) [protected]
virtual void ChildReleaseResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void ChildReleaseResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h