OverSim: DHTTtlTimer Class Reference
DHTTtlTimer Class Reference
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
#include <DHTMessage_m.h>
Public Member Functions
DHTTtlTimer (const char *name=NULL, int kind=0)
DHTTtlTimer (const DHTTtlTimer &other)
virtual ~DHTTtlTimer ()
DHTTtlTimer & operator= (const DHTTtlTimer &other)
virtual DHTTtlTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
Protected Member Functions
bool operator== (const DHTTtlTimer &)
Protected Attributes
OverlayKey key_var
uint32_t kind_var
uint32_t id_var
Private Member Functions
void copy (const DHTTtlTimer &other)
Detailed Description
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
 message DHTTtlTimer
 {
     OverlayKey key;
     uint32_t kind;
     uint32_t id;
 }
Definition at line 264 of file DHTMessage_m.h.
Constructor & Destructor Documentation
DHTTtlTimer::DHTTtlTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTTtlTimer::DHTTtlTimer (const DHTTtlTimer & other)
virtual DHTTtlTimer::~DHTTtlTimer () [virtual]
Member Function Documentation
void DHTTtlTimer::copy (const DHTTtlTimer & other) [private]
virtual DHTTtlTimer* DHTTtlTimer::dup () const [inline, virtual]
Definition at line 283 of file DHTMessage_m.h.
{return new DHTTtlTimer(*this);}
virtual uint32_t DHTTtlTimer::getId () const [virtual]
Referenced by CBRDHT::handleTimerEvent(), and DHT::handleTimerEvent().
virtual OverlayKey& DHTTtlTimer::getKey () [virtual]
Referenced by CBRDHT::handleTimerEvent(), and DHT::handleTimerEvent().
virtual const OverlayKey& DHTTtlTimer::getKey () const [inline, virtual]
Definition at line 289 of file DHTMessage_m.h.
Referenced by getKey().
{return const_cast<DHTTtlTimer*>(this)->getKey();}
virtual uint32_t DHTTtlTimer::getKind () const [virtual]
Referenced by CBRDHT::handleTimerEvent(), and DHT::handleTimerEvent().
DHTTtlTimer& DHTTtlTimer::operator= (const DHTTtlTimer & other)
bool DHTTtlTimer::operator== (const DHTTtlTimer &) [protected]
virtual void DHTTtlTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void DHTTtlTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void DHTTtlTimer::setId (uint32_t id) [virtual]
Referenced by DHT::handlePutRequest().
virtual void DHTTtlTimer::setKey (const OverlayKey & key) [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
virtual void DHTTtlTimer::setKind (uint32_t kind) [virtual]
Referenced by DHT::handlePutRequest().
Member Data Documentation
uint32_t DHTTtlTimer::id_var [protected]
Definition at line 269 of file DHTMessage_m.h.
OverlayKey DHTTtlTimer::key_var [protected]
Definition at line 267 of file DHTMessage_m.h.
uint32_t DHTTtlTimer::kind_var [protected]
Definition at line 268 of file DHTMessage_m.h.
The documentation for this class was generated from the following file:
DHTMessage_m.h