OverSim: CoordBasedRoutingAccess Class Reference
CoordBasedRoutingAccess Class Reference
Gives access to the CoordBasedRouting.
#include <CoordBasedRoutingAccess.h>
Public Member Functions
CoordBasedRouting * get ()
Detailed Description
Gives access to the CoordBasedRouting.
Definition at line 34 of file CoordBasedRoutingAccess.h.
Member Function Documentation
CoordBasedRouting* CoordBasedRoutingAccess::get () [inline]
Definition at line 37 of file CoordBasedRoutingAccess.h.
Referenced by Nps::init(), CBRDHT::initializeApp(), NeighborCache::initializeApp(), and GlobalViewBuilder::spreadGlobalView().
    {
        CoordBasedRouting* temp =
            (CoordBasedRouting*)simulation.getModuleByPath("globalObserver."
                "globalFunctions[0].function.coordBasedRouting");
        if (temp) return temp;
        return (CoordBasedRouting*)simulation.getModuleByPath("globalObserver."
                "globalFunctions[1].function.coordBasedRouting"); //TODO
    }
The documentation for this class was generated from the following file:
CoordBasedRoutingAccess.h