OverSim: NTreeMoveMessage Class Reference
NTreeMoveMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeMoveMessage (const char *name=NULL, int kind=0)
NTreeMoveMessage (const NTreeMoveMessage &other)
virtual ~NTreeMoveMessage ()
NTreeMoveMessage & operator= (const NTreeMoveMessage &other)
virtual NTreeMoveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getPlayer ()
virtual const NodeHandle & getPlayer () const
virtual void setPlayer (const NodeHandle &player)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
Protected Member Functions
bool operator== (const NTreeMoveMessage &)
Protected Attributes
NodeHandle player_var
Vector2D position_var
Private Member Functions
void copy (const NTreeMoveMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeMoveMessage extends BaseOverlayMessage
 {
         NodeHandle player;
         Vector2D position;
 }
Definition at line 542 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeMoveMessage::NTreeMoveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeMoveMessage::NTreeMoveMessage (const NTreeMoveMessage & other)
virtual NTreeMoveMessage::~NTreeMoveMessage () [virtual]
Member Function Documentation
void NTreeMoveMessage::copy (const NTreeMoveMessage & other) [private]
virtual NTreeMoveMessage* NTreeMoveMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 560 of file NTree_m.h.
{return new NTreeMoveMessage(*this);}
virtual NodeHandle& NTreeMoveMessage::getPlayer () [virtual]
Referenced by NTree::handleMoveMessage().
virtual const NodeHandle& NTreeMoveMessage::getPlayer () const [inline, virtual]
Definition at line 566 of file NTree_m.h.
Referenced by getPlayer().
{return const_cast<NTreeMoveMessage*>(this)->getPlayer();}
virtual Vector2D& NTreeMoveMessage::getPosition () [virtual]
Referenced by NTree::handleMoveMessage().
virtual const Vector2D& NTreeMoveMessage::getPosition () const [inline, virtual]
Definition at line 569 of file NTree_m.h.
Referenced by getPosition().
{return const_cast<NTreeMoveMessage*>(this)->getPosition();}
NTreeMoveMessage& NTreeMoveMessage::operator= (const NTreeMoveMessage & other)
bool NTreeMoveMessage::operator== (const NTreeMoveMessage &) [protected]
virtual void NTreeMoveMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeMoveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeMoveMessage::setPlayer (const NodeHandle & player) [virtual]
Referenced by NTree::handleMove().
virtual void NTreeMoveMessage::setPosition (const Vector2D & position) [virtual]
Referenced by NTree::handleMove().
Member Data Documentation
NodeHandle NTreeMoveMessage::player_var [protected]
Definition at line 545 of file NTree_m.h.
Vector2D NTreeMoveMessage::position_var [protected]
Definition at line 546 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h