OverSim: NTreeNodePingCall Class Reference
NTreeNodePingCall Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeNodePingCall (const char *name=NULL, int kind=0)
NTreeNodePingCall (const NTreeNodePingCall &other)
virtual ~NTreeNodePingCall ()
NTreeNodePingCall & operator= (const NTreeNodePingCall &other)
virtual NTreeNodePingCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getSiblingsArraySize () const
virtual NodeHandle & getSiblings (unsigned int k)
virtual const NodeHandle & getSiblings (unsigned int k) const
virtual void setSiblings (unsigned int k, const NodeHandle &siblings)
virtual int getQuadrant () const
virtual void setQuadrant (int quadrant)
Protected Member Functions
bool operator== (const NTreeNodePingCall &)
Protected Attributes
NodeHandle siblings_var [4]
int quadrant_var
Private Member Functions
void copy (const NTreeNodePingCall &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeNodePingCall extends NTreePingCall
 {
         NodeHandle siblings[4];
         int quadrant;
 }
Definition at line 277 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeNodePingCall::NTreeNodePingCall (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeNodePingCall::NTreeNodePingCall (const NTreeNodePingCall & other)
virtual NTreeNodePingCall::~NTreeNodePingCall () [virtual]
Member Function Documentation
void NTreeNodePingCall::copy (const NTreeNodePingCall & other) [private]
virtual NTreeNodePingCall* NTreeNodePingCall::dup () const [inline, virtual]
Reimplemented from NTreePingCall.
Definition at line 295 of file NTree_m.h.
Referenced by NTree::pingNodes().
{return new NTreeNodePingCall(*this);}
virtual int NTreeNodePingCall::getQuadrant () const [virtual]
virtual NodeHandle& NTreeNodePingCall::getSiblings (unsigned int k) [virtual]
virtual const NodeHandle& NTreeNodePingCall::getSiblings (unsigned int k) const [inline, virtual]
Definition at line 302 of file NTree_m.h.
Referenced by getSiblings().
{return const_cast<NTreeNodePingCall*>(this)->getSiblings(k);}
virtual unsigned int NTreeNodePingCall::getSiblingsArraySize () const [virtual]
NTreeNodePingCall& NTreeNodePingCall::operator= (const NTreeNodePingCall & other)
bool NTreeNodePingCall::operator== (const NTreeNodePingCall &) [protected]
virtual void NTreeNodePingCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from NTreePingCall.
Referenced by doPacking().
virtual void NTreeNodePingCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from NTreePingCall.
Referenced by doUnpacking().
virtual void NTreeNodePingCall::setQuadrant (int quadrant) [virtual]
Referenced by NTree::pingNodes().
virtual void NTreeNodePingCall::setSiblings (unsigned int k, const NodeHandle & siblings) [virtual]
Referenced by NTree::pingNodes().
Member Data Documentation
int NTreeNodePingCall::quadrant_var [protected]
Definition at line 281 of file NTree_m.h.
NodeHandle NTreeNodePingCall::siblings_var[4] [protected]
Definition at line 280 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h