OverSim: GameAPIPositionMessage Class Reference
GameAPIPositionMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
GameAPIPositionMessage (const char *name=NULL, int kind=0)
GameAPIPositionMessage (const GameAPIPositionMessage &other)
virtual ~GameAPIPositionMessage ()
GameAPIPositionMessage & operator= (const GameAPIPositionMessage &other)
virtual GameAPIPositionMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
Protected Member Functions
bool operator== (const GameAPIPositionMessage &)
Protected Attributes
Vector2D position_var
Private Member Functions
void copy (const GameAPIPositionMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet GameAPIPositionMessage extends GameAPIMessage
 {
     Vector2D position;
 }
Definition at line 2436 of file CommonMessages_m.h.
Constructor & Destructor Documentation
GameAPIPositionMessage::GameAPIPositionMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GameAPIPositionMessage::GameAPIPositionMessage (const GameAPIPositionMessage & other)
virtual GameAPIPositionMessage::~GameAPIPositionMessage () [virtual]
Member Function Documentation
void GameAPIPositionMessage::copy (const GameAPIPositionMessage & other) [private]
virtual GameAPIPositionMessage* GameAPIPositionMessage::dup () const [inline, virtual]
Reimplemented from GameAPIMessage.
Definition at line 2453 of file CommonMessages_m.h.
{return new GameAPIPositionMessage(*this);}
virtual Vector2D& GameAPIPositionMessage::getPosition () [virtual]
Referenced by Quon::handleJoin(), Vast::handleJoin(), PubSubMMOG::handleMove(), NTree::handleMove(), SimMud::handleMove(), Quon::handleMove(), and Vast::handleMove().
virtual const Vector2D& GameAPIPositionMessage::getPosition () const [inline, virtual]
Definition at line 2459 of file CommonMessages_m.h.
Referenced by getPosition().
{return const_cast<GameAPIPositionMessage*>(this)->getPosition();}
GameAPIPositionMessage& GameAPIPositionMessage::operator= (const GameAPIPositionMessage & other)
bool GameAPIPositionMessage::operator== (const GameAPIPositionMessage &) [protected]
virtual void GameAPIPositionMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doPacking().
virtual void GameAPIPositionMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GameAPIMessage.
Referenced by doUnpacking().
virtual void GameAPIPositionMessage::setPosition (const Vector2D & position) [virtual]
Referenced by SimpleGameClient::updatePosition().
Member Data Documentation
Vector2D GameAPIPositionMessage::position_var [protected]
Definition at line 2439 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h