OverSim: NTreeDivideResponse Class Reference
NTreeDivideResponse Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeDivideResponse (const char *name=NULL, int kind=0)
NTreeDivideResponse (const NTreeDivideResponse &other)
virtual ~NTreeDivideResponse ()
NTreeDivideResponse & operator= (const NTreeDivideResponse &other)
virtual NTreeDivideResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getQuadrant () const
virtual void setQuadrant (int quadrant)
Protected Member Functions
bool operator== (const NTreeDivideResponse &)
Protected Attributes
int quadrant_var
Private Member Functions
void copy (const NTreeDivideResponse &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeDivideResponse extends BaseResponseMessage
 {
         int quadrant;
 }
Definition at line 190 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeDivideResponse::NTreeDivideResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeDivideResponse::NTreeDivideResponse (const NTreeDivideResponse & other)
virtual NTreeDivideResponse::~NTreeDivideResponse () [virtual]
Member Function Documentation
void NTreeDivideResponse::copy (const NTreeDivideResponse & other) [private]
virtual NTreeDivideResponse* NTreeDivideResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 207 of file NTree_m.h.
{return new NTreeDivideResponse(*this);}
virtual int NTreeDivideResponse::getQuadrant () const [virtual]
Referenced by NTree::handleDivideResponse().
NTreeDivideResponse& NTreeDivideResponse::operator= (const NTreeDivideResponse & other)
bool NTreeDivideResponse::operator== (const NTreeDivideResponse &) [protected]
virtual void NTreeDivideResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void NTreeDivideResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void NTreeDivideResponse::setQuadrant (int quadrant) [virtual]
Referenced by NTree::handleDivideCall().
Member Data Documentation
int NTreeDivideResponse::quadrant_var [protected]
Definition at line 193 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h