OverSim: UnderlayTestResponse Class Reference
UnderlayTestResponse Class Reference
Class generated from applications/kbrtestapp/KBRTestMessage.msg by opp_msgc.
#include <KBRTestMessage_m.h>
Public Member Functions
UnderlayTestResponse (const char *name=NULL, int kind=0)
UnderlayTestResponse (const UnderlayTestResponse &other)
virtual ~UnderlayTestResponse ()
UnderlayTestResponse & operator= (const UnderlayTestResponse &other)
virtual UnderlayTestResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual simtime_t getOneWayLatency () const
virtual void setOneWayLatency (simtime_t oneWayLatency)
Protected Member Functions
bool operator== (const UnderlayTestResponse &)
Protected Attributes
simtime_t oneWayLatency_var
Private Member Functions
void copy (const UnderlayTestResponse &other)
Detailed Description
Class generated from applications/kbrtestapp/KBRTestMessage.msg by opp_msgc.
 packet UnderlayTestResponse extends BaseResponseMessage
 {
     simtime_t oneWayLatency;
 }
Definition at line 193 of file KBRTestMessage_m.h.
Constructor & Destructor Documentation
UnderlayTestResponse::UnderlayTestResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
UnderlayTestResponse::UnderlayTestResponse (const UnderlayTestResponse & other)
virtual UnderlayTestResponse::~UnderlayTestResponse () [virtual]
Member Function Documentation
void UnderlayTestResponse::copy (const UnderlayTestResponse & other) [private]
virtual UnderlayTestResponse* UnderlayTestResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 210 of file KBRTestMessage_m.h.
{return new UnderlayTestResponse(*this);}
virtual simtime_t UnderlayTestResponse::getOneWayLatency () const [virtual]
UnderlayTestResponse& UnderlayTestResponse::operator= (const UnderlayTestResponse & other)
bool UnderlayTestResponse::operator== (const UnderlayTestResponse &) [protected]
virtual void UnderlayTestResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void UnderlayTestResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void UnderlayTestResponse::setOneWayLatency (simtime_t oneWayLatency) [virtual]
Referenced by KBRTestApp::underlayTestCall().
Member Data Documentation
simtime_t UnderlayTestResponse::oneWayLatency_var [protected]
Definition at line 196 of file KBRTestMessage_m.h.
The documentation for this class was generated from the following file:
KBRTestMessage_m.h