OverSim: QuonMessage Class Reference
QuonMessage Class Reference
Class generated from overlay/quon/Quon.msg by opp_msgc.
#include <Quon_m.h>
Public Member Functions
QuonMessage (const char *name=NULL, int kind=0)
QuonMessage (const QuonMessage &other)
virtual ~QuonMessage ()
QuonMessage & operator= (const QuonMessage &other)
virtual QuonMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCommand () const
virtual void setCommand (int command)
virtual NodeHandle & getSender ()
virtual const NodeHandle & getSender () const
virtual void setSender (const NodeHandle &sender)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
virtual double getAOIsize () const
virtual void setAOIsize (double AOIsize)
Protected Member Functions
bool operator== (const QuonMessage &)
Protected Attributes
int command_var
NodeHandle sender_var
Vector2D position_var
double AOIsize_var
Private Member Functions
void copy (const QuonMessage &other)
Detailed Description
Class generated from overlay/quon/Quon.msg by opp_msgc.
 packet QuonMessage extends BaseOverlayMessage
 {
     int command enum(QUONCommand);
     NodeHandle sender;
     Vector2D position;
     double AOIsize;
 }
Definition at line 111 of file Quon_m.h.
Constructor & Destructor Documentation
QuonMessage::QuonMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
QuonMessage::QuonMessage (const QuonMessage & other)
virtual QuonMessage::~QuonMessage () [virtual]
Member Function Documentation
void QuonMessage::copy (const QuonMessage & other) [private]
virtual QuonMessage* QuonMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in QuonEventMessage, QuonMoveMessage, and QuonListMessage.
Definition at line 131 of file Quon_m.h.
{return new QuonMessage(*this);}
virtual double QuonMessage::getAOIsize () const [virtual]
Referenced by Quon::handleJoinAcknowledge(), Quon::handleNewNeighbors(), Quon::handleNodeLeave(), and Quon::handleNodeMove().
virtual int QuonMessage::getCommand () const [virtual]
Referenced by Quon::handleUDPMessage(), and Quon::sendMessage().
virtual Vector2D& QuonMessage::getPosition () [virtual]
Referenced by Quon::handleJoinAcknowledge(), Quon::handleJoinRequest(), Quon::handleNewNeighbors(), and Quon::handleNodeMove().
virtual const Vector2D& QuonMessage::getPosition () const [inline, virtual]
Definition at line 142 of file Quon_m.h.
Referenced by getPosition().
{return const_cast<QuonMessage*>(this)->getPosition();}
virtual NodeHandle& QuonMessage::getSender () [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoinAcknowledge(), Quon::handleJoinRequest(), Quon::handleNewNeighbors(), Quon::handleNodeLeave(), Quon::handleNodeMove(), and Quon::handleUDPMessage().
virtual const NodeHandle& QuonMessage::getSender () const [inline, virtual]
Definition at line 139 of file Quon_m.h.
Referenced by getSender().
{return const_cast<QuonMessage*>(this)->getSender();}
QuonMessage& QuonMessage::operator= (const QuonMessage & other)
bool QuonMessage::operator== (const QuonMessage &) [protected]
virtual void QuonMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in QuonEventMessage, QuonMoveMessage, and QuonListMessage.
Referenced by doPacking().
virtual void QuonMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in QuonEventMessage, QuonMoveMessage, and QuonListMessage.
Referenced by doUnpacking().
virtual void QuonMessage::setAOIsize (double AOIsize) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoin(), Quon::handleJoinAcknowledge(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), Quon::handleNodeMove(), and Quon::processBackupTimer().
virtual void QuonMessage::setCommand (int command) [virtual]
Referenced by Quon::handleEvent(), Quon::handleInvalidNode(), Quon::handleJoin(), Quon::handleJoinAcknowledge(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), Quon::handleNodeMove(), and Quon::processBackupTimer().
virtual void QuonMessage::setPosition (const Vector2D & position) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoin(), Quon::handleJoinAcknowledge(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), Quon::handleNodeMove(), and Quon::processBackupTimer().
virtual void QuonMessage::setSender (const NodeHandle & sender) [virtual]
Referenced by Quon::handleInvalidNode(), Quon::handleJoin(), Quon::handleJoinAcknowledge(), Quon::handleJoinRequest(), Quon::handleMove(), Quon::handleNodeGracefulLeaveNotification(), Quon::handleNodeMove(), and Quon::processBackupTimer().
Member Data Documentation
double QuonMessage::AOIsize_var [protected]
Definition at line 117 of file Quon_m.h.
int QuonMessage::command_var [protected]
Definition at line 114 of file Quon_m.h.
Vector2D QuonMessage::position_var [protected]
Definition at line 116 of file Quon_m.h.
NodeHandle QuonMessage::sender_var [protected]
Definition at line 115 of file Quon_m.h.
The documentation for this class was generated from the following file:
Quon_m.h