OverSim: BaseAppDataMessage Class Reference
BaseAppDataMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BaseAppDataMessage (const char *name=NULL, int kind=0)
BaseAppDataMessage (const BaseAppDataMessage &other)
virtual ~BaseAppDataMessage ()
BaseAppDataMessage & operator= (const BaseAppDataMessage &other)
virtual BaseAppDataMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getDestComp () const
virtual void setDestComp (int destComp)
virtual int getSrcComp () const
virtual void setSrcComp (int srcComp)
Protected Member Functions
bool operator== (const BaseAppDataMessage &)
Protected Attributes
int destComp_var
int srcComp_var
Private Member Functions
void copy (const BaseAppDataMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet BaseAppDataMessage extends BaseOverlayMessage
 {
     int destComp enum(CompType);
     int srcComp enum(CompType);
 }
Definition at line 431 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BaseAppDataMessage::BaseAppDataMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BaseAppDataMessage::BaseAppDataMessage (const BaseAppDataMessage & other)
virtual BaseAppDataMessage::~BaseAppDataMessage () [virtual]
Member Function Documentation
void BaseAppDataMessage::copy (const BaseAppDataMessage & other) [private]
virtual BaseAppDataMessage* BaseAppDataMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 449 of file CommonMessages_m.h.
{return new BaseAppDataMessage(*this);}
virtual int BaseAppDataMessage::getDestComp () const [virtual]
virtual int BaseAppDataMessage::getSrcComp () const [virtual]
BaseAppDataMessage& BaseAppDataMessage::operator= (const BaseAppDataMessage & other)
bool BaseAppDataMessage::operator== (const BaseAppDataMessage &) [protected]
virtual void BaseAppDataMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void BaseAppDataMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void BaseAppDataMessage::setDestComp (int destComp) [virtual]
Referenced by BaseOverlay::route().
virtual void BaseAppDataMessage::setSrcComp (int srcComp) [virtual]
Referenced by BaseOverlay::route().
Member Data Documentation
int BaseAppDataMessage::destComp_var [protected]
Definition at line 434 of file CommonMessages_m.h.
int BaseAppDataMessage::srcComp_var [protected]
Definition at line 435 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h