OverSim: ChildCheckCall Class Reference
ChildCheckCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
ChildCheckCall (const char *name=NULL, int kind=0)
ChildCheckCall (const ChildCheckCall &other)
virtual ~ChildCheckCall ()
ChildCheckCall & operator= (const ChildCheckCall &other)
virtual ChildCheckCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ChildCheckCall &)
Private Member Functions
void copy (const ChildCheckCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet ChildCheckCall extends BaseCallMessage
 {
 }
Definition at line 345 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
ChildCheckCall::ChildCheckCall (const char * name = NULL, int kind = 0)
Referenced by dup().
ChildCheckCall::ChildCheckCall (const ChildCheckCall & other)
virtual ChildCheckCall::~ChildCheckCall () [virtual]
Member Function Documentation
void ChildCheckCall::copy (const ChildCheckCall & other) [private]
virtual ChildCheckCall* ChildCheckCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 361 of file TreeManagementMessage_m.h.
{return new ChildCheckCall(*this);}
ChildCheckCall& ChildCheckCall::operator= (const ChildCheckCall & other)
bool ChildCheckCall::operator== (const ChildCheckCall &) [protected]
virtual void ChildCheckCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void ChildCheckCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h