OverSim: HCapacityResponse Class Reference
HCapacityResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HCapacityResponse (const char *name=NULL, int kind=0)
HCapacityResponse (const HCapacityResponse &other)
virtual ~HCapacityResponse ()
HCapacityResponse & operator= (const HCapacityResponse &other)
virtual HCapacityResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getParentNode ()
virtual const NodeHandle & getParentNode () const
virtual void setParentNode (const NodeHandle &parentNode)
virtual NodeHandle & getRespondingNode ()
virtual const NodeHandle & getRespondingNode () const
virtual void setRespondingNode (const NodeHandle &respondingNode)
virtual int getCapacity () const
virtual void setCapacity (int capacity)
Protected Member Functions
bool operator== (const HCapacityResponse &)
Protected Attributes
NodeHandle parentNode_var
NodeHandle respondingNode_var
int capacity_var
Private Member Functions
void copy (const HCapacityResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HCapacityResponse extends BaseResponseMessage {
     NodeHandle parentNode;
     NodeHandle respondingNode;
     int capacity;
 };
Definition at line 127 of file HMessage_m.h.
Constructor & Destructor Documentation
HCapacityResponse::HCapacityResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HCapacityResponse::HCapacityResponse (const HCapacityResponse & other)
virtual HCapacityResponse::~HCapacityResponse () [virtual]
Member Function Documentation
void HCapacityResponse::copy (const HCapacityResponse & other) [private]
virtual HCapacityResponse* HCapacityResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 146 of file HMessage_m.h.
{return new HCapacityResponse(*this);}
virtual int HCapacityResponse::getCapacity () const [virtual]
Referenced by HTopology::handleCapacityResponse().
virtual NodeHandle& HCapacityResponse::getParentNode () [virtual]
Referenced by HTopology::handleCapacityResponse().
virtual const NodeHandle& HCapacityResponse::getParentNode () const [inline, virtual]
Definition at line 152 of file HMessage_m.h.
Referenced by getParentNode().
{return const_cast<HCapacityResponse*>(this)->getParentNode();}
virtual NodeHandle& HCapacityResponse::getRespondingNode () [virtual]
virtual const NodeHandle& HCapacityResponse::getRespondingNode () const [inline, virtual]
Definition at line 155 of file HMessage_m.h.
Referenced by getRespondingNode().
{return const_cast<HCapacityResponse*>(this)->getRespondingNode();}
HCapacityResponse& HCapacityResponse::operator= (const HCapacityResponse & other)
bool HCapacityResponse::operator== (const HCapacityResponse &) [protected]
virtual void HCapacityResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HCapacityResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HCapacityResponse::setCapacity (int capacity) [virtual]
Referenced by HTopology::handleRpcCall().
virtual void HCapacityResponse::setParentNode (const NodeHandle & parentNode) [virtual]
virtual void HCapacityResponse::setRespondingNode (const NodeHandle & respondingNode) [virtual]
Referenced by HTopology::handleRpcCall().
Member Data Documentation
int HCapacityResponse::capacity_var [protected]
Definition at line 132 of file HMessage_m.h.
NodeHandle HCapacityResponse::parentNode_var [protected]
Definition at line 130 of file HMessage_m.h.
NodeHandle HCapacityResponse::respondingNode_var [protected]
Definition at line 131 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h