OverSim: NTreeJoinCall Class Reference
NTreeJoinCall Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeJoinCall (const char *name=NULL, int kind=0)
NTreeJoinCall (const NTreeJoinCall &other)
virtual ~NTreeJoinCall ()
NTreeJoinCall & operator= (const NTreeJoinCall &other)
virtual NTreeJoinCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getPosition ()
virtual const Vector2D & getPosition () const
virtual void setPosition (const Vector2D &position)
Protected Member Functions
bool operator== (const NTreeJoinCall &)
Protected Attributes
Vector2D position_var
Private Member Functions
void copy (const NTreeJoinCall &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeJoinCall extends BaseCallMessage
 {
         Vector2D position;
 }
Definition at line 53 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeJoinCall::NTreeJoinCall (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeJoinCall::NTreeJoinCall (const NTreeJoinCall & other)
virtual NTreeJoinCall::~NTreeJoinCall () [virtual]
Member Function Documentation
void NTreeJoinCall::copy (const NTreeJoinCall & other) [private]
virtual NTreeJoinCall* NTreeJoinCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 70 of file NTree_m.h.
{return new NTreeJoinCall(*this);}
virtual Vector2D& NTreeJoinCall::getPosition () [virtual]
Referenced by NTree::handleJoinCall().
virtual const Vector2D& NTreeJoinCall::getPosition () const [inline, virtual]
Definition at line 76 of file NTree_m.h.
Referenced by getPosition().
{return const_cast<NTreeJoinCall*>(this)->getPosition();}
NTreeJoinCall& NTreeJoinCall::operator= (const NTreeJoinCall & other)
bool NTreeJoinCall::operator== (const NTreeJoinCall &) [protected]
virtual void NTreeJoinCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void NTreeJoinCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void NTreeJoinCall::setPosition (const Vector2D & position) [virtual]
Referenced by NTree::handleAppMessage(), NTree::handleDeleteMessage(), and NTree::joinGroup().
Member Data Documentation
Vector2D NTreeJoinCall::position_var [protected]
Definition at line 56 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h