OverSim: ALMTestTracedMessage Class Reference
ALMTestTracedMessage Class Reference
Class generated from applications/almtest/ALMTestTracedMessage.msg by opp_msgc.
#include <ALMTestTracedMessage_m.h>
Public Member Functions
ALMTestTracedMessage (const char *name=NULL, int kind=0)
ALMTestTracedMessage (const ALMTestTracedMessage &other)
virtual ~ALMTestTracedMessage ()
ALMTestTracedMessage & operator= (const ALMTestTracedMessage &other)
virtual ALMTestTracedMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getGroupId ()
virtual const OverlayKey & getGroupId () const
virtual void setGroupId (const OverlayKey &groupId)
virtual long getMcastId () const
virtual void setMcastId (long mcastId)
virtual int getSenderId () const
virtual void setSenderId (int senderId)
virtual int getReceiverId () const
virtual void setReceiverId (int receiverId)
Protected Member Functions
bool operator== (const ALMTestTracedMessage &)
Protected Attributes
OverlayKey groupId_var
long mcastId_var
int senderId_var
int receiverId_var
Private Member Functions
void copy (const ALMTestTracedMessage &other)
Detailed Description
Class generated from applications/almtest/ALMTestTracedMessage.msg by opp_msgc.
 packet ALMTestTracedMessage
 {
     OverlayKey groupId;
     long mcastId;
     int senderId;
     int receiverId;
 }
Definition at line 43 of file ALMTestTracedMessage_m.h.
Constructor & Destructor Documentation
ALMTestTracedMessage::ALMTestTracedMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMTestTracedMessage::ALMTestTracedMessage (const ALMTestTracedMessage & other)
virtual ALMTestTracedMessage::~ALMTestTracedMessage () [virtual]
Member Function Documentation
void ALMTestTracedMessage::copy (const ALMTestTracedMessage & other) [private]
virtual ALMTestTracedMessage* ALMTestTracedMessage::dup () const [inline, virtual]
Definition at line 63 of file ALMTestTracedMessage_m.h.
{return new ALMTestTracedMessage(*this);}
virtual OverlayKey& ALMTestTracedMessage::getGroupId () [virtual]
Referenced by MessageObserver::receivedMessage(), and MessageObserver::sentMessage().
virtual const OverlayKey& ALMTestTracedMessage::getGroupId () const [inline, virtual]
Definition at line 69 of file ALMTestTracedMessage_m.h.
Referenced by getGroupId().
{return const_cast<ALMTestTracedMessage*>(this)->getGroupId();}
virtual long ALMTestTracedMessage::getMcastId () const [virtual]
Referenced by MessageObserver::receivedMessage().
virtual int ALMTestTracedMessage::getReceiverId () const [virtual]
Referenced by MessageObserver::receivedMessage().
virtual int ALMTestTracedMessage::getSenderId () const [virtual]
Referenced by MessageObserver::receivedMessage().
ALMTestTracedMessage& ALMTestTracedMessage::operator= (const ALMTestTracedMessage & other)
bool ALMTestTracedMessage::operator== (const ALMTestTracedMessage &) [protected]
virtual void ALMTestTracedMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ALMTestTracedMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ALMTestTracedMessage::setGroupId (const OverlayKey & groupId) [virtual]
Referenced by ALMTest::sendDataToGroup().
virtual void ALMTestTracedMessage::setMcastId (long mcastId) [virtual]
Referenced by ALMTest::sendDataToGroup().
virtual void ALMTestTracedMessage::setReceiverId (int receiverId) [virtual]
Referenced by ALMTest::handleMCast().
virtual void ALMTestTracedMessage::setSenderId (int senderId) [virtual]
Referenced by ALMTest::sendDataToGroup().
Member Data Documentation
OverlayKey ALMTestTracedMessage::groupId_var [protected]
Definition at line 46 of file ALMTestTracedMessage_m.h.
long ALMTestTracedMessage::mcastId_var [protected]
Definition at line 47 of file ALMTestTracedMessage_m.h.
int ALMTestTracedMessage::receiverId_var [protected]
Definition at line 49 of file ALMTestTracedMessage_m.h.
int ALMTestTracedMessage::senderId_var [protected]
Definition at line 48 of file ALMTestTracedMessage_m.h.
The documentation for this class was generated from the following file:
ALMTestTracedMessage_m.h