OverSim: BootstrapNodeHandle Class Reference
BootstrapNodeHandle Class Reference
#include <BootstrapNodeHandle.h>
Public Member Functions
BootstrapNodeHandle ()
BootstrapNodeHandle (const BootstrapNodeHandle &handle)
BootstrapNodeHandle (const NodeHandle &handle, BootstrapNodePrioType prio=CACHE)
BootstrapNodeHandle (const OverlayKey &key, const IPvXAddress &ip, int port, BootstrapNodePrioType prio=CACHE)
BootstrapNodePrioType getNodePrio () const
void setNodePrio (BootstrapNodePrioType nodePrio)
simtime_t getLastPing () const
void setLastPing (simtime_t lastPing)
Private Attributes
BootstrapNodePrioType nodePrio
simtime_t lastPing
Detailed Description
Definition at line 33 of file BootstrapNodeHandle.h.
Constructor & Destructor Documentation
BootstrapNodeHandle::BootstrapNodeHandle () [inline]
Definition at line 40 of file BootstrapNodeHandle.h.
                          : NodeHandle()
    {
        /* lowest priority */
        nodePrio = CACHE;
    }
BootstrapNodeHandle::BootstrapNodeHandle (const BootstrapNodeHandle & handle) [inline]
Definition at line 46 of file BootstrapNodeHandle.h.
                                                           : NodeHandle(handle)
    {
        nodePrio = handle.nodePrio;
    }
BootstrapNodeHandle::BootstrapNodeHandle (const NodeHandle & handle, BootstrapNodePrioType prio = CACHE) [inline]
Definition at line 51 of file BootstrapNodeHandle.h.
    {
        this->ip = handle.getIp();
        this->port = handle.getPort();
        this->key = handle.getKey();
        nodePrio = prio;
    }
BootstrapNodeHandle::BootstrapNodeHandle (const OverlayKey & key, const IPvXAddress & ip, int port, BootstrapNodePrioType prio = CACHE) [inline]
Definition at line 60 of file BootstrapNodeHandle.h.
                        : NodeHandle(key, ip, port)   {
        nodePrio = prio;
    }
Member Function Documentation
simtime_t BootstrapNodeHandle::getLastPing () const [inline]
Definition at line 76 of file BootstrapNodeHandle.h.
Referenced by BootstrapList::handleBootstrapListTimerExpired(), BootstrapList::insertBootstrapCandidate(), and operator<<().
{
        return lastPing;
    }
BootstrapNodePrioType BootstrapNodeHandle::getNodePrio () const [inline]
Definition at line 68 of file BootstrapNodeHandle.h.
Referenced by BootstrapList::insertBootstrapCandidate(), and operator<<().
{
        return nodePrio;
    }
void BootstrapNodeHandle::setLastPing (simtime_t lastPing) [inline]
Definition at line 80 of file BootstrapNodeHandle.h.
Referenced by BootstrapList::insertBootstrapCandidate().
{
        this->lastPing = lastPing;
    }
void BootstrapNodeHandle::setNodePrio (BootstrapNodePrioType nodePrio) [inline]
Definition at line 72 of file BootstrapNodeHandle.h.
{
        this->nodePrio = nodePrio;
    }
Member Data Documentation
simtime_t BootstrapNodeHandle::lastPing [private]
Definition at line 37 of file BootstrapNodeHandle.h.
Referenced by getLastPing(), and setLastPing().
BootstrapNodePrioType BootstrapNodeHandle::nodePrio [private]
Definition at line 36 of file BootstrapNodeHandle.h.
Referenced by BootstrapNodeHandle(), getNodePrio(), and setNodePrio().
The documentation for this class was generated from the following file:
BootstrapNodeHandle.h