OverSim: RttToNodeCall Class Reference
RttToNodeCall Class Reference
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
#include <CoordMessages_m.h>
Public Member Functions
RttToNodeCall (const char *name=NULL, int kind=0)
RttToNodeCall (const RttToNodeCall &other)
virtual ~RttToNodeCall ()
RttToNodeCall & operator= (const RttToNodeCall &other)
virtual RttToNodeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getNodeToPing ()
virtual const TransportAddress & getNodeToPing () const
virtual void setNodeToPing (const TransportAddress &nodeToPing)
Protected Member Functions
bool operator== (const RttToNodeCall &)
Protected Attributes
TransportAddress nodeToPing_var
Private Member Functions
void copy (const RttToNodeCall &other)
Detailed Description
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
 packet RttToNodeCall extends BaseCallMessage
 {
     TransportAddress nodeToPing;
 }
Definition at line 71 of file CoordMessages_m.h.
Constructor & Destructor Documentation
RttToNodeCall::RttToNodeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
RttToNodeCall::RttToNodeCall (const RttToNodeCall & other)
virtual RttToNodeCall::~RttToNodeCall () [virtual]
Member Function Documentation
void RttToNodeCall::copy (const RttToNodeCall & other) [private]
virtual RttToNodeCall* RttToNodeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 88 of file CoordMessages_m.h.
{return new RttToNodeCall(*this);}
virtual TransportAddress& RttToNodeCall::getNodeToPing () [virtual]
virtual const TransportAddress& RttToNodeCall::getNodeToPing () const [inline, virtual]
Definition at line 94 of file CoordMessages_m.h.
Referenced by getNodeToPing().
{return const_cast<RttToNodeCall*>(this)->getNodeToPing();}
RttToNodeCall& RttToNodeCall::operator= (const RttToNodeCall & other)
bool RttToNodeCall::operator== (const RttToNodeCall &) [protected]
virtual void RttToNodeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void RttToNodeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void RttToNodeCall::setNodeToPing (const TransportAddress & nodeToPing) [virtual]
Member Data Documentation
TransportAddress RttToNodeCall::nodeToPing_var [protected]
Definition at line 74 of file CoordMessages_m.h.
The documentation for this class was generated from the following file:
CoordMessages_m.h