OverSim: KoordeFindNodeExtMessage Class Reference
KoordeFindNodeExtMessage Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
KoordeFindNodeExtMessage (const char *name=NULL, int kind=0)
KoordeFindNodeExtMessage (const KoordeFindNodeExtMessage &other)
virtual ~KoordeFindNodeExtMessage ()
KoordeFindNodeExtMessage & operator= (const KoordeFindNodeExtMessage &other)
virtual KoordeFindNodeExtMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getRouteKey ()
virtual const OverlayKey & getRouteKey () const
virtual void setRouteKey (const OverlayKey &routeKey)
virtual int getStep () const
virtual void setStep (int step)
Protected Member Functions
bool operator== (const KoordeFindNodeExtMessage &)
Protected Attributes
OverlayKey routeKey_var
int step_var
Private Member Functions
void copy (const KoordeFindNodeExtMessage &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet KoordeFindNodeExtMessage
 {
     OverlayKey routeKey;
     int step;
 }
Definition at line 495 of file ChordMessage_m.h.
Constructor & Destructor Documentation
KoordeFindNodeExtMessage::KoordeFindNodeExtMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
KoordeFindNodeExtMessage::KoordeFindNodeExtMessage (const KoordeFindNodeExtMessage & other)
virtual KoordeFindNodeExtMessage::~KoordeFindNodeExtMessage () [virtual]
Member Function Documentation
void KoordeFindNodeExtMessage::copy (const KoordeFindNodeExtMessage & other) [private]
virtual KoordeFindNodeExtMessage* KoordeFindNodeExtMessage::dup () const [inline, virtual]
Definition at line 513 of file ChordMessage_m.h.
{return new KoordeFindNodeExtMessage(*this);}
virtual OverlayKey& KoordeFindNodeExtMessage::getRouteKey () [virtual]
Referenced by oversim::Koorde::findDeBruijnHop().
virtual const OverlayKey& KoordeFindNodeExtMessage::getRouteKey () const [inline, virtual]
Definition at line 519 of file ChordMessage_m.h.
Referenced by getRouteKey().
{return const_cast<KoordeFindNodeExtMessage*>(this)->getRouteKey();}
virtual int KoordeFindNodeExtMessage::getStep () const [virtual]
Referenced by oversim::Koorde::findDeBruijnHop().
KoordeFindNodeExtMessage& KoordeFindNodeExtMessage::operator= (const KoordeFindNodeExtMessage & other)
bool KoordeFindNodeExtMessage::operator== (const KoordeFindNodeExtMessage &) [protected]
virtual void KoordeFindNodeExtMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void KoordeFindNodeExtMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void KoordeFindNodeExtMessage::setRouteKey (const OverlayKey & routeKey) [virtual]
Referenced by oversim::Koorde::findDeBruijnHop(), and oversim::Koorde::findNode().
virtual void KoordeFindNodeExtMessage::setStep (int step) [virtual]
Referenced by oversim::Koorde::findDeBruijnHop(), and oversim::Koorde::findNode().
Member Data Documentation
OverlayKey KoordeFindNodeExtMessage::routeKey_var [protected]
Definition at line 498 of file ChordMessage_m.h.
int KoordeFindNodeExtMessage::step_var [protected]
Definition at line 499 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h