OverSim: NTreeDivideCall Class Reference
NTreeDivideCall Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeDivideCall (const char *name=NULL, int kind=0)
NTreeDivideCall (const NTreeDivideCall &other)
virtual ~NTreeDivideCall ()
NTreeDivideCall & operator= (const NTreeDivideCall &other)
virtual NTreeDivideCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual int getQuadrant () const
virtual void setQuadrant (int quadrant)
Protected Member Functions
bool operator== (const NTreeDivideCall &)
Protected Attributes
Vector2D origin_var
double size_var
int quadrant_var
Private Member Functions
void copy (const NTreeDivideCall &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeDivideCall extends BaseCallMessage
 {
         Vector2D origin;
         double size;
         int quadrant;
 }
Definition at line 145 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeDivideCall::NTreeDivideCall (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeDivideCall::NTreeDivideCall (const NTreeDivideCall & other)
virtual NTreeDivideCall::~NTreeDivideCall () [virtual]
Member Function Documentation
void NTreeDivideCall::copy (const NTreeDivideCall & other) [private]
virtual NTreeDivideCall* NTreeDivideCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 164 of file NTree_m.h.
Referenced by NTree::handleDivideCallTimeout(), and NTree::handleJoinCall().
{return new NTreeDivideCall(*this);}
virtual Vector2D& NTreeDivideCall::getOrigin () [virtual]
Referenced by NTree::handleDivideCall().
virtual const Vector2D& NTreeDivideCall::getOrigin () const [inline, virtual]
Definition at line 170 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeDivideCall*>(this)->getOrigin();}
virtual int NTreeDivideCall::getQuadrant () const [virtual]
Referenced by NTree::handleDivideCall().
virtual double NTreeDivideCall::getSize () const [virtual]
Referenced by NTree::handleDivideCall().
NTreeDivideCall& NTreeDivideCall::operator= (const NTreeDivideCall & other)
bool NTreeDivideCall::operator== (const NTreeDivideCall &) [protected]
virtual void NTreeDivideCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void NTreeDivideCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void NTreeDivideCall::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::handleJoinCall().
virtual void NTreeDivideCall::setQuadrant (int quadrant) [virtual]
Referenced by NTree::handleJoinCall().
virtual void NTreeDivideCall::setSize (double size) [virtual]
Referenced by NTree::handleJoinCall().
Member Data Documentation
Vector2D NTreeDivideCall::origin_var [protected]
Definition at line 148 of file NTree_m.h.
int NTreeDivideCall::quadrant_var [protected]
Definition at line 150 of file NTree_m.h.
double NTreeDivideCall::size_var [protected]
Definition at line 149 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h