OverSim: BucketResponse Class Reference
BucketResponse Class Reference
Class generated from overlay/broose/BrooseMessage.msg by opp_msgc.
#include <BrooseMessage_m.h>
Public Member Functions
BucketResponse (const char *name=NULL, int kind=0)
BucketResponse (const BucketResponse &other)
virtual ~BucketResponse ()
BucketResponse & operator= (const BucketResponse &other)
virtual BucketResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setNodesArraySize (unsigned int size)
virtual unsigned int getNodesArraySize () const
virtual NodeHandle & getNodes (unsigned int k)
virtual const NodeHandle & getNodes (unsigned int k) const
virtual void setNodes (unsigned int k, const NodeHandle &nodes)
Protected Member Functions
bool operator== (const BucketResponse &)
Protected Attributes
NodeHandle * nodes_var
unsigned int nodes_arraysize
Private Member Functions
void copy (const BucketResponse &other)
Detailed Description
Class generated from overlay/broose/BrooseMessage.msg by opp_msgc.
 packet BucketResponse extends BaseResponseMessage
 {
        NodeHandle nodes[];
 }
Definition at line 131 of file BrooseMessage_m.h.
Constructor & Destructor Documentation
BucketResponse::BucketResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
BucketResponse::BucketResponse (const BucketResponse & other)
virtual BucketResponse::~BucketResponse () [virtual]
Member Function Documentation
void BucketResponse::copy (const BucketResponse & other) [private]
virtual BucketResponse* BucketResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 149 of file BrooseMessage_m.h.
{return new BucketResponse(*this);}
virtual NodeHandle& BucketResponse::getNodes (unsigned int k) [virtual]
Referenced by Broose::handleBucketResponseRpc().
virtual const NodeHandle& BucketResponse::getNodes (unsigned int k) const [inline, virtual]
Definition at line 157 of file BrooseMessage_m.h.
Referenced by getNodes().
{return const_cast<BucketResponse*>(this)->getNodes(k);}
virtual unsigned int BucketResponse::getNodesArraySize () const [virtual]
Referenced by Broose::handleBucketResponseRpc().
BucketResponse& BucketResponse::operator= (const BucketResponse & other)
bool BucketResponse::operator== (const BucketResponse &) [protected]
virtual void BucketResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void BucketResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void BucketResponse::setNodes (unsigned int k, const NodeHandle & nodes) [virtual]
Referenced by Broose::handleBucketRequestRpc().
virtual void BucketResponse::setNodesArraySize (unsigned int size) [virtual]
Referenced by Broose::handleBucketRequestRpc().
Member Data Documentation
unsigned int BucketResponse::nodes_arraysize [protected]
Definition at line 135 of file BrooseMessage_m.h.
NodeHandle* BucketResponse::nodes_var [protected]
Definition at line 134 of file BrooseMessage_m.h.
The documentation for this class was generated from the following file:
BrooseMessage_m.h