OverSim: NotifyCall Class Reference
NotifyCall Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
NotifyCall (const char *name=NULL, int kind=0)
NotifyCall (const NotifyCall &other)
virtual ~NotifyCall ()
NotifyCall & operator= (const NotifyCall &other)
virtual NotifyCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getFailed ()
virtual const TransportAddress & getFailed () const
virtual void setFailed (const TransportAddress &failed)
Protected Member Functions
bool operator== (const NotifyCall &)
Protected Attributes
TransportAddress failed_var
Private Member Functions
void copy (const NotifyCall &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet NotifyCall extends BaseCallMessage
 {
     TransportAddress failed = TransportAddress::UNSPECIFIED_NODE;
 }
Definition at line 158 of file ChordMessage_m.h.
Constructor & Destructor Documentation
NotifyCall::NotifyCall (const char * name = NULL, int kind = 0)
Referenced by dup().
NotifyCall::NotifyCall (const NotifyCall & other)
virtual NotifyCall::~NotifyCall () [virtual]
Member Function Documentation
void NotifyCall::copy (const NotifyCall & other) [private]
virtual NotifyCall* NotifyCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 175 of file ChordMessage_m.h.
{return new NotifyCall(*this);}
virtual TransportAddress& NotifyCall::getFailed () [virtual]
Referenced by oversim::Chord::rpcNotify().
virtual const TransportAddress& NotifyCall::getFailed () const [inline, virtual]
Definition at line 181 of file ChordMessage_m.h.
Referenced by getFailed().
{return const_cast<NotifyCall*>(this)->getFailed();}
NotifyCall& NotifyCall::operator= (const NotifyCall & other)
bool NotifyCall::operator== (const NotifyCall &) [protected]
virtual void NotifyCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void NotifyCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void NotifyCall::setFailed (const TransportAddress & failed) [virtual]
Referenced by oversim::Chord::handleRpcStabilizeResponse().
Member Data Documentation
TransportAddress NotifyCall::failed_var [protected]
Definition at line 161 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h