OverSim: P2pnsResolveCall Class Reference
P2pnsResolveCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
P2pnsResolveCall (const char *name=NULL, int kind=0)
P2pnsResolveCall (const P2pnsResolveCall &other)
virtual ~P2pnsResolveCall ()
P2pnsResolveCall & operator= (const P2pnsResolveCall &other)
virtual P2pnsResolveCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual BinaryValue & getP2pName ()
virtual const BinaryValue & getP2pName () const
virtual void setP2pName (const BinaryValue &p2pName)
virtual uint32_t getKind () const
virtual void setKind (uint32_t kind)
virtual uint32_t getId () const
virtual void setId (uint32_t id)
Protected Member Functions
bool operator== (const P2pnsResolveCall &)
Protected Attributes
BinaryValue p2pName_var
uint32_t kind_var
uint32_t id_var
Private Member Functions
void copy (const P2pnsResolveCall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet P2pnsResolveCall extends BaseCallMessage
 {
     BinaryValue p2pName;
     uint32_t kind = 1;
     uint32_t id = 1;
 }
Definition at line 1868 of file CommonMessages_m.h.
Constructor & Destructor Documentation
P2pnsResolveCall::P2pnsResolveCall (const char * name = NULL, int kind = 0)
Referenced by dup().
P2pnsResolveCall::P2pnsResolveCall (const P2pnsResolveCall & other)
virtual P2pnsResolveCall::~P2pnsResolveCall () [virtual]
Member Function Documentation
void P2pnsResolveCall::copy (const P2pnsResolveCall & other) [private]
virtual P2pnsResolveCall* P2pnsResolveCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 1887 of file CommonMessages_m.h.
{return new P2pnsResolveCall(*this);}
virtual uint32_t P2pnsResolveCall::getId () const [virtual]
Referenced by P2pns::p2pnsResolveRpc().
virtual uint32_t P2pnsResolveCall::getKind () const [virtual]
Referenced by P2pns::p2pnsResolveRpc().
virtual BinaryValue& P2pnsResolveCall::getP2pName () [virtual]
Referenced by P2pns::handleDHTgetCAPIResponse(), P2pns::handleLookupResponse(), and P2pns::p2pnsResolveRpc().
virtual const BinaryValue& P2pnsResolveCall::getP2pName () const [inline, virtual]
Definition at line 1893 of file CommonMessages_m.h.
Referenced by getP2pName().
{return const_cast<P2pnsResolveCall*>(this)->getP2pName();}
P2pnsResolveCall& P2pnsResolveCall::operator= (const P2pnsResolveCall & other)
bool P2pnsResolveCall::operator== (const P2pnsResolveCall &) [protected]
virtual void P2pnsResolveCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void P2pnsResolveCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void P2pnsResolveCall::setId (uint32_t id) [virtual]
Referenced by XmlRpcInterface::p2pnsResolve().
virtual void P2pnsResolveCall::setKind (uint32_t kind) [virtual]
Referenced by XmlRpcInterface::p2pnsResolve().
virtual void P2pnsResolveCall::setP2pName (const BinaryValue & p2pName) [virtual]
Referenced by XmlRpcInterface::p2pnsResolve().
Member Data Documentation
uint32_t P2pnsResolveCall::id_var [protected]
Definition at line 1873 of file CommonMessages_m.h.
uint32_t P2pnsResolveCall::kind_var [protected]
Definition at line 1872 of file CommonMessages_m.h.
BinaryValue P2pnsResolveCall::p2pName_var [protected]
Definition at line 1871 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h