OverSim: NTreeTakeOverMessage Class Reference
NTreeTakeOverMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeTakeOverMessage (const char *name=NULL, int kind=0)
NTreeTakeOverMessage (const NTreeTakeOverMessage &other)
virtual ~NTreeTakeOverMessage ()
NTreeTakeOverMessage & operator= (const NTreeTakeOverMessage &other)
virtual NTreeTakeOverMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual NodeHandle & getPlayer ()
virtual const NodeHandle & getPlayer () const
virtual void setPlayer (const NodeHandle &player)
Protected Member Functions
bool operator== (const NTreeTakeOverMessage &)
Protected Attributes
Vector2D origin_var
double size_var
NodeHandle player_var
Private Member Functions
void copy (const NTreeTakeOverMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeTakeOverMessage extends BaseOverlayMessage
 {
         Vector2D origin;
         double size;
         NodeHandle player;
 }
Definition at line 696 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeTakeOverMessage::NTreeTakeOverMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeTakeOverMessage::NTreeTakeOverMessage (const NTreeTakeOverMessage & other)
virtual NTreeTakeOverMessage::~NTreeTakeOverMessage () [virtual]
Member Function Documentation
void NTreeTakeOverMessage::copy (const NTreeTakeOverMessage & other) [private]
virtual NTreeTakeOverMessage* NTreeTakeOverMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 715 of file NTree_m.h.
Referenced by NTree::handleReplaceMessage().
{return new NTreeTakeOverMessage(*this);}
virtual Vector2D& NTreeTakeOverMessage::getOrigin () [virtual]
Referenced by NTree::handleTakeOverMessage().
virtual const Vector2D& NTreeTakeOverMessage::getOrigin () const [inline, virtual]
Definition at line 721 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeTakeOverMessage*>(this)->getOrigin();}
virtual NodeHandle& NTreeTakeOverMessage::getPlayer () [virtual]
Referenced by NTree::handleTakeOverMessage().
virtual const NodeHandle& NTreeTakeOverMessage::getPlayer () const [inline, virtual]
Definition at line 726 of file NTree_m.h.
Referenced by getPlayer().
{return const_cast<NTreeTakeOverMessage*>(this)->getPlayer();}
virtual double NTreeTakeOverMessage::getSize () const [virtual]
Referenced by NTree::handleTakeOverMessage().
NTreeTakeOverMessage& NTreeTakeOverMessage::operator= (const NTreeTakeOverMessage & other)
bool NTreeTakeOverMessage::operator== (const NTreeTakeOverMessage &) [protected]
virtual void NTreeTakeOverMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeTakeOverMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeTakeOverMessage::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::handleReplaceMessage().
virtual void NTreeTakeOverMessage::setPlayer (const NodeHandle & player) [virtual]
Referenced by NTree::handleReplaceMessage().
virtual void NTreeTakeOverMessage::setSize (double size) [virtual]
Referenced by NTree::handleReplaceMessage().
Member Data Documentation
Vector2D NTreeTakeOverMessage::origin_var [protected]
Definition at line 699 of file NTree_m.h.
NodeHandle NTreeTakeOverMessage::player_var [protected]
Definition at line 701 of file NTree_m.h.
double NTreeTakeOverMessage::size_var [protected]
Definition at line 700 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h