OverSim: Bamboo Class Reference
Bamboo Class Reference
Bamboo overlay module.
#include <Bamboo.h>
Public Member Functions
virtual ~Bamboo ()
virtual void initializeOverlay (int stage)
Initializes derived-class-attributes.
virtual void handleTimerEvent (cMessage *msg)
void handleRpcResponse (BaseResponseMessage *msg, cPolymorphic *context, int rpcId, simtime_t rtt)
This method is called if an RPC response has been received.
void handleRequestLeafSetResponse (RequestLeafSetResponse *response)
void handleStateMessage (PastryStateMessage *msg)
processes state messages, merging with own state tables
Protected Member Functions
void lookupFinished (AbstractLookup *lookup)
virtual void changeState (int toState)
changes node state
Private Member Functions
void doLeafsetMaintenance (void)
periodically repairs the leafset by pushing it to and pulling it from from a random live leafset node
int getNextRowToMaintain ()
void doLocalTuning ()
void doGlobalTuning (void)
periodically repairs the routing table by performing random lookups
bool handleFailedNode (const TransportAddress &failed)
notifies leafset and routingtable of a failed node and sends out a repair request if possible
void checkProxCache (void)
checks whether proxCache is complete, takes appropriate actions depending on the protocol state
virtual void joinOverlay ()
Join the overlay with a given nodeID in thisNode.key.
Private Attributes
uint16_t rowToAsk
simtime_t leafsetMaintenanceInterval
simtime_t localTuningInterval
simtime_t globalTuningInterval
cMessage * leafsetMaintenanceTimer
cMessage * globalTuningTimer
cMessage * localTuningTimer
Friends
class BambooLookupListener
Detailed Description
Bamboo overlay module.
Author:
Gerhard Petruschat
See also:
BaseOverlay
Definition at line 53 of file Bamboo.h.
Constructor & Destructor Documentation
Bamboo::~Bamboo () [virtual]
Definition at line 41 of file Bamboo.cc.
{
    // destroy self timer messages
    cancelAndDelete(localTuningTimer);
    cancelAndDelete(leafsetMaintenanceTimer);
    cancelAndDelete(globalTuningTimer);
}
Member Function Documentation
void Bamboo::changeState (int toState) [protected, virtual]
changes node state
Parameters:
toState state to change to
Reimplemented from BasePastry.
Definition at line 86 of file Bamboo.cc.
Referenced by checkProxCache(), and joinOverlay().
{
    baseChangeState(toState);
    switch (toState) {
    case INIT:
        break;
    case DISCOVERY:
        break;
    case JOIN: {
        EV << "[Bamboo::changeState()]\n"
           << "    sending join message via " << bootstrapNode
           << " to " << thisNode.getKey()
           << endl;
        RequestLeafSetCall* call = new RequestLeafSetCall("JOIN Call");
        call->setTimestamp(simTime());
        call->setStatType(MAINTENANCE_STAT);
        call->setBitLength(PASTRYREQUESTLEAFSETCALL_L(call));
        call->encapsulate(createStateMessage(PASTRY_STATE_LEAFSET));
        RECORD_STATS(leafsetReqSent++;
                     leafsetReqBytesSent += call->getByteLength());
        sendRouteRpcCall(OVERLAY_COMP, bootstrapNode, thisNode.getKey(), call);
    }
    break;
    case READY:
        cancelEvent(leafsetMaintenanceTimer);
        scheduleAt(simTime(), leafsetMaintenanceTimer);
        // schedule routing table maintenance task
        cancelEvent(localTuningTimer);
        scheduleAt(simTime() + localTuningInterval, localTuningTimer);
        cancelEvent(globalTuningTimer);
        scheduleAt(simTime() + globalTuningInterval, globalTuningTimer);
        break;
    }
}
void Bamboo::checkProxCache (void) [private, virtual]
checks whether proxCache is complete, takes appropriate actions depending on the protocol state
Implements BasePastry.
Definition at line 323 of file Bamboo.cc.
Referenced by handleStateMessage(), and lookupFinished().
{
    // no cached STATE message?
    if (stateCache.msg) {
        simtime_t now = simTime();
        if (stateCache.prox) {
            // some entries not yet determined?
            if ((find(stateCache.prox->pr_rt.begin(), stateCache.prox->pr_rt.end(),
                      PASTRY_PROX_PENDING) != stateCache.prox->pr_rt.end()) ||
                (find(stateCache.prox->pr_ls.begin(), stateCache.prox->pr_ls.end(),
                      PASTRY_PROX_PENDING) != stateCache.prox->pr_ls.end()) ||
                (find(stateCache.prox->pr_ns.begin(), stateCache.prox->pr_ns.end(),
                      PASTRY_PROX_PENDING) != stateCache.prox->pr_ns.end())) {
                return;
            }
        }
        // merge info in own state tables
        // except leafset (was already handled in handleStateMessage)
        if (neighborhoodSet->mergeState(stateCache.msg, stateCache.prox)) {
            lastStateChange = now;
        }
        if (routingTable->mergeState(stateCache.msg, stateCache.prox)) {
            lastStateChange = now;
            EV << "[Bamboo::checkProxCache()]\n"
                    << "    Merged nodes into routing table."
                    << endl;
        }
    }
    delete stateCache.msg;
    stateCache.msg = NULL;
    delete stateCache.prox;
    stateCache.prox = NULL;
    if (state == JOIN) {
        changeState(READY);
    }
    updateTooltip();
    // process next queued message:
    if (! stateCacheQueue.empty()) {
        stateCache = stateCacheQueue.front();
              stateCacheQueue.pop();
        if (proximityNeighborSelection) {
            pingNodes();
        } else {
            checkProxCache();
        }
    }
}
void Bamboo::doGlobalTuning (void) [private]
periodically repairs the routing table by performing random lookups
Definition at line 275 of file Bamboo.cc.
Referenced by handleTimerEvent().
{
    int digit = getNextRowToMaintain();
    // would be a better alternative
    //OverlayKey OverlayKey::randomSuffix(uint pos) const;
    uint32_t maxDigitIndex = OverlayKey::getLength() - bitsPerDigit;
    uint32_t maxKeyIndex = OverlayKey::getLength() - 1;
    OverlayKey newKey = OverlayKey::random();
    while (newKey.getBitRange(maxDigitIndex - digit * bitsPerDigit, bitsPerDigit) ==
           thisNode.getKey().getBitRange(maxDigitIndex - digit * bitsPerDigit, bitsPerDigit)) {
        newKey = OverlayKey::random();
    }
    assert(digit * bitsPerDigit < OverlayKey::getLength());
    for (uint16_t i = 0; i < digit * bitsPerDigit; ++i) {
        newKey[maxKeyIndex - i] = thisNode.getKey().getBit(maxKeyIndex - i);
    }
    createLookup()->lookup(newKey, 1, 0, 0, new BambooLookupListener(this));
}
void Bamboo::doLeafsetMaintenance (void) [private]
periodically repairs the leafset by pushing it to and pulling it from from a random live leafset node
Definition at line 202 of file Bamboo.cc.
Referenced by handleTimerEvent().
{
    const TransportAddress& ask = leafSet->getRandomNode();
    if (!ask.isUnspecified()) {
        EV << "[Bamboo::doLeafsetMaintenance()]\n"
           << "    leafset maintenance: pulling leafset from "
           << ask << endl;
        RequestLeafSetCall* call = new RequestLeafSetCall("LeafSet PULL");
        call->setTimestamp(simTime());
        call->setStatType(MAINTENANCE_STAT);
        call->setBitLength(PASTRYREQUESTLEAFSETCALL_L(call));
        call->encapsulate(createStateMessage(PASTRY_STATE_LEAFSET));
        RECORD_STATS(leafsetReqSent++;
                     leafsetReqBytesSent += call->getByteLength());
        sendUdpRpcCall(ask, call);
    }
}
void Bamboo::doLocalTuning () [private]
Definition at line 250 of file Bamboo.cc.
Referenced by handleTimerEvent().
{
    rowToAsk = getNextRowToMaintain();
    const TransportAddress& ask4row = routingTable->getRandomNode(rowToAsk);
    if ((!ask4row.isUnspecified()) && (ask4row != thisNode)) {
        EV << "[Bamboo::doLocalTuning() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    Sending  Message to Node in Row" << rowToAsk
           << endl;
        RequestRoutingRowCall* call =
            new RequestRoutingRowCall("REQUEST ROUTINGROW Call (Local Tuning)");
        call->setStatType(MAINTENANCE_STAT);
        call->setRow(rowToAsk + 1);
        call->setBitLength(PASTRYREQUESTROUTINGROWCALL_L(call));
        RECORD_STATS(routingTableRowReqSent++;
                     routingTableRowReqBytesSent += call->getByteLength());
        sendUdpRpcCall(ask4row, call);
    }
}
int Bamboo::getNextRowToMaintain () [private]
Definition at line 224 of file Bamboo.cc.
Referenced by doGlobalTuning(), and doLocalTuning().
{
    int digit = 0;
    int lastRow = routingTable->getLastRow();
    int* choices = new int[lastRow + 1];
    int sum = 0;
    for (int i = 0; i < lastRow; ++i) {
        sum += (choices[i] = lastRow - i);
    }
    int rval = intuniform(0, sum);
    while (true) {
        rval -= choices [digit];
        if (rval <= 0)
            break;
        ++digit;
    }
    delete[] choices;
    return digit;
}
bool Bamboo::handleFailedNode (const TransportAddress & failed) [private, virtual]
notifies leafset and routingtable of a failed node and sends out a repair request if possible
Parameters:
failed the failed node
Returns:
true as long as local state is READY (signals lookup to try again)
Reimplemented from BaseOverlay.
Definition at line 299 of file Bamboo.cc.
{
    if (state != READY) return false;
    if (failed.isUnspecified()) {
        throw cRuntimeError("Bamboo::handleFailedNode(): failed is unspecified!");
    }
    const TransportAddress& lsAsk = leafSet->failedNode(failed);
    routingTable->failedNode(failed);
    neighborhoodSet->failedNode(failed);
    if (lsAsk.isUnspecified() && (! leafSet->isValid())) {
        EV << "[Bamboo::handleFailedNode()]\n"
           << "    lost connection to the network, trying to re-join."
           << endl;
        join();
        return false;
    }
    return true;
}
void Bamboo::handleRequestLeafSetResponse (RequestLeafSetResponse * response) [virtual]
Reimplemented from BasePastry.
Definition at line 183 of file Bamboo.cc.
Referenced by handleRpcResponse().
{
    EV << "[Bamboo::handleRequestLeafSetResponse() @ " << thisNode.getIp()
       << " (" << thisNode.getKey().toString(16) << ")]"
       << endl;
    if (state == JOIN) {
        PastryStateMessage* stateMsg =
             check_and_cast<PastryStateMessage*>(response->decapsulate());
        stateMsg->setLeafSetArraySize(stateMsg->getLeafSetArraySize() + 1);
        stateMsg->setLeafSet(stateMsg->getLeafSetArraySize() - 1,
                             stateMsg->getSender());
        handleStateMessage(stateMsg);
    }
}
void Bamboo::handleRpcResponse (BaseResponseMessage * msg, cPolymorphic * context, int rpcId, simtime_t rtt) [virtual]
This method is called if an RPC response has been received.
Parameters:
msg The response message.
context Pointer to an optional state object. The object has to be handled/deleted by the handleRpcResponse() code
rpcId The RPC id.
rtt The Round-Trip-Time of this RPC
Reimplemented from BasePastry.
Definition at line 162 of file Bamboo.cc.
{
    BasePastry::handleRpcResponse(msg, context, rpcId, rtt);
    RPC_SWITCH_START( msg )
    RPC_ON_RESPONSE( RequestLeafSet ) {
        EV << "[Bamboo::handleRpcResponse() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    Received a RequestLeafSet RPC Response (PUSH): id="
           << rpcId << "\n"
           << "    msg=" << *_RequestLeafSetResponse << " rtt=" << rtt
           << endl;
        handleRequestLeafSetResponse(_RequestLeafSetResponse);
        break;
    }
    RPC_SWITCH_END( )
}
void Bamboo::handleStateMessage (PastryStateMessage * msg) [virtual]
processes state messages, merging with own state tables
Parameters:
msg the pastry state message
Implements BasePastry.
Definition at line 377 of file Bamboo.cc.
Referenced by handleRequestLeafSetResponse().
{
    if (debugOutput) {
        EV << "[Bamboo::handleStateMessage() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    new STATE message to process "
           << static_cast<void*>(msg) << " in state "
           << ((state == READY)?"READY":((state == JOIN)?"JOIN":"INIT"))
           << endl;
    }
    if (state == INIT) {
        EV << "[Bamboo::handleStateMessage() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    can't handle state messages until at least reaching JOIN state."
           << endl;
        delete msg;
        return;
    }
    PastryStateMsgHandle handle(msg);
    if (state == JOIN) {
        determineAliveTable(msg);
        leafSet->mergeState(msg, &aliveTable);
        // merged state into leafset right now
        lastStateChange = simTime();
        newLeafs();
        updateTooltip();
        // no state message is processed right now, start immediately:
        stateCache = handle;
        if (proximityNeighborSelection) {
            pingNodes();
        } else {
            checkProxCache();
        }
        return;
    }
    // determine aliveTable to prevent leafSet from merging nodes that are
    // known to be dead:
    determineAliveTable(msg);
    if (leafSet->mergeState(msg, &aliveTable)) {
        // merged state into leafset right now
        lastStateChange = simTime();
        newLeafs();
        updateTooltip();
    }
    // in READY state, only ping nodes to get proximity metric:
    if (!stateCache.msg) {
        // no state message is processed right now, start immediately:
        stateCache = handle;
        if (proximityNeighborSelection) {
            pingNodes();
        } else {
            checkProxCache();
        }
    } else {
        // enqueue message for later processing:
        stateCacheQueue.push(handle);
        if (stateCacheQueue.size() > 15) {
            delete stateCacheQueue.front().msg;
            stateCacheQueue.pop();
            EV << "[Bamboo::handleStateMessage() @ " << thisNode.getIp()
               << " (" << thisNode.getKey().toString(16) << ")]\n"
               << "    stateCacheQueue full -> pop()" << endl;
        }
        if (proximityNeighborSelection) {
            prePing(msg);
        } else {
            checkProxCache();
        }
    }
}
void Bamboo::handleTimerEvent (cMessage * msg) [virtual]
Reimplemented from BaseRpc.
Definition at line 133 of file Bamboo.cc.
{
    if (msg == localTuningTimer) {
        EV << "[Bamboo::handleTimerEvent() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    starting local tuning "
           << "(aka neighbor's neighbors / routing table maintenance)"
           << endl;
        doLocalTuning();
        scheduleAt(simTime() + localTuningInterval, localTuningTimer);
    } else if (msg == leafsetMaintenanceTimer) {
        EV << "[Bamboo::handleTimerEvent() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    starting leafset maintenance"
           << endl;
        doLeafsetMaintenance();
        scheduleAt(simTime() + leafsetMaintenanceInterval,
                   leafsetMaintenanceTimer);
    } else if (msg == globalTuningTimer) {
        EV << "[Bamboo::handleTimerEvent() @ " << thisNode.getIp()
           << " (" << thisNode.getKey().toString(16) << ")]\n"
           << "    starting global tuning"
           << endl;
        doGlobalTuning();
        scheduleAt(simTime() + globalTuningInterval, globalTuningTimer);
    }
}
void Bamboo::initializeOverlay (int stage) [virtual]
Initializes derived-class-attributes.
Initializes derived-class-attributes, called by BaseOverlay::initialize(). By default this method is called once. If more stages are needed one can overload numInitStages() and add more stages.
Parameters:
stage the init stage
Reimplemented from BaseOverlay.
Definition at line 50 of file Bamboo.cc.
{
    if ( stage != MIN_STAGE_OVERLAY )
        return;
    // Bamboo provides KBR services
    kbr = true;
    rowToAsk = 0;
    baseInit();
    localTuningInterval = par("localTuningInterval");
    leafsetMaintenanceInterval = par("leafsetMaintenanceInterval");
    globalTuningInterval = par("globalTuningInterval");
    localTuningTimer = new cMessage("repairTaskTimer");
    leafsetMaintenanceTimer = new cMessage("leafsetMaintenanceTimer");
    globalTuningTimer = new cMessage("globalTuningTimer");
}
void Bamboo::joinOverlay () [private, virtual]
Join the overlay with a given nodeID in thisNode.key.
Join the overlay with a given nodeID in thisNode.key. This method may be called by an application to join the overlay with a specific nodeID. It is also called if the node's IP address changes.
Reimplemented from BaseOverlay.
Definition at line 72 of file Bamboo.cc.
{
    changeState(INIT);
    if (bootstrapNode.isUnspecified()) {
        // no existing pastry network -> first node of a new one
        changeState(READY);
    } else {
        // join existing pastry network
        changeState(JOIN);
    }
}
void Bamboo::lookupFinished (AbstractLookup * lookup) [protected, virtual]
Implements LookupListener.
Definition at line 455 of file Bamboo.cc.
Referenced by BambooLookupListener::lookupFinished().
{
    EV << "[Bamboo::lookupFinished() @ " << thisNode.getIp()
       << " (" << thisNode.getKey().toString(16) << ")]\n"
       << endl;
    if (lookup->isValid()) {
        EV  << "    Lookup successful" << endl;
        const NodeVector& result = lookup->getResult();
        if (result[0] != thisNode) {
            if (proximityNeighborSelection) {
                // Global Tuning PING
                Prox prox = neighborCache->getProx(result[0],
                                                   NEIGHBORCACHE_DEFAULT,
                                                   PING_SINGLE_NODE,
                                                   this, NULL);
                if (prox != Prox::PROX_UNKNOWN && prox != Prox::PROX_WAITING) {
                    routingTable->mergeNode(result[0], prox.proximity);
                }
            } else {
                routingTable->mergeNode(result[0], -1.0);
                checkProxCache();
            }
        }
    } else {
        EV << "    Lookup failed" << endl;
    }
}
Friends And Related Function Documentation
friend class BambooLookupListener [friend]
Definition at line 55 of file Bamboo.h.
Referenced by doGlobalTuning().
Member Data Documentation
simtime_t Bamboo::globalTuningInterval [private]
Definition at line 95 of file Bamboo.h.
Referenced by changeState(), handleTimerEvent(), and initializeOverlay().
cMessage* Bamboo::globalTuningTimer [private]
Definition at line 98 of file Bamboo.h.
Referenced by changeState(), handleTimerEvent(), initializeOverlay(), and ~Bamboo().
simtime_t Bamboo::leafsetMaintenanceInterval [private]
Definition at line 93 of file Bamboo.h.
Referenced by handleTimerEvent(), and initializeOverlay().
cMessage* Bamboo::leafsetMaintenanceTimer [private]
Definition at line 97 of file Bamboo.h.
Referenced by changeState(), handleTimerEvent(), initializeOverlay(), and ~Bamboo().
simtime_t Bamboo::localTuningInterval [private]
Definition at line 94 of file Bamboo.h.
Referenced by changeState(), handleTimerEvent(), and initializeOverlay().
cMessage* Bamboo::localTuningTimer [private]
Definition at line 99 of file Bamboo.h.
Referenced by changeState(), handleTimerEvent(), initializeOverlay(), and ~Bamboo().
uint16_t Bamboo::rowToAsk [private]
Definition at line 90 of file Bamboo.h.
Referenced by doLocalTuning(), and initializeOverlay().
The documentation for this class was generated from the following files:
Bamboo.h
Bamboo.cc