OverSim: RequestRoutingRowCall Class Reference
RequestRoutingRowCall Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestRoutingRowCall (const char *name=NULL, int kind=0)
RequestRoutingRowCall (const RequestRoutingRowCall &other)
virtual ~RequestRoutingRowCall ()
RequestRoutingRowCall & operator= (const RequestRoutingRowCall &other)
virtual RequestRoutingRowCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getRow () const
virtual void setRow (int row)
Protected Member Functions
bool operator== (const RequestRoutingRowCall &)
Protected Attributes
int row_var
Private Member Functions
void copy (const RequestRoutingRowCall &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestRoutingRowCall extends BaseCallMessage
 {
     int row;
 }
Definition at line 569 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestRoutingRowCall::RequestRoutingRowCall (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestRoutingRowCall::RequestRoutingRowCall (const RequestRoutingRowCall & other)
virtual RequestRoutingRowCall::~RequestRoutingRowCall () [virtual]
Member Function Documentation
void RequestRoutingRowCall::copy (const RequestRoutingRowCall & other) [private]
virtual RequestRoutingRowCall* RequestRoutingRowCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 586 of file PastryMessage_m.h.
{return new RequestRoutingRowCall(*this);}
virtual int RequestRoutingRowCall::getRow () const [virtual]
Referenced by BasePastry::handleRequestRoutingRowCall().
RequestRoutingRowCall& RequestRoutingRowCall::operator= (const RequestRoutingRowCall & other)
bool RequestRoutingRowCall::operator== (const RequestRoutingRowCall &) [protected]
virtual void RequestRoutingRowCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void RequestRoutingRowCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void RequestRoutingRowCall::setRow (int row) [virtual]
Referenced by Bamboo::doLocalTuning(), Pastry::doRoutingTableMaintenance(), and Pastry::handleTimerEvent().
Member Data Documentation
int RequestRoutingRowCall::row_var [protected]
Definition at line 572 of file PastryMessage_m.h.
The documentation for this class was generated from the following file:
PastryMessage_m.h