OverSim: GIASearchAppMessage Class Reference
GIASearchAppMessage Class Reference
Class generated from common/ExtAPIMessages.msg by opp_msgc.
#include <ExtAPIMessages_m.h>
Public Member Functions
GIASearchAppMessage (const char *name=NULL, int kind=0)
GIASearchAppMessage (const GIASearchAppMessage &other)
virtual ~GIASearchAppMessage ()
GIASearchAppMessage & operator= (const GIASearchAppMessage &other)
virtual GIASearchAppMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const GIASearchAppMessage &)
Protected Attributes
int command_var
Private Member Functions
void copy (const GIASearchAppMessage &other)
Detailed Description
Class generated from common/ExtAPIMessages.msg by opp_msgc.
 packet GIASearchAppMessage
 {
     int command enum (GIAAppCommand);
 }
Definition at line 55 of file ExtAPIMessages_m.h.
Constructor & Destructor Documentation
GIASearchAppMessage::GIASearchAppMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GIASearchAppMessage::GIASearchAppMessage (const GIASearchAppMessage & other)
virtual GIASearchAppMessage::~GIASearchAppMessage () [virtual]
Member Function Documentation
void GIASearchAppMessage::copy (const GIASearchAppMessage & other) [private]
virtual GIASearchAppMessage* GIASearchAppMessage::dup () const [inline, virtual]
Reimplemented in GIAanswer, GIAsearch, GIAremove, and GIAput.
Definition at line 72 of file ExtAPIMessages_m.h.
{return new GIASearchAppMessage(*this);}
virtual int GIASearchAppMessage::getCommand () const [virtual]
GIASearchAppMessage& GIASearchAppMessage::operator= (const GIASearchAppMessage & other)
bool GIASearchAppMessage::operator== (const GIASearchAppMessage &) [protected]
virtual void GIASearchAppMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented in GIAanswer, GIAsearch, GIAremove, and GIAput.
Referenced by doPacking().
virtual void GIASearchAppMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented in GIAanswer, GIAsearch, GIAremove, and GIAput.
Referenced by doUnpacking().
virtual void GIASearchAppMessage::setCommand (int command) [virtual]
Referenced by Gia::deliverSearchResult(), and GIASearchApp::handleTimerEvent().
Member Data Documentation
int GIASearchAppMessage::command_var [protected]
Definition at line 58 of file ExtAPIMessages_m.h.
The documentation for this class was generated from the following file:
ExtAPIMessages_m.h