OverSim: NTreeGroupDeleteMessage Class Reference
NTreeGroupDeleteMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeGroupDeleteMessage (const char *name=NULL, int kind=0)
NTreeGroupDeleteMessage (const NTreeGroupDeleteMessage &other)
virtual ~NTreeGroupDeleteMessage ()
NTreeGroupDeleteMessage & operator= (const NTreeGroupDeleteMessage &other)
virtual NTreeGroupDeleteMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual unsigned int getNewChildArraySize () const
virtual NodeHandle & getNewChild (unsigned int k)
virtual const NodeHandle & getNewChild (unsigned int k) const
virtual void setNewChild (unsigned int k, const NodeHandle &newChild)
Protected Member Functions
bool operator== (const NTreeGroupDeleteMessage &)
Protected Attributes
Vector2D origin_var
double size_var
NodeHandle newChild_var [4]
Private Member Functions
void copy (const NTreeGroupDeleteMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeGroupDeleteMessage extends BaseOverlayMessage
 {
         Vector2D origin;
         double size;
         NodeHandle newChild[4];
 }
Definition at line 402 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeGroupDeleteMessage::NTreeGroupDeleteMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeGroupDeleteMessage::NTreeGroupDeleteMessage (const NTreeGroupDeleteMessage & other)
virtual NTreeGroupDeleteMessage::~NTreeGroupDeleteMessage () [virtual]
Member Function Documentation
void NTreeGroupDeleteMessage::copy (const NTreeGroupDeleteMessage & other) [private]
virtual NTreeGroupDeleteMessage* NTreeGroupDeleteMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 421 of file NTree_m.h.
{return new NTreeGroupDeleteMessage(*this);}
virtual NodeHandle& NTreeGroupDeleteMessage::getNewChild (unsigned int k) [virtual]
Referenced by NTree::handleDeleteMessage().
virtual const NodeHandle& NTreeGroupDeleteMessage::getNewChild (unsigned int k) const [inline, virtual]
Definition at line 433 of file NTree_m.h.
Referenced by getNewChild().
{return const_cast<NTreeGroupDeleteMessage*>(this)->getNewChild(k);}
virtual unsigned int NTreeGroupDeleteMessage::getNewChildArraySize () const [virtual]
virtual Vector2D& NTreeGroupDeleteMessage::getOrigin () [virtual]
Referenced by NTree::handleDeleteMessage().
virtual const Vector2D& NTreeGroupDeleteMessage::getOrigin () const [inline, virtual]
Definition at line 427 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeGroupDeleteMessage*>(this)->getOrigin();}
virtual double NTreeGroupDeleteMessage::getSize () const [virtual]
Referenced by NTree::handleDeleteMessage().
NTreeGroupDeleteMessage& NTreeGroupDeleteMessage::operator= (const NTreeGroupDeleteMessage & other)
bool NTreeGroupDeleteMessage::operator== (const NTreeGroupDeleteMessage &) [protected]
virtual void NTreeGroupDeleteMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeGroupDeleteMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeGroupDeleteMessage::setNewChild (unsigned int k, const NodeHandle & newChild) [virtual]
Referenced by NTree::divideNode(), and NTree::handleCollapseMessage().
virtual void NTreeGroupDeleteMessage::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::divideNode(), and NTree::handleCollapseMessage().
virtual void NTreeGroupDeleteMessage::setSize (double size) [virtual]
Referenced by NTree::divideNode(), and NTree::handleCollapseMessage().
Member Data Documentation
NodeHandle NTreeGroupDeleteMessage::newChild_var[4] [protected]
Definition at line 407 of file NTree_m.h.
Vector2D NTreeGroupDeleteMessage::origin_var [protected]
Definition at line 405 of file NTree_m.h.
double NTreeGroupDeleteMessage::size_var [protected]
Definition at line 406 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h