OverSim: NTreeCollapseMessage Class Reference
NTreeCollapseMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeCollapseMessage (const char *name=NULL, int kind=0)
NTreeCollapseMessage (const NTreeCollapseMessage &other)
virtual ~NTreeCollapseMessage ()
NTreeCollapseMessage & operator= (const NTreeCollapseMessage &other)
virtual NTreeCollapseMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
virtual double getSize () const
virtual void setSize (double size)
virtual NodeHandle & getPlayer ()
virtual const NodeHandle & getPlayer () const
virtual void setPlayer (const NodeHandle &player)
Protected Member Functions
bool operator== (const NTreeCollapseMessage &)
Protected Attributes
Vector2D origin_var
double size_var
NodeHandle player_var
Private Member Functions
void copy (const NTreeCollapseMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeCollapseMessage extends BaseOverlayMessage
 {
         Vector2D origin;
         double size;
         NodeHandle player;
 }
Definition at line 451 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeCollapseMessage::NTreeCollapseMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeCollapseMessage::NTreeCollapseMessage (const NTreeCollapseMessage & other)
virtual NTreeCollapseMessage::~NTreeCollapseMessage () [virtual]
Member Function Documentation
void NTreeCollapseMessage::copy (const NTreeCollapseMessage & other) [private]
virtual NTreeCollapseMessage* NTreeCollapseMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 470 of file NTree_m.h.
Referenced by NTree::collapseTree(), and NTree::handleCollapseMessage().
{return new NTreeCollapseMessage(*this);}
virtual Vector2D& NTreeCollapseMessage::getOrigin () [virtual]
Referenced by NTree::handleCollapseMessage().
virtual const Vector2D& NTreeCollapseMessage::getOrigin () const [inline, virtual]
Definition at line 476 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeCollapseMessage*>(this)->getOrigin();}
virtual NodeHandle& NTreeCollapseMessage::getPlayer () [virtual]
Referenced by NTree::handleCollapseMessage().
virtual const NodeHandle& NTreeCollapseMessage::getPlayer () const [inline, virtual]
Definition at line 481 of file NTree_m.h.
Referenced by getPlayer().
{return const_cast<NTreeCollapseMessage*>(this)->getPlayer();}
virtual double NTreeCollapseMessage::getSize () const [virtual]
Referenced by NTree::handleCollapseMessage().
NTreeCollapseMessage& NTreeCollapseMessage::operator= (const NTreeCollapseMessage & other)
bool NTreeCollapseMessage::operator== (const NTreeCollapseMessage &) [protected]
virtual void NTreeCollapseMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeCollapseMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeCollapseMessage::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::collapseTree(), and NTree::handleCollapseMessage().
virtual void NTreeCollapseMessage::setPlayer (const NodeHandle & player) [virtual]
Referenced by NTree::collapseTree().
virtual void NTreeCollapseMessage::setSize (double size) [virtual]
Referenced by NTree::collapseTree(), and NTree::handleCollapseMessage().
Member Data Documentation
Vector2D NTreeCollapseMessage::origin_var [protected]
Definition at line 454 of file NTree_m.h.
NodeHandle NTreeCollapseMessage::player_var [protected]
Definition at line 456 of file NTree_m.h.
double NTreeCollapseMessage::size_var [protected]
Definition at line 455 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h