OverSim: FindNodeCall Class Reference
FindNodeCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
FindNodeCall (const char *name=NULL, int kind=0)
FindNodeCall (const FindNodeCall &other)
virtual ~FindNodeCall ()
FindNodeCall & operator= (const FindNodeCall &other)
virtual FindNodeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getLookupKey ()
virtual const OverlayKey & getLookupKey () const
virtual void setLookupKey (const OverlayKey &lookupKey)
virtual int getNumRedundantNodes () const
virtual void setNumRedundantNodes (int numRedundantNodes)
virtual int getNumSiblings () const
virtual void setNumSiblings (int numSiblings)
virtual bool getExhaustiveIterative () const
virtual void setExhaustiveIterative (bool exhaustiveIterative)
Protected Member Functions
bool operator== (const FindNodeCall &)
Protected Attributes
OverlayKey lookupKey_var
int numRedundantNodes_var
int numSiblings_var
bool exhaustiveIterative_var
Private Member Functions
void copy (const FindNodeCall &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet FindNodeCall extends BaseCallMessage
 {
     OverlayKey lookupKey;
     int numRedundantNodes;
     int numSiblings;
     bool exhaustiveIterative = false;
 }
Definition at line 639 of file CommonMessages_m.h.
Constructor & Destructor Documentation
FindNodeCall::FindNodeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
FindNodeCall::FindNodeCall (const FindNodeCall & other)
virtual FindNodeCall::~FindNodeCall () [virtual]
Member Function Documentation
void FindNodeCall::copy (const FindNodeCall & other) [private]
virtual FindNodeCall* FindNodeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Reimplemented in ProxFindNodeCall.
Definition at line 659 of file CommonMessages_m.h.
{return new FindNodeCall(*this);}
virtual bool FindNodeCall::getExhaustiveIterative () const [virtual]
Referenced by BaseOverlay::findNodeRpc().
virtual OverlayKey& FindNodeCall::getLookupKey () [virtual]
Referenced by BaseOverlay::findNodeRpc(), and IterativePathLookup::handleTimeout().
virtual const OverlayKey& FindNodeCall::getLookupKey () const [inline, virtual]
Definition at line 665 of file CommonMessages_m.h.
Referenced by getLookupKey().
{return const_cast<FindNodeCall*>(this)->getLookupKey();}
virtual int FindNodeCall::getNumRedundantNodes () const [virtual]
Referenced by BaseOverlay::findNodeRpc().
virtual int FindNodeCall::getNumSiblings () const [virtual]
Referenced by BaseOverlay::findNodeRpc(), and BaseOverlay::internalSendRouteRpc().
FindNodeCall& FindNodeCall::operator= (const FindNodeCall & other)
bool FindNodeCall::operator== (const FindNodeCall &) [protected]
virtual void FindNodeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in ProxFindNodeCall.
Referenced by doPacking().
virtual void FindNodeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Reimplemented in ProxFindNodeCall.
Referenced by doUnpacking().
virtual void FindNodeCall::setExhaustiveIterative (bool exhaustiveIterative) [virtual]
Referenced by IterativeLookup::createFindNodeCall(), and Kademlia::sendSiblingFindNodeCall().
virtual void FindNodeCall::setLookupKey (const OverlayKey & lookupKey) [virtual]
Referenced by IterativeLookup::createFindNodeCall(), RecursiveLookup::lookup(), and Kademlia::sendSiblingFindNodeCall().
virtual void FindNodeCall::setNumRedundantNodes (int numRedundantNodes) [virtual]
Referenced by IterativeLookup::createFindNodeCall(), RecursiveLookup::lookup(), and Kademlia::sendSiblingFindNodeCall().
virtual void FindNodeCall::setNumSiblings (int numSiblings) [virtual]
Referenced by IterativeLookup::createFindNodeCall(), RecursiveLookup::lookup(), and Kademlia::sendSiblingFindNodeCall().
Member Data Documentation
bool FindNodeCall::exhaustiveIterative_var [protected]
Definition at line 645 of file CommonMessages_m.h.
OverlayKey FindNodeCall::lookupKey_var [protected]
Definition at line 642 of file CommonMessages_m.h.
int FindNodeCall::numRedundantNodes_var [protected]
Definition at line 643 of file CommonMessages_m.h.
int FindNodeCall::numSiblings_var [protected]
Definition at line 644 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h