OverSim: GlobalViewBuilderCall Class Reference
GlobalViewBuilderCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
GlobalViewBuilderCall (const char *name=NULL, int kind=0)
GlobalViewBuilderCall (const GlobalViewBuilderCall &other)
virtual ~GlobalViewBuilderCall ()
GlobalViewBuilderCall & operator= (const GlobalViewBuilderCall &other)
virtual GlobalViewBuilderCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const GlobalViewBuilderCall &)
Private Member Functions
void copy (const GlobalViewBuilderCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet GlobalViewBuilderCall extends TreeAppCall
 {
 }
Definition at line 206 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
GlobalViewBuilderCall::GlobalViewBuilderCall (const char * name = NULL, int kind = 0)
Referenced by dup().
GlobalViewBuilderCall::GlobalViewBuilderCall (const GlobalViewBuilderCall & other)
virtual GlobalViewBuilderCall::~GlobalViewBuilderCall () [virtual]
Member Function Documentation
void GlobalViewBuilderCall::copy (const GlobalViewBuilderCall & other) [private]
virtual GlobalViewBuilderCall* GlobalViewBuilderCall::dup () const [inline, virtual]
Reimplemented from TreeAppCall.
Reimplemented in AreaDataCall, SimpleCoordStrategyCall, RegionsStrategyCall, TreeTestStrategyCall, RemoveRandomStrategyCall, SendAllStrategyCall, and SendCoordinatesCall.
Definition at line 222 of file TreeManagementMessage_m.h.
{return new GlobalViewBuilderCall(*this);}
GlobalViewBuilderCall& GlobalViewBuilderCall::operator= (const GlobalViewBuilderCall & other)
bool GlobalViewBuilderCall::operator== (const GlobalViewBuilderCall &) [protected]
virtual void GlobalViewBuilderCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from TreeAppCall.
Reimplemented in AreaDataCall, SimpleCoordStrategyCall, RegionsStrategyCall, TreeTestStrategyCall, RemoveRandomStrategyCall, SendAllStrategyCall, and SendCoordinatesCall.
Referenced by doPacking().
virtual void GlobalViewBuilderCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from TreeAppCall.
Reimplemented in AreaDataCall, SimpleCoordStrategyCall, RegionsStrategyCall, TreeTestStrategyCall, RemoveRandomStrategyCall, SendAllStrategyCall, and SendCoordinatesCall.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h