OverSim: BaseRpcMessage Class Reference
BaseRpcMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
BaseRpcMessage (const char *name=NULL, int kind=0)
BaseRpcMessage (const BaseRpcMessage &other)
virtual ~BaseRpcMessage ()
BaseRpcMessage & operator= (const BaseRpcMessage &other)
virtual BaseRpcMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getNonce () const
virtual void setNonce (unsigned int nonce)
virtual NodeHandle & getSrcNode ()
virtual const NodeHandle & getSrcNode () const
virtual void setSrcNode (const NodeHandle &srcNode)
virtual void setAuthBlockArraySize (uint8_t size)
virtual uint8_t getAuthBlockArraySize () const
virtual AuthBlock & getAuthBlock (uint8_t k)
virtual const AuthBlock & getAuthBlock (uint8_t k) const
virtual void setAuthBlock (uint8_t k, const AuthBlock &authBlock)
Protected Member Functions
bool operator== (const BaseRpcMessage &)
Protected Attributes
unsigned int nonce_var
NodeHandle srcNode_var
AuthBlock * authBlock_var
uint8_t authBlock_arraysize
Private Member Functions
void copy (const BaseRpcMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet BaseRpcMessage extends BaseOverlayMessage
 {
     unsigned int nonce;
     NodeHandle srcNode;
     AuthBlock authBlock[] (uint8_t);
 }
Definition at line 474 of file CommonMessages_m.h.
Constructor & Destructor Documentation
BaseRpcMessage::BaseRpcMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BaseRpcMessage::BaseRpcMessage (const BaseRpcMessage & other)
virtual BaseRpcMessage::~BaseRpcMessage () [virtual]
Member Function Documentation
void BaseRpcMessage::copy (const BaseRpcMessage & other) [private]
virtual BaseRpcMessage* BaseRpcMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in P2pnsResolveResponse, P2pnsResolveCall, P2pnsRegisterResponse, P2pnsRegisterCall, LookupResponse, LookupCall, DHTdumpResponse, DHTdumpCall, DHTgetCAPIResponse, DHTputCAPIResponse, DHTgetCAPICall, DHTputCAPICall, PubSubAdoptChildResponse, PubSubAdoptChildCall, NextHopResponse, NextHopCall, PingResponse, PubSubPingResponse, PingCall, PubSubPingCall, FailedNodeResponse, HGetChildrenResponse, PubSubBackupResponse, FailedNodeCall, HGetChildrenCall, CapReqResponse, PubSubBackupCall, HSwitchToRescueModeCall, FindNodeResponse, CapReqCall, PubSubIntermediateResponse, HScheduleSegmentsResponse, AreaDataCall, FindNodeCall, PubSubIntermediateCall, HScheduleSegmentsCall, SimpleCoordStrategyCall, RequestRoutingRowResponse, RpcTimeoutMessage, DeBruijnResponse, PubSubHelpResponse, RegionsStrategyCall, HResponsibilityAsParentCall, RequestRoutingRowCall, BaseResponseMessage, DeBruijnCall, RequestLeafSetResponse, TreeTestStrategyCall, PubSubHelpCall, HNewParentSelectedCall, BaseCallMessage, RequestLeafSetCall, RemoveRandomStrategyCall, HLeaveOverlayResponse, RequestRepairResponse, HLeaveOverlayCall, SendAllStrategyCall, FixfingersResponse, PubSubSubscriptionResponse, RequestRepairCall, HVideoSegmentCall, SendCoordinatesCall, FixfingersCall, PubSubSubscriptionCall, RequestStateResponse, ChildCheckResponse, HJoinResponse, StabilizeResponse, PubSubTakeOverSubspaceResponse, RequestStateCall, NTreeNodePingResponse, ChildCheckCall, StabilizeCall, PubSubTakeOverSubspaceCall, PastryJoinResponse, HJoinCall, NTreePingResponse, ChildReleaseResponse, PastryJoinCall, JoinResponse, PubSubResponsibleNodeResponse, HSelectParentResponse, NTreeNodePingCall, ChildReleaseCall, JoinCall, HSelectParentCall, PubSubResponsibleNodeCall, GlobalViewBuilderResponse, NTreePingCall, DHTGetResponse, PubSubJoinResponse, HGetParametersResponse, GlobalViewBuilderCall, NotifyResponse, UnderlayTestResponse, ScribePublishResponse, NTreeDivideResponse, TreeAppResponse, HGetParametersCall, PubSubJoinCall, DHTPutResponse, NotifyCall, UnderlayTestCall, RttToNodeResponse, ScribePublishCall, NTreeDivideCall, TreeAppCall, BucketResponse, HCapacityResponse, DHTGetCall, KbrTestResponse, CoordsOfNodeResponse, ScribeJoinResponse, ParentRequestResponse, ProxFindNodeResponse, NTreeJoinResponse, DiscoveryResponse, BucketCall, HCapacityCall, KbrTestCall, MyNeighborResponse, CoordsReqResponse, CBRDHTGetResponse, RttToNodeCall, ScribeJoinCall, ParentRequestCall, DHTPutCall, ProxFindNodeCall, NTreeJoinCall, DiscoveryCall, CoordsOfNodeCall, CoordsReqCall, MyNeighborCall, and CBRDHTGetCall.
Definition at line 494 of file CommonMessages_m.h.
Referenced by CryptoModule::signMessage(), and CryptoModule::verifyMessage().
{return new BaseRpcMessage(*this);}
virtual AuthBlock& BaseRpcMessage::getAuthBlock (uint8_t k) [virtual]
Referenced by CryptoModule::signMessage().
virtual const AuthBlock& BaseRpcMessage::getAuthBlock (uint8_t k) const [inline, virtual]
Definition at line 507 of file CommonMessages_m.h.
Referenced by getAuthBlock().
{return const_cast<BaseRpcMessage*>(this)->getAuthBlock(k);}
virtual uint8_t BaseRpcMessage::getAuthBlockArraySize () const [virtual]
Referenced by CryptoModule::verifyMessage().
virtual unsigned int BaseRpcMessage::getNonce () const [virtual]
Referenced by CBRDHT::handleGetCAPIRequest(), DHT::handleGetCAPIRequest(), CBRDHT::handleGetRequest(), CBRDHT::handleLookupResponse(), DHT::handlePutCAPIRequest(), BaseRpc::internalHandleRpcMessage(), SendToKeyListener::lookupFinished(), BaseOverlay::lookupRpc(), and BaseRpc::sendRpcResponse().
virtual NodeHandle& BaseRpcMessage::getSrcNode () [virtual]
Referenced by BaseOverlay::checkFindNode(), Nps::coordsReqRpcResponse(), BasePastry::createLookup(), Scribe::forward(), PubSubMMOG::handleAdoptChildResponse(), PubSubMMOG::handleBackupCall(), Broose::handleBucketRequestRpc(), TreeManagement::handleChildCheckRpcCall(), TreeManagement::handleChildCheckRpcResponse(), TreeManagement::handleChildReleaseRpcCall(), StrategyRegions::handleCoordinateRpcCall(), StrategySimplifyCoords::handleCoordinateRpcCall(), StrategySendAll::handleCoordinateRpcCall(), StrategyTreeTest::handleCoordinateRpcCall(), GlobalViewBuilder::handleCoordinateRpcCall(), NTree::handleDivideCall(), NTree::handleDivideResponse(), HTopology::handleGetParametersResponse(), DHT::handleGetResponse(), PubSubLobby::handleHelpCall(), PubSubMMOG::handleIntermediateCall(), PubSubMMOG::handleIntermediateResponse(), PubSubLobby::handleJoin(), NTree::handleJoinCall(), HTopology::handleJoinCall(), Scribe::handleJoinMessage(), NTree::handleJoinResponse(), Scribe::handleJoinResponse(), HTopology::handleLeaveCall(), TreeManagement::handleParentRequestRpcCall(), TreeManagement::handleParentRequestRpcResponse(), Pastry::handlePastryJoinCall(), Scribe::handlePublishResponse(), CBRDHT::handlePutRequest(), DHT::handlePutRequest(), IterativePathLookup::handleResponse(), Broose::handleRpcCall(), oversim::Chord::handleRpcJoinResponse(), oversim::Chord::handleRpcNotifyResponse(), DiscoveryMode::handleRpcResponse(), KBRTestApp::handleRpcResponse(), Kademlia::handleRpcResponse(), HTopology::handleRpcResponse(), Broose::handleRpcResponse(), IterativeLookup::handleRpcResponse(), oversim::Chord::handleRpcStabilizeResponse(), PubSubMMOG::handleSubscriptionCall(), HTopology::handleSwitchToRescueModeCall(), PubSubLobby::handleTakeOverResponse(), HTopology::handleVideoSegment(), BaseRpc::internalHandleRpcMessage(), BaseOverlay::internalSendRpcResponse(), Pastry::pingResponse(), BootstrapList::pingResponse(), Broose::pingResponse(), oversim::Chord::pingResponse(), Pastry::recursiveRoutingHook(), oversim::Chord::rpcJoin(), oversim::Chord::rpcNotify(), oversim::Chord::rpcStabilize(), HTopology::selectReplacement(), BaseRpc::sendRpcResponse(), and oversim::ChordSuccessorList::updateList().
virtual const NodeHandle& BaseRpcMessage::getSrcNode () const [inline, virtual]
Definition at line 502 of file CommonMessages_m.h.
Referenced by getSrcNode().
{return const_cast<BaseRpcMessage*>(this)->getSrcNode();}
BaseRpcMessage& BaseRpcMessage::operator= (const BaseRpcMessage & other)
bool BaseRpcMessage::operator== (const BaseRpcMessage &) [protected]
virtual void BaseRpcMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in P2pnsResolveResponse, P2pnsResolveCall, P2pnsRegisterResponse, P2pnsRegisterCall, LookupResponse, LookupCall, DHTdumpResponse, DHTdumpCall, DHTgetCAPIResponse, DHTputCAPIResponse, DHTgetCAPICall, DHTputCAPICall, PubSubAdoptChildResponse, PubSubAdoptChildCall, NextHopResponse, NextHopCall, PingResponse, PubSubPingResponse, PingCall, PubSubPingCall, FailedNodeResponse, HGetChildrenResponse, PubSubBackupResponse, FailedNodeCall, HGetChildrenCall, CapReqResponse, PubSubBackupCall, HSwitchToRescueModeCall, FindNodeResponse, CapReqCall, PubSubIntermediateResponse, HScheduleSegmentsResponse, AreaDataCall, FindNodeCall, PubSubIntermediateCall, HScheduleSegmentsCall, SimpleCoordStrategyCall, RequestRoutingRowResponse, RpcTimeoutMessage, DeBruijnResponse, PubSubHelpResponse, RegionsStrategyCall, HResponsibilityAsParentCall, RequestRoutingRowCall, BaseResponseMessage, DeBruijnCall, RequestLeafSetResponse, TreeTestStrategyCall, PubSubHelpCall, HNewParentSelectedCall, BaseCallMessage, RequestLeafSetCall, RemoveRandomStrategyCall, HLeaveOverlayResponse, RequestRepairResponse, HLeaveOverlayCall, SendAllStrategyCall, FixfingersResponse, PubSubSubscriptionResponse, RequestRepairCall, HVideoSegmentCall, SendCoordinatesCall, FixfingersCall, PubSubSubscriptionCall, RequestStateResponse, ChildCheckResponse, HJoinResponse, StabilizeResponse, PubSubTakeOverSubspaceResponse, RequestStateCall, NTreeNodePingResponse, ChildCheckCall, StabilizeCall, PubSubTakeOverSubspaceCall, PastryJoinResponse, HJoinCall, NTreePingResponse, ChildReleaseResponse, PastryJoinCall, JoinResponse, PubSubResponsibleNodeResponse, HSelectParentResponse, NTreeNodePingCall, ChildReleaseCall, JoinCall, HSelectParentCall, PubSubResponsibleNodeCall, GlobalViewBuilderResponse, NTreePingCall, DHTGetResponse, PubSubJoinResponse, HGetParametersResponse, GlobalViewBuilderCall, NotifyResponse, UnderlayTestResponse, ScribePublishResponse, NTreeDivideResponse, TreeAppResponse, HGetParametersCall, PubSubJoinCall, DHTPutResponse, NotifyCall, UnderlayTestCall, RttToNodeResponse, ScribePublishCall, NTreeDivideCall, TreeAppCall, BucketResponse, HCapacityResponse, DHTGetCall, KbrTestResponse, CoordsOfNodeResponse, ScribeJoinResponse, ParentRequestResponse, ProxFindNodeResponse, NTreeJoinResponse, DiscoveryResponse, BucketCall, HCapacityCall, KbrTestCall, MyNeighborResponse, CoordsReqResponse, CBRDHTGetResponse, RttToNodeCall, ScribeJoinCall, ParentRequestCall, DHTPutCall, ProxFindNodeCall, NTreeJoinCall, DiscoveryCall, CoordsOfNodeCall, CoordsReqCall, MyNeighborCall, and CBRDHTGetCall.
Referenced by doPacking().
virtual void BaseRpcMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in P2pnsResolveResponse, P2pnsResolveCall, P2pnsRegisterResponse, P2pnsRegisterCall, LookupResponse, LookupCall, DHTdumpResponse, DHTdumpCall, DHTgetCAPIResponse, DHTputCAPIResponse, DHTgetCAPICall, DHTputCAPICall, PubSubAdoptChildResponse, PubSubAdoptChildCall, NextHopResponse, NextHopCall, PingResponse, PubSubPingResponse, PingCall, PubSubPingCall, FailedNodeResponse, HGetChildrenResponse, PubSubBackupResponse, FailedNodeCall, HGetChildrenCall, CapReqResponse, PubSubBackupCall, HSwitchToRescueModeCall, FindNodeResponse, CapReqCall, PubSubIntermediateResponse, HScheduleSegmentsResponse, AreaDataCall, FindNodeCall, PubSubIntermediateCall, HScheduleSegmentsCall, SimpleCoordStrategyCall, RequestRoutingRowResponse, RpcTimeoutMessage, DeBruijnResponse, PubSubHelpResponse, RegionsStrategyCall, HResponsibilityAsParentCall, RequestRoutingRowCall, BaseResponseMessage, DeBruijnCall, RequestLeafSetResponse, TreeTestStrategyCall, PubSubHelpCall, HNewParentSelectedCall, BaseCallMessage, RequestLeafSetCall, RemoveRandomStrategyCall, HLeaveOverlayResponse, RequestRepairResponse, HLeaveOverlayCall, SendAllStrategyCall, FixfingersResponse, PubSubSubscriptionResponse, RequestRepairCall, HVideoSegmentCall, SendCoordinatesCall, FixfingersCall, PubSubSubscriptionCall, RequestStateResponse, ChildCheckResponse, HJoinResponse, StabilizeResponse, PubSubTakeOverSubspaceResponse, RequestStateCall, NTreeNodePingResponse, ChildCheckCall, StabilizeCall, PubSubTakeOverSubspaceCall, PastryJoinResponse, HJoinCall, NTreePingResponse, ChildReleaseResponse, PastryJoinCall, JoinResponse, PubSubResponsibleNodeResponse, HSelectParentResponse, NTreeNodePingCall, ChildReleaseCall, JoinCall, HSelectParentCall, PubSubResponsibleNodeCall, GlobalViewBuilderResponse, NTreePingCall, DHTGetResponse, PubSubJoinResponse, HGetParametersResponse, GlobalViewBuilderCall, NotifyResponse, UnderlayTestResponse, ScribePublishResponse, NTreeDivideResponse, TreeAppResponse, HGetParametersCall, PubSubJoinCall, DHTPutResponse, NotifyCall, UnderlayTestCall, RttToNodeResponse, ScribePublishCall, NTreeDivideCall, TreeAppCall, BucketResponse, HCapacityResponse, DHTGetCall, KbrTestResponse, CoordsOfNodeResponse, ScribeJoinResponse, ParentRequestResponse, ProxFindNodeResponse, NTreeJoinResponse, DiscoveryResponse, BucketCall, HCapacityCall, KbrTestCall, MyNeighborResponse, CoordsReqResponse, CBRDHTGetResponse, RttToNodeCall, ScribeJoinCall, ParentRequestCall, DHTPutCall, ProxFindNodeCall, NTreeJoinCall, DiscoveryCall, CoordsOfNodeCall, CoordsReqCall, MyNeighborCall, and CBRDHTGetCall.
Referenced by doUnpacking().
virtual void BaseRpcMessage::setAuthBlock (uint8_t k, const AuthBlock & authBlock) [virtual]
virtual void BaseRpcMessage::setAuthBlockArraySize (uint8_t size) [virtual]
Referenced by CryptoModule::signMessage().
virtual void BaseRpcMessage::setNonce (unsigned int nonce) [virtual]
Referenced by BaseRpc::sendRpcCall(), and BaseRpc::sendRpcResponse().
virtual void BaseRpcMessage::setSrcNode (const NodeHandle & srcNode) [virtual]
Referenced by BaseRpc::sendRpcCall(), and BaseRpc::sendRpcResponse().
Member Data Documentation
uint8_t BaseRpcMessage::authBlock_arraysize [protected]
Definition at line 480 of file CommonMessages_m.h.
AuthBlock* BaseRpcMessage::authBlock_var [protected]
Definition at line 479 of file CommonMessages_m.h.
unsigned int BaseRpcMessage::nonce_var [protected]
Definition at line 477 of file CommonMessages_m.h.
NodeHandle BaseRpcMessage::srcNode_var [protected]
Definition at line 478 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h