OverSim: PubSubResponsibleNodeResponse Class Reference
PubSubResponsibleNodeResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubResponsibleNodeResponse (const char *name=NULL, int kind=0)
PubSubResponsibleNodeResponse (const PubSubResponsibleNodeResponse &other)
virtual ~PubSubResponsibleNodeResponse ()
PubSubResponsibleNodeResponse & operator= (const PubSubResponsibleNodeResponse &other)
virtual
PubSubResponsibleNodeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getResponsibleNode ()
virtual const NodeHandle & getResponsibleNode () const
virtual void setResponsibleNode (const NodeHandle &responsibleNode)
Protected Member Functions
bool operator== (const PubSubResponsibleNodeResponse &)
Protected Attributes
int subspaceId_var
NodeHandle responsibleNode_var
Private Member Functions
void copy (const PubSubResponsibleNodeResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubResponsibleNodeResponse extends BaseResponseMessage
 {
         int subspaceId;
         NodeHandle responsibleNode;
 }
Definition at line 290 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubResponsibleNodeResponse::PubSubResponsibleNodeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubResponsibleNodeResponse::PubSubResponsibleNodeResponse (const PubSubResponsibleNodeResponse & other)
virtual PubSubResponsibleNodeResponse::~PubSubResponsibleNodeResponse () [virtual]
Member Function Documentation
void PubSubResponsibleNodeResponse::copy (const PubSubResponsibleNodeResponse & other) [private]
virtual PubSubResponsibleNodeResponse* PubSubResponsibleNodeResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 308 of file PubSubMessage_m.h.
{return new PubSubResponsibleNodeResponse(*this);}
virtual NodeHandle& PubSubResponsibleNodeResponse::getResponsibleNode () [virtual]
Referenced by PubSubMMOG::handleResponsibleNodeResponse().
virtual const NodeHandle& PubSubResponsibleNodeResponse::getResponsibleNode () const [inline, virtual]
Definition at line 316 of file PubSubMessage_m.h.
Referenced by getResponsibleNode().
{return const_cast<PubSubResponsibleNodeResponse*>(this)->getResponsibleNode();}
virtual int PubSubResponsibleNodeResponse::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleResponsibleNodeResponse().
PubSubResponsibleNodeResponse& PubSubResponsibleNodeResponse::operator= (const PubSubResponsibleNodeResponse & other)
bool PubSubResponsibleNodeResponse::operator== (const PubSubResponsibleNodeResponse &) [protected]
virtual void PubSubResponsibleNodeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubResponsibleNodeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubResponsibleNodeResponse::setResponsibleNode (const NodeHandle & responsibleNode) [virtual]
Referenced by PubSubLobby::handleRespCall(), and PubSubLobby::replaceResponsibleNode().
virtual void PubSubResponsibleNodeResponse::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubLobby::handleRespCall(), and PubSubLobby::replaceResponsibleNode().
Member Data Documentation
NodeHandle PubSubResponsibleNodeResponse::responsibleNode_var [protected]
Definition at line 294 of file PubSubMessage_m.h.
int PubSubResponsibleNodeResponse::subspaceId_var [protected]
Definition at line 293 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h