OverSim: ScribeLeaveMessage Class Reference
ScribeLeaveMessage Class Reference
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
#include <ScribeMessage_m.h>
Public Member Functions
ScribeLeaveMessage (const char *name=NULL, int kind=0)
ScribeLeaveMessage (const ScribeLeaveMessage &other)
virtual ~ScribeLeaveMessage ()
ScribeLeaveMessage & operator= (const ScribeLeaveMessage &other)
virtual ScribeLeaveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrc ()
virtual const NodeHandle & getSrc () const
virtual void setSrc (const NodeHandle &src)
virtual OverlayKey & getGroupId ()
virtual const OverlayKey & getGroupId () const
virtual void setGroupId (const OverlayKey &groupId)
Protected Member Functions
bool operator== (const ScribeLeaveMessage &)
Protected Attributes
NodeHandle src_var
OverlayKey groupId_var
Private Member Functions
void copy (const ScribeLeaveMessage &other)
Detailed Description
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
 packet ScribeLeaveMessage
 {
         NodeHandle src;
         OverlayKey groupId;
 }
Definition at line 278 of file ScribeMessage_m.h.
Constructor & Destructor Documentation
ScribeLeaveMessage::ScribeLeaveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ScribeLeaveMessage::ScribeLeaveMessage (const ScribeLeaveMessage & other)
virtual ScribeLeaveMessage::~ScribeLeaveMessage () [virtual]
Member Function Documentation
void ScribeLeaveMessage::copy (const ScribeLeaveMessage & other) [private]
virtual ScribeLeaveMessage* ScribeLeaveMessage::dup () const [inline, virtual]
Definition at line 296 of file ScribeMessage_m.h.
{return new ScribeLeaveMessage(*this);}
virtual OverlayKey& ScribeLeaveMessage::getGroupId () [virtual]
Referenced by Scribe::handleLeaveMessage().
virtual const OverlayKey& ScribeLeaveMessage::getGroupId () const [inline, virtual]
Definition at line 305 of file ScribeMessage_m.h.
Referenced by getGroupId().
{return const_cast<ScribeLeaveMessage*>(this)->getGroupId();}
virtual NodeHandle& ScribeLeaveMessage::getSrc () [virtual]
Referenced by Scribe::handleLeaveMessage().
virtual const NodeHandle& ScribeLeaveMessage::getSrc () const [inline, virtual]
Definition at line 302 of file ScribeMessage_m.h.
Referenced by getSrc().
{return const_cast<ScribeLeaveMessage*>(this)->getSrc();}
ScribeLeaveMessage& ScribeLeaveMessage::operator= (const ScribeLeaveMessage & other)
bool ScribeLeaveMessage::operator== (const ScribeLeaveMessage &) [protected]
virtual void ScribeLeaveMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void ScribeLeaveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void ScribeLeaveMessage::setGroupId (const OverlayKey & groupId) [virtual]
Referenced by Scribe::checkGroupEmpty().
virtual void ScribeLeaveMessage::setSrc (const NodeHandle & src) [virtual]
Referenced by Scribe::checkGroupEmpty().
Member Data Documentation
OverlayKey ScribeLeaveMessage::groupId_var [protected]
Definition at line 282 of file ScribeMessage_m.h.
NodeHandle ScribeLeaveMessage::src_var [protected]
Definition at line 281 of file ScribeMessage_m.h.
The documentation for this class was generated from the following file:
ScribeMessage_m.h