OverSim: BootstrapList Class Reference
BootstrapList Class Reference
The BootstrapList module maintains a list of bootstrap node candidates.
#include <BootstrapList.h>
Public Member Functions
BootstrapList ()
~BootstrapList ()
const TransportAddress getBootstrapNode (int32_t overlayId=0)
Get a bootstrap node from the bootstrap list.
void locateBootstrapNode (const NodeHandle &node)
Determine locality of a bootstrap node.
bool insertBootstrapCandidate (const NodeHandle &node, BootstrapNodePrioType prio=DNSSD)
Inserts a new bootstrap candidate into the bootstrap list.
bool insertBootstrapCandidate (BootstrapNodeHandle &node)
void removeBootstrapCandidate (const TransportAddress &addr)
Remove an unavailable bootstrap candidate from the bootstraplist.
void removeBootstrapNode (const NodeHandle &node, int32_t overlayId=0)
void registerBootstrapNode (const NodeHandle &node, int32_t overlayId=0)
Protected Member Functions
virtual void pingResponse (PingResponse *pingResponse, cPolymorphic *context, int rpcId, simtime_t rtt)
virtual void pingTimeout (PingCall *pingCall, const TransportAddress &dest, cPolymorphic *context, int rpcId)
virtual CompType getThisCompType ()
Return the component type of this module.
Private Member Functions
virtual void initializeApp (int stage)
initializes derived class-attributes
virtual void finishApp ()
collects statistical data of derived app
void handleTimerEvent (cMessage *msg)
void handleBootstrapListTimerExpired ()
Periodic maintenance method for the bootstrap list.
void handleRpcResponse (BaseResponseMessage *msg, cPolymorphic *context, int rpcId, simtime_t rtt)
This method is called if an RPC response has been received.
void handleLookupResponse (LookupResponse *msg)
Handle the response for a lookup rpc.
Private Attributes
BootstrapNodeSet bootstrapList
cMessage * timerMsg
self-message for periodic maintenance
ZeroconfConnector * zeroconfConnector
pointer to the ZeroconfConnector module
bool mergeOverlayPartitions
if true, detect and merge overlay partitions
bool maintainList
maintain a list of bootstrap candidates and check them periodically
Static Private Attributes
static const int timerInterval = 10
the interval of the maintenance timer in seconds
Detailed Description
The BootstrapList module maintains a list of bootstrap node candidates.
The BootstrapList module maintains a list of bootstrap node candidates received from various sources (GlobalNodeList for simulations and ZeroconfConnector for SingleHostUnderlay). This list is also used to detect overlay partitions and triggers the merging process.
Author:
Bin Zheng, Ingmar Baumgart
See also:
BootstrapList
Definition at line 53 of file BootstrapList.h.
Constructor & Destructor Documentation
BootstrapList::BootstrapList ()
Definition at line 60 of file BootstrapList.cc.
{
    zeroconfConnector = NULL;
    timerMsg = NULL;
}
BootstrapList::~BootstrapList ()
Definition at line 67 of file BootstrapList.cc.
{
    cancelAndDelete(timerMsg);
}
Member Function Documentation
void BootstrapList::finishApp () [private, virtual]
collects statistical data of derived app
Reimplemented from BaseApp.
Definition at line 386 of file BootstrapList.cc.
{
    // dump the list of bootstrap nodes into the local cache only when
    // using SingleHostUnderlayConfigurator
    if (zeroconfConnector) {
        ofstream nodeListFile("nodelist.dat", ios::out|ios::trunc);
        if (!nodeListFile) {
            std::cerr << "nodelist.dat could not be opened" << endl;
        } else {
            for (BootstrapNodeSet::iterator iter = bootstrapList.begin();
                 iter != bootstrapList.end(); iter++) {
                nodeListFile << iter->second->getIp().str() << ' '
                             << iter->second->getPort() << ' '
                             << iter->second->getKey().toString(16) << '\n';
            }
            nodeListFile.close();
        }
    }
    // delete all bootstrap nodes and clear the list
    for (BootstrapNodeSet::iterator iter = bootstrapList.begin();
         iter != bootstrapList.end(); iter++) {
        delete iter->second;
    }
    bootstrapList.clear();
}
const TransportAddress BootstrapList::getBootstrapNode (int32_t overlayId = 0)
Get a bootstrap node from the bootstrap list.
If not using SingleHostUnderlayConfigurator and the list is empty, return a node by asking the GlobalNodeList.
Parameters:
overlayId id of the overlay. Is used to support multiple disjoint overlays. Default is 0.
Definition at line 237 of file BootstrapList.cc.
Referenced by BasePastry::baseChangeState(), Gia::changeState(), HTopology::changeState(), oversim::Nice::changeState(), Quon::handleJoin(), Vast::handleJoin(), NeighborCache::handleReadyMessage(), Kademlia::joinOverlay(), and NeighborCache::prepareOverlay().
{
    // ask neighborCache (discovery or re-join)
    const TransportAddress temp = neighborCache->getBootstrapNode();
    if (!temp.isUnspecified()) {
        return temp;
    }
    if (!maintainList) {
        // TODO: add a parameter to return malicious bootstrap nodes also
        return overlay->globalNodeList->getRandomNode(overlayId, -1, true,
                                                      true);
        // return overlay->globalNodeList->getBootstrapNode();
    } else {
        const NodeHandle *bootstrapNode = &NodeHandle::UNSPECIFIED_NODE;
        int i, j = 0;
        // pick a random node from the list
        if (!bootstrapList.empty()) {
            i = intrand(bootstrapList.size());
            BootstrapNodeSet::iterator iter = bootstrapList.begin();
            while (j < i) {
                iter++;
                j++;
            }
            bootstrapNode = (NodeHandle *)iter->second;
        } else {
            // if the list empty, get a bootstrap node from GlobalNodeList
            if (!zeroconfConnector)
                bootstrapNode = &overlay->globalNodeList->
                        getBootstrapNode(overlayId, overlay->getThisNode());
        }
        return *bootstrapNode;
    }
}
virtual CompType BootstrapList::getThisCompType () [inline, protected, virtual]
Return the component type of this module.
This method is overloaded by BaseOverlay/BaseApp and returns the appropriate component type of this module.
Returns:
the component type of this module
Reimplemented from BaseApp.
Definition at line 113 of file BootstrapList.h.
{ return BOOTSTRAPLIST_COMP; };
void BootstrapList::handleBootstrapListTimerExpired () [private]
Periodic maintenance method for the bootstrap list.
Definition at line 140 of file BootstrapList.cc.
{
    simtime_t current = simTime();
    BootstrapNodeHandle *node;
    BootstrapNodeSet::iterator iter;
    for (iter = bootstrapList.begin(); iter != bootstrapList.end(); iter++) {
        node = iter->second;
        if (timerInterval <= SIMTIME_DBL(current - node->getLastPing())) {
            pingNode(*node);
        }
    }
}
void BootstrapList::handleLookupResponse (LookupResponse * msg) [private]
Handle the response for a lookup rpc.
This is used to detected foreign overlay partitions
Parameters:
msg The lookup response message
Definition at line 172 of file BootstrapList.cc.
{
    EV << "[BootstrapList::handleLookupResponse() @ "
       << overlay->getThisNode().getIp()
       << " (" << overlay->getThisNode().getKey().toString(16) << ")]\n"
       << "    Lookup response for key " << msg->getKey()<< " : ";
    if (msg->getIsValid()) {
        for (uint32_t i=0; i<msg->getSiblingsArraySize(); i++) {
            if (msg->getSiblings(i).getKey() == msg->getKey()) {
                EV << "Key " << msg->getSiblings(i)
                   << "belongs to a local node." << endl;
                return;
            }
        }
        EV << "New partition discovered, going to join." << endl;
        BootstrapNodeSet::iterator iter;
        for (iter = bootstrapList.begin(); iter != bootstrapList.end(); iter++) {
            if (iter->second->getKey() == msg->getKey())
                overlay->joinForeignPartition(*iter->second);
        }
    } else {
        EV << "failed" << endl;
    }
    return;
}
void BootstrapList::handleRpcResponse (BaseResponseMessage * msg, cPolymorphic * context, int rpcId, simtime_t rtt) [private, virtual]
This method is called if an RPC response has been received.
Parameters:
msg The response message.
context Pointer to an optional state object. The object has to be handled/deleted by the handleRpcResponse() code
rpcId The RPC id.
rtt The Round-Trip-Time of this RPC
Reimplemented from RpcListener.
Definition at line 155 of file BootstrapList.cc.
{
    RPC_SWITCH_START(msg)
    RPC_ON_RESPONSE(Lookup) {
        handleLookupResponse(_LookupResponse);
        EV << "[BootstrapList::handleRpcResponse() @ "
           << overlay->getThisNode().getIp()
           << " (" << overlay->getThisNode().getKey().toString(16) << ")]\n"
           << "    Lookup RPC Response received: id=" << rpcId << "\n"
           << "    msg=" << *_LookupResponse << " rtt=" << rtt
           << endl;
    }
    RPC_SWITCH_END( )
}
void BootstrapList::handleTimerEvent (cMessage * msg) [private, virtual]
Reimplemented from BaseRpc.
Definition at line 129 of file BootstrapList.cc.
{
    if (msg == timerMsg) {
        handleBootstrapListTimerExpired();
        scheduleAt(simTime() + timerInterval, msg);
    } else {
        throw cRuntimeError("BootstrapList::handleTimerEvent(): "
                             "Received unknown self-message!");
    }
}
void BootstrapList::initializeApp (int stage) [private, virtual]
initializes derived class-attributes
Parameters:
stage the init stage
Reimplemented from BaseApp.
Definition at line 73 of file BootstrapList.cc.
{
    if (stage != MIN_STAGE_COMPONENTS) {
        return;
    }
    mergeOverlayPartitions = par("mergeOverlayPartitions");
    maintainList = par("maintainList");
    if (getParentModule()->getParentModule()->getSubmodule("zeroconfConnector", 0)) {
        zeroconfConnector = check_and_cast<ZeroconfConnector *>(getParentModule()->
                getParentModule()->getSubmodule("zeroconfConnector", 0));
        if (!zeroconfConnector->isEnabled()) {
            zeroconfConnector = NULL;
        }
    }
    // load local cache list only when using SingleHostUnderlayConfigurator
    if (zeroconfConnector) {
        ifstream nodeListFile("nodelist.dat", ios::in);
        if (!nodeListFile) {
            EV << "[BootstrapList::initializeApp() @ " << overlay->getThisNode().getIp()
               << " (" << overlay->getThisNode().getKey() << ")]\n"
               << "    nodelist.dat not found"
               << endl;
        } else {
            char address[16];
            int port;
            string key;
            BootstrapNodeHandle *node;
            while (nodeListFile >> address >> port >> key) {
                node = new BootstrapNodeHandle(OverlayKey(key, 16),
                                               IPvXAddress(address), port,
                                               CACHE);
                if (node)
                    insertBootstrapCandidate(*node);
            }
            nodeListFile.close();
            //TODO
            if (bootstrapList.size()) sendReadyMessage();
        }
    } else {
        sendReadyMessage();
    }
    WATCH_UNORDERED_MAP(bootstrapList);
    if (maintainList) {
        timerMsg = new cMessage("BootstrapListTimer");
        scheduleAt(simTime() + timerInterval, timerMsg);
    }
}
bool BootstrapList::insertBootstrapCandidate (const NodeHandle & node, BootstrapNodePrioType prio = DNSSD)
Inserts a new bootstrap candidate into the bootstrap list.
Parameters:
node the bootstrap candidate
prio priority of the bootstrap node
Returns:
true, if bootstrap node is already in the list
Definition at line 293 of file BootstrapList.cc.
Referenced by GlobalNodeList::mergeBootstrapNodes().
{
    Enter_Method_Silent();
    BootstrapNodeSet::iterator iter;
    BootstrapNodeHandle *bootstrapNode;
    // if node already in the list, update its lastPing and nodePrio fields
    if ((iter = bootstrapList.find(node)) != bootstrapList.end()) {
        iter->second->setLastPing(simTime());
        iter->second->setNodePrio(prio);
        return true;
    }
    if ((bootstrapNode = new BootstrapNodeHandle(node, prio))) {
        bootstrapNode->setLastPing(simTime());
        bootstrapList.insert(NodePair(*bootstrapNode, bootstrapNode));
    }
    locateBootstrapNode(node);
    return false;
}
bool BootstrapList::insertBootstrapCandidate (BootstrapNodeHandle & node)
Definition at line 320 of file BootstrapList.cc.
{
    Enter_Method_Silent();
    BootstrapNodeSet::iterator iter;
    node.setLastPing(simTime());
    // if node already in the list, update its lastPing and nodePrio fields
    if ((iter = bootstrapList.find(node)) != bootstrapList.end()) {
        iter->second->setLastPing(node.getLastPing());
        iter->second->setNodePrio(node.getNodePrio());
        return true;
    }
    bootstrapList.insert(NodePair(node, &node));
    locateBootstrapNode(node);
    return false;
}
void BootstrapList::locateBootstrapNode (const NodeHandle & node)
Determine locality of a bootstrap node.
Parameters:
node the newly discovered bootstrap node
Definition at line 276 of file BootstrapList.cc.
{
    Enter_Method_Silent();
    if ((overlay->getState() == BaseOverlay::READY) && (!node.isUnspecified())
            && mergeOverlayPartitions) {
       LookupCall* call = new LookupCall();
       call->setBitLength(0);
       call->setKey(node.getKey());
       call->setNumSiblings(overlay->getMaxNumSiblings());
       sendInternalRpcCall(OVERLAY_COMP, call);
    }
    return;
}
void BootstrapList::pingResponse (PingResponse * pingResponse, cPolymorphic * context, int rpcId, simtime_t rtt) [protected, virtual]
Reimplemented from BaseRpc.
Definition at line 203 of file BootstrapList.cc.
{
    NodeHandle &srcNode = pingResponse->getSrcNode();
    BootstrapNodeSet::iterator iter;
    EV << "[BootstrapList::pingResponse() @ " << overlay->getThisNode().getIp()
           << " (" << overlay->getThisNode().getKey() << ")]\n"
           << "    Ping response from node " << srcNode
           << " with rtt " << rtt << endl;
    // update the lastPing field of the source node
    if (!srcNode.isUnspecified())
        if ((iter = bootstrapList.find(srcNode)) != bootstrapList.end())
            iter->second->setLastPing(simTime());
    return;
}
void BootstrapList::pingTimeout (PingCall * pingCall, const TransportAddress & dest, cPolymorphic * context, int rpcId) [protected, virtual]
Reimplemented from BaseRpc.
Definition at line 224 of file BootstrapList.cc.
{
    EV << "[BootstrapList::pingTimeout() @ " << overlay->getThisNode().getIp()
       << " (" << overlay->getThisNode().getKey() << ")]\n"
       << "    Ping timeout for node " << dest << endl;
    // destination does not answer, remove it from the list
    removeBootstrapCandidate(dest);
}
void BootstrapList::registerBootstrapNode (const NodeHandle & node, int32_t overlayId = 0)
Definition at line 373 of file BootstrapList.cc.
Referenced by TCPExampleApp::initializeApp().
{
    globalNodeList->registerPeer(node, overlayId);
    // at this point, we consider this node as booted and therefore have to
    // announce the boot service for it via zeroconfConnector
    if (zeroconfConnector) {
        zeroconfConnector->announceService(node);
    }
}
void BootstrapList::removeBootstrapCandidate (const TransportAddress & addr)
Remove an unavailable bootstrap candidate from the bootstraplist.
Parameters:
addr the address of the bootstrap candidate
Definition at line 343 of file BootstrapList.cc.
{
    BootstrapNodeSet::iterator iter;
    BootstrapNodeHandle* bootstrapNode;
    if (!addr.isUnspecified()) {
        if ((iter = bootstrapList.find(addr)) != bootstrapList.end()) {
            bootstrapNode = iter->second;
            bootstrapList.erase(iter);
            delete bootstrapNode;
        }
    }
    return;
}
void BootstrapList::removeBootstrapNode (const NodeHandle & node, int32_t overlayId = 0)
Definition at line 360 of file BootstrapList.cc.
Referenced by BasePastry::baseChangeState(), HTopology::changeState(), oversim::Nice::changeState(), Gia::finishOverlay(), BasePastry::finishOverlay(), HTopology::finishOverlay(), and Kademlia::joinOverlay().
{
    overlay->globalNodeList->removePeer(node, overlayId);
    // at this point, we consider this node not being able to provide the
    // boot service anymore, therefore we have to revoke
    // the service via zeroconfConnector
    if (zeroconfConnector) {
        zeroconfConnector->revokeService();
    }
}
Member Data Documentation
BootstrapNodeSet BootstrapList::bootstrapList [private]
Definition at line 113 of file BootstrapList.h.
bool BootstrapList::maintainList [private]
maintain a list of bootstrap candidates and check them periodically
Definition at line 150 of file BootstrapList.h.
bool BootstrapList::mergeOverlayPartitions [private]
if true, detect and merge overlay partitions
Definition at line 149 of file BootstrapList.h.
const int BootstrapList::timerInterval = 10 [static, private]
the interval of the maintenance timer in seconds
Definition at line 145 of file BootstrapList.h.
cMessage* BootstrapList::timerMsg [private]
self-message for periodic maintenance
Definition at line 147 of file BootstrapList.h.
ZeroconfConnector* BootstrapList::zeroconfConnector [private]
pointer to the ZeroconfConnector module
Definition at line 148 of file BootstrapList.h.
The documentation for this class was generated from the following files:
BootstrapList.h
BootstrapList.cc