OverSim: VastMessage Class Reference
VastMessage Class Reference
Class generated from overlay/vast/Vast.msg by opp_msgc.
#include <Vast_m.h>
Public Member Functions
VastMessage (const char *name=NULL, int kind=0)
VastMessage (const VastMessage &other)
virtual ~VastMessage ()
VastMessage & operator= (const VastMessage &other)
virtual VastMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getCommand () const
virtual void setCommand (int command)
virtual NodeHandle & getSourceNode ()
virtual const NodeHandle & getSourceNode () const
virtual void setSourceNode (const NodeHandle &sourceNode)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual Vector2D & getPos ()
virtual const Vector2D & getPos () const
virtual void setPos (const Vector2D &pos)
virtual int getNeighborCount () const
virtual void setNeighborCount (int neighborCount)
Protected Member Functions
bool operator== (const VastMessage &)
Protected Attributes
int command_var
NodeHandle sourceNode_var
OverlayKey destKey_var
Vector2D pos_var
int neighborCount_var
Private Member Functions
void copy (const VastMessage &other)
Detailed Description
Class generated from overlay/vast/Vast.msg by opp_msgc.
 packet VastMessage extends BaseOverlayMessage
 {
     int command enum(VASTCommand);
     NodeHandle sourceNode;
     OverlayKey destKey;
     Vector2D pos;
     int neighborCount;
 }
Definition at line 83 of file Vast_m.h.
Constructor & Destructor Documentation
VastMessage::VastMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
VastMessage::VastMessage (const VastMessage & other)
virtual VastMessage::~VastMessage () [virtual]
Member Function Documentation
void VastMessage::copy (const VastMessage & other) [private]
virtual VastMessage* VastMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in VastEventMessage, VastDiscardMessage, VastMoveMessage, and VastListMessage.
Definition at line 104 of file Vast_m.h.
{return new VastMessage(*this);}
virtual int VastMessage::getCommand () const [virtual]
Referenced by Vast::handleUDPMessage(), and Vast::sendMessage().
virtual OverlayKey& VastMessage::getDestKey () [virtual]
Referenced by Vast::handleUDPMessage(), and Vast::sendDiscardNode().
virtual const OverlayKey& VastMessage::getDestKey () const [inline, virtual]
Definition at line 115 of file Vast_m.h.
Referenced by getDestKey().
{return const_cast<VastMessage*>(this)->getDestKey();}
virtual int VastMessage::getNeighborCount () const [virtual]
Referenced by Vast::handleJoinAcknowledge(), Vast::handleNodeMove(), and Vast::handlePong().
virtual Vector2D& VastMessage::getPos () [virtual]
Referenced by Vast::handleJoinAcknowledge(), Vast::handleJoinRequest(), Vast::handleNodeMove(), and Vast::handlePong().
virtual const Vector2D& VastMessage::getPos () const [inline, virtual]
Definition at line 118 of file Vast_m.h.
Referenced by getPos().
{return const_cast<VastMessage*>(this)->getPos();}
virtual NodeHandle& VastMessage::getSourceNode () [virtual]
Referenced by Vast::handleEnclosingNeighborsRequest(), Vast::handleJoinAcknowledge(), Vast::handleJoinRequest(), Vast::handleNodeLeave(), Vast::handleNodeMove(), Vast::handlePing(), Vast::handlePong(), Vast::handleUDPMessage(), Vast::sendDiscardNode(), Vast::sendMessage(), and Vast::synchronizeApp().
virtual const NodeHandle& VastMessage::getSourceNode () const [inline, virtual]
Definition at line 112 of file Vast_m.h.
Referenced by getSourceNode().
{return const_cast<VastMessage*>(this)->getSourceNode();}
VastMessage& VastMessage::operator= (const VastMessage & other)
bool VastMessage::operator== (const VastMessage &) [protected]
virtual void VastMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in VastEventMessage, VastDiscardMessage, VastMoveMessage, and VastListMessage.
Referenced by doPacking().
virtual void VastMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in VastEventMessage, VastDiscardMessage, VastMoveMessage, and VastListMessage.
Referenced by doUnpacking().
virtual void VastMessage::setCommand (int command) [virtual]
Referenced by Vast::handleEnclosingNeighborsRequest(), Vast::handleEvent(), Vast::handleJoin(), Vast::handleJoinAcknowledge(), Vast::handleJoinRequest(), Vast::handleMove(), Vast::handleNewNeighbors(), Vast::handleNodeGracefulLeaveNotification(), Vast::handleNodeMove(), Vast::handlePing(), Vast::processCheckCriticalTimer(), Vast::processDiscoveryTimer(), Vast::processPingTimer(), and Vast::sendDiscardNode().
virtual void VastMessage::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by Vast::sendMessage().
virtual void VastMessage::setNeighborCount (int neighborCount) [virtual]
Referenced by Vast::sendMessage().
virtual void VastMessage::setPos (const Vector2D & pos) [virtual]
Referenced by Vast::sendMessage().
virtual void VastMessage::setSourceNode (const NodeHandle & sourceNode) [virtual]
Referenced by Vast::sendMessage().
Member Data Documentation
int VastMessage::command_var [protected]
Definition at line 86 of file Vast_m.h.
OverlayKey VastMessage::destKey_var [protected]
Definition at line 88 of file Vast_m.h.
int VastMessage::neighborCount_var [protected]
Definition at line 90 of file Vast_m.h.
Vector2D VastMessage::pos_var [protected]
Definition at line 89 of file Vast_m.h.
NodeHandle VastMessage::sourceNode_var [protected]
Definition at line 87 of file Vast_m.h.
The documentation for this class was generated from the following file:
Vast_m.h