OverSim: I3QueryReplyMessage_Base Class Reference
I3QueryReplyMessage_Base Class Reference
Class generated from applications/i3/I3Message.msg by opp_msgc.
#include <I3Message_m.h>
Public Member Functions
virtual ~I3QueryReplyMessage_Base ()
virtual I3QueryReplyMessage_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual I3IPAddress & getSource ()
virtual const I3IPAddress & getSource () const
virtual void setSource (const I3IPAddress &source)
virtual I3Identifier & getIdentifier ()
virtual const I3Identifier & getIdentifier () const
virtual void setIdentifier (const I3Identifier &identifier)
virtual simtime_t getSendingTime () const
virtual void setSendingTime (simtime_t sendingTime)
Protected Member Functions
bool operator== (const I3QueryReplyMessage_Base &)
I3QueryReplyMessage_Base (const char *name=NULL, int kind=0)
I3QueryReplyMessage_Base (const I3QueryReplyMessage_Base &other)
I3QueryReplyMessage_Base & operator= (const I3QueryReplyMessage_Base &other)
Protected Attributes
I3IPAddress source_var
I3Identifier identifier_var
simtime_t sendingTime_var
Private Member Functions
void copy (const I3QueryReplyMessage_Base &other)
Detailed Description
Class generated from applications/i3/I3Message.msg by opp_msgc.
 packet I3QueryReplyMessage extends I3Message
 {
     (true);
         I3IPAddress source;
         I3Identifier identifier;
         simtime_t sendingTime;
 }
I3QueryReplyMessage_Base is only useful if it gets subclassed, and I3QueryReplyMessage is derived from it. The minimum code to be written for I3QueryReplyMessage is the following:
 class I3QueryReplyMessage : public I3QueryReplyMessage_Base
 {
   private:
     void copy(const I3QueryReplyMessage& other) { ... }
   public:
     I3QueryReplyMessage(const char *name=NULL, int kind=0) : I3QueryReplyMessage_Base(name,kind) {}
     I3QueryReplyMessage(const I3QueryReplyMessage& other) : I3QueryReplyMessage_Base(other) {copy(other);}
     I3QueryReplyMessage& operator=(const I3QueryReplyMessage& other) {if (this==&other) return *this; I3QueryReplyMessage_Base::operator=(other); copy(other); return *this;}
     virtual I3QueryReplyMessage *dup() const {return new I3QueryReplyMessage(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from I3QueryReplyMessage_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(I3QueryReplyMessage);
Definition at line 199 of file I3Message_m.h.
Constructor & Destructor Documentation
I3QueryReplyMessage_Base::I3QueryReplyMessage_Base (const char * name = NULL, int kind = 0) [protected]
I3QueryReplyMessage_Base::I3QueryReplyMessage_Base (const I3QueryReplyMessage_Base & other) [protected]
virtual I3QueryReplyMessage_Base::~I3QueryReplyMessage_Base () [virtual]
Member Function Documentation
void I3QueryReplyMessage_Base::copy (const I3QueryReplyMessage_Base & other) [private]
virtual I3QueryReplyMessage_Base* I3QueryReplyMessage_Base::dup () const [inline, virtual]
Reimplemented from I3Message.
Reimplemented in I3QueryReplyMessage.
Definition at line 220 of file I3Message_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class I3QueryReplyMessage");}
virtual I3Identifier& I3QueryReplyMessage_Base::getIdentifier () [virtual]
Referenced by I3BaseApp::handleUDPMessage().
virtual const I3Identifier& I3QueryReplyMessage_Base::getIdentifier () const [inline, virtual]
Definition at line 229 of file I3Message_m.h.
Referenced by getIdentifier().
{return const_cast<I3QueryReplyMessage_Base*>(this)->getIdentifier();}
virtual simtime_t I3QueryReplyMessage_Base::getSendingTime () const [virtual]
Referenced by I3BaseApp::handleUDPMessage().
virtual I3IPAddress& I3QueryReplyMessage_Base::getSource () [virtual]
Referenced by I3BaseApp::handleUDPMessage().
virtual const I3IPAddress& I3QueryReplyMessage_Base::getSource () const [inline, virtual]
Definition at line 226 of file I3Message_m.h.
Referenced by getSource().
{return const_cast<I3QueryReplyMessage_Base*>(this)->getSource();}
I3QueryReplyMessage_Base& I3QueryReplyMessage_Base::operator= (const I3QueryReplyMessage_Base & other) [protected]
bool I3QueryReplyMessage_Base::operator== (const I3QueryReplyMessage_Base &) [protected]
virtual void I3QueryReplyMessage_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3QueryReplyMessage_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3QueryReplyMessage_Base::setIdentifier (const I3Identifier & identifier) [virtual]
virtual void I3QueryReplyMessage_Base::setSendingTime (simtime_t sendingTime) [virtual]
virtual void I3QueryReplyMessage_Base::setSource (const I3IPAddress & source) [virtual]
Member Data Documentation
I3Identifier I3QueryReplyMessage_Base::identifier_var [protected]
Definition at line 203 of file I3Message_m.h.
simtime_t I3QueryReplyMessage_Base::sendingTime_var [protected]
Definition at line 204 of file I3Message_m.h.
I3IPAddress I3QueryReplyMessage_Base::source_var [protected]
Definition at line 202 of file I3Message_m.h.
The documentation for this class was generated from the following file:
I3Message_m.h