OverSim: GiaMessage Class Reference
GiaMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
GiaMessage (const char *name=NULL, int kind=0)
GiaMessage (const GiaMessage &other)
virtual ~GiaMessage ()
GiaMessage & operator= (const GiaMessage &other)
virtual GiaMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getSrcNode ()
virtual const NodeHandle & getSrcNode () const
virtual void setSrcNode (const NodeHandle &srcNode)
virtual int getHopCount () const
virtual void setHopCount (int hopCount)
virtual int getCommand () const
virtual void setCommand (int command)
virtual double getSrcCapacity () const
virtual void setSrcCapacity (double srcCapacity)
virtual int getSrcDegree () const
virtual void setSrcDegree (int srcDegree)
Protected Member Functions
bool operator== (const GiaMessage &)
Protected Attributes
NodeHandle srcNode_var
int hopCount_var
int command_var
double srcCapacity_var
int srcDegree_var
Private Member Functions
void copy (const GiaMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message GiaMessage extends BaseOverlayMessage
 {
        NodeHandle srcNode;
        int hopCount = 0;
        int command enum(GIACommand);
        double srcCapacity;
        int srcDegree;
 };
Definition at line 93 of file GiaMessage_m.h.
Constructor & Destructor Documentation
GiaMessage::GiaMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GiaMessage::GiaMessage (const GiaMessage & other)
virtual GiaMessage::~GiaMessage () [virtual]
Member Function Documentation
void GiaMessage::copy (const GiaMessage & other) [private]
virtual GiaMessage* GiaMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in SearchResponseMessage, SearchMessage, KeyListMessage, GiaRouteMessage, GiaIDMessage, TokenMessage, and GiaNeighborMessage.
Definition at line 114 of file GiaMessage_m.h.
{return new GiaMessage(*this);}
virtual int GiaMessage::getCommand () const [virtual]
Referenced by Gia::handleUDPMessage().
virtual int GiaMessage::getHopCount () const [virtual]
Referenced by Gia::forwardMessage(), Gia::forwardSearchResponseMessage(), and Gia::handleUDPMessage().
virtual double GiaMessage::getSrcCapacity () const [virtual]
Referenced by Gia::handleUDPMessage().
virtual int GiaMessage::getSrcDegree () const [virtual]
Referenced by Gia::handleUDPMessage(), and Gia::updateNeighborList().
virtual NodeHandle& GiaMessage::getSrcNode () [virtual]
Referenced by GiaMessageBookkeeping::addMessage(), Gia::deliverSearchResult(), Gia::forwardMessage(), Gia::handleUDPMessage(), and Gia::updateNeighborList().
virtual const NodeHandle& GiaMessage::getSrcNode () const [inline, virtual]
Definition at line 120 of file GiaMessage_m.h.
Referenced by getSrcNode().
{return const_cast<GiaMessage*>(this)->getSrcNode();}
GiaMessage& GiaMessage::operator= (const GiaMessage & other)
bool GiaMessage::operator== (const GiaMessage &) [protected]
virtual void GiaMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in SearchResponseMessage, SearchMessage, KeyListMessage, GiaRouteMessage, GiaIDMessage, TokenMessage, and GiaNeighborMessage.
Referenced by doPacking().
virtual void GiaMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Reimplemented in SearchResponseMessage, SearchMessage, KeyListMessage, GiaRouteMessage, GiaIDMessage, TokenMessage, and GiaNeighborMessage.
Referenced by doUnpacking().
virtual void GiaMessage::setCommand (int command) [virtual]
Referenced by Gia::getRoute(), Gia::sendKeyListToNeighbor(), Gia::sendMessage_DISCONNECT(), Gia::sendMessage_JOIN_ACK(), Gia::sendMessage_JOIN_DNY(), Gia::sendMessage_JOIN_REQ(), Gia::sendMessage_JOIN_RSP(), Gia::sendMessage_UPDATE(), Gia::sendSearchResponseMessage(), and Gia::sendToken().
virtual void GiaMessage::setHopCount (int hopCount) [virtual]
Referenced by Gia::forwardMessage(), Gia::getRoute(), Gia::sendSearchResponseMessage(), and Gia::sendToken().
virtual void GiaMessage::setSrcCapacity (double srcCapacity) [virtual]
Referenced by Gia::forwardMessage(), Gia::getRoute(), Gia::sendKeyListToNeighbor(), Gia::sendMessage_DISCONNECT(), Gia::sendMessage_JOIN_ACK(), Gia::sendMessage_JOIN_DNY(), Gia::sendMessage_JOIN_REQ(), Gia::sendMessage_JOIN_RSP(), Gia::sendMessage_UPDATE(), Gia::sendSearchResponseMessage(), and Gia::sendToken().
virtual void GiaMessage::setSrcDegree (int srcDegree) [virtual]
Referenced by Gia::forwardMessage(), Gia::getRoute(), Gia::sendKeyListToNeighbor(), Gia::sendMessage_DISCONNECT(), Gia::sendMessage_JOIN_ACK(), Gia::sendMessage_JOIN_DNY(), Gia::sendMessage_JOIN_REQ(), Gia::sendMessage_JOIN_RSP(), Gia::sendMessage_UPDATE(), Gia::sendSearchResponseMessage(), and Gia::sendToken().
virtual void GiaMessage::setSrcNode (const NodeHandle & srcNode) [virtual]
Referenced by Gia::forwardMessage(), Gia::getRoute(), Gia::sendKeyListToNeighbor(), Gia::sendMessage_DISCONNECT(), Gia::sendMessage_JOIN_ACK(), Gia::sendMessage_JOIN_DNY(), Gia::sendMessage_JOIN_REQ(), Gia::sendMessage_JOIN_RSP(), Gia::sendMessage_UPDATE(), Gia::sendSearchResponseMessage(), and Gia::sendToken().
Member Data Documentation
int GiaMessage::command_var [protected]
Definition at line 98 of file GiaMessage_m.h.
int GiaMessage::hopCount_var [protected]
Definition at line 97 of file GiaMessage_m.h.
double GiaMessage::srcCapacity_var [protected]
Definition at line 99 of file GiaMessage_m.h.
int GiaMessage::srcDegree_var [protected]
Definition at line 100 of file GiaMessage_m.h.
NodeHandle GiaMessage::srcNode_var [protected]
Definition at line 96 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h