OverSim: CompReadyMessage Class Reference
CompReadyMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
CompReadyMessage (const char *name=NULL, int kind=0)
CompReadyMessage (const CompReadyMessage &other)
virtual ~CompReadyMessage ()
CompReadyMessage & operator= (const CompReadyMessage &other)
virtual CompReadyMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getReady () const
virtual void setReady (bool ready)
virtual int getComp () const
virtual void setComp (int comp)
virtual OverlayKey & getNodeId ()
virtual const OverlayKey & getNodeId () const
virtual void setNodeId (const OverlayKey &nodeId)
Protected Member Functions
bool operator== (const CompReadyMessage &)
Protected Attributes
bool ready_var
int comp_var
OverlayKey nodeId_var
Private Member Functions
void copy (const CompReadyMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet CompReadyMessage
 {
     bool ready;
     int comp enum(CompType);
     OverlayKey nodeId = OverlayKey::UNSPECIFIED_KEY;
 }
Definition at line 881 of file CommonMessages_m.h.
Constructor & Destructor Documentation
CompReadyMessage::CompReadyMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
CompReadyMessage::CompReadyMessage (const CompReadyMessage & other)
virtual CompReadyMessage::~CompReadyMessage () [virtual]
Member Function Documentation
void CompReadyMessage::copy (const CompReadyMessage & other) [private]
virtual CompReadyMessage* CompReadyMessage::dup () const [inline, virtual]
Definition at line 900 of file CommonMessages_m.h.
{return new CompReadyMessage(*this);}
virtual int CompReadyMessage::getComp () const [virtual]
Referenced by BaseOverlay::handleMessage(), HStreaming::handleReadyMessage(), ALMTest::handleReadyMessage(), P2pns::handleReadyMessage(), SimpleGameClient::handleReadyMessage(), SimMud::handleReadyMessage(), Scribe::handleReadyMessage(), XmlRpcInterface::handleReadyMessage(), and NeighborCache::handleReadyMessage().
virtual OverlayKey& CompReadyMessage::getNodeId () [virtual]
Referenced by BaseOverlay::handleMessage().
virtual const OverlayKey& CompReadyMessage::getNodeId () const [inline, virtual]
Definition at line 910 of file CommonMessages_m.h.
Referenced by getNodeId().
{return const_cast<CompReadyMessage*>(this)->getNodeId();}
virtual bool CompReadyMessage::getReady () const [virtual]
Referenced by BaseOverlay::handleMessage(), HStreaming::handleReadyMessage(), ALMTest::handleReadyMessage(), P2pns::handleReadyMessage(), SimpleGameClient::handleReadyMessage(), SimMud::handleReadyMessage(), Scribe::handleReadyMessage(), XmlRpcInterface::handleReadyMessage(), and NeighborCache::handleReadyMessage().
CompReadyMessage& CompReadyMessage::operator= (const CompReadyMessage & other)
bool CompReadyMessage::operator== (const CompReadyMessage &) [protected]
virtual void CompReadyMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void CompReadyMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void CompReadyMessage::setComp (int comp) [virtual]
Referenced by Quon::changeState(), Vast::changeState(), PubSubMMOG::handleAppMessage(), NTree::handleAppMessage(), Quon::handleNodeGracefulLeaveNotification(), Vast::handleNodeLeaveNotification(), SimMud::handleReadyMessage(), Scribe::handleReadyMessage(), PubSubMMOG::handleSubscriptionResponse(), PubSubMMOG::handleTimerEvent(), NTree::handleTimerEvent(), BaseApp::sendReadyMessage(), and BaseOverlay::setOverlayReady().
virtual void CompReadyMessage::setNodeId (const OverlayKey & nodeId) [virtual]
Referenced by BaseApp::sendReadyMessage().
virtual void CompReadyMessage::setReady (bool ready) [virtual]
Referenced by Quon::changeState(), Vast::changeState(), PubSubMMOG::handleAppMessage(), NTree::handleAppMessage(), Quon::handleNodeGracefulLeaveNotification(), Vast::handleNodeLeaveNotification(), Scribe::handleReadyMessage(), PubSubMMOG::handleSubscriptionResponse(), PubSubMMOG::handleTimerEvent(), NTree::handleTimerEvent(), BaseApp::sendReadyMessage(), and BaseOverlay::setOverlayReady().
Member Data Documentation
int CompReadyMessage::comp_var [protected]
Definition at line 885 of file CommonMessages_m.h.
OverlayKey CompReadyMessage::nodeId_var [protected]
Definition at line 886 of file CommonMessages_m.h.
bool CompReadyMessage::ready_var [protected]
Definition at line 884 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h