OverSim: KBRforward Class Reference
KBRforward Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
KBRforward (const char *name=NULL, int kind=0)
KBRforward (const KBRforward &other)
virtual ~KBRforward ()
KBRforward & operator= (const KBRforward &other)
virtual KBRforward * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getDestKey ()
virtual const OverlayKey & getDestKey () const
virtual void setDestKey (const OverlayKey &destKey)
virtual NodeHandle & getNextHopNode ()
virtual const NodeHandle & getNextHopNode () const
virtual void setNextHopNode (const NodeHandle &nextHopNode)
Protected Member Functions
bool operator== (const KBRforward &)
Protected Attributes
OverlayKey destKey_var
NodeHandle nextHopNode_var
Private Member Functions
void copy (const KBRforward &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet KBRforward extends CommonAPIMessage
 {
     OverlayKey destKey;
     NodeHandle nextHopNode;
 }
Definition at line 1199 of file CommonMessages_m.h.
Constructor & Destructor Documentation
KBRforward::KBRforward (const char * name = NULL, int kind = 0)
Referenced by dup().
KBRforward::KBRforward (const KBRforward & other)
virtual KBRforward::~KBRforward () [virtual]
Member Function Documentation
void KBRforward::copy (const KBRforward & other) [private]
virtual KBRforward* KBRforward::dup () const [inline, virtual]
Reimplemented from CommonAPIMessage.
Definition at line 1217 of file CommonMessages_m.h.
{return new KBRforward(*this);}
virtual OverlayKey& KBRforward::getDestKey () [virtual]
Referenced by BaseApp::handleCommonAPIMessage(), and BaseOverlay::handleMessage().
virtual const OverlayKey& KBRforward::getDestKey () const [inline, virtual]
Definition at line 1223 of file CommonMessages_m.h.
Referenced by getDestKey().
{return const_cast<KBRforward*>(this)->getDestKey();}
virtual NodeHandle& KBRforward::getNextHopNode () [virtual]
Referenced by BaseApp::handleCommonAPIMessage(), and BaseOverlay::handleMessage().
virtual const NodeHandle& KBRforward::getNextHopNode () const [inline, virtual]
Definition at line 1226 of file CommonMessages_m.h.
Referenced by getNextHopNode().
{return const_cast<KBRforward*>(this)->getNextHopNode();}
KBRforward& KBRforward::operator= (const KBRforward & other)
bool KBRforward::operator== (const KBRforward &) [protected]
virtual void KBRforward::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from CommonAPIMessage.
Referenced by doPacking().
virtual void KBRforward::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from CommonAPIMessage.
Referenced by doUnpacking().
virtual void KBRforward::setDestKey (const OverlayKey & destKey) [virtual]
Referenced by BaseOverlay::callForward().
virtual void KBRforward::setNextHopNode (const NodeHandle & nextHopNode) [virtual]
Referenced by BaseOverlay::callForward().
Member Data Documentation
OverlayKey KBRforward::destKey_var [protected]
Definition at line 1202 of file CommonMessages_m.h.
NodeHandle KBRforward::nextHopNode_var [protected]
Definition at line 1203 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h