OverSim: I3SendPacketMessage Class Reference
I3SendPacketMessage Class Reference
#include <I3Message.h>
Public Member Functions
I3SendPacketMessage (const char *name=NULL, int kind=0)
I3SendPacketMessage (const I3SendPacketMessage &other)
I3SendPacketMessage & operator= (const I3SendPacketMessage &other)
virtual I3SendPacketMessage * dup () const
Detailed Description
Definition at line 49 of file I3Message.h.
Constructor & Destructor Documentation
I3SendPacketMessage::I3SendPacketMessage (const char * name = NULL, int kind = 0)
Definition at line 84 of file I3Message.cc.
Referenced by dup().
        : I3SendPacketMessage_Base(name,kind)
{
    setType(SEND_PACKET);
    setName("I3::SendPacket");
}
I3SendPacketMessage::I3SendPacketMessage (const I3SendPacketMessage & other)
Definition at line 91 of file I3Message.cc.
                                                                         :
        I3SendPacketMessage_Base(other.getName())
{
    setType(SEND_PACKET);
    operator=(other);
}
Member Function Documentation
I3SendPacketMessage * I3SendPacketMessage::dup () const [virtual]
Reimplemented from I3SendPacketMessage_Base.
Definition at line 104 of file I3Message.cc.
Referenced by I3::sendPacket().
{
    return new I3SendPacketMessage(*this);
}
I3SendPacketMessage & I3SendPacketMessage::operator= (const I3SendPacketMessage & other)
Definition at line 98 of file I3Message.cc.
Referenced by I3SendPacketMessage().
{
    I3SendPacketMessage_Base::operator=(other);
    return *this;
}
The documentation for this class was generated from the following files:
I3Message.h
I3Message.cc