OverSim: RequestLeafSetResponse Class Reference
RequestLeafSetResponse Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestLeafSetResponse (const char *name=NULL, int kind=0)
RequestLeafSetResponse (const RequestLeafSetResponse &other)
virtual ~RequestLeafSetResponse ()
RequestLeafSetResponse & operator= (const RequestLeafSetResponse &other)
virtual RequestLeafSetResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RequestLeafSetResponse &)
Private Member Functions
void copy (const RequestLeafSetResponse &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestLeafSetResponse extends BaseResponseMessage
 {
 }
Definition at line 534 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestLeafSetResponse::RequestLeafSetResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestLeafSetResponse::RequestLeafSetResponse (const RequestLeafSetResponse & other)
virtual RequestLeafSetResponse::~RequestLeafSetResponse () [virtual]
Member Function Documentation
void RequestLeafSetResponse::copy (const RequestLeafSetResponse & other) [private]
virtual RequestLeafSetResponse* RequestLeafSetResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 550 of file PastryMessage_m.h.
{return new RequestLeafSetResponse(*this);}
RequestLeafSetResponse& RequestLeafSetResponse::operator= (const RequestLeafSetResponse & other)
bool RequestLeafSetResponse::operator== (const RequestLeafSetResponse &) [protected]
virtual void RequestLeafSetResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void RequestLeafSetResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h