OverSim: FailedNodeResponse Class Reference
FailedNodeResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
FailedNodeResponse (const char *name=NULL, int kind=0)
FailedNodeResponse (const FailedNodeResponse &other)
virtual ~FailedNodeResponse ()
FailedNodeResponse & operator= (const FailedNodeResponse &other)
virtual FailedNodeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getTryAgain () const
virtual void setTryAgain (bool tryAgain)
Protected Member Functions
bool operator== (const FailedNodeResponse &)
Protected Attributes
bool tryAgain_var
Private Member Functions
void copy (const FailedNodeResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet FailedNodeResponse extends BaseResponseMessage
 {
     bool tryAgain;
 }
Definition at line 773 of file CommonMessages_m.h.
Constructor & Destructor Documentation
FailedNodeResponse::FailedNodeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
FailedNodeResponse::FailedNodeResponse (const FailedNodeResponse & other)
virtual FailedNodeResponse::~FailedNodeResponse () [virtual]
Member Function Documentation
void FailedNodeResponse::copy (const FailedNodeResponse & other) [private]
virtual FailedNodeResponse* FailedNodeResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 790 of file CommonMessages_m.h.
{return new FailedNodeResponse(*this);}
virtual bool FailedNodeResponse::getTryAgain () const [virtual]
Referenced by IterativeLookup::handleRpcResponse().
FailedNodeResponse& FailedNodeResponse::operator= (const FailedNodeResponse & other)
bool FailedNodeResponse::operator== (const FailedNodeResponse &) [protected]
virtual void FailedNodeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void FailedNodeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void FailedNodeResponse::setTryAgain (bool tryAgain) [virtual]
Referenced by BaseOverlay::failedNodeRpc().
Member Data Documentation
bool FailedNodeResponse::tryAgain_var [protected]
Definition at line 776 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h