OverSim: PubSubIntermediateResponse Class Reference
PubSubIntermediateResponse Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubIntermediateResponse (const char *name=NULL, int kind=0)
PubSubIntermediateResponse (const PubSubIntermediateResponse &other)
virtual ~PubSubIntermediateResponse ()
PubSubIntermediateResponse & operator= (const PubSubIntermediateResponse &other)
virtual
PubSubIntermediateResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
Protected Member Functions
bool operator== (const PubSubIntermediateResponse &)
Protected Attributes
int subspaceId_var
Private Member Functions
void copy (const PubSubIntermediateResponse &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubIntermediateResponse extends BaseResponseMessage
 {
         int subspaceId;
 }
Definition at line 656 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubIntermediateResponse::PubSubIntermediateResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubIntermediateResponse::PubSubIntermediateResponse (const PubSubIntermediateResponse & other)
virtual PubSubIntermediateResponse::~PubSubIntermediateResponse () [virtual]
Member Function Documentation
void PubSubIntermediateResponse::copy (const PubSubIntermediateResponse & other) [private]
virtual PubSubIntermediateResponse* PubSubIntermediateResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 673 of file PubSubMessage_m.h.
{return new PubSubIntermediateResponse(*this);}
virtual int PubSubIntermediateResponse::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse().
PubSubIntermediateResponse& PubSubIntermediateResponse::operator= (const PubSubIntermediateResponse & other)
bool PubSubIntermediateResponse::operator== (const PubSubIntermediateResponse &) [protected]
virtual void PubSubIntermediateResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void PubSubIntermediateResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void PubSubIntermediateResponse::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleIntermediateCall().
Member Data Documentation
int PubSubIntermediateResponse::subspaceId_var [protected]
Definition at line 659 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h