OverSim: HMessage Class Reference
HMessage Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HMessage (const char *name=NULL, int kind=0)
HMessage (const HMessage &other)
virtual ~HMessage ()
HMessage & operator= (const HMessage &other)
virtual HMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type)
virtual TransportAddress & getSenderAddress ()
virtual const TransportAddress & getSenderAddress () const
virtual void setSenderAddress (const TransportAddress &senderAddress)
virtual int getNodeID () const
virtual void setNodeID (int nodeID)
virtual int getParentID () const
virtual void setParentID (int parentID)
virtual int getOptionalParameter () const
virtual void setOptionalParameter (int optionalParameter)
virtual const char * getAnyMessage () const
virtual void setAnyMessage (const char *anyMessage)
Protected Member Functions
bool operator== (const HMessage &)
Protected Attributes
int type_var
TransportAddress senderAddress_var
int nodeID_var
int parentID_var
int optionalParameter_var
opp_string anyMessage_var
Private Member Functions
void copy (const HMessage &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HMessage {
     int type enum(MessageType);
     TransportAddress senderAddress;
     int nodeID;
     int parentID;
     int optionalParameter;
     string anyMessage;
 };
Definition at line 806 of file HMessage_m.h.
Constructor & Destructor Documentation
HMessage::HMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
HMessage::HMessage (const HMessage & other)
virtual HMessage::~HMessage () [virtual]
Member Function Documentation
void HMessage::copy (const HMessage & other) [private]
virtual HMessage* HMessage::dup () const [inline, virtual]
Definition at line 828 of file HMessage_m.h.
{return new HMessage(*this);}
virtual const char* HMessage::getAnyMessage () const [virtual]
virtual int HMessage::getNodeID () const [virtual]
virtual int HMessage::getOptionalParameter () const [virtual]
virtual int HMessage::getParentID () const [virtual]
virtual TransportAddress& HMessage::getSenderAddress () [virtual]
virtual const TransportAddress& HMessage::getSenderAddress () const [inline, virtual]
Definition at line 836 of file HMessage_m.h.
Referenced by getSenderAddress().
{return const_cast<HMessage*>(this)->getSenderAddress();}
virtual int HMessage::getType () const [virtual]
HMessage& HMessage::operator= (const HMessage & other)
bool HMessage::operator== (const HMessage &) [protected]
virtual void HMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void HMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void HMessage::setAnyMessage (const char * anyMessage) [virtual]
virtual void HMessage::setNodeID (int nodeID) [virtual]
virtual void HMessage::setOptionalParameter (int optionalParameter) [virtual]
virtual void HMessage::setParentID (int parentID) [virtual]
virtual void HMessage::setSenderAddress (const TransportAddress & senderAddress) [virtual]
virtual void HMessage::setType (int type) [virtual]
Member Data Documentation
opp_string HMessage::anyMessage_var [protected]
Definition at line 814 of file HMessage_m.h.
int HMessage::nodeID_var [protected]
Definition at line 811 of file HMessage_m.h.
int HMessage::optionalParameter_var [protected]
Definition at line 813 of file HMessage_m.h.
int HMessage::parentID_var [protected]
Definition at line 812 of file HMessage_m.h.
TransportAddress HMessage::senderAddress_var [protected]
Definition at line 810 of file HMessage_m.h.
int HMessage::type_var [protected]
Definition at line 809 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h