OverSim: I3InsertTriggerMessage_Base Class Reference
I3InsertTriggerMessage_Base Class Reference
Class generated from applications/i3/I3Message.msg by opp_msgc.
#include <I3Message_m.h>
Public Member Functions
virtual ~I3InsertTriggerMessage_Base ()
virtual
I3InsertTriggerMessage_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getSendReply () const
virtual void setSendReply (bool sendReply)
virtual I3Trigger & getTrigger ()
virtual const I3Trigger & getTrigger () const
virtual void setTrigger (const I3Trigger &trigger)
virtual I3IPAddress & getSource ()
virtual const I3IPAddress & getSource () const
virtual void setSource (const I3IPAddress &source)
Protected Member Functions
bool operator== (const I3InsertTriggerMessage_Base &)
I3InsertTriggerMessage_Base (const char *name=NULL, int kind=0)
I3InsertTriggerMessage_Base (const I3InsertTriggerMessage_Base &other)
I3InsertTriggerMessage_Base & operator= (const I3InsertTriggerMessage_Base &other)
Protected Attributes
bool sendReply_var
I3Trigger trigger_var
I3IPAddress source_var
Private Member Functions
void copy (const I3InsertTriggerMessage_Base &other)
Detailed Description
Class generated from applications/i3/I3Message.msg by opp_msgc.
 packet I3InsertTriggerMessage extends I3Message
 {
     (true);
         bool sendReply;
         I3Trigger trigger;
         I3IPAddress source;
 }
I3InsertTriggerMessage_Base is only useful if it gets subclassed, and I3InsertTriggerMessage is derived from it. The minimum code to be written for I3InsertTriggerMessage is the following:
 class I3InsertTriggerMessage : public I3InsertTriggerMessage_Base
 {
   private:
     void copy(const I3InsertTriggerMessage& other) { ... }
   public:
     I3InsertTriggerMessage(const char *name=NULL, int kind=0) : I3InsertTriggerMessage_Base(name,kind) {}
     I3InsertTriggerMessage(const I3InsertTriggerMessage& other) : I3InsertTriggerMessage_Base(other) {copy(other);}
     I3InsertTriggerMessage& operator=(const I3InsertTriggerMessage& other) {if (this==&other) return *this; I3InsertTriggerMessage_Base::operator=(other); copy(other); return *this;}
     virtual I3InsertTriggerMessage *dup() const {return new I3InsertTriggerMessage(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from I3InsertTriggerMessage_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(I3InsertTriggerMessage);
Definition at line 127 of file I3Message_m.h.
Constructor & Destructor Documentation
I3InsertTriggerMessage_Base::I3InsertTriggerMessage_Base (const char * name = NULL, int kind = 0) [protected]
I3InsertTriggerMessage_Base::I3InsertTriggerMessage_Base (const I3InsertTriggerMessage_Base & other) [protected]
virtual I3InsertTriggerMessage_Base::~I3InsertTriggerMessage_Base () [virtual]
Member Function Documentation
void I3InsertTriggerMessage_Base::copy (const I3InsertTriggerMessage_Base & other) [private]
virtual I3InsertTriggerMessage_Base* I3InsertTriggerMessage_Base::dup () const [inline, virtual]
Reimplemented from I3Message.
Reimplemented in I3InsertTriggerMessage.
Definition at line 148 of file I3Message_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class I3InsertTriggerMessage");}
virtual bool I3InsertTriggerMessage_Base::getSendReply () const [virtual]
Referenced by I3::deliver().
virtual I3IPAddress& I3InsertTriggerMessage_Base::getSource () [virtual]
Referenced by I3::deliver().
virtual const I3IPAddress& I3InsertTriggerMessage_Base::getSource () const [inline, virtual]
Definition at line 159 of file I3Message_m.h.
Referenced by getSource().
{return const_cast<I3InsertTriggerMessage_Base*>(this)->getSource();}
virtual I3Trigger& I3InsertTriggerMessage_Base::getTrigger () [virtual]
Referenced by I3::deliver(), and I3::handleUDPMessage().
virtual const I3Trigger& I3InsertTriggerMessage_Base::getTrigger () const [inline, virtual]
Definition at line 156 of file I3Message_m.h.
Referenced by getTrigger().
{return const_cast<I3InsertTriggerMessage_Base*>(this)->getTrigger();}
I3InsertTriggerMessage_Base& I3InsertTriggerMessage_Base::operator= (const I3InsertTriggerMessage_Base & other) [protected]
bool I3InsertTriggerMessage_Base::operator== (const I3InsertTriggerMessage_Base &) [protected]
virtual void I3InsertTriggerMessage_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3InsertTriggerMessage_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3InsertTriggerMessage_Base::setSendReply (bool sendReply) [virtual]
Referenced by I3TRTClient::handleTimerEvent(), I3InsertTriggerMessage::I3InsertTriggerMessage(), and I3BaseApp::insertTrigger().
virtual void I3InsertTriggerMessage_Base::setSource (const I3IPAddress & source) [virtual]
Referenced by I3TRTClient::handleTimerEvent(), and I3BaseApp::insertTrigger().
virtual void I3InsertTriggerMessage_Base::setTrigger (const I3Trigger & trigger) [virtual]
Referenced by I3TRTClient::handleTimerEvent(), and I3BaseApp::insertTrigger().
Member Data Documentation
bool I3InsertTriggerMessage_Base::sendReply_var [protected]
Definition at line 130 of file I3Message_m.h.
I3IPAddress I3InsertTriggerMessage_Base::source_var [protected]
Definition at line 132 of file I3Message_m.h.
I3Trigger I3InsertTriggerMessage_Base::trigger_var [protected]
Definition at line 131 of file I3Message_m.h.
The documentation for this class was generated from the following file:
I3Message_m.h