OverSim: DHTPutResponse Class Reference
DHTPutResponse Class Reference
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
#include <DHTMessage_m.h>
Public Member Functions
DHTPutResponse (const char *name=NULL, int kind=0)
DHTPutResponse (const DHTPutResponse &other)
virtual ~DHTPutResponse ()
DHTPutResponse & operator= (const DHTPutResponse &other)
virtual DHTPutResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getSuccess () const
virtual void setSuccess (bool success)
Protected Member Functions
bool operator== (const DHTPutResponse &)
Protected Attributes
bool success_var
Private Member Functions
void copy (const DHTPutResponse &other)
Detailed Description
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
 packet DHTPutResponse extends BaseResponseMessage
 {
     bool success;
 }
Definition at line 168 of file DHTMessage_m.h.
Constructor & Destructor Documentation
DHTPutResponse::DHTPutResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTPutResponse::DHTPutResponse (const DHTPutResponse & other)
virtual DHTPutResponse::~DHTPutResponse () [virtual]
Member Function Documentation
void DHTPutResponse::copy (const DHTPutResponse & other) [private]
virtual DHTPutResponse* DHTPutResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 185 of file DHTMessage_m.h.
{return new DHTPutResponse(*this);}
virtual bool DHTPutResponse::getSuccess () const [virtual]
Referenced by CBRDHT::handlePutResponse(), and DHT::handlePutResponse().
DHTPutResponse& DHTPutResponse::operator= (const DHTPutResponse & other)
bool DHTPutResponse::operator== (const DHTPutResponse &) [protected]
virtual void DHTPutResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void DHTPutResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void DHTPutResponse::setSuccess (bool success) [virtual]
Referenced by CBRDHT::handlePutRequest(), and DHT::handlePutRequest().
Member Data Documentation
bool DHTPutResponse::success_var [protected]
Definition at line 171 of file DHTMessage_m.h.
The documentation for this class was generated from the following file:
DHTMessage_m.h