OverSim: DiscoveryCall Class Reference
DiscoveryCall Class Reference
Class generated from common/DiscoveryMode.msg by opp_msgc.
#include <DiscoveryMode_m.h>
Public Member Functions
DiscoveryCall (const char *name=NULL, int kind=0)
DiscoveryCall (const DiscoveryCall &other)
virtual ~DiscoveryCall ()
DiscoveryCall & operator= (const DiscoveryCall &other)
virtual DiscoveryCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getNodesType () const
virtual void setNodesType (unsigned int nodesType)
virtual int getNumberOfNodes () const
virtual void setNumberOfNodes (int numberOfNodes)
virtual int getIndex () const
virtual void setIndex (int index)
Protected Member Functions
bool operator== (const DiscoveryCall &)
Protected Attributes
unsigned int nodesType_var
int numberOfNodes_var
int index_var
Private Member Functions
void copy (const DiscoveryCall &other)
Detailed Description
Class generated from common/DiscoveryMode.msg by opp_msgc.
 packet DiscoveryCall extends BaseCallMessage {
     unsigned int nodesType enum(DiscoveryNodesType) = CLOSE_NODES;
     int numberOfNodes = -1;
     int index = -1;
 }
Definition at line 47 of file DiscoveryMode_m.h.
Constructor & Destructor Documentation
DiscoveryCall::DiscoveryCall (const char * name = NULL, int kind = 0)
Referenced by dup().
DiscoveryCall::DiscoveryCall (const DiscoveryCall & other)
virtual DiscoveryCall::~DiscoveryCall () [virtual]
Member Function Documentation
void DiscoveryCall::copy (const DiscoveryCall & other) [private]
virtual DiscoveryCall* DiscoveryCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 66 of file DiscoveryMode_m.h.
{return new DiscoveryCall(*this);}
virtual int DiscoveryCall::getIndex () const [virtual]
Referenced by DiscoveryMode::handleRpcCall().
virtual unsigned int DiscoveryCall::getNodesType () const [virtual]
Referenced by DiscoveryMode::handleRpcCall().
virtual int DiscoveryCall::getNumberOfNodes () const [virtual]
Referenced by DiscoveryMode::handleRpcCall().
DiscoveryCall& DiscoveryCall::operator= (const DiscoveryCall & other)
bool DiscoveryCall::operator== (const DiscoveryCall &) [protected]
virtual void DiscoveryCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void DiscoveryCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void DiscoveryCall::setIndex (int index) [virtual]
virtual void DiscoveryCall::setNodesType (unsigned int nodesType) [virtual]
Referenced by DiscoveryMode::sendNewRequest(), and DiscoveryMode::start().
virtual void DiscoveryCall::setNumberOfNodes (int numberOfNodes) [virtual]
Referenced by DiscoveryMode::sendNewRequest(), and DiscoveryMode::start().
Member Data Documentation
int DiscoveryCall::index_var [protected]
Definition at line 52 of file DiscoveryMode_m.h.
unsigned int DiscoveryCall::nodesType_var [protected]
Definition at line 50 of file DiscoveryMode_m.h.
int DiscoveryCall::numberOfNodes_var [protected]
Definition at line 51 of file DiscoveryMode_m.h.
The documentation for this class was generated from the following file:
DiscoveryMode_m.h