OverSim: NTreeGroupAddMessage Class Reference
NTreeGroupAddMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeGroupAddMessage (const char *name=NULL, int kind=0)
NTreeGroupAddMessage (const NTreeGroupAddMessage &other)
virtual ~NTreeGroupAddMessage ()
NTreeGroupAddMessage & operator= (const NTreeGroupAddMessage &other)
virtual NTreeGroupAddMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getPlayer ()
virtual const NodeHandle & getPlayer () const
virtual void setPlayer (const NodeHandle &player)
virtual Vector2D & getOrigin ()
virtual const Vector2D & getOrigin () const
virtual void setOrigin (const Vector2D &origin)
Protected Member Functions
bool operator== (const NTreeGroupAddMessage &)
Protected Attributes
NodeHandle player_var
Vector2D origin_var
Private Member Functions
void copy (const NTreeGroupAddMessage &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeGroupAddMessage extends BaseOverlayMessage
 {
         NodeHandle player;
         Vector2D origin;
 }
Definition at line 586 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeGroupAddMessage::NTreeGroupAddMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeGroupAddMessage::NTreeGroupAddMessage (const NTreeGroupAddMessage & other)
virtual NTreeGroupAddMessage::~NTreeGroupAddMessage () [virtual]
Member Function Documentation
void NTreeGroupAddMessage::copy (const NTreeGroupAddMessage & other) [private]
virtual NTreeGroupAddMessage* NTreeGroupAddMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 604 of file NTree_m.h.
{return new NTreeGroupAddMessage(*this);}
virtual Vector2D& NTreeGroupAddMessage::getOrigin () [virtual]
Referenced by NTree::handleAddMessage().
virtual const Vector2D& NTreeGroupAddMessage::getOrigin () const [inline, virtual]
Definition at line 613 of file NTree_m.h.
Referenced by getOrigin().
{return const_cast<NTreeGroupAddMessage*>(this)->getOrigin();}
virtual NodeHandle& NTreeGroupAddMessage::getPlayer () [virtual]
Referenced by NTree::handleAddMessage().
virtual const NodeHandle& NTreeGroupAddMessage::getPlayer () const [inline, virtual]
Definition at line 610 of file NTree_m.h.
Referenced by getPlayer().
{return const_cast<NTreeGroupAddMessage*>(this)->getPlayer();}
NTreeGroupAddMessage& NTreeGroupAddMessage::operator= (const NTreeGroupAddMessage & other)
bool NTreeGroupAddMessage::operator== (const NTreeGroupAddMessage &) [protected]
virtual void NTreeGroupAddMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void NTreeGroupAddMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void NTreeGroupAddMessage::setOrigin (const Vector2D & origin) [virtual]
Referenced by NTree::handleJoinCall().
virtual void NTreeGroupAddMessage::setPlayer (const NodeHandle & player) [virtual]
Referenced by NTree::handleJoinCall().
Member Data Documentation
Vector2D NTreeGroupAddMessage::origin_var [protected]
Definition at line 590 of file NTree_m.h.
NodeHandle NTreeGroupAddMessage::player_var [protected]
Definition at line 589 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h