OverSim: ParetoChurnMessage Class Reference
ParetoChurnMessage Class Reference
Class generated from common/Churn.msg by opp_msgc.
#include <Churn_m.h>
Public Member Functions
ParetoChurnMessage (const char *name=NULL, int kind=0)
ParetoChurnMessage (const ParetoChurnMessage &other)
virtual ~ParetoChurnMessage ()
ParetoChurnMessage & operator= (const ParetoChurnMessage &other)
virtual ParetoChurnMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual double getMeanLifetime () const
virtual void setMeanLifetime (double meanLifetime)
virtual double getMeanDeadtime () const
virtual void setMeanDeadtime (double meanDeadtime)
Protected Member Functions
bool operator== (const ParetoChurnMessage &)
Protected Attributes
double meanLifetime_var
double meanDeadtime_var
Private Member Functions
void copy (const ParetoChurnMessage &other)
Detailed Description
Class generated from common/Churn.msg by opp_msgc.
 packet ParetoChurnMessage extends ChurnMessage
 {
         double meanLifetime;
         double meanDeadtime;
 }
Definition at line 83 of file Churn_m.h.
Constructor & Destructor Documentation
ParetoChurnMessage::ParetoChurnMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ParetoChurnMessage::ParetoChurnMessage (const ParetoChurnMessage & other)
virtual ParetoChurnMessage::~ParetoChurnMessage () [virtual]
Member Function Documentation
void ParetoChurnMessage::copy (const ParetoChurnMessage & other) [private]
virtual ParetoChurnMessage* ParetoChurnMessage::dup () const [inline, virtual]
Reimplemented from ChurnMessage.
Definition at line 101 of file Churn_m.h.
{return new ParetoChurnMessage(*this);}
virtual double ParetoChurnMessage::getMeanDeadtime () const [virtual]
Referenced by ParetoChurn::handleMessage().
virtual double ParetoChurnMessage::getMeanLifetime () const [virtual]
Referenced by ParetoChurn::handleMessage().
ParetoChurnMessage& ParetoChurnMessage::operator= (const ParetoChurnMessage & other)
bool ParetoChurnMessage::operator== (const ParetoChurnMessage &) [protected]
virtual void ParetoChurnMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ChurnMessage.
Referenced by doPacking().
virtual void ParetoChurnMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ChurnMessage.
Referenced by doUnpacking().
virtual void ParetoChurnMessage::setMeanDeadtime (double meanDeadtime) [virtual]
Referenced by ParetoChurn::createNode(), and ParetoChurn::scheduleCreateNodeAt().
virtual void ParetoChurnMessage::setMeanLifetime (double meanLifetime) [virtual]
Referenced by ParetoChurn::createNode(), and ParetoChurn::scheduleCreateNodeAt().
Member Data Documentation
double ParetoChurnMessage::meanDeadtime_var [protected]
Definition at line 87 of file Churn_m.h.
double ParetoChurnMessage::meanLifetime_var [protected]
Definition at line 86 of file Churn_m.h.
The documentation for this class was generated from the following file:
Churn_m.h