OverSim: KademliaBucket Class Reference
KademliaBucket Class Reference
#include <KademliaBucket.h>
Public Member Functions
KademliaBucket (uint16_t maxSize=0, const Comparator< OverlayKey > *comparator=NULL)
~KademliaBucket ()
void setLastUsage (simtime_t time)
simtime_t getLastUsage () const
Public Attributes
std::list< KademliaBucketEntry > replacementCache
Private Attributes
simtime_t lastUsage
Detailed Description
Definition at line 28 of file KademliaBucket.h.
Constructor & Destructor Documentation
KademliaBucket::KademliaBucket (uint16_t maxSize = 0, const Comparator< OverlayKey > * comparator = NULL)
Definition at line 26 of file KademliaBucket.cc.
    : BaseKeySortedVector< KademliaBucketEntry >(maxSize, comparator)
{
    lastUsage = -1;
}
KademliaBucket::~KademliaBucket ()
Definition at line 33 of file KademliaBucket.cc.
{
}
Member Function Documentation
simtime_t KademliaBucket::getLastUsage () const [inline]
Definition at line 39 of file KademliaBucket.h.
Referenced by Kademlia::handleBucketRefreshTimerExpired(), and operator<<().
{
        return this->lastUsage;
    }
void KademliaBucket::setLastUsage (simtime_t time) [inline]
Definition at line 35 of file KademliaBucket.h.
Referenced by Kademlia::handleBucketRefreshTimerExpired(), and Kademlia::setBucketUsage().
{
        this->lastUsage = time;
    }
Member Data Documentation
simtime_t KademliaBucket::lastUsage [private]
Definition at line 46 of file KademliaBucket.h.
Referenced by getLastUsage(), KademliaBucket(), and setLastUsage().
std::list<KademliaBucketEntry> KademliaBucket::replacementCache
Definition at line 43 of file KademliaBucket.h.
Referenced by Kademlia::routingAdd(), and Kademlia::routingTimeout().
The documentation for this class was generated from the following files:
KademliaBucket.h
KademliaBucket.cc