OverSim: NTreeNodePingResponse Class Reference
NTreeNodePingResponse Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>
Public Member Functions
NTreeNodePingResponse (const char *name=NULL, int kind=0)
NTreeNodePingResponse (const NTreeNodePingResponse &other)
virtual ~NTreeNodePingResponse ()
NTreeNodePingResponse & operator= (const NTreeNodePingResponse &other)
virtual NTreeNodePingResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setMembersArraySize (unsigned int size)
virtual unsigned int getMembersArraySize () const
virtual NodeHandle & getMembers (unsigned int k)
virtual const NodeHandle & getMembers (unsigned int k) const
virtual void setMembers (unsigned int k, const NodeHandle &members)
virtual int getAggChildCount () const
virtual void setAggChildCount (int aggChildCount)
Protected Member Functions
bool operator== (const NTreeNodePingResponse &)
Protected Attributes
NodeHandle * members_var
unsigned int members_arraysize
int aggChildCount_var
Private Member Functions
void copy (const NTreeNodePingResponse &other)
Detailed Description
Class generated from overlay/ntree/NTree.msg by opp_msgc.
 packet NTreeNodePingResponse extends NTreePingResponse
 {
         NodeHandle members[];
         int aggChildCount;
 }
Definition at line 355 of file NTree_m.h.
Constructor & Destructor Documentation
NTreeNodePingResponse::NTreeNodePingResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
NTreeNodePingResponse::NTreeNodePingResponse (const NTreeNodePingResponse & other)
virtual NTreeNodePingResponse::~NTreeNodePingResponse () [virtual]
Member Function Documentation
void NTreeNodePingResponse::copy (const NTreeNodePingResponse & other) [private]
virtual NTreeNodePingResponse* NTreeNodePingResponse::dup () const [inline, virtual]
Reimplemented from NTreePingResponse.
Definition at line 374 of file NTree_m.h.
{return new NTreeNodePingResponse(*this);}
virtual int NTreeNodePingResponse::getAggChildCount () const [virtual]
virtual NodeHandle& NTreeNodePingResponse::getMembers (unsigned int k) [virtual]
virtual const NodeHandle& NTreeNodePingResponse::getMembers (unsigned int k) const [inline, virtual]
Definition at line 382 of file NTree_m.h.
Referenced by getMembers().
{return const_cast<NTreeNodePingResponse*>(this)->getMembers(k);}
virtual unsigned int NTreeNodePingResponse::getMembersArraySize () const [virtual]
NTreeNodePingResponse& NTreeNodePingResponse::operator= (const NTreeNodePingResponse & other)
bool NTreeNodePingResponse::operator== (const NTreeNodePingResponse &) [protected]
virtual void NTreeNodePingResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from NTreePingResponse.
Referenced by doPacking().
virtual void NTreeNodePingResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from NTreePingResponse.
Referenced by doUnpacking().
virtual void NTreeNodePingResponse::setAggChildCount (int aggChildCount) [virtual]
Referenced by NTree::handlePingCall().
virtual void NTreeNodePingResponse::setMembers (unsigned int k, const NodeHandle & members) [virtual]
Referenced by NTree::handlePingCall().
virtual void NTreeNodePingResponse::setMembersArraySize (unsigned int size) [virtual]
Referenced by NTree::handlePingCall().
Member Data Documentation
int NTreeNodePingResponse::aggChildCount_var [protected]
Definition at line 360 of file NTree_m.h.
unsigned int NTreeNodePingResponse::members_arraysize [protected]
Definition at line 359 of file NTree_m.h.
NodeHandle* NTreeNodePingResponse::members_var [protected]
Definition at line 358 of file NTree_m.h.
The documentation for this class was generated from the following file:
NTree_m.h