OverSim: DiscoveryResponse Class Reference
DiscoveryResponse Class Reference
Class generated from common/DiscoveryMode.msg by opp_msgc.
#include <DiscoveryMode_m.h>
Public Member Functions
DiscoveryResponse (const char *name=NULL, int kind=0)
DiscoveryResponse (const DiscoveryResponse &other)
virtual ~DiscoveryResponse ()
DiscoveryResponse & operator= (const DiscoveryResponse &other)
virtual DiscoveryResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setNodesArraySize (unsigned int size)
virtual unsigned int getNodesArraySize () const
virtual TransportAddress & getNodes (unsigned int k)
virtual const TransportAddress & getNodes (unsigned int k) const
virtual void setNodes (unsigned int k, const TransportAddress &nodes)
virtual int getMaxIndex () const
virtual void setMaxIndex (int maxIndex)
Protected Member Functions
bool operator== (const DiscoveryResponse &)
Protected Attributes
TransportAddress * nodes_var
unsigned int nodes_arraysize
int maxIndex_var
Private Member Functions
void copy (const DiscoveryResponse &other)
Detailed Description
Class generated from common/DiscoveryMode.msg by opp_msgc.
 packet DiscoveryResponse extends BaseResponseMessage {
     TransportAddress nodes[];
     int maxIndex = -1;
 }
Definition at line 91 of file DiscoveryMode_m.h.
Constructor & Destructor Documentation
DiscoveryResponse::DiscoveryResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
DiscoveryResponse::DiscoveryResponse (const DiscoveryResponse & other)
virtual DiscoveryResponse::~DiscoveryResponse () [virtual]
Member Function Documentation
void DiscoveryResponse::copy (const DiscoveryResponse & other) [private]
virtual DiscoveryResponse* DiscoveryResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 110 of file DiscoveryMode_m.h.
{return new DiscoveryResponse(*this);}
virtual int DiscoveryResponse::getMaxIndex () const [virtual]
Referenced by DiscoveryMode::handleRpcResponse().
virtual TransportAddress& DiscoveryResponse::getNodes (unsigned int k) [virtual]
Referenced by DiscoveryMode::handleRpcResponse().
virtual const TransportAddress& DiscoveryResponse::getNodes (unsigned int k) const [inline, virtual]
Definition at line 118 of file DiscoveryMode_m.h.
Referenced by getNodes().
{return const_cast<DiscoveryResponse*>(this)->getNodes(k);}
virtual unsigned int DiscoveryResponse::getNodesArraySize () const [virtual]
Referenced by DiscoveryMode::handleRpcResponse().
DiscoveryResponse& DiscoveryResponse::operator= (const DiscoveryResponse & other)
bool DiscoveryResponse::operator== (const DiscoveryResponse &) [protected]
virtual void DiscoveryResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void DiscoveryResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void DiscoveryResponse::setMaxIndex (int maxIndex) [virtual]
Referenced by DiscoveryMode::handleRpcCall().
virtual void DiscoveryResponse::setNodes (unsigned int k, const TransportAddress & nodes) [virtual]
Referenced by DiscoveryMode::handleRpcCall().
virtual void DiscoveryResponse::setNodesArraySize (unsigned int size) [virtual]
Referenced by DiscoveryMode::handleRpcCall().
Member Data Documentation
int DiscoveryResponse::maxIndex_var [protected]
Definition at line 96 of file DiscoveryMode_m.h.
unsigned int DiscoveryResponse::nodes_arraysize [protected]
Definition at line 95 of file DiscoveryMode_m.h.
TransportAddress* DiscoveryResponse::nodes_var [protected]
Definition at line 94 of file DiscoveryMode_m.h.
The documentation for this class was generated from the following file:
DiscoveryMode_m.h