OverSim: CoordsOfNodeResponse Class Reference
CoordsOfNodeResponse Class Reference
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
#include <CoordMessages_m.h>
Public Member Functions
CoordsOfNodeResponse (const char *name=NULL, int kind=0)
CoordsOfNodeResponse (const CoordsOfNodeResponse &other)
virtual ~CoordsOfNodeResponse ()
CoordsOfNodeResponse & operator= (const CoordsOfNodeResponse &other)
virtual CoordsOfNodeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual char getLayer () const
virtual void setLayer (char layer)
Protected Member Functions
bool operator== (const CoordsOfNodeResponse &)
Protected Attributes
char layer_var
Private Member Functions
void copy (const CoordsOfNodeResponse &other)
Detailed Description
Class generated from common/cbr/CoordMessages.msg by opp_msgc.
 packet CoordsOfNodeResponse extends BaseResponseMessage
 {
     char layer;
 }
Definition at line 111 of file CoordMessages_m.h.
Constructor & Destructor Documentation
CoordsOfNodeResponse::CoordsOfNodeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
CoordsOfNodeResponse::CoordsOfNodeResponse (const CoordsOfNodeResponse & other)
virtual CoordsOfNodeResponse::~CoordsOfNodeResponse () [virtual]
Member Function Documentation
void CoordsOfNodeResponse::copy (const CoordsOfNodeResponse & other) [private]
virtual CoordsOfNodeResponse* CoordsOfNodeResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 128 of file CoordMessages_m.h.
{return new CoordsOfNodeResponse(*this);}
virtual char CoordsOfNodeResponse::getLayer () const [virtual]
CoordsOfNodeResponse& CoordsOfNodeResponse::operator= (const CoordsOfNodeResponse & other)
bool CoordsOfNodeResponse::operator== (const CoordsOfNodeResponse &) [protected]
virtual void CoordsOfNodeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void CoordsOfNodeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void CoordsOfNodeResponse::setLayer (char layer) [virtual]
Member Data Documentation
char CoordsOfNodeResponse::layer_var [protected]
Definition at line 114 of file CoordMessages_m.h.
The documentation for this class was generated from the following file:
CoordMessages_m.h