OverSim: StabilizeResponse Class Reference
StabilizeResponse Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
StabilizeResponse (const char *name=NULL, int kind=0)
StabilizeResponse (const StabilizeResponse &other)
virtual ~StabilizeResponse ()
StabilizeResponse & operator= (const StabilizeResponse &other)
virtual StabilizeResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getPreNode ()
virtual const NodeHandle & getPreNode () const
virtual void setPreNode (const NodeHandle &preNode)
Protected Member Functions
bool operator== (const StabilizeResponse &)
Protected Attributes
NodeHandle preNode_var
Private Member Functions
void copy (const StabilizeResponse &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet StabilizeResponse extends BaseResponseMessage
 {
     NodeHandle preNode;
 }
Definition at line 371 of file ChordMessage_m.h.
Constructor & Destructor Documentation
StabilizeResponse::StabilizeResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
StabilizeResponse::StabilizeResponse (const StabilizeResponse & other)
virtual StabilizeResponse::~StabilizeResponse () [virtual]
Member Function Documentation
void StabilizeResponse::copy (const StabilizeResponse & other) [private]
virtual StabilizeResponse* StabilizeResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 388 of file ChordMessage_m.h.
{return new StabilizeResponse(*this);}
virtual NodeHandle& StabilizeResponse::getPreNode () [virtual]
Referenced by oversim::Chord::handleRpcStabilizeResponse().
virtual const NodeHandle& StabilizeResponse::getPreNode () const [inline, virtual]
Definition at line 394 of file ChordMessage_m.h.
Referenced by getPreNode().
{return const_cast<StabilizeResponse*>(this)->getPreNode();}
StabilizeResponse& StabilizeResponse::operator= (const StabilizeResponse & other)
bool StabilizeResponse::operator== (const StabilizeResponse &) [protected]
virtual void StabilizeResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void StabilizeResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void StabilizeResponse::setPreNode (const NodeHandle & preNode) [virtual]
Referenced by oversim::Chord::rpcStabilize().
Member Data Documentation
NodeHandle StabilizeResponse::preNode_var [protected]
Definition at line 374 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h