OverSim: HLeaveOverlayResponse Class Reference
HLeaveOverlayResponse Class Reference
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
#include <HMessage_m.h>
Public Member Functions
HLeaveOverlayResponse (const char *name=NULL, int kind=0)
HLeaveOverlayResponse (const HLeaveOverlayResponse &other)
virtual ~HLeaveOverlayResponse ()
HLeaveOverlayResponse & operator= (const HLeaveOverlayResponse &other)
virtual HLeaveOverlayResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getPermissionGranted () const
virtual void setPermissionGranted (int permissionGranted)
Protected Member Functions
bool operator== (const HLeaveOverlayResponse &)
Protected Attributes
int permissionGranted_var
Private Member Functions
void copy (const HLeaveOverlayResponse &other)
Detailed Description
Class generated from overlay/htopology/HMessage.msg by opp_msgc.
 packet HLeaveOverlayResponse extends BaseResponseMessage {
     int permissionGranted;
 }
Definition at line 491 of file HMessage_m.h.
Constructor & Destructor Documentation
HLeaveOverlayResponse::HLeaveOverlayResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
HLeaveOverlayResponse::HLeaveOverlayResponse (const HLeaveOverlayResponse & other)
virtual HLeaveOverlayResponse::~HLeaveOverlayResponse () [virtual]
Member Function Documentation
void HLeaveOverlayResponse::copy (const HLeaveOverlayResponse & other) [private]
virtual HLeaveOverlayResponse* HLeaveOverlayResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 508 of file HMessage_m.h.
{return new HLeaveOverlayResponse(*this);}
virtual int HLeaveOverlayResponse::getPermissionGranted () const [virtual]
HLeaveOverlayResponse& HLeaveOverlayResponse::operator= (const HLeaveOverlayResponse & other)
bool HLeaveOverlayResponse::operator== (const HLeaveOverlayResponse &) [protected]
virtual void HLeaveOverlayResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void HLeaveOverlayResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void HLeaveOverlayResponse::setPermissionGranted (int permissionGranted) [virtual]
Referenced by HTopology::goAheadWithRestSelectionProcess().
Member Data Documentation
int HLeaveOverlayResponse::permissionGranted_var [protected]
Definition at line 494 of file HMessage_m.h.
The documentation for this class was generated from the following file:
HMessage_m.h