OverSim: PubSubNodeLeftMessage Class Reference
PubSubNodeLeftMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubNodeLeftMessage (const char *name=NULL, int kind=0)
PubSubNodeLeftMessage (const PubSubNodeLeftMessage &other)
virtual ~PubSubNodeLeftMessage ()
PubSubNodeLeftMessage & operator= (const PubSubNodeLeftMessage &other)
virtual PubSubNodeLeftMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getNode ()
virtual const NodeHandle & getNode () const
virtual void setNode (const NodeHandle &node)
Protected Member Functions
bool operator== (const PubSubNodeLeftMessage &)
Protected Attributes
int subspaceId_var
NodeHandle node_var
Private Member Functions
void copy (const PubSubNodeLeftMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubNodeLeftMessage extends BaseOverlayMessage
 {
         int subspaceId;
         NodeHandle node;
 }
Definition at line 956 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubNodeLeftMessage::PubSubNodeLeftMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubNodeLeftMessage::PubSubNodeLeftMessage (const PubSubNodeLeftMessage & other)
virtual PubSubNodeLeftMessage::~PubSubNodeLeftMessage () [virtual]
Member Function Documentation
void PubSubNodeLeftMessage::copy (const PubSubNodeLeftMessage & other) [private]
virtual PubSubNodeLeftMessage* PubSubNodeLeftMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 974 of file PubSubMessage_m.h.
{return new PubSubNodeLeftMessage(*this);}
virtual NodeHandle& PubSubNodeLeftMessage::getNode () [virtual]
Referenced by PubSubMMOG::handleNodeLeftMessage().
virtual const NodeHandle& PubSubNodeLeftMessage::getNode () const [inline, virtual]
Definition at line 982 of file PubSubMessage_m.h.
Referenced by getNode().
{return const_cast<PubSubNodeLeftMessage*>(this)->getNode();}
virtual int PubSubNodeLeftMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleNodeLeftMessage().
PubSubNodeLeftMessage& PubSubNodeLeftMessage::operator= (const PubSubNodeLeftMessage & other)
bool PubSubNodeLeftMessage::operator== (const PubSubNodeLeftMessage &) [protected]
virtual void PubSubNodeLeftMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubNodeLeftMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubNodeLeftMessage::setNode (const NodeHandle & node) [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse(), PubSubMMOG::handleIntermediateResponse(), PubSubMMOG::handlePingCallTimeout(), and PubSubMMOG::unsubscribeChild().
virtual void PubSubNodeLeftMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleAdoptChildResponse(), PubSubMMOG::handleIntermediateResponse(), PubSubMMOG::handlePingCallTimeout(), and PubSubMMOG::unsubscribeChild().
Member Data Documentation
NodeHandle PubSubNodeLeftMessage::node_var [protected]
Definition at line 960 of file PubSubMessage_m.h.
int PubSubNodeLeftMessage::subspaceId_var [protected]
Definition at line 959 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h