OverSim: I3SendPacketMessage_Base Class Reference
I3SendPacketMessage_Base Class Reference
Class generated from applications/i3/I3Message.msg by opp_msgc.
#include <I3Message_m.h>
Public Member Functions
virtual ~I3SendPacketMessage_Base ()
virtual I3SendPacketMessage_Base * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual I3IdentifierStack & getIdentifierStack ()
virtual const I3IdentifierStack & getIdentifierStack () const
virtual void setIdentifierStack (const I3IdentifierStack &identifierStack)
virtual I3Trigger & getMatchedTrigger ()
virtual const I3Trigger & getMatchedTrigger () const
virtual void setMatchedTrigger (const I3Trigger &matchedTrigger)
virtual bool getSendReply () const
virtual void setSendReply (bool sendReply)
virtual I3IPAddress & getSource ()
virtual const I3IPAddress & getSource () const
virtual void setSource (const I3IPAddress &source)
Protected Member Functions
bool operator== (const I3SendPacketMessage_Base &)
I3SendPacketMessage_Base (const char *name=NULL, int kind=0)
I3SendPacketMessage_Base (const I3SendPacketMessage_Base &other)
I3SendPacketMessage_Base & operator= (const I3SendPacketMessage_Base &other)
Protected Attributes
I3IdentifierStack identifierStack_var
I3Trigger matchedTrigger_var
bool sendReply_var
I3IPAddress source_var
Private Member Functions
void copy (const I3SendPacketMessage_Base &other)
Detailed Description
Class generated from applications/i3/I3Message.msg by opp_msgc.
 packet I3SendPacketMessage extends I3Message
 {
     (true);
         I3IdentifierStack identifierStack;
         I3Trigger matchedTrigger;
         bool sendReply;
         I3IPAddress source;
 }
I3SendPacketMessage_Base is only useful if it gets subclassed, and I3SendPacketMessage is derived from it. The minimum code to be written for I3SendPacketMessage is the following:
 class I3SendPacketMessage : public I3SendPacketMessage_Base
 {
   private:
     void copy(const I3SendPacketMessage& other) { ... }
   public:
     I3SendPacketMessage(const char *name=NULL, int kind=0) : I3SendPacketMessage_Base(name,kind) {}
     I3SendPacketMessage(const I3SendPacketMessage& other) : I3SendPacketMessage_Base(other) {copy(other);}
     I3SendPacketMessage& operator=(const I3SendPacketMessage& other) {if (this==&other) return *this; I3SendPacketMessage_Base::operator=(other); copy(other); return *this;}
     virtual I3SendPacketMessage *dup() const {return new I3SendPacketMessage(*this);}
     // ADD CODE HERE to redefine and implement pure virtual functions from I3SendPacketMessage_Base
 };
The following should go into a .cc (.cpp) file:
 Register_Class(I3SendPacketMessage);
Definition at line 335 of file I3Message_m.h.
Constructor & Destructor Documentation
I3SendPacketMessage_Base::I3SendPacketMessage_Base (const char * name = NULL, int kind = 0) [protected]
I3SendPacketMessage_Base::I3SendPacketMessage_Base (const I3SendPacketMessage_Base & other) [protected]
virtual I3SendPacketMessage_Base::~I3SendPacketMessage_Base () [virtual]
Member Function Documentation
void I3SendPacketMessage_Base::copy (const I3SendPacketMessage_Base & other) [private]
virtual I3SendPacketMessage_Base* I3SendPacketMessage_Base::dup () const [inline, virtual]
Reimplemented from I3Message.
Reimplemented in I3SendPacketMessage.
Definition at line 357 of file I3Message_m.h.
{throw cRuntimeError("You forgot to manually add a dup() function to class I3SendPacketMessage");}
virtual I3IdentifierStack& I3SendPacketMessage_Base::getIdentifierStack () [virtual]
Referenced by I3::handleUDPMessage(), I3BaseApp::handleUDPMessage(), I3::sendPacket(), I3BaseApp::sendPacket(), and I3::sendToNode().
virtual const I3IdentifierStack& I3SendPacketMessage_Base::getIdentifierStack () const [inline, virtual]
Definition at line 363 of file I3Message_m.h.
Referenced by getIdentifierStack().
{return const_cast<I3SendPacketMessage_Base*>(this)->getIdentifierStack();}
virtual I3Trigger& I3SendPacketMessage_Base::getMatchedTrigger () [virtual]
Referenced by I3BaseApp::handleUDPMessage(), and I3::sendPacket().
virtual const I3Trigger& I3SendPacketMessage_Base::getMatchedTrigger () const [inline, virtual]
Definition at line 366 of file I3Message_m.h.
Referenced by getMatchedTrigger().
{return const_cast<I3SendPacketMessage_Base*>(this)->getMatchedTrigger();}
virtual bool I3SendPacketMessage_Base::getSendReply () const [virtual]
Referenced by I3::sendPacket().
virtual I3IPAddress& I3SendPacketMessage_Base::getSource () [virtual]
Referenced by I3::sendPacket().
virtual const I3IPAddress& I3SendPacketMessage_Base::getSource () const [inline, virtual]
Definition at line 371 of file I3Message_m.h.
Referenced by getSource().
{return const_cast<I3SendPacketMessage_Base*>(this)->getSource();}
I3SendPacketMessage_Base& I3SendPacketMessage_Base::operator= (const I3SendPacketMessage_Base & other) [protected]
bool I3SendPacketMessage_Base::operator== (const I3SendPacketMessage_Base &) [protected]
virtual void I3SendPacketMessage_Base::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3SendPacketMessage_Base::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from I3Message.
virtual void I3SendPacketMessage_Base::setIdentifierStack (const I3IdentifierStack & identifierStack) [virtual]
Referenced by I3::sendPacket(), and I3BaseApp::sendPacket().
virtual void I3SendPacketMessage_Base::setMatchedTrigger (const I3Trigger & matchedTrigger) [virtual]
Referenced by I3::sendPacket().
virtual void I3SendPacketMessage_Base::setSendReply (bool sendReply) [virtual]
Referenced by I3BaseApp::sendPacket().
virtual void I3SendPacketMessage_Base::setSource (const I3IPAddress & source) [virtual]
Referenced by I3BaseApp::sendPacket().
Member Data Documentation
I3IdentifierStack I3SendPacketMessage_Base::identifierStack_var [protected]
Definition at line 338 of file I3Message_m.h.
I3Trigger I3SendPacketMessage_Base::matchedTrigger_var [protected]
Definition at line 339 of file I3Message_m.h.
bool I3SendPacketMessage_Base::sendReply_var [protected]
Definition at line 340 of file I3Message_m.h.
I3IPAddress I3SendPacketMessage_Base::source_var [protected]
Definition at line 341 of file I3Message_m.h.
The documentation for this class was generated from the following file:
I3Message_m.h