OverSim: PubSubBackupIntermediateMessage Class Reference
PubSubBackupIntermediateMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubBackupIntermediateMessage (const char *name=NULL, int kind=0)
PubSubBackupIntermediateMessage (const PubSubBackupIntermediateMessage &other)
virtual ~PubSubBackupIntermediateMessage ()
PubSubBackupIntermediateMessage & operator= (const PubSubBackupIntermediateMessage &other)
virtual
PubSubBackupIntermediateMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getNode ()
virtual const NodeHandle & getNode () const
virtual void setNode (const NodeHandle &node)
virtual int getPos () const
virtual void setPos (int pos)
Protected Member Functions
bool operator== (const PubSubBackupIntermediateMessage &)
Protected Attributes
int subspaceId_var
NodeHandle node_var
int pos_var
Private Member Functions
void copy (const PubSubBackupIntermediateMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubBackupIntermediateMessage extends BaseOverlayMessage
 {
         int subspaceId;
         NodeHandle node;
         int pos;
 }
Definition at line 1220 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubBackupIntermediateMessage::PubSubBackupIntermediateMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubBackupIntermediateMessage::PubSubBackupIntermediateMessage (const PubSubBackupIntermediateMessage & other)
virtual PubSubBackupIntermediateMessage::~PubSubBackupIntermediateMessage () [virtual]
Member Function Documentation
void PubSubBackupIntermediateMessage::copy (const PubSubBackupIntermediateMessage & other) [private]
virtual PubSubBackupIntermediateMessage* PubSubBackupIntermediateMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 1239 of file PubSubMessage_m.h.
{return new PubSubBackupIntermediateMessage(*this);}
virtual NodeHandle& PubSubBackupIntermediateMessage::getNode () [virtual]
Referenced by PubSubMMOG::handleIntermediateBackup().
virtual const NodeHandle& PubSubBackupIntermediateMessage::getNode () const [inline, virtual]
Definition at line 1247 of file PubSubMessage_m.h.
Referenced by getNode().
{return const_cast<PubSubBackupIntermediateMessage*>(this)->getNode();}
virtual int PubSubBackupIntermediateMessage::getPos () const [virtual]
Referenced by PubSubMMOG::handleIntermediateBackup().
virtual int PubSubBackupIntermediateMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleIntermediateBackup().
PubSubBackupIntermediateMessage& PubSubBackupIntermediateMessage::operator= (const PubSubBackupIntermediateMessage & other)
bool PubSubBackupIntermediateMessage::operator== (const PubSubBackupIntermediateMessage &) [protected]
virtual void PubSubBackupIntermediateMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubBackupIntermediateMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubBackupIntermediateMessage::setNode (const NodeHandle & node) [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse().
virtual void PubSubBackupIntermediateMessage::setPos (int pos) [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse(), and PubSubMMOG::handlePingCallTimeout().
virtual void PubSubBackupIntermediateMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse(), and PubSubMMOG::handlePingCallTimeout().
Member Data Documentation
NodeHandle PubSubBackupIntermediateMessage::node_var [protected]
Definition at line 1224 of file PubSubMessage_m.h.
int PubSubBackupIntermediateMessage::pos_var [protected]
Definition at line 1225 of file PubSubMessage_m.h.
int PubSubBackupIntermediateMessage::subspaceId_var [protected]
Definition at line 1223 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h