OverSim: KBRTestMessage Class Reference
KBRTestMessage Class Reference
Class generated from applications/kbrtestapp/KBRTestMessage.msg by opp_msgc.
#include <KBRTestMessage_m.h>
Public Member Functions
KBRTestMessage (const char *name=NULL, int kind=0)
KBRTestMessage (const KBRTestMessage &other)
virtual ~KBRTestMessage ()
KBRTestMessage & operator= (const KBRTestMessage &other)
virtual KBRTestMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getId () const
virtual void setId (int id)
virtual int getSeqNum () const
virtual void setSeqNum (int seqNum)
virtual bool getMeasurementPhase () const
virtual void setMeasurementPhase (bool measurementPhase)
virtual void setVisitedNodesArraySize (unsigned int size)
virtual unsigned int getVisitedNodesArraySize () const
virtual IPvXAddress & getVisitedNodes (unsigned int k)
virtual const IPvXAddress & getVisitedNodes (unsigned int k) const
virtual void setVisitedNodes (unsigned int k, const IPvXAddress &visitedNodes)
Protected Member Functions
bool operator== (const KBRTestMessage &)
Protected Attributes
int id_var
int seqNum_var
bool measurementPhase_var
IPvXAddress * visitedNodes_var
unsigned int visitedNodes_arraysize
Private Member Functions
void copy (const KBRTestMessage &other)
Detailed Description
Class generated from applications/kbrtestapp/KBRTestMessage.msg by opp_msgc.
 packet KBRTestMessage
 {
     int id;
     int seqNum;
     bool measurementPhase;
     IPvXAddress visitedNodes[];
 }
Definition at line 36 of file KBRTestMessage_m.h.
Constructor & Destructor Documentation
KBRTestMessage::KBRTestMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
KBRTestMessage::KBRTestMessage (const KBRTestMessage & other)
virtual KBRTestMessage::~KBRTestMessage () [virtual]
Member Function Documentation
void KBRTestMessage::copy (const KBRTestMessage & other) [private]
virtual KBRTestMessage* KBRTestMessage::dup () const [inline, virtual]
Definition at line 57 of file KBRTestMessage_m.h.
{return new KBRTestMessage(*this);}
virtual int KBRTestMessage::getId () const [virtual]
Referenced by KBRTestApp::deliver().
virtual bool KBRTestMessage::getMeasurementPhase () const [virtual]
Referenced by KBRTestApp::deliver().
virtual int KBRTestMessage::getSeqNum () const [virtual]
Referenced by KBRTestApp::deliver().
virtual IPvXAddress& KBRTestMessage::getVisitedNodes (unsigned int k) [virtual]
virtual const IPvXAddress& KBRTestMessage::getVisitedNodes (unsigned int k) const [inline, virtual]
Definition at line 71 of file KBRTestMessage_m.h.
Referenced by getVisitedNodes().
{return const_cast<KBRTestMessage*>(this)->getVisitedNodes(k);}
virtual unsigned int KBRTestMessage::getVisitedNodesArraySize () const [virtual]
Referenced by KBRTestApp::forward().
KBRTestMessage& KBRTestMessage::operator= (const KBRTestMessage & other)
bool KBRTestMessage::operator== (const KBRTestMessage &) [protected]
virtual void KBRTestMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void KBRTestMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void KBRTestMessage::setId (int id) [virtual]
Referenced by KBRTestApp::handleTimerEvent().
virtual void KBRTestMessage::setMeasurementPhase (bool measurementPhase) [virtual]
Referenced by KBRTestApp::handleTimerEvent().
virtual void KBRTestMessage::setSeqNum (int seqNum) [virtual]
Referenced by KBRTestApp::handleTimerEvent().
virtual void KBRTestMessage::setVisitedNodes (unsigned int k, const IPvXAddress & visitedNodes) [virtual]
Referenced by KBRTestApp::forward().
virtual void KBRTestMessage::setVisitedNodesArraySize (unsigned int size) [virtual]
Referenced by KBRTestApp::forward().
Member Data Documentation
int KBRTestMessage::id_var [protected]
Definition at line 39 of file KBRTestMessage_m.h.
bool KBRTestMessage::measurementPhase_var [protected]
Definition at line 41 of file KBRTestMessage_m.h.
int KBRTestMessage::seqNum_var [protected]
Definition at line 40 of file KBRTestMessage_m.h.
unsigned int KBRTestMessage::visitedNodes_arraysize [protected]
Definition at line 43 of file KBRTestMessage_m.h.
IPvXAddress* KBRTestMessage::visitedNodes_var [protected]
Definition at line 42 of file KBRTestMessage_m.h.
The documentation for this class was generated from the following file:
KBRTestMessage_m.h