OverSim: ProxFindNodeCall Class Reference
ProxFindNodeCall Class Reference
Class generated from common/ProximityLookupMessages.msg by opp_msgc.
#include <ProximityLookupMessages_m.h>
Public Member Functions
ProxFindNodeCall (const char *name=NULL, int kind=0)
ProxFindNodeCall (const ProxFindNodeCall &other)
virtual ~ProxFindNodeCall ()
ProxFindNodeCall & operator= (const ProxFindNodeCall &other)
virtual ProxFindNodeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ProxFindNodeCall &)
Private Member Functions
void copy (const ProxFindNodeCall &other)
Detailed Description
Class generated from common/ProximityLookupMessages.msg by opp_msgc.
 packet ProxFindNodeCall extends FindNodeCall
 {
 }
Definition at line 61 of file ProximityLookupMessages_m.h.
Constructor & Destructor Documentation
ProxFindNodeCall::ProxFindNodeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
ProxFindNodeCall::ProxFindNodeCall (const ProxFindNodeCall & other)
virtual ProxFindNodeCall::~ProxFindNodeCall () [virtual]
Member Function Documentation
void ProxFindNodeCall::copy (const ProxFindNodeCall & other) [private]
virtual ProxFindNodeCall* ProxFindNodeCall::dup () const [inline, virtual]
Reimplemented from FindNodeCall.
Definition at line 77 of file ProximityLookupMessages_m.h.
{return new ProxFindNodeCall(*this);}
ProxFindNodeCall& ProxFindNodeCall::operator= (const ProxFindNodeCall & other)
bool ProxFindNodeCall::operator== (const ProxFindNodeCall &) [protected]
virtual void ProxFindNodeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from FindNodeCall.
Referenced by doPacking().
virtual void ProxFindNodeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from FindNodeCall.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
ProximityLookupMessages_m.h