OverSim: P2pnsTunnelMessage Class Reference
P2pnsTunnelMessage Class Reference
Class generated from tier2/p2pns/P2pnsMessage.msg by opp_msgc.
#include <P2pnsMessage_m.h>
Public Member Functions
P2pnsTunnelMessage (const char *name=NULL, int kind=0)
P2pnsTunnelMessage (const P2pnsTunnelMessage &other)
virtual ~P2pnsTunnelMessage ()
P2pnsTunnelMessage & operator= (const P2pnsTunnelMessage &other)
virtual P2pnsTunnelMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getSrcId ()
virtual const OverlayKey & getSrcId () const
virtual void setSrcId (const OverlayKey &srcId)
virtual BinaryValue & getPayload ()
virtual const BinaryValue & getPayload () const
virtual void setPayload (const BinaryValue &payload)
Protected Member Functions
bool operator== (const P2pnsTunnelMessage &)
Protected Attributes
OverlayKey srcId_var
BinaryValue payload_var
Private Member Functions
void copy (const P2pnsTunnelMessage &other)
Detailed Description
Class generated from tier2/p2pns/P2pnsMessage.msg by opp_msgc.
 packet P2pnsTunnelMessage extends OverSimMessage
 {
     OverlayKey srcId;
     BinaryValue payload;
 }
Definition at line 39 of file P2pnsMessage_m.h.
Constructor & Destructor Documentation
P2pnsTunnelMessage::P2pnsTunnelMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
P2pnsTunnelMessage::P2pnsTunnelMessage (const P2pnsTunnelMessage & other)
virtual P2pnsTunnelMessage::~P2pnsTunnelMessage () [virtual]
Member Function Documentation
void P2pnsTunnelMessage::copy (const P2pnsTunnelMessage & other) [private]
virtual P2pnsTunnelMessage* P2pnsTunnelMessage::dup () const [inline, virtual]
Reimplemented from OverSimMessage.
Definition at line 57 of file P2pnsMessage_m.h.
{return new P2pnsTunnelMessage(*this);}
virtual BinaryValue& P2pnsTunnelMessage::getPayload () [virtual]
Referenced by P2pns::deliver().
virtual const BinaryValue& P2pnsTunnelMessage::getPayload () const [inline, virtual]
Definition at line 66 of file P2pnsMessage_m.h.
Referenced by getPayload().
{return const_cast<P2pnsTunnelMessage*>(this)->getPayload();}
virtual OverlayKey& P2pnsTunnelMessage::getSrcId () [virtual]
Referenced by P2pns::updateIdCacheWithNewTransport().
virtual const OverlayKey& P2pnsTunnelMessage::getSrcId () const [inline, virtual]
Definition at line 63 of file P2pnsMessage_m.h.
Referenced by getSrcId().
{return const_cast<P2pnsTunnelMessage*>(this)->getSrcId();}
P2pnsTunnelMessage& P2pnsTunnelMessage::operator= (const P2pnsTunnelMessage & other)
bool P2pnsTunnelMessage::operator== (const P2pnsTunnelMessage &) [protected]
virtual void P2pnsTunnelMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from OverSimMessage.
Referenced by doPacking().
virtual void P2pnsTunnelMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from OverSimMessage.
Referenced by doUnpacking().
virtual void P2pnsTunnelMessage::setPayload (const BinaryValue & payload) [virtual]
Referenced by P2pns::sendTunnelMessage().
virtual void P2pnsTunnelMessage::setSrcId (const OverlayKey & srcId) [virtual]
Referenced by P2pns::sendTunnelMessage().
Member Data Documentation
BinaryValue P2pnsTunnelMessage::payload_var [protected]
Definition at line 43 of file P2pnsMessage_m.h.
OverlayKey P2pnsTunnelMessage::srcId_var [protected]
Definition at line 42 of file P2pnsMessage_m.h.
The documentation for this class was generated from the following file:
P2pnsMessage_m.h