OverSim: MyNeighborResponse Class Reference
MyNeighborResponse Class Reference
Class generated from overlay/myoverlay/MyOverlay.msg by opp_msgc.
#include <MyOverlay_m.h>
Public Member Functions
MyNeighborResponse (const char *name=NULL, int kind=0)
MyNeighborResponse (const MyNeighborResponse &other)
virtual ~MyNeighborResponse ()
MyNeighborResponse & operator= (const MyNeighborResponse &other)
virtual MyNeighborResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getRespondingNode ()
virtual const NodeHandle & getRespondingNode () const
virtual void setRespondingNode (const NodeHandle &respondingNode)
virtual NodeHandle & getPrevNeighbor ()
virtual const NodeHandle & getPrevNeighbor () const
virtual void setPrevNeighbor (const NodeHandle &prevNeighbor)
virtual NodeHandle & getNextNeighbor ()
virtual const NodeHandle & getNextNeighbor () const
virtual void setNextNeighbor (const NodeHandle &nextNeighbor)
Protected Member Functions
bool operator== (const MyNeighborResponse &)
Protected Attributes
NodeHandle respondingNode_var
NodeHandle prevNeighbor_var
NodeHandle nextNeighbor_var
Private Member Functions
void copy (const MyNeighborResponse &other)
Detailed Description
Class generated from overlay/myoverlay/MyOverlay.msg by opp_msgc.
 packet MyNeighborResponse extends BaseResponseMessage
 {
     NodeHandle respondingNode;
     NodeHandle prevNeighbor;
     NodeHandle nextNeighbor;
 };
Definition at line 74 of file MyOverlay_m.h.
Constructor & Destructor Documentation
MyNeighborResponse::MyNeighborResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
MyNeighborResponse::MyNeighborResponse (const MyNeighborResponse & other)
virtual MyNeighborResponse::~MyNeighborResponse () [virtual]
Member Function Documentation
void MyNeighborResponse::copy (const MyNeighborResponse & other) [private]
virtual MyNeighborResponse* MyNeighborResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 93 of file MyOverlay_m.h.
{return new MyNeighborResponse(*this);}
virtual NodeHandle& MyNeighborResponse::getNextNeighbor () [virtual]
Referenced by MyOverlay::handleRpcResponse().
virtual const NodeHandle& MyNeighborResponse::getNextNeighbor () const [inline, virtual]
Definition at line 105 of file MyOverlay_m.h.
Referenced by getNextNeighbor().
{return const_cast<MyNeighborResponse*>(this)->getNextNeighbor();}
virtual NodeHandle& MyNeighborResponse::getPrevNeighbor () [virtual]
Referenced by MyOverlay::handleRpcResponse().
virtual const NodeHandle& MyNeighborResponse::getPrevNeighbor () const [inline, virtual]
Definition at line 102 of file MyOverlay_m.h.
Referenced by getPrevNeighbor().
{return const_cast<MyNeighborResponse*>(this)->getPrevNeighbor();}
virtual NodeHandle& MyNeighborResponse::getRespondingNode () [virtual]
Referenced by MyOverlay::handleRpcResponse().
virtual const NodeHandle& MyNeighborResponse::getRespondingNode () const [inline, virtual]
Definition at line 99 of file MyOverlay_m.h.
Referenced by getRespondingNode().
{return const_cast<MyNeighborResponse*>(this)->getRespondingNode();}
MyNeighborResponse& MyNeighborResponse::operator= (const MyNeighborResponse & other)
bool MyNeighborResponse::operator== (const MyNeighborResponse &) [protected]
virtual void MyNeighborResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void MyNeighborResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void MyNeighborResponse::setNextNeighbor (const NodeHandle & nextNeighbor) [virtual]
Referenced by MyOverlay::handleRpcCall().
virtual void MyNeighborResponse::setPrevNeighbor (const NodeHandle & prevNeighbor) [virtual]
Referenced by MyOverlay::handleRpcCall().
virtual void MyNeighborResponse::setRespondingNode (const NodeHandle & respondingNode) [virtual]
Referenced by MyOverlay::handleRpcCall().
Member Data Documentation
NodeHandle MyNeighborResponse::nextNeighbor_var [protected]
Definition at line 79 of file MyOverlay_m.h.
NodeHandle MyNeighborResponse::prevNeighbor_var [protected]
Definition at line 78 of file MyOverlay_m.h.
NodeHandle MyNeighborResponse::respondingNode_var [protected]
Definition at line 77 of file MyOverlay_m.h.
The documentation for this class was generated from the following file:
MyOverlay_m.h