OverSim: SearchMessage Class Reference
SearchMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
SearchMessage (const char *name=NULL, int kind=0)
SearchMessage (const SearchMessage &other)
virtual ~SearchMessage ()
SearchMessage & operator= (const SearchMessage &other)
virtual SearchMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getSearchKey ()
virtual const OverlayKey & getSearchKey () const
virtual void setSearchKey (const OverlayKey &searchKey)
virtual int getMaxResponses () const
virtual void setMaxResponses (int maxResponses)
virtual void setReversePathArraySize (unsigned int size)
virtual unsigned int getReversePathArraySize () const
virtual OverlayKey & getReversePath (unsigned int k)
virtual const OverlayKey & getReversePath (unsigned int k) const
virtual void setReversePath (unsigned int k, const OverlayKey &reversePath)
virtual void setFoundNodeArraySize (unsigned int size)
virtual unsigned int getFoundNodeArraySize () const
virtual OverlayKey & getFoundNode (unsigned int k)
virtual const OverlayKey & getFoundNode (unsigned int k) const
virtual void setFoundNode (unsigned int k, const OverlayKey &foundNode)
Protected Member Functions
bool operator== (const SearchMessage &)
Protected Attributes
OverlayKey searchKey_var
int maxResponses_var
OverlayKey * reversePath_var
unsigned int reversePath_arraysize
OverlayKey * foundNode_var
unsigned int foundNode_arraysize
Private Member Functions
void copy (const SearchMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message SearchMessage extends GiaIDMessage
 {
         OverlayKey searchKey;
         int maxResponses;
         OverlayKey reversePath[];
         OverlayKey foundNode[];
 };
Definition at line 365 of file GiaMessage_m.h.
Constructor & Destructor Documentation
SearchMessage::SearchMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
SearchMessage::SearchMessage (const SearchMessage & other)
virtual SearchMessage::~SearchMessage () [virtual]
Member Function Documentation
void SearchMessage::copy (const SearchMessage & other) [private]
virtual SearchMessage* SearchMessage::dup () const [inline, virtual]
Reimplemented from GiaIDMessage.
Definition at line 387 of file GiaMessage_m.h.
{return new SearchMessage(*this);}
virtual OverlayKey& SearchMessage::getFoundNode (unsigned int k) [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual const OverlayKey& SearchMessage::getFoundNode (unsigned int k) const [inline, virtual]
Definition at line 405 of file GiaMessage_m.h.
Referenced by getFoundNode().
{return const_cast<SearchMessage*>(this)->getFoundNode(k);}
virtual unsigned int SearchMessage::getFoundNodeArraySize () const [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual int SearchMessage::getMaxResponses () const [virtual]
Referenced by Gia::processSearchMessage(), and Gia::sendSearchResponseMessage().
virtual OverlayKey& SearchMessage::getReversePath (unsigned int k) [virtual]
Referenced by Gia::processSearchMessage(), and Gia::sendSearchResponseMessage().
virtual const OverlayKey& SearchMessage::getReversePath (unsigned int k) const [inline, virtual]
Definition at line 400 of file GiaMessage_m.h.
Referenced by getReversePath().
{return const_cast<SearchMessage*>(this)->getReversePath(k);}
virtual unsigned int SearchMessage::getReversePathArraySize () const [virtual]
Referenced by Gia::processSearchMessage(), and Gia::sendSearchResponseMessage().
virtual OverlayKey& SearchMessage::getSearchKey () [virtual]
Referenced by Gia::processSearchMessage(), and Gia::sendSearchResponseMessage().
virtual const OverlayKey& SearchMessage::getSearchKey () const [inline, virtual]
Definition at line 393 of file GiaMessage_m.h.
Referenced by getSearchKey().
{return const_cast<SearchMessage*>(this)->getSearchKey();}
SearchMessage& SearchMessage::operator= (const SearchMessage & other)
bool SearchMessage::operator== (const SearchMessage &) [protected]
virtual void SearchMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaIDMessage.
Referenced by doPacking().
virtual void SearchMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaIDMessage.
Referenced by doUnpacking().
virtual void SearchMessage::setFoundNode (unsigned int k, const OverlayKey & foundNode) [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual void SearchMessage::setFoundNodeArraySize (unsigned int size) [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual void SearchMessage::setMaxResponses (int maxResponses) [virtual]
Referenced by Gia::sendSearchResponseMessage().
virtual void SearchMessage::setReversePath (unsigned int k, const OverlayKey & reversePath) [virtual]
Referenced by Gia::processSearchMessage().
virtual void SearchMessage::setReversePathArraySize (unsigned int size) [virtual]
Referenced by Gia::processSearchMessage().
virtual void SearchMessage::setSearchKey (const OverlayKey & searchKey) [virtual]
Member Data Documentation
unsigned int SearchMessage::foundNode_arraysize [protected]
Definition at line 373 of file GiaMessage_m.h.
OverlayKey* SearchMessage::foundNode_var [protected]
Definition at line 372 of file GiaMessage_m.h.
int SearchMessage::maxResponses_var [protected]
Definition at line 369 of file GiaMessage_m.h.
unsigned int SearchMessage::reversePath_arraysize [protected]
Definition at line 371 of file GiaMessage_m.h.
OverlayKey* SearchMessage::reversePath_var [protected]
Definition at line 370 of file GiaMessage_m.h.
OverlayKey SearchMessage::searchKey_var [protected]
Definition at line 368 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h