OverSim: FixfingersCall Class Reference
FixfingersCall Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
FixfingersCall (const char *name=NULL, int kind=0)
FixfingersCall (const FixfingersCall &other)
virtual ~FixfingersCall ()
FixfingersCall & operator= (const FixfingersCall &other)
virtual FixfingersCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getFinger () const
virtual void setFinger (int finger)
Protected Member Functions
bool operator== (const FixfingersCall &)
Protected Attributes
int finger_var
Private Member Functions
void copy (const FixfingersCall &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet FixfingersCall extends BaseCallMessage
 {
     int finger;
 }
Definition at line 410 of file ChordMessage_m.h.
Constructor & Destructor Documentation
FixfingersCall::FixfingersCall (const char * name = NULL, int kind = 0)
Referenced by dup().
FixfingersCall::FixfingersCall (const FixfingersCall & other)
virtual FixfingersCall::~FixfingersCall () [virtual]
Member Function Documentation
void FixfingersCall::copy (const FixfingersCall & other) [private]
virtual FixfingersCall* FixfingersCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 427 of file ChordMessage_m.h.
{return new FixfingersCall(*this);}
virtual int FixfingersCall::getFinger () const [virtual]
Referenced by oversim::Chord::rpcFixfingers().
FixfingersCall& FixfingersCall::operator= (const FixfingersCall & other)
bool FixfingersCall::operator== (const FixfingersCall &) [protected]
virtual void FixfingersCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void FixfingersCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void FixfingersCall::setFinger (int finger) [virtual]
Referenced by oversim::Chord::handleFixFingersTimerExpired().
Member Data Documentation
int FixfingersCall::finger_var [protected]
Definition at line 413 of file ChordMessage_m.h.
The documentation for this class was generated from the following file:
ChordMessage_m.h