OverSim: BrooseFindNodeExtMessage Class Reference
BrooseFindNodeExtMessage Class Reference
Class generated from overlay/broose/BrooseMessage.msg by opp_msgc.
#include <BrooseMessage_m.h>
Public Member Functions
BrooseFindNodeExtMessage (const char *name=NULL, int kind=0)
BrooseFindNodeExtMessage (const BrooseFindNodeExtMessage &other)
virtual ~BrooseFindNodeExtMessage ()
BrooseFindNodeExtMessage & operator= (const BrooseFindNodeExtMessage &other)
virtual BrooseFindNodeExtMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getRouteKey ()
virtual const OverlayKey & getRouteKey () const
virtual void setRouteKey (const OverlayKey &routeKey)
virtual int getStep () const
virtual void setStep (int step)
virtual int getMaxDistance () const
virtual void setMaxDistance (int maxDistance)
virtual bool getRightShifting () const
virtual void setRightShifting (bool rightShifting)
virtual NodeHandle & getLastNode ()
virtual const NodeHandle & getLastNode () const
virtual void setLastNode (const NodeHandle &lastNode)
Protected Member Functions
bool operator== (const BrooseFindNodeExtMessage &)
Protected Attributes
OverlayKey routeKey_var
int step_var
int maxDistance_var
bool rightShifting_var
NodeHandle lastNode_var
Private Member Functions
void copy (const BrooseFindNodeExtMessage &other)
Detailed Description
Class generated from overlay/broose/BrooseMessage.msg by opp_msgc.
 packet BrooseFindNodeExtMessage
 {
         OverlayKey routeKey;
         int step;
         int maxDistance;
         bool rightShifting;
         NodeHandle lastNode;
 }
Definition at line 177 of file BrooseMessage_m.h.
Constructor & Destructor Documentation
BrooseFindNodeExtMessage::BrooseFindNodeExtMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
BrooseFindNodeExtMessage::BrooseFindNodeExtMessage (const BrooseFindNodeExtMessage & other)
virtual BrooseFindNodeExtMessage::~BrooseFindNodeExtMessage () [virtual]
Member Function Documentation
void BrooseFindNodeExtMessage::copy (const BrooseFindNodeExtMessage & other) [private]
virtual BrooseFindNodeExtMessage* BrooseFindNodeExtMessage::dup () const [inline, virtual]
Definition at line 198 of file BrooseMessage_m.h.
{return new BrooseFindNodeExtMessage(*this);}
virtual NodeHandle& BrooseFindNodeExtMessage::getLastNode () [virtual]
Referenced by Broose::findNode().
virtual const NodeHandle& BrooseFindNodeExtMessage::getLastNode () const [inline, virtual]
Definition at line 213 of file BrooseMessage_m.h.
Referenced by getLastNode().
{return const_cast<BrooseFindNodeExtMessage*>(this)->getLastNode();}
virtual int BrooseFindNodeExtMessage::getMaxDistance () const [virtual]
virtual bool BrooseFindNodeExtMessage::getRightShifting () const [virtual]
Referenced by Broose::findNode().
virtual OverlayKey& BrooseFindNodeExtMessage::getRouteKey () [virtual]
Referenced by Broose::findNode().
virtual const OverlayKey& BrooseFindNodeExtMessage::getRouteKey () const [inline, virtual]
Definition at line 204 of file BrooseMessage_m.h.
Referenced by getRouteKey().
{return const_cast<BrooseFindNodeExtMessage*>(this)->getRouteKey();}
virtual int BrooseFindNodeExtMessage::getStep () const [virtual]
Referenced by Broose::findNode().
BrooseFindNodeExtMessage& BrooseFindNodeExtMessage::operator= (const BrooseFindNodeExtMessage & other)
bool BrooseFindNodeExtMessage::operator== (const BrooseFindNodeExtMessage &) [protected]
virtual void BrooseFindNodeExtMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void BrooseFindNodeExtMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void BrooseFindNodeExtMessage::setLastNode (const NodeHandle & lastNode) [virtual]
Referenced by Broose::findNode().
virtual void BrooseFindNodeExtMessage::setMaxDistance (int maxDistance) [virtual]
virtual void BrooseFindNodeExtMessage::setRightShifting (bool rightShifting) [virtual]
Referenced by Broose::findNode().
virtual void BrooseFindNodeExtMessage::setRouteKey (const OverlayKey & routeKey) [virtual]
Referenced by Broose::findNode().
virtual void BrooseFindNodeExtMessage::setStep (int step) [virtual]
Referenced by Broose::findNode().
Member Data Documentation
NodeHandle BrooseFindNodeExtMessage::lastNode_var [protected]
Definition at line 184 of file BrooseMessage_m.h.
int BrooseFindNodeExtMessage::maxDistance_var [protected]
Definition at line 182 of file BrooseMessage_m.h.
bool BrooseFindNodeExtMessage::rightShifting_var [protected]
Definition at line 183 of file BrooseMessage_m.h.
OverlayKey BrooseFindNodeExtMessage::routeKey_var [protected]
Definition at line 180 of file BrooseMessage_m.h.
int BrooseFindNodeExtMessage::step_var [protected]
Definition at line 181 of file BrooseMessage_m.h.
The documentation for this class was generated from the following file:
BrooseMessage_m.h