OverSim: QuonMoveMessage Class Reference
QuonMoveMessage Class Reference
Class generated from overlay/quon/Quon.msg by opp_msgc.
#include <Quon_m.h>
Public Member Functions
QuonMoveMessage (const char *name=NULL, int kind=0)
QuonMoveMessage (const QuonMoveMessage &other)
virtual ~QuonMoveMessage ()
QuonMoveMessage & operator= (const QuonMoveMessage &other)
virtual QuonMoveMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual Vector2D & getNewPosition ()
virtual const Vector2D & getNewPosition () const
virtual void setNewPosition (const Vector2D &newPosition)
virtual bool getIsBinding () const
virtual void setIsBinding (bool isBinding)
Protected Member Functions
bool operator== (const QuonMoveMessage &)
Protected Attributes
Vector2D newPosition_var
bool isBinding_var
Private Member Functions
void copy (const QuonMoveMessage &other)
Detailed Description
Class generated from overlay/quon/Quon.msg by opp_msgc.
 packet QuonMoveMessage extends QuonListMessage
 {
     Vector2D newPosition;
     bool isBinding = false;
 }
Definition at line 211 of file Quon_m.h.
Constructor & Destructor Documentation
QuonMoveMessage::QuonMoveMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
QuonMoveMessage::QuonMoveMessage (const QuonMoveMessage & other)
virtual QuonMoveMessage::~QuonMoveMessage () [virtual]
Member Function Documentation
void QuonMoveMessage::copy (const QuonMoveMessage & other) [private]
virtual QuonMoveMessage* QuonMoveMessage::dup () const [inline, virtual]
Reimplemented from QuonListMessage.
Definition at line 229 of file Quon_m.h.
{return new QuonMoveMessage(*this);}
virtual bool QuonMoveMessage::getIsBinding () const [virtual]
Referenced by Quon::handleNodeMove().
virtual Vector2D& QuonMoveMessage::getNewPosition () [virtual]
Referenced by Quon::handleNodeMove().
virtual const Vector2D& QuonMoveMessage::getNewPosition () const [inline, virtual]
Definition at line 235 of file Quon_m.h.
Referenced by getNewPosition().
{return const_cast<QuonMoveMessage*>(this)->getNewPosition();}
QuonMoveMessage& QuonMoveMessage::operator= (const QuonMoveMessage & other)
bool QuonMoveMessage::operator== (const QuonMoveMessage &) [protected]
virtual void QuonMoveMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from QuonListMessage.
Referenced by doPacking().
virtual void QuonMoveMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from QuonListMessage.
Referenced by doUnpacking().
virtual void QuonMoveMessage::setIsBinding (bool isBinding) [virtual]
Referenced by Quon::handleJoinAcknowledge(), Quon::handleMove(), and Quon::processBackupTimer().
virtual void QuonMoveMessage::setNewPosition (const Vector2D & newPosition) [virtual]
Referenced by Quon::handleJoinAcknowledge(), Quon::handleMove(), and Quon::processBackupTimer().
Member Data Documentation
bool QuonMoveMessage::isBinding_var [protected]
Definition at line 215 of file Quon_m.h.
Vector2D QuonMoveMessage::newPosition_var [protected]
Definition at line 214 of file Quon_m.h.
The documentation for this class was generated from the following file:
Quon_m.h