OverSim: AbstractNcsNodeInfo Class Reference
AbstractNcsNodeInfo Class Reference
#include <CoordinateSystem.h>
Public Member Functions
virtual ~AbstractNcsNodeInfo ()
virtual bool isValid ()=0
virtual Prox getDistance (const AbstractNcsNodeInfo &node) const =0
virtual bool update (const AbstractNcsNodeInfo &info)=0
virtual const Coords & getCoords () const =0
virtual operator Coords () const =0
Detailed Description
Definition at line 42 of file CoordinateSystem.h.
Constructor & Destructor Documentation
virtual AbstractNcsNodeInfo::~AbstractNcsNodeInfo () [inline, virtual]
Definition at line 45 of file CoordinateSystem.h.
{};
Member Function Documentation
virtual const Coords& AbstractNcsNodeInfo::getCoords () const [pure virtual]
Implemented in EuclideanNcsNodeInfo.
Referenced by NeighborCache::setCbrNodeId(), StrategySendAll::setMyCoordinates(), StrategySimplifyCoords::setMyCoordinates(), and StrategyRegions::setMyCoordinates().
virtual Prox AbstractNcsNodeInfo::getDistance (const AbstractNcsNodeInfo & node) const [pure virtual]
Implemented in VivaldiCoordsInfo, SimpleCoordsInfo, SimpleUnderlayCoordsInfo, and EuclideanNcsNodeInfo.
Referenced by NeighborCache::getAvgAbsPredictionError().
virtual bool AbstractNcsNodeInfo::isValid () [pure virtual]
Implemented in VivaldiCoordsInfo, SimpleCoordsInfo, SimpleUnderlayCoordsInfo, and GnpNpsCoordsInfo.
virtual AbstractNcsNodeInfo::operator Coords () const [pure virtual]
Implemented in VivaldiCoordsInfo, SimpleCoordsInfo, SimpleUnderlayCoordsInfo, and GnpNpsCoordsInfo.
virtual bool AbstractNcsNodeInfo::update (const AbstractNcsNodeInfo & info) [pure virtual]
Implemented in VivaldiCoordsInfo, SimpleCoordsInfo, SimpleUnderlayCoordsInfo, and GnpNpsCoordsInfo.
Referenced by NeighborCache::updateNcsInfo(), and NeighborCache::updateNode().
The documentation for this class was generated from the following file:
CoordinateSystem.h