OverSim: NextHopResponse Class Reference
NextHopResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
NextHopResponse (const char *name=NULL, int kind=0)
NextHopResponse (const NextHopResponse &other)
virtual ~NextHopResponse ()
NextHopResponse & operator= (const NextHopResponse &other)
virtual NextHopResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const NextHopResponse &)
Private Member Functions
void copy (const NextHopResponse &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet NextHopResponse extends BaseResponseMessage
 {
 }
Definition at line 993 of file CommonMessages_m.h.
Constructor & Destructor Documentation
NextHopResponse::NextHopResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
NextHopResponse::NextHopResponse (const NextHopResponse & other)
virtual NextHopResponse::~NextHopResponse () [virtual]
Member Function Documentation
void NextHopResponse::copy (const NextHopResponse & other) [private]
virtual NextHopResponse* NextHopResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 1009 of file CommonMessages_m.h.
{return new NextHopResponse(*this);}
NextHopResponse& NextHopResponse::operator= (const NextHopResponse & other)
bool NextHopResponse::operator== (const NextHopResponse &) [protected]
virtual void NextHopResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void NextHopResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h