OverSim: AreaDataCall Class Reference
AreaDataCall Class Reference
Class generated from common/TreeManagementMessage.msg by opp_msgc.
#include <TreeManagementMessage_m.h>
Public Member Functions
AreaDataCall (const char *name=NULL, int kind=0)
AreaDataCall (const AreaDataCall &other)
virtual ~AreaDataCall ()
AreaDataCall & operator= (const AreaDataCall &other)
virtual AreaDataCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual AreaDataContainer & getAreaData ()
virtual const AreaDataContainer & getAreaData () const
virtual void setAreaData (const AreaDataContainer &areaData)
Protected Member Functions
bool operator== (const AreaDataCall &)
Protected Attributes
AreaDataContainer areaData_var
Private Member Functions
void copy (const AreaDataCall &other)
Detailed Description
Class generated from common/TreeManagementMessage.msg by opp_msgc.
 packet AreaDataCall extends GlobalViewBuilderCall
 {
     AreaDataContainer areaData;
 }
Definition at line 648 of file TreeManagementMessage_m.h.
Constructor & Destructor Documentation
AreaDataCall::AreaDataCall (const char * name = NULL, int kind = 0)
Referenced by dup().
AreaDataCall::AreaDataCall (const AreaDataCall & other)
virtual AreaDataCall::~AreaDataCall () [virtual]
Member Function Documentation
void AreaDataCall::copy (const AreaDataCall & other) [private]
virtual AreaDataCall* AreaDataCall::dup () const [inline, virtual]
Reimplemented from GlobalViewBuilderCall.
Definition at line 665 of file TreeManagementMessage_m.h.
{return new AreaDataCall(*this);}
virtual AreaDataContainer& AreaDataCall::getAreaData () [virtual]
Referenced by GlobalViewBuilder::handleCoordinateRpcCall().
virtual const AreaDataContainer& AreaDataCall::getAreaData () const [inline, virtual]
Definition at line 671 of file TreeManagementMessage_m.h.
Referenced by getAreaData().
{return const_cast<AreaDataCall*>(this)->getAreaData();}
AreaDataCall& AreaDataCall::operator= (const AreaDataCall & other)
bool AreaDataCall::operator== (const AreaDataCall &) [protected]
virtual void AreaDataCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doPacking().
virtual void AreaDataCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GlobalViewBuilderCall.
Referenced by doUnpacking().
virtual void AreaDataCall::setAreaData (const AreaDataContainer & areaData) [virtual]
Referenced by GlobalViewBuilder::handleCoordinateRpcCall(), and GlobalViewBuilder::spreadGlobalView().
Member Data Documentation
AreaDataContainer AreaDataCall::areaData_var [protected]
Definition at line 651 of file TreeManagementMessage_m.h.
The documentation for this class was generated from the following file:
TreeManagementMessage_m.h