OverSim: ScribePublishCall Class Reference
ScribePublishCall Class Reference
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
#include <ScribeMessage_m.h>
Public Member Functions
ScribePublishCall (const char *name=NULL, int kind=0)
ScribePublishCall (const ScribePublishCall &other)
virtual ~ScribePublishCall ()
ScribePublishCall & operator= (const ScribePublishCall &other)
virtual ScribePublishCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getGroupId ()
virtual const OverlayKey & getGroupId () const
virtual void setGroupId (const OverlayKey &groupId)
Protected Member Functions
bool operator== (const ScribePublishCall &)
Protected Attributes
OverlayKey groupId_var
Private Member Functions
void copy (const ScribePublishCall &other)
Detailed Description
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
 packet ScribePublishCall extends BaseCallMessage
 {
         OverlayKey groupId;
 }
Definition at line 150 of file ScribeMessage_m.h.
Constructor & Destructor Documentation
ScribePublishCall::ScribePublishCall (const char * name = NULL, int kind = 0)
Referenced by dup().
ScribePublishCall::ScribePublishCall (const ScribePublishCall & other)
virtual ScribePublishCall::~ScribePublishCall () [virtual]
Member Function Documentation
void ScribePublishCall::copy (const ScribePublishCall & other) [private]
virtual ScribePublishCall* ScribePublishCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 167 of file ScribeMessage_m.h.
{return new ScribePublishCall(*this);}
virtual OverlayKey& ScribePublishCall::getGroupId () [virtual]
Referenced by Scribe::deliverALMDataToRoot(), and Scribe::handlePublishCall().
virtual const OverlayKey& ScribePublishCall::getGroupId () const [inline, virtual]
Definition at line 173 of file ScribeMessage_m.h.
Referenced by getGroupId().
{return const_cast<ScribePublishCall*>(this)->getGroupId();}
ScribePublishCall& ScribePublishCall::operator= (const ScribePublishCall & other)
bool ScribePublishCall::operator== (const ScribePublishCall &) [protected]
virtual void ScribePublishCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void ScribePublishCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void ScribePublishCall::setGroupId (const OverlayKey & groupId) [virtual]
Referenced by Scribe::deliverALMDataToRoot().
Member Data Documentation
OverlayKey ScribePublishCall::groupId_var [protected]
Definition at line 153 of file ScribeMessage_m.h.
The documentation for this class was generated from the following file:
ScribeMessage_m.h