OverSim: GiaNeighborMessage Class Reference
GiaNeighborMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>
Public Member Functions
GiaNeighborMessage (const char *name=NULL, int kind=0)
GiaNeighborMessage (const GiaNeighborMessage &other)
virtual ~GiaNeighborMessage ()
GiaNeighborMessage & operator= (const GiaNeighborMessage &other)
virtual GiaNeighborMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setNeighborsArraySize (unsigned int size)
virtual unsigned int getNeighborsArraySize () const
virtual GiaNode & getNeighbors (unsigned int k)
virtual const GiaNode & getNeighbors (unsigned int k) const
virtual void setNeighbors (unsigned int k, const GiaNode &neighbors)
Protected Member Functions
bool operator== (const GiaNeighborMessage &)
Protected Attributes
GiaNode * neighbors_var
unsigned int neighbors_arraysize
Private Member Functions
void copy (const GiaNeighborMessage &other)
Detailed Description
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
 message GiaNeighborMessage extends GiaMessage
 {
         GiaNode neighbors[];
 };
Definition at line 144 of file GiaMessage_m.h.
Constructor & Destructor Documentation
GiaNeighborMessage::GiaNeighborMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GiaNeighborMessage::GiaNeighborMessage (const GiaNeighborMessage & other)
virtual GiaNeighborMessage::~GiaNeighborMessage () [virtual]
Member Function Documentation
void GiaNeighborMessage::copy (const GiaNeighborMessage & other) [private]
virtual GiaNeighborMessage* GiaNeighborMessage::dup () const [inline, virtual]
Reimplemented from GiaMessage.
Definition at line 162 of file GiaMessage_m.h.
{return new GiaNeighborMessage(*this);}
virtual GiaNode& GiaNeighborMessage::getNeighbors (unsigned int k) [virtual]
virtual const GiaNode& GiaNeighborMessage::getNeighbors (unsigned int k) const [inline, virtual]
Definition at line 170 of file GiaMessage_m.h.
Referenced by getNeighbors().
{return const_cast<GiaNeighborMessage*>(this)->getNeighbors(k);}
virtual unsigned int GiaNeighborMessage::getNeighborsArraySize () const [virtual]
GiaNeighborMessage& GiaNeighborMessage::operator= (const GiaNeighborMessage & other)
bool GiaNeighborMessage::operator== (const GiaNeighborMessage &) [protected]
virtual void GiaNeighborMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Referenced by doPacking().
virtual void GiaNeighborMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from GiaMessage.
Referenced by doUnpacking().
virtual void GiaNeighborMessage::setNeighbors (unsigned int k, const GiaNode & neighbors) [virtual]
Referenced by Gia::sendMessage_JOIN_ACK(), and Gia::sendMessage_JOIN_RSP().
virtual void GiaNeighborMessage::setNeighborsArraySize (unsigned int size) [virtual]
Referenced by Gia::sendMessage_JOIN_ACK(), and Gia::sendMessage_JOIN_RSP().
Member Data Documentation
unsigned int GiaNeighborMessage::neighbors_arraysize [protected]
Definition at line 148 of file GiaMessage_m.h.
GiaNode* GiaNeighborMessage::neighbors_var [protected]
Definition at line 147 of file GiaMessage_m.h.
The documentation for this class was generated from the following file:
GiaMessage_m.h