OverSim: ALMCreateMessage Class Reference
ALMCreateMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
ALMCreateMessage (const char *name=NULL, int kind=0)
ALMCreateMessage (const ALMCreateMessage &other)
virtual ~ALMCreateMessage ()
ALMCreateMessage & operator= (const ALMCreateMessage &other)
virtual ALMCreateMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const ALMCreateMessage &)
Private Member Functions
void copy (const ALMCreateMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet ALMCreateMessage extends ALMMessage
 {
 }
Definition at line 2135 of file CommonMessages_m.h.
Constructor & Destructor Documentation
ALMCreateMessage::ALMCreateMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
ALMCreateMessage::ALMCreateMessage (const ALMCreateMessage & other)
virtual ALMCreateMessage::~ALMCreateMessage () [virtual]
Member Function Documentation
void ALMCreateMessage::copy (const ALMCreateMessage & other) [private]
virtual ALMCreateMessage* ALMCreateMessage::dup () const [inline, virtual]
Reimplemented from ALMMessage.
Definition at line 2151 of file CommonMessages_m.h.
{return new ALMCreateMessage(*this);}
ALMCreateMessage& ALMCreateMessage::operator= (const ALMCreateMessage & other)
bool ALMCreateMessage::operator== (const ALMCreateMessage &) [protected]
virtual void ALMCreateMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doPacking().
virtual void ALMCreateMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from ALMMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h