OverSim: PubSubReleaseIntermediateMessage Class Reference
PubSubReleaseIntermediateMessage Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubReleaseIntermediateMessage (const char *name=NULL, int kind=0)
PubSubReleaseIntermediateMessage (const PubSubReleaseIntermediateMessage &other)
virtual ~PubSubReleaseIntermediateMessage ()
PubSubReleaseIntermediateMessage & operator= (const PubSubReleaseIntermediateMessage &other)
virtual
PubSubReleaseIntermediateMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
Protected Member Functions
bool operator== (const PubSubReleaseIntermediateMessage &)
Protected Attributes
int subspaceId_var
Private Member Functions
void copy (const PubSubReleaseIntermediateMessage &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubReleaseIntermediateMessage extends BaseOverlayMessage
 {
         int subspaceId;
 }
Definition at line 1084 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubReleaseIntermediateMessage::PubSubReleaseIntermediateMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubReleaseIntermediateMessage::PubSubReleaseIntermediateMessage (const PubSubReleaseIntermediateMessage & other)
virtual PubSubReleaseIntermediateMessage::~PubSubReleaseIntermediateMessage () [virtual]
Member Function Documentation
void PubSubReleaseIntermediateMessage::copy (const PubSubReleaseIntermediateMessage & other) [private]
virtual PubSubReleaseIntermediateMessage* PubSubReleaseIntermediateMessage::dup () const [inline, virtual]
Reimplemented from BaseOverlayMessage.
Definition at line 1101 of file PubSubMessage_m.h.
{return new PubSubReleaseIntermediateMessage(*this);}
virtual int PubSubReleaseIntermediateMessage::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleReleaseIntermediate().
PubSubReleaseIntermediateMessage& PubSubReleaseIntermediateMessage::operator= (const PubSubReleaseIntermediateMessage & other)
bool PubSubReleaseIntermediateMessage::operator== (const PubSubReleaseIntermediateMessage &) [protected]
virtual void PubSubReleaseIntermediateMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doPacking().
virtual void PubSubReleaseIntermediateMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseOverlayMessage.
Referenced by doUnpacking().
virtual void PubSubReleaseIntermediateMessage::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::unsubscribeChild().
Member Data Documentation
int PubSubReleaseIntermediateMessage::subspaceId_var [protected]
Definition at line 1087 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h