OverSim: CoordsReqResponse Class Reference
CoordsReqResponse Class Reference
Class generated from common/Nps.msg by opp_msgc.
#include <Nps_m.h>
Public Member Functions
CoordsReqResponse (const char *name=NULL, int kind=0)
CoordsReqResponse (const CoordsReqResponse &other)
virtual ~CoordsReqResponse ()
CoordsReqResponse & operator= (const CoordsReqResponse &other)
virtual CoordsReqResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual char getLayer () const
virtual void setLayer (char layer)
Protected Member Functions
bool operator== (const CoordsReqResponse &)
Protected Attributes
char layer_var
Private Member Functions
void copy (const CoordsReqResponse &other)
Detailed Description
Class generated from common/Nps.msg by opp_msgc.
 packet CoordsReqResponse extends BaseResponseMessage
 {
     char layer;
 }
Definition at line 72 of file Nps_m.h.
Constructor & Destructor Documentation
CoordsReqResponse::CoordsReqResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
CoordsReqResponse::CoordsReqResponse (const CoordsReqResponse & other)
virtual CoordsReqResponse::~CoordsReqResponse () [virtual]
Member Function Documentation
void CoordsReqResponse::copy (const CoordsReqResponse & other) [private]
virtual CoordsReqResponse* CoordsReqResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 89 of file Nps_m.h.
{return new CoordsReqResponse(*this);}
virtual char CoordsReqResponse::getLayer () const [virtual]
CoordsReqResponse& CoordsReqResponse::operator= (const CoordsReqResponse & other)
bool CoordsReqResponse::operator== (const CoordsReqResponse &) [protected]
virtual void CoordsReqResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void CoordsReqResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
virtual void CoordsReqResponse::setLayer (char layer) [virtual]
Referenced by Nps::coordsReqRpc().
Member Data Documentation
char CoordsReqResponse::layer_var [protected]
Definition at line 75 of file Nps_m.h.
The documentation for this class was generated from the following file:
Nps_m.h