OverSim: KBRupdate Class Reference
KBRupdate Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
KBRupdate (const char *name=NULL, int kind=0)
KBRupdate (const KBRupdate &other)
virtual ~KBRupdate ()
KBRupdate & operator= (const KBRupdate &other)
virtual KBRupdate * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual NodeHandle & getNode ()
virtual const NodeHandle & getNode () const
virtual void setNode (const NodeHandle &node)
virtual bool getJoined () const
virtual void setJoined (bool joined)
Protected Member Functions
bool operator== (const KBRupdate &)
Protected Attributes
NodeHandle node_var
bool joined_var
Private Member Functions
void copy (const KBRupdate &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet KBRupdate extends CommonAPIMessage
 {
     NodeHandle node;
     bool joined;
 }
Definition at line 1282 of file CommonMessages_m.h.
Constructor & Destructor Documentation
KBRupdate::KBRupdate (const char * name = NULL, int kind = 0)
Referenced by dup().
KBRupdate::KBRupdate (const KBRupdate & other)
virtual KBRupdate::~KBRupdate () [virtual]
Member Function Documentation
void KBRupdate::copy (const KBRupdate & other) [private]
virtual KBRupdate* KBRupdate::dup () const [inline, virtual]
Reimplemented from CommonAPIMessage.
Definition at line 1300 of file CommonMessages_m.h.
{return new KBRupdate(*this);}
virtual bool KBRupdate::getJoined () const [virtual]
Referenced by BaseApp::handleCommonAPIMessage().
virtual NodeHandle& KBRupdate::getNode () [virtual]
Referenced by BaseApp::handleCommonAPIMessage().
virtual const NodeHandle& KBRupdate::getNode () const [inline, virtual]
Definition at line 1306 of file CommonMessages_m.h.
Referenced by getNode().
{return const_cast<KBRupdate*>(this)->getNode();}
KBRupdate& KBRupdate::operator= (const KBRupdate & other)
bool KBRupdate::operator== (const KBRupdate &) [protected]
virtual void KBRupdate::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from CommonAPIMessage.
Referenced by doPacking().
virtual void KBRupdate::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from CommonAPIMessage.
Referenced by doUnpacking().
virtual void KBRupdate::setJoined (bool joined) [virtual]
Referenced by BaseOverlay::callUpdate().
virtual void KBRupdate::setNode (const NodeHandle & node) [virtual]
Referenced by BaseOverlay::callUpdate().
Member Data Documentation
bool KBRupdate::joined_var [protected]
Definition at line 1286 of file CommonMessages_m.h.
NodeHandle KBRupdate::node_var [protected]
Definition at line 1285 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h