OverSim: RpcTimeoutMessage Class Reference
RpcTimeoutMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
RpcTimeoutMessage (const char *name=NULL, int kind=0)
RpcTimeoutMessage (const RpcTimeoutMessage &other)
virtual ~RpcTimeoutMessage ()
RpcTimeoutMessage & operator= (const RpcTimeoutMessage &other)
virtual RpcTimeoutMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RpcTimeoutMessage &)
Private Member Functions
void copy (const RpcTimeoutMessage &other)
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet RpcTimeoutMessage extends BaseRpcMessage
 {
 }
Definition at line 601 of file CommonMessages_m.h.
Constructor & Destructor Documentation
RpcTimeoutMessage::RpcTimeoutMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
RpcTimeoutMessage::RpcTimeoutMessage (const RpcTimeoutMessage & other)
virtual RpcTimeoutMessage::~RpcTimeoutMessage () [virtual]
Member Function Documentation
void RpcTimeoutMessage::copy (const RpcTimeoutMessage & other) [private]
virtual RpcTimeoutMessage* RpcTimeoutMessage::dup () const [inline, virtual]
Reimplemented from BaseRpcMessage.
Definition at line 617 of file CommonMessages_m.h.
{return new RpcTimeoutMessage(*this);}
RpcTimeoutMessage& RpcTimeoutMessage::operator= (const RpcTimeoutMessage & other)
bool RpcTimeoutMessage::operator== (const RpcTimeoutMessage &) [protected]
virtual void RpcTimeoutMessage::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseRpcMessage.
Referenced by doPacking().
virtual void RpcTimeoutMessage::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseRpcMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
CommonMessages_m.h