OverSim: DHTGetResponse Class Reference
DHTGetResponse Class Reference
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
#include <DHTMessage_m.h>
Public Member Functions
DHTGetResponse (const char *name=NULL, int kind=0)
DHTGetResponse (const DHTGetResponse &other)
virtual ~DHTGetResponse ()
DHTGetResponse & operator= (const DHTGetResponse &other)
virtual DHTGetResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual OverlayKey & getKey ()
virtual const OverlayKey & getKey () const
virtual void setKey (const OverlayKey &key)
virtual BinaryValue & getHashValue ()
virtual const BinaryValue & getHashValue () const
virtual void setHashValue (const BinaryValue &hashValue)
virtual bool getIsHash () const
virtual void setIsHash (bool isHash)
virtual void setResultArraySize (unsigned int size)
virtual unsigned int getResultArraySize () const
virtual DhtDumpEntry & getResult (unsigned int k)
virtual const DhtDumpEntry & getResult (unsigned int k) const
virtual void setResult (unsigned int k, const DhtDumpEntry &result)
Protected Member Functions
bool operator== (const DHTGetResponse &)
Protected Attributes
OverlayKey key_var
BinaryValue hashValue_var
bool isHash_var
DhtDumpEntry * result_var
unsigned int result_arraysize
Private Member Functions
void copy (const DHTGetResponse &other)
Detailed Description
Class generated from applications/dht/DHTMessage.msg by opp_msgc.
 packet DHTGetResponse extends BaseResponseMessage
 {
     OverlayKey key;
     BinaryValue hashValue;
     bool isHash;
     DhtDumpEntry result[];
 }
Definition at line 209 of file DHTMessage_m.h.
Constructor & Destructor Documentation
DHTGetResponse::DHTGetResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
DHTGetResponse::DHTGetResponse (const DHTGetResponse & other)
virtual DHTGetResponse::~DHTGetResponse () [virtual]
Member Function Documentation
void DHTGetResponse::copy (const DHTGetResponse & other) [private]
virtual DHTGetResponse* DHTGetResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in CBRDHTGetResponse.
Definition at line 230 of file DHTMessage_m.h.
{return new DHTGetResponse(*this);}
virtual BinaryValue& DHTGetResponse::getHashValue () [virtual]
Referenced by CBRDHT::handleGetResponse(), and DHT::handleGetResponse().
virtual const BinaryValue& DHTGetResponse::getHashValue () const [inline, virtual]
Definition at line 239 of file DHTMessage_m.h.
Referenced by getHashValue().
{return const_cast<DHTGetResponse*>(this)->getHashValue();}
virtual bool DHTGetResponse::getIsHash () const [virtual]
Referenced by CBRDHT::handleGetResponse(), and DHT::handleGetResponse().
virtual OverlayKey& DHTGetResponse::getKey () [virtual]
Referenced by CBRDHT::handleGetResponse(), and DHT::handleGetResponse().
virtual const OverlayKey& DHTGetResponse::getKey () const [inline, virtual]
Definition at line 236 of file DHTMessage_m.h.
Referenced by getKey().
{return const_cast<DHTGetResponse*>(this)->getKey();}
virtual DhtDumpEntry& DHTGetResponse::getResult (unsigned int k) [virtual]
Referenced by CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::resultValuesBitLength(), and DHT::resultValuesBitLength().
virtual const DhtDumpEntry& DHTGetResponse::getResult (unsigned int k) const [inline, virtual]
Definition at line 246 of file DHTMessage_m.h.
Referenced by getResult().
{return const_cast<DHTGetResponse*>(this)->getResult(k);}
virtual unsigned int DHTGetResponse::getResultArraySize () const [virtual]
Referenced by CBRDHT::handleGetResponse(), DHT::handleGetResponse(), CBRDHT::resultValuesBitLength(), and DHT::resultValuesBitLength().
DHTGetResponse& DHTGetResponse::operator= (const DHTGetResponse & other)
bool DHTGetResponse::operator== (const DHTGetResponse &) [protected]
virtual void DHTGetResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in CBRDHTGetResponse.
Referenced by doPacking().
virtual void DHTGetResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Reimplemented in CBRDHTGetResponse.
Referenced by doUnpacking().
virtual void DHTGetResponse::setHashValue (const BinaryValue & hashValue) [virtual]
Referenced by DHT::handleGetRequest().
virtual void DHTGetResponse::setIsHash (bool isHash) [virtual]
Referenced by CBRDHT::handleGetRequest(), and DHT::handleGetRequest().
virtual void DHTGetResponse::setKey (const OverlayKey & key) [virtual]
Referenced by CBRDHT::handleGetRequest(), and DHT::handleGetRequest().
virtual void DHTGetResponse::setResult (unsigned int k, const DhtDumpEntry & result) [virtual]
Referenced by CBRDHT::handleGetRequest(), and DHT::handleGetRequest().
virtual void DHTGetResponse::setResultArraySize (unsigned int size) [virtual]
Referenced by CBRDHT::handleGetRequest(), and DHT::handleGetRequest().
Member Data Documentation
BinaryValue DHTGetResponse::hashValue_var [protected]
Definition at line 213 of file DHTMessage_m.h.
bool DHTGetResponse::isHash_var [protected]
Definition at line 214 of file DHTMessage_m.h.
OverlayKey DHTGetResponse::key_var [protected]
Definition at line 212 of file DHTMessage_m.h.
unsigned int DHTGetResponse::result_arraysize [protected]
Definition at line 216 of file DHTMessage_m.h.
DhtDumpEntry* DHTGetResponse::result_var [protected]
Definition at line 215 of file DHTMessage_m.h.
The documentation for this class was generated from the following file:
DHTMessage_m.h