OverSim: StabilizeCall Class Reference
StabilizeCall Class Reference
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
#include <ChordMessage_m.h>
Public Member Functions
StabilizeCall (const char *name=NULL, int kind=0)
StabilizeCall (const StabilizeCall &other)
virtual ~StabilizeCall ()
StabilizeCall & operator= (const StabilizeCall &other)
virtual StabilizeCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const StabilizeCall &)
Private Member Functions
void copy (const StabilizeCall &other)
Detailed Description
Class generated from overlay/chord/ChordMessage.msg by opp_msgc.
 packet StabilizeCall extends BaseCallMessage
 {
 }
Definition at line 336 of file ChordMessage_m.h.
Constructor & Destructor Documentation
StabilizeCall::StabilizeCall (const char * name = NULL, int kind = 0)
Referenced by dup().
StabilizeCall::StabilizeCall (const StabilizeCall & other)
virtual StabilizeCall::~StabilizeCall () [virtual]
Member Function Documentation
void StabilizeCall::copy (const StabilizeCall & other) [private]
virtual StabilizeCall* StabilizeCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 352 of file ChordMessage_m.h.
{return new StabilizeCall(*this);}
StabilizeCall& StabilizeCall::operator= (const StabilizeCall & other)
bool StabilizeCall::operator== (const StabilizeCall &) [protected]
virtual void StabilizeCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void StabilizeCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
ChordMessage_m.h