OverSim: SessionMsg Class Reference
SessionMsg Class Reference
Class generated from applications/i3/i3Apps/I3SessionMessage.msg by opp_msgc.
#include <I3SessionMessage_m.h>
Public Member Functions
SessionMsg (const char *name=NULL, int kind=0)
SessionMsg (const SessionMsg &other)
virtual ~SessionMsg ()
SessionMsg & operator= (const SessionMsg &other)
virtual SessionMsg * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type)
virtual double getValue () const
virtual void setValue (double value)
virtual I3Identifier & getSource ()
virtual const I3Identifier & getSource () const
virtual void setSource (const I3Identifier &source)
Protected Member Functions
bool operator== (const SessionMsg &)
Protected Attributes
int type_var
double value_var
I3Identifier source_var
Private Member Functions
void copy (const SessionMsg &other)
Detailed Description
Class generated from applications/i3/i3Apps/I3SessionMessage.msg by opp_msgc.
 packet SessionMsg
 {
         int type enum(SessionMsgType);
         double value;
                 I3Identifier source;
 }
Definition at line 51 of file I3SessionMessage_m.h.
Constructor & Destructor Documentation
SessionMsg::SessionMsg (const char * name = NULL, int kind = 0)
Referenced by dup().
SessionMsg::SessionMsg (const SessionMsg & other)
virtual SessionMsg::~SessionMsg () [virtual]
Member Function Documentation
void SessionMsg::copy (const SessionMsg & other) [private]
virtual SessionMsg* SessionMsg::dup () const [inline, virtual]
Definition at line 70 of file I3SessionMessage_m.h.
{return new SessionMsg(*this);}
virtual I3Identifier& SessionMsg::getSource () [virtual]
Referenced by I3SessionClient::deliver().
virtual const I3Identifier& SessionMsg::getSource () const [inline, virtual]
Definition at line 80 of file I3SessionMessage_m.h.
Referenced by getSource().
{return const_cast<SessionMsg*>(this)->getSource();}
virtual int SessionMsg::getType () const [virtual]
Referenced by I3SessionClient::deliver().
virtual double SessionMsg::getValue () const [virtual]
Referenced by I3SessionServer::deliver(), and I3SessionClient::deliver().
SessionMsg& SessionMsg::operator= (const SessionMsg & other)
bool SessionMsg::operator== (const SessionMsg &) [protected]
virtual void SessionMsg::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void SessionMsg::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void SessionMsg::setSource (const I3Identifier & source) [virtual]
Referenced by I3SessionClient::deliver(), and I3SessionClient::handleTimerEvent().
virtual void SessionMsg::setType (int type) [virtual]
Referenced by I3SessionClient::deliver(), I3SessionClient::handleTimerEvent(), and I3SessionClientStarter::initializeI3().
virtual void SessionMsg::setValue (double value) [virtual]
Referenced by I3SessionServer::deliver(), I3SessionClient::deliver(), I3SessionClient::handleTimerEvent(), and I3SessionClientStarter::initializeI3().
Member Data Documentation
I3Identifier SessionMsg::source_var [protected]
Definition at line 56 of file I3SessionMessage_m.h.
int SessionMsg::type_var [protected]
Definition at line 54 of file I3SessionMessage_m.h.
double SessionMsg::value_var [protected]
Definition at line 55 of file I3SessionMessage_m.h.
The documentation for this class was generated from the following file:
I3SessionMessage_m.h