OverSim: RequestStateResponse Class Reference
RequestStateResponse Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>
Public Member Functions
RequestStateResponse (const char *name=NULL, int kind=0)
RequestStateResponse (const RequestStateResponse &other)
virtual ~RequestStateResponse ()
RequestStateResponse & operator= (const RequestStateResponse &other)
virtual RequestStateResponse * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const RequestStateResponse &)
Private Member Functions
void copy (const RequestStateResponse &other)
Detailed Description
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
 packet RequestStateResponse extends BaseResponseMessage
 {
 }
Definition at line 398 of file PastryMessage_m.h.
Constructor & Destructor Documentation
RequestStateResponse::RequestStateResponse (const char * name = NULL, int kind = 0)
Referenced by dup().
RequestStateResponse::RequestStateResponse (const RequestStateResponse & other)
virtual RequestStateResponse::~RequestStateResponse () [virtual]
Member Function Documentation
void RequestStateResponse::copy (const RequestStateResponse & other) [private]
virtual RequestStateResponse* RequestStateResponse::dup () const [inline, virtual]
Reimplemented from BaseResponseMessage.
Definition at line 414 of file PastryMessage_m.h.
{return new RequestStateResponse(*this);}
RequestStateResponse& RequestStateResponse::operator= (const RequestStateResponse & other)
bool RequestStateResponse::operator== (const RequestStateResponse &) [protected]
virtual void RequestStateResponse::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doPacking().
virtual void RequestStateResponse::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseResponseMessage.
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
PastryMessage_m.h