OverSim: PubSubAdoptChildCall Class Reference
PubSubAdoptChildCall Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubAdoptChildCall (const char *name=NULL, int kind=0)
PubSubAdoptChildCall (const PubSubAdoptChildCall &other)
virtual ~PubSubAdoptChildCall ()
PubSubAdoptChildCall & operator= (const PubSubAdoptChildCall &other)
virtual PubSubAdoptChildCall * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId)
virtual NodeHandle & getChild ()
virtual const NodeHandle & getChild () const
virtual void setChild (const NodeHandle &child)
Protected Member Functions
bool operator== (const PubSubAdoptChildCall &)
Protected Attributes
int subspaceId_var
NodeHandle child_var
Private Member Functions
void copy (const PubSubAdoptChildCall &other)
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 packet PubSubAdoptChildCall extends BaseCallMessage
 {
         int subspaceId;
         NodeHandle child;
 }
Definition at line 999 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubAdoptChildCall::PubSubAdoptChildCall (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubAdoptChildCall::PubSubAdoptChildCall (const PubSubAdoptChildCall & other)
virtual PubSubAdoptChildCall::~PubSubAdoptChildCall () [virtual]
Member Function Documentation
void PubSubAdoptChildCall::copy (const PubSubAdoptChildCall & other) [private]
virtual PubSubAdoptChildCall* PubSubAdoptChildCall::dup () const [inline, virtual]
Reimplemented from BaseCallMessage.
Definition at line 1017 of file PubSubMessage_m.h.
{return new PubSubAdoptChildCall(*this);}
virtual NodeHandle& PubSubAdoptChildCall::getChild () [virtual]
Referenced by PubSubMMOG::handleAdoptChildCall().
virtual const NodeHandle& PubSubAdoptChildCall::getChild () const [inline, virtual]
Definition at line 1025 of file PubSubMessage_m.h.
Referenced by getChild().
{return const_cast<PubSubAdoptChildCall*>(this)->getChild();}
virtual int PubSubAdoptChildCall::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleAdoptChildCall().
PubSubAdoptChildCall& PubSubAdoptChildCall::operator= (const PubSubAdoptChildCall & other)
bool PubSubAdoptChildCall::operator== (const PubSubAdoptChildCall &) [protected]
virtual void PubSubAdoptChildCall::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doPacking().
virtual void PubSubAdoptChildCall::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from BaseCallMessage.
Referenced by doUnpacking().
virtual void PubSubAdoptChildCall::setChild (const NodeHandle & child) [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse(), PubSubMMOG::handleSubscriptionCall(), and PubSubMMOG::unsubscribeChild().
virtual void PubSubAdoptChildCall::setSubspaceId (int subspaceId) [virtual]
Referenced by PubSubMMOG::handleIntermediateResponse(), PubSubMMOG::handleSubscriptionCall(), and PubSubMMOG::unsubscribeChild().
Member Data Documentation
NodeHandle PubSubAdoptChildCall::child_var [protected]
Definition at line 1003 of file PubSubMessage_m.h.
int PubSubAdoptChildCall::subspaceId_var [protected]
Definition at line 1002 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h