OverSim: NiceClusterMerge Class Reference
NiceClusterMerge Class Reference
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
#include <NiceMessage_m.h>
Public Member Functions
NiceClusterMerge (const char *name=NULL, int kind=0)
NiceClusterMerge (const NiceClusterMerge &other)
virtual ~NiceClusterMerge ()
NiceClusterMerge & operator= (const NiceClusterMerge &other)
virtual NiceClusterMerge * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual TransportAddress & getNewClusterLeader ()
virtual const TransportAddress & getNewClusterLeader () const
virtual void setNewClusterLeader (const TransportAddress &newClusterLeader)
Protected Member Functions
bool operator== (const NiceClusterMerge &)
Protected Attributes
TransportAddress newClusterLeader_var
Private Member Functions
void copy (const NiceClusterMerge &other)
Detailed Description
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
 message NiceClusterMerge extends NiceMemberMessage
 {
     TransportAddress newClusterLeader;
 }
Definition at line 185 of file NiceMessage_m.h.
Constructor & Destructor Documentation
NiceClusterMerge::NiceClusterMerge (const char * name = NULL, int kind = 0)
Referenced by dup().
NiceClusterMerge::NiceClusterMerge (const NiceClusterMerge & other)
virtual NiceClusterMerge::~NiceClusterMerge () [virtual]
Member Function Documentation
void NiceClusterMerge::copy (const NiceClusterMerge & other) [private]
virtual NiceClusterMerge* NiceClusterMerge::dup () const [inline, virtual]
Reimplemented from NiceMemberMessage.
Definition at line 202 of file NiceMessage_m.h.
Referenced by oversim::Nice::handleNiceClusterMergeRequest().
{return new NiceClusterMerge(*this);}
virtual TransportAddress& NiceClusterMerge::getNewClusterLeader () [virtual]
Referenced by oversim::Nice::handleNiceClusterMergeRequest().
virtual const TransportAddress& NiceClusterMerge::getNewClusterLeader () const [inline, virtual]
Definition at line 208 of file NiceMessage_m.h.
Referenced by getNewClusterLeader().
{return const_cast<NiceClusterMerge*>(this)->getNewClusterLeader();}
NiceClusterMerge& NiceClusterMerge::operator= (const NiceClusterMerge & other)
bool NiceClusterMerge::operator== (const NiceClusterMerge &) [protected]
virtual void NiceClusterMerge::parsimPack (cCommBuffer * b) [virtual]
Reimplemented from NiceMemberMessage.
Referenced by doPacking().
virtual void NiceClusterMerge::parsimUnpack (cCommBuffer * b) [virtual]
Reimplemented from NiceMemberMessage.
Referenced by doUnpacking().
virtual void NiceClusterMerge::setNewClusterLeader (const TransportAddress & newClusterLeader) [virtual]
Referenced by oversim::Nice::ClusterMergeRequest().
Member Data Documentation
TransportAddress NiceClusterMerge::newClusterLeader_var [protected]
Definition at line 188 of file NiceMessage_m.h.
The documentation for this class was generated from the following file:
NiceMessage_m.h